"""Hand-maintained WAXS advanced panel layout."""


from PyQt5 import QtCore, QtWidgets


class WaxsAdvancedPanelView:
    def setupUi(self, waxsAdvancedControlTabs):
        waxsAdvancedControlTabs.setObjectName("waxsAdvancedControlTabs")
        self.displayTab = QtWidgets.QWidget()
        self.displayTab.setObjectName("displayTab")
        self.displayForm = QtWidgets.QFormLayout(self.displayTab)
        self.displayForm.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.displayForm.setRowWrapPolicy(QtWidgets.QFormLayout.WrapLongRows)
        self.displayForm.setContentsMargins(12, 12, 12, 12)
        self.displayForm.setSpacing(8)
        self.displayForm.setObjectName("displayForm")
        self.vminLabel = QtWidgets.QLabel(self.displayTab)
        self.vminLabel.setObjectName("vminLabel")
        self.displayForm.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.vminLabel)
        self.vmin_spin = QtWidgets.QDoubleSpinBox(self.displayTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vmin_spin.sizePolicy().hasHeightForWidth())
        self.vmin_spin.setSizePolicy(sizePolicy)
        self.vmin_spin.setDecimals(9)
        self.vmin_spin.setMinimum(-1000000000000.0)
        self.vmin_spin.setMaximum(1000000000000.0)
        self.vmin_spin.setSingleStep(0.1)
        self.vmin_spin.setObjectName("vmin_spin")
        self.displayForm.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.vmin_spin)
        self.vmaxLabel = QtWidgets.QLabel(self.displayTab)
        self.vmaxLabel.setObjectName("vmaxLabel")
        self.displayForm.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.vmaxLabel)
        self.vmax_spin = QtWidgets.QDoubleSpinBox(self.displayTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vmax_spin.sizePolicy().hasHeightForWidth())
        self.vmax_spin.setSizePolicy(sizePolicy)
        self.vmax_spin.setDecimals(9)
        self.vmax_spin.setMinimum(-1000000000000.0)
        self.vmax_spin.setMaximum(1000000000000.0)
        self.vmax_spin.setSingleStep(0.1)
        self.vmax_spin.setProperty("value", 800.0)
        self.vmax_spin.setObjectName("vmax_spin")
        self.displayForm.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.vmax_spin)
        self.display_auto_scale = QtWidgets.QCheckBox(self.displayTab)
        self.display_auto_scale.setChecked(True)
        self.display_auto_scale.setObjectName("display_auto_scale")
        self.displayForm.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.display_auto_scale)
        self.display_log = QtWidgets.QCheckBox(self.displayTab)
        self.display_log.setObjectName("display_log")
        self.displayForm.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.display_log)
        self.displayCmapLabel = QtWidgets.QLabel(self.displayTab)
        self.displayCmapLabel.setObjectName("displayCmapLabel")
        self.displayForm.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.displayCmapLabel)
        self.display_cmap = QtWidgets.QComboBox(self.displayTab)
        self.display_cmap.setObjectName("display_cmap")
        self.display_cmap.addItem("")
        self.display_cmap.addItem("")
        self.display_cmap.addItem("")
        self.display_cmap.addItem("")
        self.display_cmap.addItem("")
        self.display_cmap.addItem("")
        self.display_cmap.addItem("")
        self.displayForm.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.display_cmap)
        self.display_flip = QtWidgets.QCheckBox(self.displayTab)
        self.display_flip.setObjectName("display_flip")
        self.displayForm.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.display_flip)
        waxsAdvancedControlTabs.addTab(self.displayTab, "")
        self.maskTab = QtWidgets.QWidget()
        self.maskTab.setObjectName("maskTab")
        self.maskForm = QtWidgets.QFormLayout(self.maskTab)
        self.maskForm.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.maskForm.setRowWrapPolicy(QtWidgets.QFormLayout.WrapLongRows)
        self.maskForm.setContentsMargins(12, 12, 12, 12)
        self.maskForm.setSpacing(8)
        self.maskForm.setObjectName("maskForm")
        self.maskMinLabel = QtWidgets.QLabel(self.maskTab)
        self.maskMinLabel.setObjectName("maskMinLabel")
        self.maskForm.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.maskMinLabel)
        self.mask_min_spin = QtWidgets.QDoubleSpinBox(self.maskTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mask_min_spin.sizePolicy().hasHeightForWidth())
        self.mask_min_spin.setSizePolicy(sizePolicy)
        self.mask_min_spin.setDecimals(9)
        self.mask_min_spin.setMinimum(-1000000000000.0)
        self.mask_min_spin.setMaximum(1000000000000.0)
        self.mask_min_spin.setSingleStep(0.1)
        self.mask_min_spin.setProperty("value", -1000000000000.0)
        self.mask_min_spin.setObjectName("mask_min_spin")
        self.maskForm.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.mask_min_spin)
        self.maskMaxLabel = QtWidgets.QLabel(self.maskTab)
        self.maskMaxLabel.setObjectName("maskMaxLabel")
        self.maskForm.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.maskMaxLabel)
        self.mask_max_spin = QtWidgets.QDoubleSpinBox(self.maskTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mask_max_spin.sizePolicy().hasHeightForWidth())
        self.mask_max_spin.setSizePolicy(sizePolicy)
        self.mask_max_spin.setDecimals(9)
        self.mask_max_spin.setMinimum(-1000000000000.0)
        self.mask_max_spin.setMaximum(1000000000000.0)
        self.mask_max_spin.setSingleStep(0.1)
        self.mask_max_spin.setProperty("value", 1000000000000.0)
        self.mask_max_spin.setObjectName("mask_max_spin")
        self.maskForm.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.mask_max_spin)
        self.badPixelLabel = QtWidgets.QLabel(self.maskTab)
        self.badPixelLabel.setObjectName("badPixelLabel")
        self.maskForm.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.badPixelLabel)
        self.bad_pixel_spin = QtWidgets.QDoubleSpinBox(self.maskTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bad_pixel_spin.sizePolicy().hasHeightForWidth())
        self.bad_pixel_spin.setSizePolicy(sizePolicy)
        self.bad_pixel_spin.setDecimals(9)
        self.bad_pixel_spin.setMinimum(-1000000000000.0)
        self.bad_pixel_spin.setMaximum(1000000000000.0)
        self.bad_pixel_spin.setSingleStep(0.1)
        self.bad_pixel_spin.setProperty("value", -1.0)
        self.bad_pixel_spin.setObjectName("bad_pixel_spin")
        self.maskForm.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.bad_pixel_spin)
        self.apply_mask_check = QtWidgets.QCheckBox(self.maskTab)
        self.apply_mask_check.setChecked(True)
        self.apply_mask_check.setObjectName("apply_mask_check")
        self.maskForm.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.apply_mask_check)
        self.reset_mask_button = QtWidgets.QPushButton(self.maskTab)
        self.reset_mask_button.setObjectName("reset_mask_button")
        self.maskForm.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.reset_mask_button)
        waxsAdvancedControlTabs.addTab(self.maskTab, "")
        self.geometryTab = QtWidgets.QWidget()
        self.geometryTab.setObjectName("geometryTab")
        self.geometryForm = QtWidgets.QFormLayout(self.geometryTab)
        self.geometryForm.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.geometryForm.setRowWrapPolicy(QtWidgets.QFormLayout.WrapLongRows)
        self.geometryForm.setContentsMargins(12, 12, 12, 12)
        self.geometryForm.setSpacing(8)
        self.geometryForm.setObjectName("geometryForm")
        self.incidenceLabel = QtWidgets.QLabel(self.geometryTab)
        self.incidenceLabel.setObjectName("incidenceLabel")
        self.geometryForm.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.incidenceLabel)
        self.incidence_spin = QtWidgets.QDoubleSpinBox(self.geometryTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.incidence_spin.sizePolicy().hasHeightForWidth())
        self.incidence_spin.setSizePolicy(sizePolicy)
        self.incidence_spin.setDecimals(9)
        self.incidence_spin.setMinimum(-90.0)
        self.incidence_spin.setMaximum(90.0)
        self.incidence_spin.setSingleStep(0.1)
        self.incidence_spin.setProperty("value", 0.5)
        self.incidence_spin.setObjectName("incidence_spin")
        self.geometryForm.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.incidence_spin)
        self.centerXLabel = QtWidgets.QLabel(self.geometryTab)
        self.centerXLabel.setObjectName("centerXLabel")
        self.geometryForm.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.centerXLabel)
        self.center_x_spin = QtWidgets.QDoubleSpinBox(self.geometryTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.center_x_spin.sizePolicy().hasHeightForWidth())
        self.center_x_spin.setSizePolicy(sizePolicy)
        self.center_x_spin.setDecimals(9)
        self.center_x_spin.setMinimum(-1000000.0)
        self.center_x_spin.setMaximum(1000000.0)
        self.center_x_spin.setSingleStep(0.1)
        self.center_x_spin.setProperty("value", 1000.0)
        self.center_x_spin.setObjectName("center_x_spin")
        self.geometryForm.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.center_x_spin)
        self.centerYLabel = QtWidgets.QLabel(self.geometryTab)
        self.centerYLabel.setObjectName("centerYLabel")
        self.geometryForm.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.centerYLabel)
        self.center_y_spin = QtWidgets.QDoubleSpinBox(self.geometryTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.center_y_spin.sizePolicy().hasHeightForWidth())
        self.center_y_spin.setSizePolicy(sizePolicy)
        self.center_y_spin.setDecimals(9)
        self.center_y_spin.setMinimum(-1000000.0)
        self.center_y_spin.setMaximum(1000000.0)
        self.center_y_spin.setSingleStep(0.1)
        self.center_y_spin.setProperty("value", 1000.0)
        self.center_y_spin.setObjectName("center_y_spin")
        self.geometryForm.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.center_y_spin)
        self.distanceLabel = QtWidgets.QLabel(self.geometryTab)
        self.distanceLabel.setObjectName("distanceLabel")
        self.geometryForm.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.distanceLabel)
        self.distance_spin = QtWidgets.QDoubleSpinBox(self.geometryTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.distance_spin.sizePolicy().hasHeightForWidth())
        self.distance_spin.setSizePolicy(sizePolicy)
        self.distance_spin.setDecimals(9)
        self.distance_spin.setMinimum(1e-06)
        self.distance_spin.setMaximum(1000000000.0)
        self.distance_spin.setSingleStep(0.1)
        self.distance_spin.setProperty("value", 2000.0)
        self.distance_spin.setObjectName("distance_spin")
        self.geometryForm.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.distance_spin)
        self.pixelXLabel = QtWidgets.QLabel(self.geometryTab)
        self.pixelXLabel.setObjectName("pixelXLabel")
        self.geometryForm.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.pixelXLabel)
        self.pixel_x_spin = QtWidgets.QDoubleSpinBox(self.geometryTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pixel_x_spin.sizePolicy().hasHeightForWidth())
        self.pixel_x_spin.setSizePolicy(sizePolicy)
        self.pixel_x_spin.setDecimals(9)
        self.pixel_x_spin.setMinimum(1e-06)
        self.pixel_x_spin.setMaximum(1000000000.0)
        self.pixel_x_spin.setSingleStep(0.1)
        self.pixel_x_spin.setProperty("value", 75.0)
        self.pixel_x_spin.setObjectName("pixel_x_spin")
        self.geometryForm.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.pixel_x_spin)
        self.pixelYLabel = QtWidgets.QLabel(self.geometryTab)
        self.pixelYLabel.setObjectName("pixelYLabel")
        self.geometryForm.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.pixelYLabel)
        self.pixel_y_spin = QtWidgets.QDoubleSpinBox(self.geometryTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pixel_y_spin.sizePolicy().hasHeightForWidth())
        self.pixel_y_spin.setSizePolicy(sizePolicy)
        self.pixel_y_spin.setDecimals(9)
        self.pixel_y_spin.setMinimum(1e-06)
        self.pixel_y_spin.setMaximum(1000000000.0)
        self.pixel_y_spin.setSingleStep(0.1)
        self.pixel_y_spin.setProperty("value", 75.0)
        self.pixel_y_spin.setObjectName("pixel_y_spin")
        self.geometryForm.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.pixel_y_spin)
        self.wavelengthLabel = QtWidgets.QLabel(self.geometryTab)
        self.wavelengthLabel.setObjectName("wavelengthLabel")
        self.geometryForm.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.wavelengthLabel)
        self.wavelength_spin = QtWidgets.QDoubleSpinBox(self.geometryTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wavelength_spin.sizePolicy().hasHeightForWidth())
        self.wavelength_spin.setSizePolicy(sizePolicy)
        self.wavelength_spin.setDecimals(9)
        self.wavelength_spin.setMinimum(1e-06)
        self.wavelength_spin.setMaximum(1000000000.0)
        self.wavelength_spin.setSingleStep(0.1)
        self.wavelength_spin.setProperty("value", 1.0332)
        self.wavelength_spin.setObjectName("wavelength_spin")
        self.geometryForm.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.wavelength_spin)
        waxsAdvancedControlTabs.addTab(self.geometryTab, "")

        self.retranslateUi(waxsAdvancedControlTabs)
        waxsAdvancedControlTabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(waxsAdvancedControlTabs)
        waxsAdvancedControlTabs.setTabOrder(self.vmin_spin, self.vmax_spin)
        waxsAdvancedControlTabs.setTabOrder(self.vmax_spin, self.display_auto_scale)
        waxsAdvancedControlTabs.setTabOrder(self.display_auto_scale, self.display_log)
        waxsAdvancedControlTabs.setTabOrder(self.display_log, self.display_cmap)
        waxsAdvancedControlTabs.setTabOrder(self.display_cmap, self.display_flip)
        waxsAdvancedControlTabs.setTabOrder(self.display_flip, self.mask_min_spin)
        waxsAdvancedControlTabs.setTabOrder(self.mask_min_spin, self.mask_max_spin)
        waxsAdvancedControlTabs.setTabOrder(self.mask_max_spin, self.bad_pixel_spin)
        waxsAdvancedControlTabs.setTabOrder(self.bad_pixel_spin, self.apply_mask_check)
        waxsAdvancedControlTabs.setTabOrder(self.apply_mask_check, self.reset_mask_button)
        waxsAdvancedControlTabs.setTabOrder(self.reset_mask_button, self.incidence_spin)
        waxsAdvancedControlTabs.setTabOrder(self.incidence_spin, self.center_x_spin)
        waxsAdvancedControlTabs.setTabOrder(self.center_x_spin, self.center_y_spin)
        waxsAdvancedControlTabs.setTabOrder(self.center_y_spin, self.distance_spin)
        waxsAdvancedControlTabs.setTabOrder(self.distance_spin, self.pixel_x_spin)
        waxsAdvancedControlTabs.setTabOrder(self.pixel_x_spin, self.pixel_y_spin)
        waxsAdvancedControlTabs.setTabOrder(self.pixel_y_spin, self.wavelength_spin)

    def retranslateUi(self, waxsAdvancedControlTabs):
        _translate = QtCore.QCoreApplication.translate
        self.vminLabel.setText(_translate("WaxsAdvancedPanel", "Colorbar Min:"))
        self.vmaxLabel.setText(_translate("WaxsAdvancedPanel", "Colorbar Max:"))
        self.display_auto_scale.setText(_translate("WaxsAdvancedPanel", "Auto color scale"))
        self.display_log.setText(_translate("WaxsAdvancedPanel", "Log intensity"))
        self.displayCmapLabel.setText(_translate("WaxsAdvancedPanel", "Colormap:"))
        self.display_cmap.setItemText(0, _translate("WaxsAdvancedPanel", "turbo"))
        self.display_cmap.setItemText(1, _translate("WaxsAdvancedPanel", "jet"))
        self.display_cmap.setItemText(2, _translate("WaxsAdvancedPanel", "viridis"))
        self.display_cmap.setItemText(3, _translate("WaxsAdvancedPanel", "plasma"))
        self.display_cmap.setItemText(4, _translate("WaxsAdvancedPanel", "inferno"))
        self.display_cmap.setItemText(5, _translate("WaxsAdvancedPanel", "magma"))
        self.display_cmap.setItemText(6, _translate("WaxsAdvancedPanel", "gray"))
        self.display_flip.setText(_translate("WaxsAdvancedPanel", "Flip vertical"))
        waxsAdvancedControlTabs.setTabText(waxsAdvancedControlTabs.indexOf(self.displayTab), _translate("WaxsAdvancedPanel", "Display"))
        self.maskMinLabel.setText(_translate("WaxsAdvancedPanel", "Mask Min:"))
        self.mask_min_spin.setToolTip(_translate("WaxsAdvancedPanel", "Values below this threshold are hidden."))
        self.maskMaxLabel.setText(_translate("WaxsAdvancedPanel", "Mask Max:"))
        self.mask_max_spin.setToolTip(_translate("WaxsAdvancedPanel", "Values above this threshold are hidden."))
        self.badPixelLabel.setText(_translate("WaxsAdvancedPanel", "Bad Pixel Threshold:"))
        self.bad_pixel_spin.setToolTip(_translate("WaxsAdvancedPanel", "Reserved bad-pixel marker for P03-style gap handling."))
        self.apply_mask_check.setText(_translate("WaxsAdvancedPanel", "Apply mask"))
        self.reset_mask_button.setText(_translate("WaxsAdvancedPanel", "Reset Mask"))
        waxsAdvancedControlTabs.setTabText(waxsAdvancedControlTabs.indexOf(self.maskTab), _translate("WaxsAdvancedPanel", "Mask"))
        self.incidenceLabel.setText(_translate("WaxsAdvancedPanel", "Incidence Angle:"))
        self.incidence_spin.setToolTip(_translate("WaxsAdvancedPanel", "Incidence angle in degrees."))
        self.centerXLabel.setText(_translate("WaxsAdvancedPanel", "Beam Center X:"))
        self.centerYLabel.setText(_translate("WaxsAdvancedPanel", "Beam Center Y:"))
        self.distanceLabel.setText(_translate("WaxsAdvancedPanel", "Detector Distance:"))
        self.distance_spin.setToolTip(_translate("WaxsAdvancedPanel", "Detector distance in mm."))
        self.pixelXLabel.setText(_translate("WaxsAdvancedPanel", "Pixel Size X:"))
        self.pixel_x_spin.setToolTip(_translate("WaxsAdvancedPanel", "Detector pixel size X in micrometers."))
        self.pixelYLabel.setText(_translate("WaxsAdvancedPanel", "Pixel Size Y:"))
        self.pixel_y_spin.setToolTip(_translate("WaxsAdvancedPanel", "Detector pixel size Y in micrometers."))
        self.wavelengthLabel.setText(_translate("WaxsAdvancedPanel", "Wavelength:"))
        self.wavelength_spin.setToolTip(_translate("WaxsAdvancedPanel", "Beam wavelength in Angstrom."))
        waxsAdvancedControlTabs.setTabText(waxsAdvancedControlTabs.indexOf(self.geometryTab), _translate("WaxsAdvancedPanel", "Geometry"))
