"""Hand-maintained WAXS batch panel layout."""


from PyQt5 import QtCore, QtGui, QtWidgets


class WaxsBatchPanelView:
    def setupUi(self, waxsBatchPanel):
        waxsBatchPanel.setObjectName("waxsBatchPanel")
        self.batchPanelLayout = QtWidgets.QVBoxLayout(waxsBatchPanel)
        self.batchPanelLayout.setContentsMargins(12, 12, 12, 12)
        self.batchPanelLayout.setSpacing(8)
        self.batchPanelLayout.setObjectName("batchPanelLayout")
        self.batchInputGroup = QtWidgets.QGroupBox(waxsBatchPanel)
        self.batchInputGroup.setObjectName("batchInputGroup")
        self.batchInputLayout = QtWidgets.QGridLayout(self.batchInputGroup)
        self.batchInputLayout.setObjectName("batchInputLayout")
        self.batchInputFolderLabel = QtWidgets.QLabel(self.batchInputGroup)
        self.batchInputFolderLabel.setObjectName("batchInputFolderLabel")
        self.batchInputLayout.addWidget(self.batchInputFolderLabel, 0, 0, 1, 1)
        self.batch_folder_edit = QtWidgets.QLineEdit(self.batchInputGroup)
        self.batch_folder_edit.setObjectName("batch_folder_edit")
        self.batchInputLayout.addWidget(self.batch_folder_edit, 0, 1, 1, 1)
        self.batch_browse_button = QtWidgets.QPushButton(self.batchInputGroup)
        self.batch_browse_button.setObjectName("batch_browse_button")
        self.batchInputLayout.addWidget(self.batch_browse_button, 0, 2, 1, 1)
        self.batchPatternLabel = QtWidgets.QLabel(self.batchInputGroup)
        self.batchPatternLabel.setObjectName("batchPatternLabel")
        self.batchInputLayout.addWidget(self.batchPatternLabel, 1, 0, 1, 1)
        self.batch_pattern_edit = QtWidgets.QLineEdit(self.batchInputGroup)
        self.batch_pattern_edit.setObjectName("batch_pattern_edit")
        self.batchInputLayout.addWidget(self.batch_pattern_edit, 1, 1, 1, 2)
        self.batchOutputFolderLabel = QtWidgets.QLabel(self.batchInputGroup)
        self.batchOutputFolderLabel.setObjectName("batchOutputFolderLabel")
        self.batchInputLayout.addWidget(self.batchOutputFolderLabel, 2, 0, 1, 1)
        self.batch_output_edit = QtWidgets.QLineEdit(self.batchInputGroup)
        self.batch_output_edit.setObjectName("batch_output_edit")
        self.batchInputLayout.addWidget(self.batch_output_edit, 2, 1, 1, 1)
        self.batch_output_browse_button = QtWidgets.QPushButton(self.batchInputGroup)
        self.batch_output_browse_button.setObjectName("batch_output_browse_button")
        self.batchInputLayout.addWidget(self.batch_output_browse_button, 2, 2, 1, 1)
        self.batchPanelLayout.addWidget(self.batchInputGroup)
        self.batchExportGroup = QtWidgets.QGroupBox(waxsBatchPanel)
        self.batchExportGroup.setObjectName("batchExportGroup")
        self.batchExportLayout = QtWidgets.QVBoxLayout(self.batchExportGroup)
        self.batchExportLayout.setObjectName("batchExportLayout")
        self.batch_export_images = QtWidgets.QCheckBox(self.batchExportGroup)
        self.batch_export_images.setObjectName("batch_export_images")
        self.batchExportLayout.addWidget(self.batch_export_images)
        self.batch_export_curves = QtWidgets.QCheckBox(self.batchExportGroup)
        self.batch_export_curves.setObjectName("batch_export_curves")
        self.batchExportLayout.addWidget(self.batch_export_curves)
        self.batch_export_subbg = QtWidgets.QCheckBox(self.batchExportGroup)
        self.batch_export_subbg.setObjectName("batch_export_subbg")
        self.batchExportLayout.addWidget(self.batch_export_subbg)
        self.batchPanelLayout.addWidget(self.batchExportGroup)
        self.batchButtonsLayout = QtWidgets.QHBoxLayout()
        self.batchButtonsLayout.setObjectName("batchButtonsLayout")
        self.batch_start_button = QtWidgets.QPushButton(waxsBatchPanel)
        self.batch_start_button.setObjectName("batch_start_button")
        self.batchButtonsLayout.addWidget(self.batch_start_button)
        self.batch_pause_button = QtWidgets.QPushButton(waxsBatchPanel)
        self.batch_pause_button.setEnabled(False)
        self.batch_pause_button.setObjectName("batch_pause_button")
        self.batchButtonsLayout.addWidget(self.batch_pause_button)
        self.batch_stop_button = QtWidgets.QPushButton(waxsBatchPanel)
        self.batch_stop_button.setEnabled(False)
        self.batch_stop_button.setObjectName("batch_stop_button")
        self.batchButtonsLayout.addWidget(self.batch_stop_button)
        self.batchPanelLayout.addLayout(self.batchButtonsLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.batchPanelLayout.addItem(spacerItem)

        self.retranslateUi(waxsBatchPanel)
        QtCore.QMetaObject.connectSlotsByName(waxsBatchPanel)
        waxsBatchPanel.setTabOrder(self.batch_folder_edit, self.batch_browse_button)
        waxsBatchPanel.setTabOrder(self.batch_browse_button, self.batch_pattern_edit)
        waxsBatchPanel.setTabOrder(self.batch_pattern_edit, self.batch_output_edit)
        waxsBatchPanel.setTabOrder(self.batch_output_edit, self.batch_output_browse_button)
        waxsBatchPanel.setTabOrder(self.batch_output_browse_button, self.batch_export_images)
        waxsBatchPanel.setTabOrder(self.batch_export_images, self.batch_export_curves)
        waxsBatchPanel.setTabOrder(self.batch_export_curves, self.batch_export_subbg)
        waxsBatchPanel.setTabOrder(self.batch_export_subbg, self.batch_start_button)
        waxsBatchPanel.setTabOrder(self.batch_start_button, self.batch_pause_button)
        waxsBatchPanel.setTabOrder(self.batch_pause_button, self.batch_stop_button)

    def retranslateUi(self, waxsBatchPanel):
        _translate = QtCore.QCoreApplication.translate
        self.batchInputGroup.setTitle(_translate("WaxsBatchPanel", "Input"))
        self.batchInputFolderLabel.setText(_translate("WaxsBatchPanel", "Input Folder:"))
        self.batch_browse_button.setText(_translate("WaxsBatchPanel", "Browse"))
        self.batchPatternLabel.setText(_translate("WaxsBatchPanel", "File Pattern:"))
        self.batch_pattern_edit.setToolTip(_translate("WaxsBatchPanel", "Examples: *.tif, *.tiff, *.nxs, *_m*.nxs"))
        self.batch_pattern_edit.setText(_translate("WaxsBatchPanel", "*.tif"))
        self.batchOutputFolderLabel.setText(_translate("WaxsBatchPanel", "Output Folder:"))
        self.batch_output_browse_button.setText(_translate("WaxsBatchPanel", "Output"))
        self.batchExportGroup.setTitle(_translate("WaxsBatchPanel", "Export"))
        self.batch_export_images.setText(_translate("WaxsBatchPanel", "Export 2D images"))
        self.batch_export_curves.setText(_translate("WaxsBatchPanel", "Export 1D curves"))
        self.batch_export_subbg.setText(_translate("WaxsBatchPanel", "Export background-subtracted results"))
        self.batch_start_button.setText(_translate("WaxsBatchPanel", "Start"))
        self.batch_pause_button.setText(_translate("WaxsBatchPanel", "Pause"))
        self.batch_stop_button.setText(_translate("WaxsBatchPanel", "Stop"))
