"""Hand-maintained WAXS workspace layout."""


from PyQt5 import QtCore, QtGui, QtWidgets


class WaxsPageView:
    def setupUi(self, waxsEmbeddedPage):
        waxsEmbeddedPage.setObjectName("waxsEmbeddedPage")
        self.waxsRootLayout = QtWidgets.QVBoxLayout(waxsEmbeddedPage)
        self.waxsRootLayout.setContentsMargins(12, 12, 12, 12)
        self.waxsRootLayout.setSpacing(8)
        self.waxsRootLayout.setObjectName("waxsRootLayout")
        self.waxsInputSection = QtWidgets.QFrame(waxsEmbeddedPage)
        self.waxsInputSection.setProperty("gimapSection", True)
        self.waxsInputSection.setObjectName("waxsInputSection")
        self.waxsInputSectionLayout = QtWidgets.QVBoxLayout(self.waxsInputSection)
        self.waxsInputSectionLayout.setContentsMargins(12, 10, 12, 12)
        self.waxsInputSectionLayout.setSpacing(8)
        self.waxsInputSectionLayout.setObjectName("waxsInputSectionLayout")
        self.waxsInputTitle = QtWidgets.QLabel(self.waxsInputSection)
        self.waxsInputTitle.setProperty("gimapSectionTitle", True)
        self.waxsInputTitle.setObjectName("waxsInputTitle")
        self.waxsInputSectionLayout.addWidget(self.waxsInputTitle)
        self.waxsInputDescription = QtWidgets.QLabel(self.waxsInputSection)
        self.waxsInputDescription.setProperty("gimapSectionDescription", True)
        self.waxsInputDescription.setWordWrap(True)
        self.waxsInputDescription.setObjectName("waxsInputDescription")
        self.waxsInputSectionLayout.addWidget(self.waxsInputDescription)
        self.waxsInputContent = QtWidgets.QWidget(self.waxsInputSection)
        self.waxsInputContent.setObjectName("waxsInputContent")
        self.waxsInputContentLayout = QtWidgets.QVBoxLayout(self.waxsInputContent)
        self.waxsInputContentLayout.setContentsMargins(0, 0, 0, 0)
        self.waxsInputContentLayout.setSpacing(8)
        self.waxsInputContentLayout.setObjectName("waxsInputContentLayout")
        self.waxsInputSectionLayout.addWidget(self.waxsInputContent)
        self.waxsRootLayout.addWidget(self.waxsInputSection)
        self.waxsContentSplitter = QtWidgets.QSplitter(waxsEmbeddedPage)
        self.waxsContentSplitter.setOrientation(QtCore.Qt.Horizontal)
        self.waxsContentSplitter.setChildrenCollapsible(False)
        self.waxsContentSplitter.setHandleWidth(8)
        self.waxsContentSplitter.setObjectName("waxsContentSplitter")
        self.waxsPreviewPanel = QtWidgets.QFrame(self.waxsContentSplitter)
        self.waxsPreviewPanel.setProperty("gimapSection", True)
        self.waxsPreviewPanel.setObjectName("waxsPreviewPanel")
        self.waxsPreviewPanelLayout = QtWidgets.QVBoxLayout(self.waxsPreviewPanel)
        self.waxsPreviewPanelLayout.setContentsMargins(12, 10, 12, 12)
        self.waxsPreviewPanelLayout.setSpacing(8)
        self.waxsPreviewPanelLayout.setObjectName("waxsPreviewPanelLayout")
        self.waxsPreviewTitle = QtWidgets.QLabel(self.waxsPreviewPanel)
        self.waxsPreviewTitle.setProperty("gimapSectionTitle", True)
        self.waxsPreviewTitle.setObjectName("waxsPreviewTitle")
        self.waxsPreviewPanelLayout.addWidget(self.waxsPreviewTitle)
        self.waxsPreviewDescription = QtWidgets.QLabel(self.waxsPreviewPanel)
        self.waxsPreviewDescription.setProperty("gimapSectionDescription", True)
        self.waxsPreviewDescription.setWordWrap(True)
        self.waxsPreviewDescription.setObjectName("waxsPreviewDescription")
        self.waxsPreviewPanelLayout.addWidget(self.waxsPreviewDescription)
        self.waxsPreviewContent = QtWidgets.QWidget(self.waxsPreviewPanel)
        self.waxsPreviewContent.setObjectName("waxsPreviewContent")
        self.waxsPreviewContentLayout = QtWidgets.QVBoxLayout(self.waxsPreviewContent)
        self.waxsPreviewContentLayout.setContentsMargins(0, 0, 0, 0)
        self.waxsPreviewContentLayout.setSpacing(8)
        self.waxsPreviewContentLayout.setObjectName("waxsPreviewContentLayout")
        self.waxsPreviewPanelLayout.addWidget(self.waxsPreviewContent)
        self.waxsControlsScrollArea = QtWidgets.QScrollArea(self.waxsContentSplitter)
        self.waxsControlsScrollArea.setMinimumSize(QtCore.QSize(380, 0))
        self.waxsControlsScrollArea.setMaximumSize(QtCore.QSize(540, 16777215))
        self.waxsControlsScrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.waxsControlsScrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.waxsControlsScrollArea.setWidgetResizable(True)
        self.waxsControlsScrollArea.setObjectName("waxsControlsScrollArea")
        self.waxsControlsContent = QtWidgets.QWidget()
        self.waxsControlsContent.setGeometry(QtCore.QRect(0, 0, 420, 900))
        self.waxsControlsContent.setObjectName("waxsControlsContent")
        self.waxsControlsContentLayout = QtWidgets.QVBoxLayout(self.waxsControlsContent)
        self.waxsControlsContentLayout.setContentsMargins(0, 0, 0, 0)
        self.waxsControlsContentLayout.setSpacing(8)
        self.waxsControlsContentLayout.setObjectName("waxsControlsContentLayout")
        self.waxsConfigureSection = QtWidgets.QFrame(self.waxsControlsContent)
        self.waxsConfigureSection.setProperty("gimapSection", True)
        self.waxsConfigureSection.setObjectName("waxsConfigureSection")
        self.waxsConfigureSectionLayout = QtWidgets.QVBoxLayout(self.waxsConfigureSection)
        self.waxsConfigureSectionLayout.setContentsMargins(12, 10, 12, 12)
        self.waxsConfigureSectionLayout.setSpacing(8)
        self.waxsConfigureSectionLayout.setObjectName("waxsConfigureSectionLayout")
        self.waxsConfigureTitle = QtWidgets.QLabel(self.waxsConfigureSection)
        self.waxsConfigureTitle.setProperty("gimapSectionTitle", True)
        self.waxsConfigureTitle.setObjectName("waxsConfigureTitle")
        self.waxsConfigureSectionLayout.addWidget(self.waxsConfigureTitle)
        self.waxsConfigureDescription = QtWidgets.QLabel(self.waxsConfigureSection)
        self.waxsConfigureDescription.setProperty("gimapSectionDescription", True)
        self.waxsConfigureDescription.setWordWrap(True)
        self.waxsConfigureDescription.setObjectName("waxsConfigureDescription")
        self.waxsConfigureSectionLayout.addWidget(self.waxsConfigureDescription)
        self.waxsConfigureContent = QtWidgets.QWidget(self.waxsConfigureSection)
        self.waxsConfigureContent.setObjectName("waxsConfigureContent")
        self.waxsConfigureContentLayout = QtWidgets.QVBoxLayout(self.waxsConfigureContent)
        self.waxsConfigureContentLayout.setContentsMargins(0, 0, 0, 0)
        self.waxsConfigureContentLayout.setSpacing(8)
        self.waxsConfigureContentLayout.setObjectName("waxsConfigureContentLayout")
        self.waxsConfigureSectionLayout.addWidget(self.waxsConfigureContent)
        self.waxsControlsContentLayout.addWidget(self.waxsConfigureSection)
        self.waxsAdvancedSection = QtWidgets.QFrame(self.waxsControlsContent)
        self.waxsAdvancedSection.setProperty("gimapSection", True)
        self.waxsAdvancedSection.setObjectName("waxsAdvancedSection")
        self.waxsAdvancedSectionLayout = QtWidgets.QVBoxLayout(self.waxsAdvancedSection)
        self.waxsAdvancedSectionLayout.setContentsMargins(8, 8, 8, 8)
        self.waxsAdvancedSectionLayout.setSpacing(7)
        self.waxsAdvancedSectionLayout.setObjectName("waxsAdvancedSectionLayout")
        self.waxsAdvancedToggle = QtWidgets.QToolButton(self.waxsAdvancedSection)
        self.waxsAdvancedToggle.setProperty("gimapAdvancedToggle", True)
        self.waxsAdvancedToggle.setCheckable(True)
        self.waxsAdvancedToggle.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.waxsAdvancedToggle.setArrowType(QtCore.Qt.RightArrow)
        self.waxsAdvancedToggle.setObjectName("waxsAdvancedToggle")
        self.waxsAdvancedSectionLayout.addWidget(self.waxsAdvancedToggle)
        self.waxsAdvancedDescription = QtWidgets.QLabel(self.waxsAdvancedSection)
        self.waxsAdvancedDescription.setVisible(False)
        self.waxsAdvancedDescription.setProperty("gimapSectionDescription", True)
        self.waxsAdvancedDescription.setWordWrap(True)
        self.waxsAdvancedDescription.setObjectName("waxsAdvancedDescription")
        self.waxsAdvancedSectionLayout.addWidget(self.waxsAdvancedDescription)
        self.waxsAdvancedContent = QtWidgets.QWidget(self.waxsAdvancedSection)
        self.waxsAdvancedContent.setVisible(False)
        self.waxsAdvancedContent.setObjectName("waxsAdvancedContent")
        self.waxsAdvancedContentLayout = QtWidgets.QVBoxLayout(self.waxsAdvancedContent)
        self.waxsAdvancedContentLayout.setContentsMargins(4, 2, 4, 4)
        self.waxsAdvancedContentLayout.setSpacing(8)
        self.waxsAdvancedContentLayout.setObjectName("waxsAdvancedContentLayout")
        self.waxsAdvancedSectionLayout.addWidget(self.waxsAdvancedContent)
        self.waxsControlsContentLayout.addWidget(self.waxsAdvancedSection)
        self.waxsRunSection = QtWidgets.QFrame(self.waxsControlsContent)
        self.waxsRunSection.setProperty("gimapSection", True)
        self.waxsRunSection.setObjectName("waxsRunSection")
        self.waxsRunSectionLayout = QtWidgets.QVBoxLayout(self.waxsRunSection)
        self.waxsRunSectionLayout.setContentsMargins(12, 10, 12, 12)
        self.waxsRunSectionLayout.setSpacing(8)
        self.waxsRunSectionLayout.setObjectName("waxsRunSectionLayout")
        self.waxsRunTitle = QtWidgets.QLabel(self.waxsRunSection)
        self.waxsRunTitle.setProperty("gimapSectionTitle", True)
        self.waxsRunTitle.setObjectName("waxsRunTitle")
        self.waxsRunSectionLayout.addWidget(self.waxsRunTitle)
        self.waxsRunDescription = QtWidgets.QLabel(self.waxsRunSection)
        self.waxsRunDescription.setProperty("gimapSectionDescription", True)
        self.waxsRunDescription.setWordWrap(True)
        self.waxsRunDescription.setObjectName("waxsRunDescription")
        self.waxsRunSectionLayout.addWidget(self.waxsRunDescription)
        self.waxsRunContent = QtWidgets.QWidget(self.waxsRunSection)
        self.waxsRunContent.setObjectName("waxsRunContent")
        self.waxsRunContentLayout = QtWidgets.QVBoxLayout(self.waxsRunContent)
        self.waxsRunContentLayout.setContentsMargins(0, 0, 0, 0)
        self.waxsRunContentLayout.setSpacing(8)
        self.waxsRunContentLayout.setObjectName("waxsRunContentLayout")
        self.waxs_job_status = JobStatus(self.waxsRunContent)
        self.waxs_job_status.setObjectName("waxs_job_status")
        self.waxsRunContentLayout.addWidget(self.waxs_job_status)
        self.waxsRunSectionLayout.addWidget(self.waxsRunContent)
        self.waxsControlsContentLayout.addWidget(self.waxsRunSection)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.waxsControlsContentLayout.addItem(spacerItem)
        self.waxsControlsScrollArea.setWidget(self.waxsControlsContent)
        self.waxsRootLayout.addWidget(self.waxsContentSplitter)
        self.waxsOutcomeLayout = QtWidgets.QHBoxLayout()
        self.waxsOutcomeLayout.setSpacing(8)
        self.waxsOutcomeLayout.setObjectName("waxsOutcomeLayout")
        self.waxsResultsSection = QtWidgets.QFrame(waxsEmbeddedPage)
        self.waxsResultsSection.setProperty("gimapSection", True)
        self.waxsResultsSection.setObjectName("waxsResultsSection")
        self.waxsResultsSectionLayout = QtWidgets.QVBoxLayout(self.waxsResultsSection)
        self.waxsResultsSectionLayout.setContentsMargins(12, 10, 12, 12)
        self.waxsResultsSectionLayout.setSpacing(8)
        self.waxsResultsSectionLayout.setObjectName("waxsResultsSectionLayout")
        self.waxsResultsTitle = QtWidgets.QLabel(self.waxsResultsSection)
        self.waxsResultsTitle.setProperty("gimapSectionTitle", True)
        self.waxsResultsTitle.setObjectName("waxsResultsTitle")
        self.waxsResultsSectionLayout.addWidget(self.waxsResultsTitle)
        self.waxsResultsDescription = QtWidgets.QLabel(self.waxsResultsSection)
        self.waxsResultsDescription.setProperty("gimapSectionDescription", True)
        self.waxsResultsDescription.setWordWrap(True)
        self.waxsResultsDescription.setObjectName("waxsResultsDescription")
        self.waxsResultsSectionLayout.addWidget(self.waxsResultsDescription)
        self.waxsResultsContent = QtWidgets.QWidget(self.waxsResultsSection)
        self.waxsResultsContent.setObjectName("waxsResultsContent")
        self.waxsResultsContentLayout = QtWidgets.QVBoxLayout(self.waxsResultsContent)
        self.waxsResultsContentLayout.setContentsMargins(0, 0, 0, 0)
        self.waxsResultsContentLayout.setObjectName("waxsResultsContentLayout")
        self.integration_status = QtWidgets.QLabel(self.waxsResultsContent)
        self.integration_status.setWordWrap(True)
        self.integration_status.setObjectName("integration_status")
        self.waxsResultsContentLayout.addWidget(self.integration_status)
        self.waxsResultsSectionLayout.addWidget(self.waxsResultsContent)
        self.waxsOutcomeLayout.addWidget(self.waxsResultsSection)
        self.waxsExportSection = QtWidgets.QFrame(waxsEmbeddedPage)
        self.waxsExportSection.setProperty("gimapSection", True)
        self.waxsExportSection.setObjectName("waxsExportSection")
        self.waxsExportSectionLayout = QtWidgets.QVBoxLayout(self.waxsExportSection)
        self.waxsExportSectionLayout.setContentsMargins(12, 10, 12, 12)
        self.waxsExportSectionLayout.setSpacing(8)
        self.waxsExportSectionLayout.setObjectName("waxsExportSectionLayout")
        self.waxsExportTitle = QtWidgets.QLabel(self.waxsExportSection)
        self.waxsExportTitle.setProperty("gimapSectionTitle", True)
        self.waxsExportTitle.setObjectName("waxsExportTitle")
        self.waxsExportSectionLayout.addWidget(self.waxsExportTitle)
        self.waxsExportDescription = QtWidgets.QLabel(self.waxsExportSection)
        self.waxsExportDescription.setProperty("gimapSectionDescription", True)
        self.waxsExportDescription.setWordWrap(True)
        self.waxsExportDescription.setObjectName("waxsExportDescription")
        self.waxsExportSectionLayout.addWidget(self.waxsExportDescription)
        self.waxsExportContent = QtWidgets.QWidget(self.waxsExportSection)
        self.waxsExportContent.setObjectName("waxsExportContent")
        self.waxsExportContentLayout = QtWidgets.QHBoxLayout(self.waxsExportContent)
        self.waxsExportContentLayout.setContentsMargins(0, 0, 0, 0)
        self.waxsExportContentLayout.setSpacing(8)
        self.waxsExportContentLayout.setObjectName("waxsExportContentLayout")
        self.export_button = QtWidgets.QPushButton(self.waxsExportContent)
        self.export_button.setObjectName("export_button")
        self.waxsExportContentLayout.addWidget(self.export_button)
        self.export_1d_button = QtWidgets.QPushButton(self.waxsExportContent)
        self.export_1d_button.setObjectName("export_1d_button")
        self.waxsExportContentLayout.addWidget(self.export_1d_button)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.waxsExportContentLayout.addItem(spacerItem1)
        self.waxsExportSectionLayout.addWidget(self.waxsExportContent)
        self.waxsOutcomeLayout.addWidget(self.waxsExportSection)
        self.waxsRootLayout.addLayout(self.waxsOutcomeLayout)
        self.waxsRootLayout.setStretch(1, 1)

        self.retranslateUi(waxsEmbeddedPage)
        QtCore.QMetaObject.connectSlotsByName(waxsEmbeddedPage)

    def retranslateUi(self, waxsEmbeddedPage):
        _translate = QtCore.QCoreApplication.translate
        self.waxsInputTitle.setText(_translate("WaxsPage", "Input"))
        self.waxsInputDescription.setText(_translate("WaxsPage", "Open a detector file, reload it or select a frame from an NXS stack."))
        self.waxsPreviewTitle.setText(_translate("WaxsPage", "Preview"))
        self.waxsPreviewDescription.setText(_translate("WaxsPage", "Inspect the 2D detector image or the calculated 1D curve."))
        self.waxsConfigureTitle.setText(_translate("WaxsPage", "Configure"))
        self.waxsConfigureDescription.setText(_translate("WaxsPage", "Choose the ROI/cut definition and 1D integration settings."))
        self.waxsAdvancedToggle.setText(_translate("WaxsPage", "Advanced display, mask and geometry"))
        self.waxsAdvancedDescription.setText(_translate("WaxsPage", "Tune rendering, detector masking and reciprocal-space geometry."))
        self.waxsRunTitle.setText(_translate("WaxsPage", "Run"))
        self.waxsRunDescription.setText(_translate("WaxsPage", "Batch and in-situ processing continue through the existing WaxsViewModel and JobRunner adapter."))
        self.waxsResultsTitle.setText(_translate("WaxsPage", "Results"))
        self.waxsResultsDescription.setText(_translate("WaxsPage", "The latest integration result and point count are reported here."))
        self.integration_status.setText(_translate("WaxsPage", "No curve calculated."))
        self.waxsExportTitle.setText(_translate("WaxsPage", "Export"))
        self.waxsExportDescription.setText(_translate("WaxsPage", "Export the current 2D image or calculated 1D curve with the original actions."))
        self.export_button.setText(_translate("WaxsPage", "Export Image"))
        self.export_1d_button.setText(_translate("WaxsPage", "Export 1D"))
from src.gimap.app.presentation import JobStatus
