"""Hand-maintained WAXS ROI panel layout."""


from PyQt5 import QtCore, QtGui, QtWidgets


class WaxsRoiPanelView:
    def setupUi(self, waxsRoiPanel):
        waxsRoiPanel.setObjectName("waxsRoiPanel")
        self.roi_layout = QtWidgets.QFormLayout(waxsRoiPanel)
        self.roi_layout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.roi_layout.setRowWrapPolicy(QtWidgets.QFormLayout.WrapLongRows)
        self.roi_layout.setContentsMargins(12, 12, 12, 12)
        self.roi_layout.setSpacing(8)
        self.roi_layout.setObjectName("roi_layout")
        self.cutTypeLabel = QtWidgets.QLabel(waxsRoiPanel)
        self.cutTypeLabel.setObjectName("cutTypeLabel")
        self.roi_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.cutTypeLabel)
        self.cut_type_combo = QtWidgets.QComboBox(waxsRoiPanel)
        self.cut_type_combo.setObjectName("cut_type_combo")
        self.cut_type_combo.addItem("")
        self.cut_type_combo.addItem("")
        self.cut_type_combo.addItem("")
        self.roi_layout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cut_type_combo)
        self.show_cut_region_check = QtWidgets.QCheckBox(waxsRoiPanel)
        self.show_cut_region_check.setChecked(True)
        self.show_cut_region_check.setObjectName("show_cut_region_check")
        self.roi_layout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.show_cut_region_check)
        self.show_center_check = QtWidgets.QCheckBox(waxsRoiPanel)
        self.show_center_check.setChecked(True)
        self.show_center_check.setObjectName("show_center_check")
        self.roi_layout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.show_center_check)
        self.pick_center_button = QtWidgets.QPushButton(waxsRoiPanel)
        self.pick_center_button.setObjectName("pick_center_button")
        self.roi_layout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.pick_center_button)
        self.q_range_header = QtWidgets.QLabel(waxsRoiPanel)
        self.q_range_header.setObjectName("q_range_header")
        self.roi_layout.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.q_range_header)
        self.qrMinLabel = QtWidgets.QLabel(waxsRoiPanel)
        self.qrMinLabel.setObjectName("qrMinLabel")
        self.roi_layout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.qrMinLabel)
        self.qr_min_spin = QtWidgets.QDoubleSpinBox(waxsRoiPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qr_min_spin.sizePolicy().hasHeightForWidth())
        self.qr_min_spin.setSizePolicy(sizePolicy)
        self.qr_min_spin.setDecimals(9)
        self.qr_min_spin.setMinimum(-1000000.0)
        self.qr_min_spin.setMaximum(1000000.0)
        self.qr_min_spin.setSingleStep(0.1)
        self.qr_min_spin.setProperty("value", -121.0)
        self.qr_min_spin.setObjectName("qr_min_spin")
        self.roi_layout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.qr_min_spin)
        self.qrMaxLabel = QtWidgets.QLabel(waxsRoiPanel)
        self.qrMaxLabel.setObjectName("qrMaxLabel")
        self.roi_layout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.qrMaxLabel)
        self.qr_max_spin = QtWidgets.QDoubleSpinBox(waxsRoiPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qr_max_spin.sizePolicy().hasHeightForWidth())
        self.qr_max_spin.setSizePolicy(sizePolicy)
        self.qr_max_spin.setDecimals(9)
        self.qr_max_spin.setMinimum(-1000000.0)
        self.qr_max_spin.setMaximum(1000000.0)
        self.qr_max_spin.setSingleStep(0.1)
        self.qr_max_spin.setProperty("value", -121.0)
        self.qr_max_spin.setObjectName("qr_max_spin")
        self.roi_layout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.qr_max_spin)
        self.qzMinLabel = QtWidgets.QLabel(waxsRoiPanel)
        self.qzMinLabel.setObjectName("qzMinLabel")
        self.roi_layout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.qzMinLabel)
        self.qz_min_spin = QtWidgets.QDoubleSpinBox(waxsRoiPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qz_min_spin.sizePolicy().hasHeightForWidth())
        self.qz_min_spin.setSizePolicy(sizePolicy)
        self.qz_min_spin.setDecimals(9)
        self.qz_min_spin.setMinimum(-1000000.0)
        self.qz_min_spin.setMaximum(1000000.0)
        self.qz_min_spin.setSingleStep(0.1)
        self.qz_min_spin.setProperty("value", -121.0)
        self.qz_min_spin.setObjectName("qz_min_spin")
        self.roi_layout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.qz_min_spin)
        self.qzMaxLabel = QtWidgets.QLabel(waxsRoiPanel)
        self.qzMaxLabel.setObjectName("qzMaxLabel")
        self.roi_layout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.qzMaxLabel)
        self.qz_max_spin = QtWidgets.QDoubleSpinBox(waxsRoiPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qz_max_spin.sizePolicy().hasHeightForWidth())
        self.qz_max_spin.setSizePolicy(sizePolicy)
        self.qz_max_spin.setDecimals(9)
        self.qz_max_spin.setMinimum(-1000000.0)
        self.qz_max_spin.setMaximum(1000000.0)
        self.qz_max_spin.setSingleStep(0.1)
        self.qz_max_spin.setProperty("value", -121.0)
        self.qz_max_spin.setObjectName("qz_max_spin")
        self.roi_layout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.qz_max_spin)
        self.qRangeHint = QtWidgets.QLabel(waxsRoiPanel)
        self.qRangeHint.setWordWrap(True)
        self.qRangeHint.setObjectName("qRangeHint")
        self.roi_layout.setWidget(9, QtWidgets.QFormLayout.SpanningRole, self.qRangeHint)
        self.select_roi_button = QtWidgets.QPushButton(waxsRoiPanel)
        self.select_roi_button.setObjectName("select_roi_button")
        self.roi_layout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.select_roi_button)
        self.line_cut_header = QtWidgets.QLabel(waxsRoiPanel)
        self.line_cut_header.setObjectName("line_cut_header")
        self.roi_layout.setWidget(11, QtWidgets.QFormLayout.SpanningRole, self.line_cut_header)
        self.lineCenterXLabel = QtWidgets.QLabel(waxsRoiPanel)
        self.lineCenterXLabel.setObjectName("lineCenterXLabel")
        self.roi_layout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.lineCenterXLabel)
        self.line_center_x_spin = QtWidgets.QDoubleSpinBox(waxsRoiPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_center_x_spin.sizePolicy().hasHeightForWidth())
        self.line_center_x_spin.setSizePolicy(sizePolicy)
        self.line_center_x_spin.setDecimals(9)
        self.line_center_x_spin.setMinimum(-1000000.0)
        self.line_center_x_spin.setMaximum(1000000.0)
        self.line_center_x_spin.setSingleStep(0.1)
        self.line_center_x_spin.setProperty("value", 1000.0)
        self.line_center_x_spin.setObjectName("line_center_x_spin")
        self.roi_layout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.line_center_x_spin)
        self.lineCenterYLabel = QtWidgets.QLabel(waxsRoiPanel)
        self.lineCenterYLabel.setObjectName("lineCenterYLabel")
        self.roi_layout.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.lineCenterYLabel)
        self.line_center_y_spin = QtWidgets.QDoubleSpinBox(waxsRoiPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_center_y_spin.sizePolicy().hasHeightForWidth())
        self.line_center_y_spin.setSizePolicy(sizePolicy)
        self.line_center_y_spin.setDecimals(9)
        self.line_center_y_spin.setMinimum(-1000000.0)
        self.line_center_y_spin.setMaximum(1000000.0)
        self.line_center_y_spin.setSingleStep(0.1)
        self.line_center_y_spin.setProperty("value", 1000.0)
        self.line_center_y_spin.setObjectName("line_center_y_spin")
        self.roi_layout.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.line_center_y_spin)
        self.lineWidthLabel = QtWidgets.QLabel(waxsRoiPanel)
        self.lineWidthLabel.setObjectName("lineWidthLabel")
        self.roi_layout.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.lineWidthLabel)
        self.line_width_spin = QtWidgets.QDoubleSpinBox(waxsRoiPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_width_spin.sizePolicy().hasHeightForWidth())
        self.line_width_spin.setSizePolicy(sizePolicy)
        self.line_width_spin.setDecimals(9)
        self.line_width_spin.setMaximum(1000000.0)
        self.line_width_spin.setSingleStep(0.1)
        self.line_width_spin.setProperty("value", 100.0)
        self.line_width_spin.setObjectName("line_width_spin")
        self.roi_layout.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.line_width_spin)
        self.lineHeightLabel = QtWidgets.QLabel(waxsRoiPanel)
        self.lineHeightLabel.setObjectName("lineHeightLabel")
        self.roi_layout.setWidget(15, QtWidgets.QFormLayout.LabelRole, self.lineHeightLabel)
        self.line_height_spin = QtWidgets.QDoubleSpinBox(waxsRoiPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_height_spin.sizePolicy().hasHeightForWidth())
        self.line_height_spin.setSizePolicy(sizePolicy)
        self.line_height_spin.setDecimals(9)
        self.line_height_spin.setMaximum(1000000.0)
        self.line_height_spin.setSingleStep(0.1)
        self.line_height_spin.setProperty("value", 20.0)
        self.line_height_spin.setObjectName("line_height_spin")
        self.roi_layout.setWidget(15, QtWidgets.QFormLayout.FieldRole, self.line_height_spin)
        self.select_line_button = QtWidgets.QPushButton(waxsRoiPanel)
        self.select_line_button.setObjectName("select_line_button")
        self.roi_layout.setWidget(16, QtWidgets.QFormLayout.FieldRole, self.select_line_button)
        self.circle_cut_header = QtWidgets.QLabel(waxsRoiPanel)
        self.circle_cut_header.setObjectName("circle_cut_header")
        self.roi_layout.setWidget(17, QtWidgets.QFormLayout.SpanningRole, self.circle_cut_header)
        self.circleCenterXLabel = QtWidgets.QLabel(waxsRoiPanel)
        self.circleCenterXLabel.setObjectName("circleCenterXLabel")
        self.roi_layout.setWidget(18, QtWidgets.QFormLayout.LabelRole, self.circleCenterXLabel)
        self.circle_center_x_spin = QtWidgets.QDoubleSpinBox(waxsRoiPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.circle_center_x_spin.sizePolicy().hasHeightForWidth())
        self.circle_center_x_spin.setSizePolicy(sizePolicy)
        self.circle_center_x_spin.setDecimals(9)
        self.circle_center_x_spin.setMinimum(-1000000.0)
        self.circle_center_x_spin.setMaximum(1000000.0)
        self.circle_center_x_spin.setSingleStep(0.1)
        self.circle_center_x_spin.setProperty("value", 1000.0)
        self.circle_center_x_spin.setObjectName("circle_center_x_spin")
        self.roi_layout.setWidget(18, QtWidgets.QFormLayout.FieldRole, self.circle_center_x_spin)
        self.circleCenterYLabel = QtWidgets.QLabel(waxsRoiPanel)
        self.circleCenterYLabel.setObjectName("circleCenterYLabel")
        self.roi_layout.setWidget(19, QtWidgets.QFormLayout.LabelRole, self.circleCenterYLabel)
        self.circle_center_y_spin = QtWidgets.QDoubleSpinBox(waxsRoiPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.circle_center_y_spin.sizePolicy().hasHeightForWidth())
        self.circle_center_y_spin.setSizePolicy(sizePolicy)
        self.circle_center_y_spin.setDecimals(9)
        self.circle_center_y_spin.setMinimum(-1000000.0)
        self.circle_center_y_spin.setMaximum(1000000.0)
        self.circle_center_y_spin.setSingleStep(0.1)
        self.circle_center_y_spin.setProperty("value", 1000.0)
        self.circle_center_y_spin.setObjectName("circle_center_y_spin")
        self.roi_layout.setWidget(19, QtWidgets.QFormLayout.FieldRole, self.circle_center_y_spin)
        self.circleInnerLabel = QtWidgets.QLabel(waxsRoiPanel)
        self.circleInnerLabel.setObjectName("circleInnerLabel")
        self.roi_layout.setWidget(20, QtWidgets.QFormLayout.LabelRole, self.circleInnerLabel)
        self.circle_inner_spin = QtWidgets.QDoubleSpinBox(waxsRoiPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.circle_inner_spin.sizePolicy().hasHeightForWidth())
        self.circle_inner_spin.setSizePolicy(sizePolicy)
        self.circle_inner_spin.setDecimals(9)
        self.circle_inner_spin.setMaximum(1000000.0)
        self.circle_inner_spin.setSingleStep(0.1)
        self.circle_inner_spin.setProperty("value", 50.0)
        self.circle_inner_spin.setObjectName("circle_inner_spin")
        self.roi_layout.setWidget(20, QtWidgets.QFormLayout.FieldRole, self.circle_inner_spin)
        self.circleOuterLabel = QtWidgets.QLabel(waxsRoiPanel)
        self.circleOuterLabel.setObjectName("circleOuterLabel")
        self.roi_layout.setWidget(21, QtWidgets.QFormLayout.LabelRole, self.circleOuterLabel)
        self.circle_outer_spin = QtWidgets.QDoubleSpinBox(waxsRoiPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.circle_outer_spin.sizePolicy().hasHeightForWidth())
        self.circle_outer_spin.setSizePolicy(sizePolicy)
        self.circle_outer_spin.setDecimals(9)
        self.circle_outer_spin.setMaximum(1000000.0)
        self.circle_outer_spin.setSingleStep(0.1)
        self.circle_outer_spin.setProperty("value", 200.0)
        self.circle_outer_spin.setObjectName("circle_outer_spin")
        self.roi_layout.setWidget(21, QtWidgets.QFormLayout.FieldRole, self.circle_outer_spin)
        self.circleStartLabel = QtWidgets.QLabel(waxsRoiPanel)
        self.circleStartLabel.setObjectName("circleStartLabel")
        self.roi_layout.setWidget(22, QtWidgets.QFormLayout.LabelRole, self.circleStartLabel)
        self.circle_start_spin = QtWidgets.QDoubleSpinBox(waxsRoiPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.circle_start_spin.sizePolicy().hasHeightForWidth())
        self.circle_start_spin.setSizePolicy(sizePolicy)
        self.circle_start_spin.setDecimals(9)
        self.circle_start_spin.setMinimum(-360.0)
        self.circle_start_spin.setMaximum(360.0)
        self.circle_start_spin.setSingleStep(0.1)
        self.circle_start_spin.setProperty("value", -180.0)
        self.circle_start_spin.setObjectName("circle_start_spin")
        self.roi_layout.setWidget(22, QtWidgets.QFormLayout.FieldRole, self.circle_start_spin)
        self.circleEndLabel = QtWidgets.QLabel(waxsRoiPanel)
        self.circleEndLabel.setObjectName("circleEndLabel")
        self.roi_layout.setWidget(23, QtWidgets.QFormLayout.LabelRole, self.circleEndLabel)
        self.circle_end_spin = QtWidgets.QDoubleSpinBox(waxsRoiPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.circle_end_spin.sizePolicy().hasHeightForWidth())
        self.circle_end_spin.setSizePolicy(sizePolicy)
        self.circle_end_spin.setDecimals(9)
        self.circle_end_spin.setMinimum(-360.0)
        self.circle_end_spin.setMaximum(360.0)
        self.circle_end_spin.setSingleStep(0.1)
        self.circle_end_spin.setProperty("value", 180.0)
        self.circle_end_spin.setObjectName("circle_end_spin")
        self.roi_layout.setWidget(23, QtWidgets.QFormLayout.FieldRole, self.circle_end_spin)
        self.select_circle_button = QtWidgets.QPushButton(waxsRoiPanel)
        self.select_circle_button.setObjectName("select_circle_button")
        self.roi_layout.setWidget(24, QtWidgets.QFormLayout.FieldRole, self.select_circle_button)
        self.clear_roi_button = QtWidgets.QPushButton(waxsRoiPanel)
        self.clear_roi_button.setObjectName("clear_roi_button")
        self.roi_layout.setWidget(25, QtWidgets.QFormLayout.FieldRole, self.clear_roi_button)
        self.apply_cut_button = QtWidgets.QPushButton(waxsRoiPanel)
        self.apply_cut_button.setObjectName("apply_cut_button")
        self.roi_layout.setWidget(26, QtWidgets.QFormLayout.FieldRole, self.apply_cut_button)

        self.retranslateUi(waxsRoiPanel)
        QtCore.QMetaObject.connectSlotsByName(waxsRoiPanel)
        waxsRoiPanel.setTabOrder(self.cut_type_combo, self.show_cut_region_check)
        waxsRoiPanel.setTabOrder(self.show_cut_region_check, self.show_center_check)
        waxsRoiPanel.setTabOrder(self.show_center_check, self.pick_center_button)
        waxsRoiPanel.setTabOrder(self.pick_center_button, self.qr_min_spin)
        waxsRoiPanel.setTabOrder(self.qr_min_spin, self.qr_max_spin)
        waxsRoiPanel.setTabOrder(self.qr_max_spin, self.qz_min_spin)
        waxsRoiPanel.setTabOrder(self.qz_min_spin, self.qz_max_spin)
        waxsRoiPanel.setTabOrder(self.qz_max_spin, self.select_roi_button)
        waxsRoiPanel.setTabOrder(self.select_roi_button, self.line_center_x_spin)
        waxsRoiPanel.setTabOrder(self.line_center_x_spin, self.line_center_y_spin)
        waxsRoiPanel.setTabOrder(self.line_center_y_spin, self.line_width_spin)
        waxsRoiPanel.setTabOrder(self.line_width_spin, self.line_height_spin)
        waxsRoiPanel.setTabOrder(self.line_height_spin, self.select_line_button)
        waxsRoiPanel.setTabOrder(self.select_line_button, self.circle_center_x_spin)
        waxsRoiPanel.setTabOrder(self.circle_center_x_spin, self.circle_center_y_spin)
        waxsRoiPanel.setTabOrder(self.circle_center_y_spin, self.circle_inner_spin)
        waxsRoiPanel.setTabOrder(self.circle_inner_spin, self.circle_outer_spin)
        waxsRoiPanel.setTabOrder(self.circle_outer_spin, self.circle_start_spin)
        waxsRoiPanel.setTabOrder(self.circle_start_spin, self.circle_end_spin)
        waxsRoiPanel.setTabOrder(self.circle_end_spin, self.select_circle_button)
        waxsRoiPanel.setTabOrder(self.select_circle_button, self.clear_roi_button)
        waxsRoiPanel.setTabOrder(self.clear_roi_button, self.apply_cut_button)

    def retranslateUi(self, waxsRoiPanel):
        _translate = QtCore.QCoreApplication.translate
        self.cutTypeLabel.setText(_translate("WaxsRoiPanel", "Cut Type:"))
        self.cut_type_combo.setItemText(0, _translate("WaxsRoiPanel", "Q Range"))
        self.cut_type_combo.setItemText(1, _translate("WaxsRoiPanel", "Line Cut"))
        self.cut_type_combo.setItemText(2, _translate("WaxsRoiPanel", "Circle Cut"))
        self.show_cut_region_check.setText(_translate("WaxsRoiPanel", "Show Cut Region"))
        self.show_center_check.setText(_translate("WaxsRoiPanel", "Show Center"))
        self.pick_center_button.setText(_translate("WaxsRoiPanel", "Pick Center"))
        self.q_range_header.setText(_translate("WaxsRoiPanel", "<b>Q Range</b>"))
        self.qrMinLabel.setText(_translate("WaxsRoiPanel", "Qr Min:"))
        self.qrMaxLabel.setText(_translate("WaxsRoiPanel", "Qr Max:"))
        self.qzMinLabel.setText(_translate("WaxsRoiPanel", "Qz Min:"))
        self.qzMaxLabel.setText(_translate("WaxsRoiPanel", "Qz Max:"))
        self.qRangeHint.setText(_translate("WaxsRoiPanel", "Use -121 for no Q-range limit."))
        self.select_roi_button.setText(_translate("WaxsRoiPanel", "Select Q Range from Image"))
        self.line_cut_header.setText(_translate("WaxsRoiPanel", "<b>Line Cut</b>"))
        self.lineCenterXLabel.setText(_translate("WaxsRoiPanel", "Center X:"))
        self.lineCenterYLabel.setText(_translate("WaxsRoiPanel", "Center Y:"))
        self.lineWidthLabel.setText(_translate("WaxsRoiPanel", "Width:"))
        self.lineHeightLabel.setText(_translate("WaxsRoiPanel", "Height:"))
        self.select_line_button.setText(_translate("WaxsRoiPanel", "Select Line Cut"))
        self.circle_cut_header.setText(_translate("WaxsRoiPanel", "<b>Circle Cut</b>"))
        self.circleCenterXLabel.setText(_translate("WaxsRoiPanel", "Center X:"))
        self.circleCenterYLabel.setText(_translate("WaxsRoiPanel", "Center Y:"))
        self.circleInnerLabel.setText(_translate("WaxsRoiPanel", "Inner Radius:"))
        self.circleOuterLabel.setText(_translate("WaxsRoiPanel", "Outer Radius:"))
        self.circleStartLabel.setText(_translate("WaxsRoiPanel", "Start Angle:"))
        self.circleEndLabel.setText(_translate("WaxsRoiPanel", "End Angle:"))
        self.select_circle_button.setText(_translate("WaxsRoiPanel", "Select Circle Cut"))
        self.clear_roi_button.setText(_translate("WaxsRoiPanel", "Clear ROI"))
        self.apply_cut_button.setText(_translate("WaxsRoiPanel", "Apply Cut"))
