"""Hand-maintained WAXS toolbar layout."""


from PyQt5 import QtCore, QtGui, QtWidgets


class WaxsToolbarView:
    def setupUi(self, waxsTopToolbar):
        waxsTopToolbar.setObjectName("waxsTopToolbar")
        self.waxsToolbarLayout = QtWidgets.QHBoxLayout(waxsTopToolbar)
        self.waxsToolbarLayout.setContentsMargins(8, 6, 8, 6)
        self.waxsToolbarLayout.setSpacing(8)
        self.waxsToolbarLayout.setObjectName("waxsToolbarLayout")
        self.open_button = QtWidgets.QPushButton(waxsTopToolbar)
        self.open_button.setObjectName("open_button")
        self.waxsToolbarLayout.addWidget(self.open_button)
        self.reload_button = QtWidgets.QPushButton(waxsTopToolbar)
        self.reload_button.setObjectName("reload_button")
        self.waxsToolbarLayout.addWidget(self.reload_button)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.waxsToolbarLayout.addItem(spacerItem)
        self.frame_label = QtWidgets.QLabel(waxsTopToolbar)
        self.frame_label.setObjectName("frame_label")
        self.waxsToolbarLayout.addWidget(self.frame_label)
        self.frame_spin = QtWidgets.QSpinBox(waxsTopToolbar)
        self.frame_spin.setMinimum(1)
        self.frame_spin.setMaximum(1)
        self.frame_spin.setProperty("value", 1)
        self.frame_spin.setObjectName("frame_spin")
        self.waxsToolbarLayout.addWidget(self.frame_spin)
        spacerItem1 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.waxsToolbarLayout.addItem(spacerItem1)
        self.toolbar_auto_scale = QtWidgets.QCheckBox(waxsTopToolbar)
        self.toolbar_auto_scale.setChecked(True)
        self.toolbar_auto_scale.setObjectName("toolbar_auto_scale")
        self.waxsToolbarLayout.addWidget(self.toolbar_auto_scale)
        self.toolbar_log_scale = QtWidgets.QCheckBox(waxsTopToolbar)
        self.toolbar_log_scale.setObjectName("toolbar_log_scale")
        self.waxsToolbarLayout.addWidget(self.toolbar_log_scale)
        self.toolbarColormapLabel = QtWidgets.QLabel(waxsTopToolbar)
        self.toolbarColormapLabel.setObjectName("toolbarColormapLabel")
        self.waxsToolbarLayout.addWidget(self.toolbarColormapLabel)
        self.toolbar_cmap = QtWidgets.QComboBox(waxsTopToolbar)
        self.toolbar_cmap.setObjectName("toolbar_cmap")
        self.toolbar_cmap.addItem("")
        self.toolbar_cmap.addItem("")
        self.toolbar_cmap.addItem("")
        self.toolbar_cmap.addItem("")
        self.toolbar_cmap.addItem("")
        self.toolbar_cmap.addItem("")
        self.toolbar_cmap.addItem("")
        self.waxsToolbarLayout.addWidget(self.toolbar_cmap)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.waxsToolbarLayout.addItem(spacerItem2)

        self.retranslateUi(waxsTopToolbar)
        QtCore.QMetaObject.connectSlotsByName(waxsTopToolbar)
        waxsTopToolbar.setTabOrder(self.open_button, self.reload_button)
        waxsTopToolbar.setTabOrder(self.reload_button, self.frame_spin)
        waxsTopToolbar.setTabOrder(self.frame_spin, self.toolbar_auto_scale)
        waxsTopToolbar.setTabOrder(self.toolbar_auto_scale, self.toolbar_log_scale)
        waxsTopToolbar.setTabOrder(self.toolbar_log_scale, self.toolbar_cmap)

    def retranslateUi(self, waxsTopToolbar):
        _translate = QtCore.QCoreApplication.translate
        self.open_button.setText(_translate("WaxsToolbar", "Open File"))
        self.reload_button.setText(_translate("WaxsToolbar", "Reload"))
        self.frame_label.setText(_translate("WaxsToolbar", "Frame:"))
        self.frame_spin.setToolTip(_translate("WaxsToolbar", "Frame selector for .nxs files"))
        self.toolbar_auto_scale.setText(_translate("WaxsToolbar", "Auto Scale"))
        self.toolbar_log_scale.setText(_translate("WaxsToolbar", "Log Scale"))
        self.toolbarColormapLabel.setText(_translate("WaxsToolbar", "Colormap:"))
        self.toolbar_cmap.setItemText(0, _translate("WaxsToolbar", "turbo"))
        self.toolbar_cmap.setItemText(1, _translate("WaxsToolbar", "jet"))
        self.toolbar_cmap.setItemText(2, _translate("WaxsToolbar", "viridis"))
        self.toolbar_cmap.setItemText(3, _translate("WaxsToolbar", "plasma"))
        self.toolbar_cmap.setItemText(4, _translate("WaxsToolbar", "inferno"))
        self.toolbar_cmap.setItemText(5, _translate("WaxsToolbar", "magma"))
        self.toolbar_cmap.setItemText(6, _translate("WaxsToolbar", "gray"))
