"""Stable physical-background parameter definitions."""

PHYSICAL_BACKGROUND_PARAMETERS = (
    {
        "key": "target_fraction",
        "label": "Overall level / signal",
        "minimum": 0.05,
        "maximum": 0.30,
        "decimals": 3,
        "help": "Background 95th percentile relative to the simulated signal 75th percentile.",
    },
    {
        "key": "constant_fraction",
        "label": "Constant floor",
        "minimum": 0.00,
        "maximum": 0.03,
        "decimals": 3,
        "help": "Uniform detector background before the overall relative scaling is applied.",
    },
    {
        "key": "specular_amplitude",
        "label": "Specular ridge amplitude",
        "minimum": 0.20,
        "maximum": 1.00,
        "decimals": 3,
        "help": "Relative strength of the narrow vertical specular ridge around qy = 0.",
    },
    {
        "key": "specular_width_fraction",
        "label": "Specular qy width",
        "minimum": 0.01,
        "maximum": 0.04,
        "decimals": 4,
        "help": "Gaussian ridge width as a fraction of the ROI qy span.",
    },
    {
        "key": "specular_widening",
        "label": "Specular widening",
        "minimum": 0.00,
        "maximum": 0.12,
        "decimals": 3,
        "help": "How much the specular ridge widens toward larger qz.",
    },
    {
        "key": "specular_decay_fraction",
        "label": "Specular qz decay",
        "minimum": 0.20,
        "maximum": 0.80,
        "decimals": 3,
        "help": "Vertical decay length as a fraction of the ROI qz span.",
    },
    {
        "key": "yoneda_amplitude",
        "label": "Yoneda band amplitude",
        "minimum": 0.10,
        "maximum": 0.70,
        "decimals": 3,
        "help": "Relative strength of the horizontal Yoneda-like band.",
    },
    {
        "key": "yoneda_center_fraction",
        "label": "Yoneda qz position",
        "minimum": 0.50,
        "maximum": 0.72,
        "decimals": 3,
        "help": "Vertical band position from ROI bottom (0) to top (1) in qz coordinates.",
    },
    {
        "key": "yoneda_width_fraction",
        "label": "Yoneda qz width",
        "minimum": 0.02,
        "maximum": 0.08,
        "decimals": 3,
        "help": "Gaussian band width as a fraction of the ROI qz span.",
    },
    {
        "key": "yoneda_center_hole",
        "label": "Yoneda center hole",
        "minimum": 0.40,
        "maximum": 0.95,
        "decimals": 3,
        "help": "Suppresses the Yoneda band close to qy = 0 to avoid an unrealistically bright cross.",
    },
    {
        "key": "wedge_amplitude",
        "label": "Diffuse wedge amplitude",
        "minimum": 0.05,
        "maximum": 0.40,
        "decimals": 3,
        "help": "Relative strength of the anisotropic Guinier–Porod diffuse component.",
    },
    {
        "key": "wedge_anisotropy",
        "label": "Diffuse anisotropy",
        "minimum": 0.60,
        "maximum": 2.00,
        "decimals": 3,
        "help": "Aspect ratio of the diffuse wedge in qy versus qz.",
    },
    {
        "key": "wedge_porod_exponent",
        "label": "Porod exponent",
        "minimum": 2.00,
        "maximum": 3.80,
        "decimals": 3,
        "help": "Controls how quickly the diffuse tail decays at high q.",
    },
    {
        "key": "wedge_rg_fraction",
        "label": "Diffuse Rg scale",
        "minimum": 0.05,
        "maximum": 0.25,
        "decimals": 3,
        "help": "Guinier knee position expressed as a fraction of the normalized ROI q span.",
    },
    {
        "key": "plane_qy_slope",
        "label": "Plane slope along qy",
        "minimum": -0.08,
        "maximum": 0.08,
        "decimals": 3,
        "help": "Slow left-to-right detector background gradient.",
    },
    {
        "key": "plane_qz_slope",
        "label": "Plane slope along qz",
        "minimum": -0.08,
        "maximum": 0.08,
        "decimals": 3,
        "help": "Slow bottom-to-top detector background gradient.",
    },
    {
        "key": "low_qz_cut_fraction",
        "label": "Low-qz suppression",
        "minimum": 0.00,
        "maximum": 0.08,
        "decimals": 3,
        "help": "Smoothly suppresses background below this fraction of the ROI qz span.",
    },
    {
        "key": "blur_sigma_px",
        "label": "PSF blur σ (px)",
        "minimum": 0.00,
        "maximum": 0.60,
        "decimals": 3,
        "help": "Gaussian point-spread blur applied only to the generated physical background.",
    },
)
