"""Analyze application public API (the presentation layer imports only this)."""

from __future__ import annotations

import math

from src.gimap.shared.geometry import DetectorGeometry, InstrumentProfile, scattering_vectors

from ..domain import (
    PROFILES,
    GISAXS,
    GIWAXS,
    PICK_KINDS,
    RING,
    SECTOR,
    SPOT,
    Peak,
    Pick,
    region_kind,
    POLYGON,
    RECTANGLE,
    CakeMap,
    CutRegion,
    MaskShape,
    PeakTrack,
    SeriesCorrection,
    SeriesMap,
    X_AXIS_Q,
    X_AXIS_TWO_THETA,
    MAX_GAP_GUARD_PX,
    Corrections,
    Curve,
    GisaxsCutSettings,
    GiwaxsSettings,
    QBox,
    ReciprocalSpaceMap,
    Reduction,
    Sector,
    SymmetryCenter,
    YonedaEstimate,
    exit_angle_deg_at_row,
    source_labels,
    max_scattering_angle_deg,
    q_from_two_theta,
    default_region_near,
    region_key,
    region_outline,
    track_peak,
    two_theta_deg,
)
from .models import (
    AUTO,
    CENTER_HEADER,
    CENTER_PROFILE,
    CENTER_SESSION,
    MODES,
    AnalysisRequest,
    FrameAnalysis,
    FrameRef,
    GeometryResolution,
)
from .batch_fit import (
    FIT_MODEL,
    FIT_NONE,
    FIT_PEAKS,
    MODEL_COMPONENTS,
    START_FIRST,
    START_FRESH,
    START_PREVIOUS,
    FitStarts,
    FitTable,
    PeakInput,
    PeakTarget,
    fit_model,
    fit_model_curve,
    fit_peak_inputs,
    fit_peaks,
    model_row,
    peak_inputs,
    peak_row,
    peak_targets,
)
from .batch_job import (
    BALANCED,
    FAST,
    GENTLE,
    SPEEDS,
    FrameJob,
    FrameOutcome,
    FrameTools,
    frames_at_once,
    run_frame_job,
    write_frame_images,
)
from .batch_export import (
    BATCH_TITLE,
    SCALE_AUTO,
    SCALE_SCREEN,
    FOLDERS,
    FRAME_FORMATS,
    IMAGE_FORMATS,
    TEXT_FORMATS,
    BatchChoices,
    CurveTables,
    batch_stem,
    chosen_curves,
    export_frame,
    fit_curve_rows,
    output_names,
    readme_text,
)
from .cut_regions import (
    CUT_SET_FORMAT,
    PlaceRegions,
    cut_set,
    region_to_dict,
    regions_from_cut_set,
    regions_from_dicts,
)
from .ports import CurveWriter, FigureWriter, FrameSource, InstrumentProfileStore
from .series import CorrectSeriesFrame
from .settings_file import SETTINGS_FORMAT, AnalyzeSettings, settings_from_record, settings_record
from .series_map import SERIES_TITLE, build_series_map, export_series_map, export_series_track, row_label, series_row
from .use_cases import (
    AnalyzeFrame,
    ExportAnalysis,
    ResolveGeometry,
    SaveInstrumentProfile,
    analysis_metadata,
    expand_sources,
    export_stem,
    fit_input_curve,
    fit_input_observation,
    geometry_from_fitting_settings,
    header_beam_center,
    refine_center_by_symmetry,
)


def q_at_position(geometry: DetectorGeometry, x_px: float, y_px: float) -> dict[str, float]:
    """Exact q components (Å⁻¹) and exit angle at one continuous detector position."""
    import numpy as np

    x = np.array([(float(x_px) - geometry.beam_center_x_px) * geometry.pixel_size_x_m])
    y = np.array([(geometry.beam_center_y_px - float(y_px)) * geometry.pixel_size_y_m])
    q = scattering_vectors(
        x, y, geometry.distance_m, geometry.incidence_rad, geometry.wavevector_inv_angstrom
    )
    k = geometry.wavevector_inv_angstrom
    sin_alpha_f = float(q.qz[0]) / k - math.sin(geometry.incidence_rad)
    return {
        "qx": float(q.qx[0]),
        "qy": float(q.qy[0]),
        "qz": float(q.qz[0]),
        "q": float(q.q[0]),
        "q_parallel": float(q.q_parallel[0]),
        "alpha_f_deg": math.degrees(math.asin(max(-1.0, min(1.0, sin_alpha_f)))),
    }


__all__ = [
    "FOLDERS",
    "FRAME_FORMATS",
    "IMAGE_FORMATS",
    "TEXT_FORMATS",
    "fit_curve_rows",
    "output_names",
    "readme_text",
    "FIT_MODEL",
    "FIT_NONE",
    "FIT_PEAKS",
    "MODEL_COMPONENTS",
    "START_FIRST",
    "START_FRESH",
    "START_PREVIOUS",
    "FitStarts",
    "SCALE_AUTO",
    "SCALE_SCREEN",
    "PeakInput",
    "fit_model_curve",
    "fit_peak_inputs",
    "peak_inputs",
    "BALANCED",
    "FAST",
    "GENTLE",
    "SPEEDS",
    "FrameJob",
    "FrameOutcome",
    "FrameTools",
    "frames_at_once",
    "run_frame_job",
    "write_frame_images",
    "FitTable",
    "PeakTarget",
    "fit_model",
    "fit_peaks",
    "model_row",
    "peak_row",
    "peak_targets",
    "PROFILES",
    "AnalyzeSettings",
    "SETTINGS_FORMAT",
    "settings_from_record",
    "settings_record",
    "BATCH_TITLE",
    "BatchChoices",
    "CurveTables",
    "batch_stem",
    "chosen_curves",
    "export_frame",
    "CUT_SET_FORMAT",
    "PICK_KINDS",
    "Peak",
    "Pick",
    "PlaceRegions",
    "RING",
    "SECTOR",
    "SPOT",
    "cut_set",
    "region_kind",
    "region_to_dict",
    "regions_from_cut_set",
    "regions_from_dicts",
    "source_labels",
    "CakeMap",
    "CutRegion",
    "MaskShape",
    "POLYGON",
    "PeakTrack",
    "RECTANGLE",
    "default_region_near",
    "region_key",
    "region_outline",
    "track_peak",
    "SERIES_TITLE",
    "SeriesMap",
    "build_series_map",
    "export_series_map",
    "export_series_track",
    "row_label",
    "series_row",
    "AUTO",
    "CENTER_HEADER",
    "CENTER_PROFILE",
    "CENTER_SESSION",
    "CorrectSeriesFrame",
    "Corrections",
    "FrameRef",
    "MAX_GAP_GUARD_PX",
    "SymmetryCenter",
    "refine_center_by_symmetry",
    "SeriesCorrection",
    "QBox",
    "Sector",
    "X_AXIS_Q",
    "X_AXIS_TWO_THETA",
    "header_beam_center",
    "q_from_two_theta",
    "two_theta_deg",
    "AnalysisRequest",
    "AnalyzeFrame",
    "Curve",
    "CurveWriter",
    "FigureWriter",
    "DetectorGeometry",
    "ExportAnalysis",
    "FrameAnalysis",
    "FrameSource",
    "GISAXS",
    "GIWAXS",
    "GeometryResolution",
    "GisaxsCutSettings",
    "GiwaxsSettings",
    "InstrumentProfile",
    "InstrumentProfileStore",
    "MODES",
    "ReciprocalSpaceMap",
    "Reduction",
    "ResolveGeometry",
    "SaveInstrumentProfile",
    "YonedaEstimate",
    "analysis_metadata",
    "exit_angle_deg_at_row",
    "expand_sources",
    "export_stem",
    "fit_input_curve",
    "fit_input_observation",
    "geometry_from_fitting_settings",
    "max_scattering_angle_deg",
    "q_at_position",
]
