"""Hand-maintained Inspection panel layout."""


from PyQt5 import QtCore, QtGui, QtWidgets


class ClassificationInspectionPanelView:
    def setupUi(self, DataInspectionSection):
        DataInspectionSection.setObjectName("DataInspectionSection")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DataInspectionSection.sizePolicy().hasHeightForWidth())
        DataInspectionSection.setSizePolicy(sizePolicy)
        self.inspectionPanelLayout = QtWidgets.QVBoxLayout(DataInspectionSection)
        self.inspectionPanelLayout.setContentsMargins(10, 8, 10, 8)
        self.inspectionPanelLayout.setSpacing(8)
        self.inspectionPanelLayout.setObjectName("inspectionPanelLayout")
        self.sectionTitle = QtWidgets.QLabel(DataInspectionSection)
        self.sectionTitle.setObjectName("sectionTitle")
        self.inspectionPanelLayout.addWidget(self.sectionTitle)
        self.previewHeaderLayout = QtWidgets.QHBoxLayout()
        self.previewHeaderLayout.setObjectName("previewHeaderLayout")
        self.prevSampleButton = QtWidgets.QToolButton(DataInspectionSection)
        self.prevSampleButton.setObjectName("prevSampleButton")
        self.previewHeaderLayout.addWidget(self.prevSampleButton)
        self.nextSampleButton = QtWidgets.QToolButton(DataInspectionSection)
        self.nextSampleButton.setObjectName("nextSampleButton")
        self.previewHeaderLayout.addWidget(self.nextSampleButton)
        self.sampleIndexLabel = QtWidgets.QLabel(DataInspectionSection)
        self.sampleIndexLabel.setObjectName("sampleIndexLabel")
        self.previewHeaderLayout.addWidget(self.sampleIndexLabel)
        self.sampleFileLabel = QtWidgets.QLabel(DataInspectionSection)
        self.sampleFileLabel.setObjectName("sampleFileLabel")
        self.previewHeaderLayout.addWidget(self.sampleFileLabel)
        self.sampleShapeLabel = QtWidgets.QLabel(DataInspectionSection)
        self.sampleShapeLabel.setObjectName("sampleShapeLabel")
        self.previewHeaderLayout.addWidget(self.sampleShapeLabel)
        self.inspectionPanelLayout.addLayout(self.previewHeaderLayout)
        self.previewGraphicsView = QtWidgets.QGraphicsView(DataInspectionSection)
        self.previewGraphicsView.setMinimumSize(QtCore.QSize(0, 220))
        self.previewGraphicsView.setObjectName("previewGraphicsView")
        self.inspectionPanelLayout.addWidget(self.previewGraphicsView)
        self.previewControlsLayout = QtWidgets.QGridLayout()
        self.previewControlsLayout.setObjectName("previewControlsLayout")
        self.previewLogScaleCheckBox = QtWidgets.QCheckBox(DataInspectionSection)
        self.previewLogScaleCheckBox.setObjectName("previewLogScaleCheckBox")
        self.previewControlsLayout.addWidget(self.previewLogScaleCheckBox, 0, 0, 1, 1)
        self.previewColormapLabel = QtWidgets.QLabel(DataInspectionSection)
        self.previewColormapLabel.setObjectName("previewColormapLabel")
        self.previewControlsLayout.addWidget(self.previewColormapLabel, 0, 1, 1, 1)
        self.previewColormapCombo = QtWidgets.QComboBox(DataInspectionSection)
        self.previewColormapCombo.setObjectName("previewColormapCombo")
        self.previewColormapCombo.addItem("")
        self.previewColormapCombo.addItem("")
        self.previewColormapCombo.addItem("")
        self.previewColormapCombo.addItem("")
        self.previewColormapCombo.addItem("")
        self.previewControlsLayout.addWidget(self.previewColormapCombo, 0, 2, 1, 1)
        self.previewAutoScaleCheckBox = QtWidgets.QCheckBox(DataInspectionSection)
        self.previewAutoScaleCheckBox.setChecked(True)
        self.previewAutoScaleCheckBox.setObjectName("previewAutoScaleCheckBox")
        self.previewControlsLayout.addWidget(self.previewAutoScaleCheckBox, 0, 3, 1, 1)
        self.previewVminLabel = QtWidgets.QLabel(DataInspectionSection)
        self.previewVminLabel.setObjectName("previewVminLabel")
        self.previewControlsLayout.addWidget(self.previewVminLabel, 1, 0, 1, 1)
        self.previewVminSpinBox = QtWidgets.QDoubleSpinBox(DataInspectionSection)
        self.previewVminSpinBox.setMinimum(-1000000000000.0)
        self.previewVminSpinBox.setMaximum(1000000000000.0)
        self.previewVminSpinBox.setObjectName("previewVminSpinBox")
        self.previewControlsLayout.addWidget(self.previewVminSpinBox, 1, 1, 1, 1)
        self.previewVmaxLabel = QtWidgets.QLabel(DataInspectionSection)
        self.previewVmaxLabel.setObjectName("previewVmaxLabel")
        self.previewControlsLayout.addWidget(self.previewVmaxLabel, 1, 2, 1, 1)
        self.previewVmaxSpinBox = QtWidgets.QDoubleSpinBox(DataInspectionSection)
        self.previewVmaxSpinBox.setMinimum(-1000000000000.0)
        self.previewVmaxSpinBox.setMaximum(1000000000000.0)
        self.previewVmaxSpinBox.setObjectName("previewVmaxSpinBox")
        self.previewControlsLayout.addWidget(self.previewVmaxSpinBox, 1, 3, 1, 1)
        self.fitPreviewButton = QtWidgets.QPushButton(DataInspectionSection)
        self.fitPreviewButton.setObjectName("fitPreviewButton")
        self.previewControlsLayout.addWidget(self.fitPreviewButton, 2, 0, 1, 1)
        self.openFileLocationButton = QtWidgets.QPushButton(DataInspectionSection)
        self.openFileLocationButton.setObjectName("openFileLocationButton")
        self.previewControlsLayout.addWidget(self.openFileLocationButton, 2, 1, 1, 3)
        self.inspectionPanelLayout.addLayout(self.previewControlsLayout)
        self.qualityFrame = QtWidgets.QFrame(DataInspectionSection)
        self.qualityFrame.setObjectName("qualityFrame")
        self.qualityLayout = QtWidgets.QVBoxLayout(self.qualityFrame)
        self.qualityLayout.setContentsMargins(10, 8, 10, 8)
        self.qualityLayout.setObjectName("qualityLayout")
        self.qualityHeaderLayout = QtWidgets.QHBoxLayout()
        self.qualityHeaderLayout.setObjectName("qualityHeaderLayout")
        self.qualityTitle = QtWidgets.QLabel(self.qualityFrame)
        self.qualityTitle.setObjectName("qualityTitle")
        self.qualityHeaderLayout.addWidget(self.qualityTitle)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.qualityHeaderLayout.addItem(spacerItem)
        self.qualityStatusLabel = QtWidgets.QLabel(self.qualityFrame)
        self.qualityStatusLabel.setObjectName("qualityStatusLabel")
        self.qualityHeaderLayout.addWidget(self.qualityStatusLabel)
        self.qualityLayout.addLayout(self.qualityHeaderLayout)
        self.qualityListWidget = QtWidgets.QListWidget(self.qualityFrame)
        self.qualityListWidget.setMaximumSize(QtCore.QSize(16777215, 110))
        self.qualityListWidget.setObjectName("qualityListWidget")
        self.qualityLayout.addWidget(self.qualityListWidget)
        self.inspectionPanelLayout.addWidget(self.qualityFrame)
        self.inspectionPanelLayout.setStretch(2, 3)

        self.retranslateUi(DataInspectionSection)
        QtCore.QMetaObject.connectSlotsByName(DataInspectionSection)
        DataInspectionSection.setTabOrder(self.prevSampleButton, self.nextSampleButton)
        DataInspectionSection.setTabOrder(self.nextSampleButton, self.previewGraphicsView)
        DataInspectionSection.setTabOrder(self.previewGraphicsView, self.previewLogScaleCheckBox)
        DataInspectionSection.setTabOrder(self.previewLogScaleCheckBox, self.previewColormapCombo)
        DataInspectionSection.setTabOrder(self.previewColormapCombo, self.previewAutoScaleCheckBox)
        DataInspectionSection.setTabOrder(self.previewAutoScaleCheckBox, self.previewVminSpinBox)
        DataInspectionSection.setTabOrder(self.previewVminSpinBox, self.previewVmaxSpinBox)
        DataInspectionSection.setTabOrder(self.previewVmaxSpinBox, self.fitPreviewButton)
        DataInspectionSection.setTabOrder(self.fitPreviewButton, self.openFileLocationButton)
        DataInspectionSection.setTabOrder(self.openFileLocationButton, self.qualityListWidget)

    def retranslateUi(self, DataInspectionSection):
        _translate = QtCore.QCoreApplication.translate
        self.sectionTitle.setText(_translate("ClassificationInspectionPanel", "Data Inspection"))
        self.prevSampleButton.setText(_translate("ClassificationInspectionPanel", "<"))
        self.nextSampleButton.setText(_translate("ClassificationInspectionPanel", ">"))
        self.sampleIndexLabel.setText(_translate("ClassificationInspectionPanel", "0 / 0"))
        self.sampleFileLabel.setText(_translate("ClassificationInspectionPanel", "No sample selected"))
        self.sampleShapeLabel.setText(_translate("ClassificationInspectionPanel", "-"))
        self.previewLogScaleCheckBox.setText(_translate("ClassificationInspectionPanel", "Log scale"))
        self.previewColormapLabel.setText(_translate("ClassificationInspectionPanel", "Colormap"))
        self.previewColormapCombo.setItemText(0, _translate("ClassificationInspectionPanel", "viridis"))
        self.previewColormapCombo.setItemText(1, _translate("ClassificationInspectionPanel", "magma"))
        self.previewColormapCombo.setItemText(2, _translate("ClassificationInspectionPanel", "plasma"))
        self.previewColormapCombo.setItemText(3, _translate("ClassificationInspectionPanel", "jet"))
        self.previewColormapCombo.setItemText(4, _translate("ClassificationInspectionPanel", "gray"))
        self.previewAutoScaleCheckBox.setText(_translate("ClassificationInspectionPanel", "Auto scale"))
        self.previewVminLabel.setText(_translate("ClassificationInspectionPanel", "vmin"))
        self.previewVmaxLabel.setText(_translate("ClassificationInspectionPanel", "vmax"))
        self.fitPreviewButton.setText(_translate("ClassificationInspectionPanel", "Fit"))
        self.openFileLocationButton.setText(_translate("ClassificationInspectionPanel", "Open file location"))
        self.qualityTitle.setText(_translate("ClassificationInspectionPanel", "Data Quality"))
        self.qualityStatusLabel.setText(_translate("ClassificationInspectionPanel", "Warning"))
