"""Hand-maintained Preprocessing panel layout."""


from PyQt5 import QtCore, QtGui, QtWidgets


class ClassificationPreprocessingPanelView:
    def setupUi(self, PreprocessingSection):
        PreprocessingSection.setObjectName("PreprocessingSection")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PreprocessingSection.sizePolicy().hasHeightForWidth())
        PreprocessingSection.setSizePolicy(sizePolicy)
        self.preprocessingPanelLayout = QtWidgets.QVBoxLayout(PreprocessingSection)
        self.preprocessingPanelLayout.setContentsMargins(10, 8, 10, 8)
        self.preprocessingPanelLayout.setSpacing(8)
        self.preprocessingPanelLayout.setObjectName("preprocessingPanelLayout")
        self.sectionTitle = QtWidgets.QLabel(PreprocessingSection)
        self.sectionTitle.setObjectName("sectionTitle")
        self.preprocessingPanelLayout.addWidget(self.sectionTitle)
        self.preprocessingIntro = QtWidgets.QLabel(PreprocessingSection)
        self.preprocessingIntro.setWordWrap(True)
        self.preprocessingIntro.setObjectName("preprocessingIntro")
        self.preprocessingPanelLayout.addWidget(self.preprocessingIntro)
        self.preprocessingFrame = QtWidgets.QFrame(PreprocessingSection)
        self.preprocessingFrame.setObjectName("preprocessingFrame")
        self.preprocessingForm = QtWidgets.QFormLayout(self.preprocessingFrame)
        self.preprocessingForm.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.preprocessingForm.setRowWrapPolicy(QtWidgets.QFormLayout.WrapLongRows)
        self.preprocessingForm.setContentsMargins(10, 8, 10, 8)
        self.preprocessingForm.setHorizontalSpacing(12)
        self.preprocessingForm.setVerticalSpacing(8)
        self.preprocessingForm.setObjectName("preprocessingForm")
        self.dataTypeTitle = QtWidgets.QLabel(self.preprocessingFrame)
        self.dataTypeTitle.setObjectName("dataTypeTitle")
        self.preprocessingForm.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.dataTypeTitle)
        self.dataTypeBadgeLabel = QtWidgets.QLabel(self.preprocessingFrame)
        self.dataTypeBadgeLabel.setObjectName("dataTypeBadgeLabel")
        self.preprocessingForm.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.dataTypeBadgeLabel)
        self.oneDPreprocessingTitle = QtWidgets.QLabel(self.preprocessingFrame)
        self.oneDPreprocessingTitle.setObjectName("oneDPreprocessingTitle")
        self.preprocessingForm.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.oneDPreprocessingTitle)
        self.oneDPreprocessingCombo = QtWidgets.QComboBox(self.preprocessingFrame)
        self.oneDPreprocessingCombo.setObjectName("oneDPreprocessingCombo")
        self.oneDPreprocessingCombo.addItem("")
        self.oneDPreprocessingCombo.addItem("")
        self.oneDPreprocessingCombo.addItem("")
        self.oneDPreprocessingCombo.addItem("")
        self.oneDPreprocessingCombo.addItem("")
        self.oneDPreprocessingCombo.addItem("")
        self.oneDPreprocessingCombo.addItem("")
        self.oneDPreprocessingCombo.addItem("")
        self.preprocessingForm.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.oneDPreprocessingCombo)
        self.twoDPreprocessingTitle = QtWidgets.QLabel(self.preprocessingFrame)
        self.twoDPreprocessingTitle.setObjectName("twoDPreprocessingTitle")
        self.preprocessingForm.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.twoDPreprocessingTitle)
        self.twoDPreprocessingCombo = QtWidgets.QComboBox(self.preprocessingFrame)
        self.twoDPreprocessingCombo.setObjectName("twoDPreprocessingCombo")
        self.twoDPreprocessingCombo.addItem("")
        self.twoDPreprocessingCombo.addItem("")
        self.twoDPreprocessingCombo.addItem("")
        self.twoDPreprocessingCombo.addItem("")
        self.twoDPreprocessingCombo.addItem("")
        self.twoDPreprocessingCombo.addItem("")
        self.twoDPreprocessingCombo.addItem("")
        self.preprocessingForm.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.twoDPreprocessingCombo)
        self.normalizeTitle = QtWidgets.QLabel(self.preprocessingFrame)
        self.normalizeTitle.setObjectName("normalizeTitle")
        self.preprocessingForm.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.normalizeTitle)
        self.normalizeCombo = QtWidgets.QComboBox(self.preprocessingFrame)
        self.normalizeCombo.setObjectName("normalizeCombo")
        self.normalizeCombo.addItem("")
        self.normalizeCombo.addItem("")
        self.normalizeCombo.addItem("")
        self.preprocessingForm.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.normalizeCombo)
        self.preprocessingLogCheckBox = QtWidgets.QCheckBox(self.preprocessingFrame)
        self.preprocessingLogCheckBox.setObjectName("preprocessingLogCheckBox")
        self.preprocessingForm.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.preprocessingLogCheckBox)
        self.inputSummaryTitle = QtWidgets.QLabel(self.preprocessingFrame)
        self.inputSummaryTitle.setObjectName("inputSummaryTitle")
        self.preprocessingForm.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.inputSummaryTitle)
        self.inputSummaryLabel = QtWidgets.QLabel(self.preprocessingFrame)
        self.inputSummaryLabel.setWordWrap(True)
        self.inputSummaryLabel.setObjectName("inputSummaryLabel")
        self.preprocessingForm.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.inputSummaryLabel)
        self.preprocessingPanelLayout.addWidget(self.preprocessingFrame)
        self.classificationPreprocessingAdvancedSection = QtWidgets.QFrame(PreprocessingSection)
        self.classificationPreprocessingAdvancedSection.setProperty("gimapSection", True)
        self.classificationPreprocessingAdvancedSection.setObjectName("classificationPreprocessingAdvancedSection")
        self.preprocessingAdvancedSectionLayout = QtWidgets.QVBoxLayout(self.classificationPreprocessingAdvancedSection)
        self.preprocessingAdvancedSectionLayout.setContentsMargins(8, 8, 8, 8)
        self.preprocessingAdvancedSectionLayout.setSpacing(7)
        self.preprocessingAdvancedSectionLayout.setObjectName("preprocessingAdvancedSectionLayout")
        self.preprocessingAdvancedToggle = QtWidgets.QToolButton(self.classificationPreprocessingAdvancedSection)
        self.preprocessingAdvancedToggle.setProperty("gimapAdvancedToggle", True)
        self.preprocessingAdvancedToggle.setCheckable(True)
        self.preprocessingAdvancedToggle.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.preprocessingAdvancedToggle.setArrowType(QtCore.Qt.RightArrow)
        self.preprocessingAdvancedToggle.setObjectName("preprocessingAdvancedToggle")
        self.preprocessingAdvancedSectionLayout.addWidget(self.preprocessingAdvancedToggle)
        self.preprocessingAdvancedDescription = QtWidgets.QLabel(self.classificationPreprocessingAdvancedSection)
        self.preprocessingAdvancedDescription.setVisible(False)
        self.preprocessingAdvancedDescription.setProperty("gimapSectionDescription", True)
        self.preprocessingAdvancedDescription.setWordWrap(True)
        self.preprocessingAdvancedDescription.setObjectName("preprocessingAdvancedDescription")
        self.preprocessingAdvancedSectionLayout.addWidget(self.preprocessingAdvancedDescription)
        self.preprocessingAdvancedContent = QtWidgets.QWidget(self.classificationPreprocessingAdvancedSection)
        self.preprocessingAdvancedContent.setVisible(False)
        self.preprocessingAdvancedContent.setObjectName("preprocessingAdvancedContent")
        self.preprocessingAdvancedContentLayout = QtWidgets.QFormLayout(self.preprocessingAdvancedContent)
        self.preprocessingAdvancedContentLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.preprocessingAdvancedContentLayout.setContentsMargins(4, 2, 4, 4)
        self.preprocessingAdvancedContentLayout.setObjectName("preprocessingAdvancedContentLayout")
        self.smoothingTitle = QtWidgets.QLabel(self.preprocessingAdvancedContent)
        self.smoothingTitle.setObjectName("smoothingTitle")
        self.preprocessingAdvancedContentLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.smoothingTitle)
        self.smoothingSpinBox = QtWidgets.QSpinBox(self.preprocessingAdvancedContent)
        self.smoothingSpinBox.setMaximum(99)
        self.smoothingSpinBox.setObjectName("smoothingSpinBox")
        self.preprocessingAdvancedContentLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.smoothingSpinBox)
        self.resizeRowsTitle = QtWidgets.QLabel(self.preprocessingAdvancedContent)
        self.resizeRowsTitle.setObjectName("resizeRowsTitle")
        self.preprocessingAdvancedContentLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.resizeRowsTitle)
        self.resizeRowsSpinBox = QtWidgets.QSpinBox(self.preprocessingAdvancedContent)
        self.resizeRowsSpinBox.setMinimum(1)
        self.resizeRowsSpinBox.setMaximum(10000)
        self.resizeRowsSpinBox.setProperty("value", 256)
        self.resizeRowsSpinBox.setObjectName("resizeRowsSpinBox")
        self.preprocessingAdvancedContentLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.resizeRowsSpinBox)
        self.resizeColsTitle = QtWidgets.QLabel(self.preprocessingAdvancedContent)
        self.resizeColsTitle.setObjectName("resizeColsTitle")
        self.preprocessingAdvancedContentLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.resizeColsTitle)
        self.resizeColsSpinBox = QtWidgets.QSpinBox(self.preprocessingAdvancedContent)
        self.resizeColsSpinBox.setMinimum(1)
        self.resizeColsSpinBox.setMaximum(10000)
        self.resizeColsSpinBox.setProperty("value", 256)
        self.resizeColsSpinBox.setObjectName("resizeColsSpinBox")
        self.preprocessingAdvancedContentLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.resizeColsSpinBox)
        self.preprocessingAdvancedSectionLayout.addWidget(self.preprocessingAdvancedContent)
        self.preprocessingPanelLayout.addWidget(self.classificationPreprocessingAdvancedSection)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.preprocessingPanelLayout.addItem(spacerItem)

        self.retranslateUi(PreprocessingSection)
        self.oneDPreprocessingCombo.setCurrentIndex(1)
        self.twoDPreprocessingCombo.setCurrentIndex(1)
        self.normalizeCombo.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(PreprocessingSection)
        PreprocessingSection.setTabOrder(self.oneDPreprocessingCombo, self.twoDPreprocessingCombo)
        PreprocessingSection.setTabOrder(self.twoDPreprocessingCombo, self.normalizeCombo)
        PreprocessingSection.setTabOrder(self.normalizeCombo, self.preprocessingLogCheckBox)
        PreprocessingSection.setTabOrder(self.preprocessingLogCheckBox, self.preprocessingAdvancedToggle)
        PreprocessingSection.setTabOrder(self.preprocessingAdvancedToggle, self.smoothingSpinBox)
        PreprocessingSection.setTabOrder(self.smoothingSpinBox, self.resizeRowsSpinBox)
        PreprocessingSection.setTabOrder(self.resizeRowsSpinBox, self.resizeColsSpinBox)

    def retranslateUi(self, PreprocessingSection):
        _translate = QtCore.QCoreApplication.translate
        self.sectionTitle.setText(_translate("ClassificationPreprocessingPanel", "Preprocessing"))
        self.preprocessingIntro.setText(_translate("ClassificationPreprocessingPanel", "Configure a shared preprocessing pipeline. Changes apply to every selected algorithm."))
        self.dataTypeTitle.setText(_translate("ClassificationPreprocessingPanel", "Data type"))
        self.dataTypeBadgeLabel.setText(_translate("ClassificationPreprocessingPanel", "auto"))
        self.oneDPreprocessingTitle.setText(_translate("ClassificationPreprocessingPanel", "1D preprocessing"))
        self.oneDPreprocessingCombo.setItemText(0, _translate("ClassificationPreprocessingPanel", "None"))
        self.oneDPreprocessingCombo.setItemText(1, _translate("ClassificationPreprocessingPanel", "Interpolate to common grid"))
        self.oneDPreprocessingCombo.setItemText(2, _translate("ClassificationPreprocessingPanel", "Crop range"))
        self.oneDPreprocessingCombo.setItemText(3, _translate("ClassificationPreprocessingPanel", "Normalize by max"))
        self.oneDPreprocessingCombo.setItemText(4, _translate("ClassificationPreprocessingPanel", "Normalize by area"))
        self.oneDPreprocessingCombo.setItemText(5, _translate("ClassificationPreprocessingPanel", "Standard scaling"))
        self.oneDPreprocessingCombo.setItemText(6, _translate("ClassificationPreprocessingPanel", "Log transform"))
        self.oneDPreprocessingCombo.setItemText(7, _translate("ClassificationPreprocessingPanel", "Smoothing"))
        self.twoDPreprocessingTitle.setText(_translate("ClassificationPreprocessingPanel", "2D preprocessing"))
        self.twoDPreprocessingCombo.setItemText(0, _translate("ClassificationPreprocessingPanel", "None"))
        self.twoDPreprocessingCombo.setItemText(1, _translate("ClassificationPreprocessingPanel", "Center crop"))
        self.twoDPreprocessingCombo.setItemText(2, _translate("ClassificationPreprocessingPanel", "Resize"))
        self.twoDPreprocessingCombo.setItemText(3, _translate("ClassificationPreprocessingPanel", "Normalize"))
        self.twoDPreprocessingCombo.setItemText(4, _translate("ClassificationPreprocessingPanel", "Log transform"))
        self.twoDPreprocessingCombo.setItemText(5, _translate("ClassificationPreprocessingPanel", "Mask invalid pixels"))
        self.twoDPreprocessingCombo.setItemText(6, _translate("ClassificationPreprocessingPanel", "Flatten"))
        self.normalizeTitle.setText(_translate("ClassificationPreprocessingPanel", "Normalize"))
        self.normalizeCombo.setItemText(0, _translate("ClassificationPreprocessingPanel", "none"))
        self.normalizeCombo.setItemText(1, _translate("ClassificationPreprocessingPanel", "max"))
        self.normalizeCombo.setItemText(2, _translate("ClassificationPreprocessingPanel", "area"))
        self.preprocessingLogCheckBox.setText(_translate("ClassificationPreprocessingPanel", "Log transform"))
        self.inputSummaryTitle.setText(_translate("ClassificationPreprocessingPanel", "Input summary"))
        self.inputSummaryLabel.setText(_translate("ClassificationPreprocessingPanel", "Samples: 0 | Features: 0 | Input shape: - | Memory: -"))
        self.preprocessingAdvancedToggle.setText(_translate("ClassificationPreprocessingPanel", "Advanced preprocessing"))
        self.preprocessingAdvancedDescription.setText(_translate("ClassificationPreprocessingPanel", "Tune smoothing and explicit 2D resize dimensions."))
        self.smoothingTitle.setText(_translate("ClassificationPreprocessingPanel", "Smoothing"))
        self.resizeRowsTitle.setText(_translate("ClassificationPreprocessingPanel", "Resize rows"))
        self.resizeColsTitle.setText(_translate("ClassificationPreprocessingPanel", "Resize cols"))
