"""Hand-maintained Classification workspace layout."""


from PyQt5 import QtCore, QtGui, QtWidgets


class ClassificationPageView:
    def setupUi(self, ClassificationPageRoot):
        ClassificationPageRoot.setObjectName("ClassificationPageRoot")
        ClassificationPageRoot.setAcceptDrops(True)
        self.rootLayout = QtWidgets.QVBoxLayout(ClassificationPageRoot)
        self.rootLayout.setContentsMargins(14, 14, 14, 14)
        self.rootLayout.setSpacing(10)
        self.rootLayout.setObjectName("rootLayout")
        self.classificationHeader = QtWidgets.QWidget(ClassificationPageRoot)
        self.classificationHeader.setObjectName("classificationHeader")
        self.headerLayout = QtWidgets.QHBoxLayout(self.classificationHeader)
        self.headerLayout.setContentsMargins(0, 0, 0, 0)
        self.headerLayout.setSpacing(10)
        self.headerLayout.setObjectName("headerLayout")
        self.titleLayout = QtWidgets.QVBoxLayout()
        self.titleLayout.setSpacing(2)
        self.titleLayout.setObjectName("titleLayout")
        self.titleLabel = QtWidgets.QLabel(self.classificationHeader)
        self.titleLabel.setObjectName("titleLabel")
        self.titleLayout.addWidget(self.titleLabel)
        self.subtitleLabel = QtWidgets.QLabel(self.classificationHeader)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.subtitleLabel.sizePolicy().hasHeightForWidth())
        self.subtitleLabel.setSizePolicy(sizePolicy)
        self.subtitleLabel.setWordWrap(True)
        self.subtitleLabel.setObjectName("subtitleLabel")
        self.titleLayout.addWidget(self.subtitleLabel)
        self.headerLayout.addLayout(self.titleLayout)
        self.newSessionButton = QtWidgets.QPushButton(self.classificationHeader)
        self.newSessionButton.setObjectName("newSessionButton")
        self.headerLayout.addWidget(self.newSessionButton)
        self.loadSessionButton = QtWidgets.QPushButton(self.classificationHeader)
        self.loadSessionButton.setObjectName("loadSessionButton")
        self.headerLayout.addWidget(self.loadSessionButton)
        self.saveSessionButton = QtWidgets.QPushButton(self.classificationHeader)
        self.saveSessionButton.setObjectName("saveSessionButton")
        self.headerLayout.addWidget(self.saveSessionButton)
        self.helpButton = QtWidgets.QToolButton(self.classificationHeader)
        self.helpButton.setObjectName("helpButton")
        self.headerLayout.addWidget(self.helpButton)
        self.headerLayout.setStretch(0, 1)
        self.rootLayout.addWidget(self.classificationHeader)
        self.classificationStepper = QtWidgets.QFrame(ClassificationPageRoot)
        self.classificationStepper.setObjectName("classificationStepper")
        self.stepperLayout = QtWidgets.QHBoxLayout(self.classificationStepper)
        self.stepperLayout.setContentsMargins(8, 6, 8, 6)
        self.stepperLayout.setSpacing(8)
        self.stepperLayout.setObjectName("stepperLayout")
        self.datasetStepButton = QtWidgets.QToolButton(self.classificationStepper)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datasetStepButton.sizePolicy().hasHeightForWidth())
        self.datasetStepButton.setSizePolicy(sizePolicy)
        self.datasetStepButton.setMinimumSize(QtCore.QSize(105, 0))
        self.datasetStepButton.setCheckable(True)
        self.datasetStepButton.setAutoRaise(False)
        self.datasetStepButton.setObjectName("datasetStepButton")
        self.stepperLayout.addWidget(self.datasetStepButton)
        self.preprocessingStepButton = QtWidgets.QToolButton(self.classificationStepper)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.preprocessingStepButton.sizePolicy().hasHeightForWidth())
        self.preprocessingStepButton.setSizePolicy(sizePolicy)
        self.preprocessingStepButton.setMinimumSize(QtCore.QSize(105, 0))
        self.preprocessingStepButton.setCheckable(True)
        self.preprocessingStepButton.setAutoRaise(False)
        self.preprocessingStepButton.setObjectName("preprocessingStepButton")
        self.stepperLayout.addWidget(self.preprocessingStepButton)
        self.algorithmsStepButton = QtWidgets.QToolButton(self.classificationStepper)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.algorithmsStepButton.sizePolicy().hasHeightForWidth())
        self.algorithmsStepButton.setSizePolicy(sizePolicy)
        self.algorithmsStepButton.setMinimumSize(QtCore.QSize(105, 0))
        self.algorithmsStepButton.setCheckable(True)
        self.algorithmsStepButton.setAutoRaise(False)
        self.algorithmsStepButton.setObjectName("algorithmsStepButton")
        self.stepperLayout.addWidget(self.algorithmsStepButton)
        self.resultsStepButton = QtWidgets.QToolButton(self.classificationStepper)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resultsStepButton.sizePolicy().hasHeightForWidth())
        self.resultsStepButton.setSizePolicy(sizePolicy)
        self.resultsStepButton.setMinimumSize(QtCore.QSize(105, 0))
        self.resultsStepButton.setCheckable(True)
        self.resultsStepButton.setAutoRaise(False)
        self.resultsStepButton.setObjectName("resultsStepButton")
        self.stepperLayout.addWidget(self.resultsStepButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.stepperLayout.addItem(spacerItem)
        self.stateBadgeLabel = QtWidgets.QLabel(self.classificationStepper)
        self.stateBadgeLabel.setObjectName("stateBadgeLabel")
        self.stepperLayout.addWidget(self.stateBadgeLabel)
        self.stepperLayout.setStretch(0, 1)
        self.stepperLayout.setStretch(1, 1)
        self.stepperLayout.setStretch(2, 1)
        self.stepperLayout.setStretch(3, 1)
        self.stepperLayout.setStretch(4, 1)
        self.rootLayout.addWidget(self.classificationStepper)
        self.workflowStack = QtWidgets.QStackedWidget(ClassificationPageRoot)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.workflowStack.sizePolicy().hasHeightForWidth())
        self.workflowStack.setSizePolicy(sizePolicy)
        self.workflowStack.setObjectName("workflowStack")
        self.datasetStepScrollArea = QtWidgets.QScrollArea()
        self.datasetStepScrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.datasetStepScrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.datasetStepScrollArea.setWidgetResizable(True)
        self.datasetStepScrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.datasetStepScrollArea.setObjectName("datasetStepScrollArea")
        self.datasetStepContent = QtWidgets.QWidget()
        self.datasetStepContent.setGeometry(QtCore.QRect(0, 0, 1100, 650))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datasetStepContent.sizePolicy().hasHeightForWidth())
        self.datasetStepContent.setSizePolicy(sizePolicy)
        self.datasetStepContent.setObjectName("datasetStepContent")
        self.datasetStepLayout = QtWidgets.QVBoxLayout(self.datasetStepContent)
        self.datasetStepLayout.setContentsMargins(0, 0, 0, 0)
        self.datasetStepLayout.setObjectName("datasetStepLayout")
        self.datasetInspectionSplitter = QtWidgets.QSplitter(self.datasetStepContent)
        self.datasetInspectionSplitter.setOrientation(QtCore.Qt.Horizontal)
        self.datasetInspectionSplitter.setChildrenCollapsible(False)
        self.datasetInspectionSplitter.setObjectName("datasetInspectionSplitter")
        self.classificationInputSection = QtWidgets.QFrame(self.datasetInspectionSplitter)
        self.classificationInputSection.setProperty("gimapSection", True)
        self.classificationInputSection.setObjectName("classificationInputSection")
        self.classificationInputSectionLayout = QtWidgets.QVBoxLayout(self.classificationInputSection)
        self.classificationInputSectionLayout.setContentsMargins(12, 10, 12, 12)
        self.classificationInputSectionLayout.setSpacing(8)
        self.classificationInputSectionLayout.setObjectName("classificationInputSectionLayout")
        self.classificationInputTitle = QtWidgets.QLabel(self.classificationInputSection)
        self.classificationInputTitle.setProperty("gimapSectionTitle", True)
        self.classificationInputTitle.setObjectName("classificationInputTitle")
        self.classificationInputSectionLayout.addWidget(self.classificationInputTitle)
        self.classificationInputDescription = QtWidgets.QLabel(self.classificationInputSection)
        self.classificationInputDescription.setProperty("gimapSectionDescription", True)
        self.classificationInputDescription.setWordWrap(True)
        self.classificationInputDescription.setObjectName("classificationInputDescription")
        self.classificationInputSectionLayout.addWidget(self.classificationInputDescription)
        self.classificationInputContent = QtWidgets.QWidget(self.classificationInputSection)
        self.classificationInputContent.setObjectName("classificationInputContent")
        self.classificationInputContentLayout = QtWidgets.QVBoxLayout(self.classificationInputContent)
        self.classificationInputContentLayout.setContentsMargins(0, 0, 0, 0)
        self.classificationInputContentLayout.setSpacing(8)
        self.classificationInputContentLayout.setObjectName("classificationInputContentLayout")
        self.classificationInputSectionLayout.addWidget(self.classificationInputContent)
        self.classificationPreviewPanel = QtWidgets.QFrame(self.datasetInspectionSplitter)
        self.classificationPreviewPanel.setProperty("gimapSection", True)
        self.classificationPreviewPanel.setObjectName("classificationPreviewPanel")
        self.classificationPreviewSectionLayout = QtWidgets.QVBoxLayout(self.classificationPreviewPanel)
        self.classificationPreviewSectionLayout.setContentsMargins(12, 10, 12, 12)
        self.classificationPreviewSectionLayout.setSpacing(8)
        self.classificationPreviewSectionLayout.setObjectName("classificationPreviewSectionLayout")
        self.classificationPreviewTitle = QtWidgets.QLabel(self.classificationPreviewPanel)
        self.classificationPreviewTitle.setProperty("gimapSectionTitle", True)
        self.classificationPreviewTitle.setObjectName("classificationPreviewTitle")
        self.classificationPreviewSectionLayout.addWidget(self.classificationPreviewTitle)
        self.classificationPreviewDescription = QtWidgets.QLabel(self.classificationPreviewPanel)
        self.classificationPreviewDescription.setProperty("gimapSectionDescription", True)
        self.classificationPreviewDescription.setWordWrap(True)
        self.classificationPreviewDescription.setObjectName("classificationPreviewDescription")
        self.classificationPreviewSectionLayout.addWidget(self.classificationPreviewDescription)
        self.classificationPreviewContent = QtWidgets.QWidget(self.classificationPreviewPanel)
        self.classificationPreviewContent.setObjectName("classificationPreviewContent")
        self.classificationPreviewContentLayout = QtWidgets.QVBoxLayout(self.classificationPreviewContent)
        self.classificationPreviewContentLayout.setContentsMargins(0, 0, 0, 0)
        self.classificationPreviewContentLayout.setSpacing(8)
        self.classificationPreviewContentLayout.setObjectName("classificationPreviewContentLayout")
        self.classificationPreviewSectionLayout.addWidget(self.classificationPreviewContent)
        self.datasetStepLayout.addWidget(self.datasetInspectionSplitter)
        self.datasetStepScrollArea.setWidget(self.datasetStepContent)
        self.workflowStack.addWidget(self.datasetStepScrollArea)
        self.preprocessingStepScrollArea = QtWidgets.QScrollArea()
        self.preprocessingStepScrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.preprocessingStepScrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.preprocessingStepScrollArea.setWidgetResizable(True)
        self.preprocessingStepScrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.preprocessingStepScrollArea.setObjectName("preprocessingStepScrollArea")
        self.classificationConfigureSection = QtWidgets.QFrame()
        self.classificationConfigureSection.setGeometry(QtCore.QRect(0, 0, 1100, 650))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.classificationConfigureSection.sizePolicy().hasHeightForWidth())
        self.classificationConfigureSection.setSizePolicy(sizePolicy)
        self.classificationConfigureSection.setProperty("gimapSection", True)
        self.classificationConfigureSection.setObjectName("classificationConfigureSection")
        self.classificationConfigureSectionLayout = QtWidgets.QVBoxLayout(self.classificationConfigureSection)
        self.classificationConfigureSectionLayout.setContentsMargins(12, 10, 12, 12)
        self.classificationConfigureSectionLayout.setSpacing(8)
        self.classificationConfigureSectionLayout.setObjectName("classificationConfigureSectionLayout")
        self.classificationConfigureTitle = QtWidgets.QLabel(self.classificationConfigureSection)
        self.classificationConfigureTitle.setProperty("gimapSectionTitle", True)
        self.classificationConfigureTitle.setObjectName("classificationConfigureTitle")
        self.classificationConfigureSectionLayout.addWidget(self.classificationConfigureTitle)
        self.classificationConfigureDescription = QtWidgets.QLabel(self.classificationConfigureSection)
        self.classificationConfigureDescription.setProperty("gimapSectionDescription", True)
        self.classificationConfigureDescription.setWordWrap(True)
        self.classificationConfigureDescription.setObjectName("classificationConfigureDescription")
        self.classificationConfigureSectionLayout.addWidget(self.classificationConfigureDescription)
        self.classificationConfigureContent = QtWidgets.QWidget(self.classificationConfigureSection)
        self.classificationConfigureContent.setObjectName("classificationConfigureContent")
        self.classificationConfigureContentLayout = QtWidgets.QVBoxLayout(self.classificationConfigureContent)
        self.classificationConfigureContentLayout.setContentsMargins(0, 0, 0, 0)
        self.classificationConfigureContentLayout.setSpacing(8)
        self.classificationConfigureContentLayout.setObjectName("classificationConfigureContentLayout")
        self.classificationConfigureSectionLayout.addWidget(self.classificationConfigureContent)
        self.preprocessingStepScrollArea.setWidget(self.classificationConfigureSection)
        self.workflowStack.addWidget(self.preprocessingStepScrollArea)
        self.algorithmsStepScrollArea = QtWidgets.QScrollArea()
        self.algorithmsStepScrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.algorithmsStepScrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.algorithmsStepScrollArea.setWidgetResizable(True)
        self.algorithmsStepScrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.algorithmsStepScrollArea.setObjectName("algorithmsStepScrollArea")
        self.classificationAlgorithmSection = QtWidgets.QFrame()
        self.classificationAlgorithmSection.setGeometry(QtCore.QRect(0, 0, 1100, 650))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.classificationAlgorithmSection.sizePolicy().hasHeightForWidth())
        self.classificationAlgorithmSection.setSizePolicy(sizePolicy)
        self.classificationAlgorithmSection.setProperty("gimapSection", True)
        self.classificationAlgorithmSection.setObjectName("classificationAlgorithmSection")
        self.classificationAlgorithmSectionLayout = QtWidgets.QVBoxLayout(self.classificationAlgorithmSection)
        self.classificationAlgorithmSectionLayout.setContentsMargins(12, 10, 12, 12)
        self.classificationAlgorithmSectionLayout.setSpacing(8)
        self.classificationAlgorithmSectionLayout.setObjectName("classificationAlgorithmSectionLayout")
        self.classificationAlgorithmTitle = QtWidgets.QLabel(self.classificationAlgorithmSection)
        self.classificationAlgorithmTitle.setProperty("gimapSectionTitle", True)
        self.classificationAlgorithmTitle.setObjectName("classificationAlgorithmTitle")
        self.classificationAlgorithmSectionLayout.addWidget(self.classificationAlgorithmTitle)
        self.classificationAlgorithmDescription = QtWidgets.QLabel(self.classificationAlgorithmSection)
        self.classificationAlgorithmDescription.setProperty("gimapSectionDescription", True)
        self.classificationAlgorithmDescription.setWordWrap(True)
        self.classificationAlgorithmDescription.setObjectName("classificationAlgorithmDescription")
        self.classificationAlgorithmSectionLayout.addWidget(self.classificationAlgorithmDescription)
        self.classificationAlgorithmContent = QtWidgets.QWidget(self.classificationAlgorithmSection)
        self.classificationAlgorithmContent.setObjectName("classificationAlgorithmContent")
        self.classificationAlgorithmContentLayout = QtWidgets.QVBoxLayout(self.classificationAlgorithmContent)
        self.classificationAlgorithmContentLayout.setContentsMargins(0, 0, 0, 0)
        self.classificationAlgorithmContentLayout.setSpacing(8)
        self.classificationAlgorithmContentLayout.setObjectName("classificationAlgorithmContentLayout")
        self.classificationAlgorithmSectionLayout.addWidget(self.classificationAlgorithmContent)
        self.algorithmsStepScrollArea.setWidget(self.classificationAlgorithmSection)
        self.workflowStack.addWidget(self.algorithmsStepScrollArea)
        self.resultsStepScrollArea = QtWidgets.QScrollArea()
        self.resultsStepScrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.resultsStepScrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.resultsStepScrollArea.setWidgetResizable(True)
        self.resultsStepScrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.resultsStepScrollArea.setObjectName("resultsStepScrollArea")
        self.resultsPanel = QtWidgets.QWidget()
        self.resultsPanel.setGeometry(QtCore.QRect(0, 0, 1100, 650))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resultsPanel.sizePolicy().hasHeightForWidth())
        self.resultsPanel.setSizePolicy(sizePolicy)
        self.resultsPanel.setObjectName("resultsPanel")
        self.resultsPageLayout = QtWidgets.QVBoxLayout(self.resultsPanel)
        self.resultsPageLayout.setContentsMargins(0, 0, 0, 0)
        self.resultsPageLayout.setSpacing(8)
        self.resultsPageLayout.setObjectName("resultsPageLayout")
        self.classificationResultsSection = QtWidgets.QFrame(self.resultsPanel)
        self.classificationResultsSection.setProperty("gimapSection", True)
        self.classificationResultsSection.setObjectName("classificationResultsSection")
        self.classificationResultsSectionLayout = QtWidgets.QVBoxLayout(self.classificationResultsSection)
        self.classificationResultsSectionLayout.setContentsMargins(12, 10, 12, 12)
        self.classificationResultsSectionLayout.setSpacing(8)
        self.classificationResultsSectionLayout.setObjectName("classificationResultsSectionLayout")
        self.classificationResultsTitle = QtWidgets.QLabel(self.classificationResultsSection)
        self.classificationResultsTitle.setProperty("gimapSectionTitle", True)
        self.classificationResultsTitle.setObjectName("classificationResultsTitle")
        self.classificationResultsSectionLayout.addWidget(self.classificationResultsTitle)
        self.classificationResultsDescription = QtWidgets.QLabel(self.classificationResultsSection)
        self.classificationResultsDescription.setProperty("gimapSectionDescription", True)
        self.classificationResultsDescription.setWordWrap(True)
        self.classificationResultsDescription.setObjectName("classificationResultsDescription")
        self.classificationResultsSectionLayout.addWidget(self.classificationResultsDescription)
        self.classificationResultsContent = QtWidgets.QWidget(self.classificationResultsSection)
        self.classificationResultsContent.setObjectName("classificationResultsContent")
        self.classificationResultsContentLayout = QtWidgets.QVBoxLayout(self.classificationResultsContent)
        self.classificationResultsContentLayout.setContentsMargins(0, 0, 0, 0)
        self.classificationResultsContentLayout.setSpacing(8)
        self.classificationResultsContentLayout.setObjectName("classificationResultsContentLayout")
        self.classificationResultsSectionLayout.addWidget(self.classificationResultsContent)
        self.resultsPageLayout.addWidget(self.classificationResultsSection)
        self.classificationExportSection = QtWidgets.QFrame(self.resultsPanel)
        self.classificationExportSection.setProperty("gimapSection", True)
        self.classificationExportSection.setObjectName("classificationExportSection")
        self.classificationExportSectionLayout = QtWidgets.QVBoxLayout(self.classificationExportSection)
        self.classificationExportSectionLayout.setContentsMargins(12, 10, 12, 12)
        self.classificationExportSectionLayout.setSpacing(8)
        self.classificationExportSectionLayout.setObjectName("classificationExportSectionLayout")
        self.classificationExportTitle = QtWidgets.QLabel(self.classificationExportSection)
        self.classificationExportTitle.setProperty("gimapSectionTitle", True)
        self.classificationExportTitle.setObjectName("classificationExportTitle")
        self.classificationExportSectionLayout.addWidget(self.classificationExportTitle)
        self.classificationExportDescription = QtWidgets.QLabel(self.classificationExportSection)
        self.classificationExportDescription.setProperty("gimapSectionDescription", True)
        self.classificationExportDescription.setWordWrap(True)
        self.classificationExportDescription.setObjectName("classificationExportDescription")
        self.classificationExportSectionLayout.addWidget(self.classificationExportDescription)
        self.classificationExportContent = QtWidgets.QWidget(self.classificationExportSection)
        self.classificationExportContent.setObjectName("classificationExportContent")
        self.classificationExportContentLayout = QtWidgets.QHBoxLayout(self.classificationExportContent)
        self.classificationExportContentLayout.setContentsMargins(0, 0, 0, 0)
        self.classificationExportContentLayout.setSpacing(8)
        self.classificationExportContentLayout.setObjectName("classificationExportContentLayout")
        self.classificationExportSectionLayout.addWidget(self.classificationExportContent)
        self.resultsPageLayout.addWidget(self.classificationExportSection)
        self.resultsPageLayout.setStretch(0, 1)
        self.resultsStepScrollArea.setWidget(self.resultsPanel)
        self.workflowStack.addWidget(self.resultsStepScrollArea)
        self.rootLayout.addWidget(self.workflowStack)
        self.classificationLogSection = QtWidgets.QFrame(ClassificationPageRoot)
        self.classificationLogSection.setProperty("gimapSection", True)
        self.classificationLogSection.setObjectName("classificationLogSection")
        self.classificationLogSectionLayout = QtWidgets.QVBoxLayout(self.classificationLogSection)
        self.classificationLogSectionLayout.setContentsMargins(8, 8, 8, 8)
        self.classificationLogSectionLayout.setSpacing(7)
        self.classificationLogSectionLayout.setObjectName("classificationLogSectionLayout")
        self.logToggleButton = QtWidgets.QToolButton(self.classificationLogSection)
        self.logToggleButton.setProperty("gimapAdvancedToggle", True)
        self.logToggleButton.setCheckable(True)
        self.logToggleButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.logToggleButton.setArrowType(QtCore.Qt.RightArrow)
        self.logToggleButton.setObjectName("logToggleButton")
        self.classificationLogSectionLayout.addWidget(self.logToggleButton)
        self.classificationLogDescription = QtWidgets.QLabel(self.classificationLogSection)
        self.classificationLogDescription.setVisible(False)
        self.classificationLogDescription.setProperty("gimapSectionDescription", True)
        self.classificationLogDescription.setWordWrap(True)
        self.classificationLogDescription.setObjectName("classificationLogDescription")
        self.classificationLogSectionLayout.addWidget(self.classificationLogDescription)
        self.classificationLogContent = QtWidgets.QWidget(self.classificationLogSection)
        self.classificationLogContent.setVisible(False)
        self.classificationLogContent.setObjectName("classificationLogContent")
        self.classificationLogContentLayout = QtWidgets.QVBoxLayout(self.classificationLogContent)
        self.classificationLogContentLayout.setContentsMargins(4, 2, 4, 4)
        self.classificationLogContentLayout.setSpacing(8)
        self.classificationLogContentLayout.setObjectName("classificationLogContentLayout")
        self.logTextBrowser = QtWidgets.QTextBrowser(self.classificationLogContent)
        self.logTextBrowser.setMinimumSize(QtCore.QSize(0, 140))
        self.logTextBrowser.setMaximumSize(QtCore.QSize(16777215, 220))
        self.logTextBrowser.setObjectName("logTextBrowser")
        self.classificationLogContentLayout.addWidget(self.logTextBrowser)
        self.classificationLogSectionLayout.addWidget(self.classificationLogContent)
        self.rootLayout.addWidget(self.classificationLogSection)
        self.rootLayout.setStretch(2, 1)

        self.retranslateUi(ClassificationPageRoot)
        self.workflowStack.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ClassificationPageRoot)
        ClassificationPageRoot.setTabOrder(self.newSessionButton, self.loadSessionButton)
        ClassificationPageRoot.setTabOrder(self.loadSessionButton, self.saveSessionButton)
        ClassificationPageRoot.setTabOrder(self.saveSessionButton, self.helpButton)
        ClassificationPageRoot.setTabOrder(self.helpButton, self.datasetStepButton)
        ClassificationPageRoot.setTabOrder(self.datasetStepButton, self.preprocessingStepButton)
        ClassificationPageRoot.setTabOrder(self.preprocessingStepButton, self.algorithmsStepButton)
        ClassificationPageRoot.setTabOrder(self.algorithmsStepButton, self.resultsStepButton)
        ClassificationPageRoot.setTabOrder(self.resultsStepButton, self.logToggleButton)
        ClassificationPageRoot.setTabOrder(self.logToggleButton, self.logTextBrowser)

    def retranslateUi(self, ClassificationPageRoot):
        _translate = QtCore.QCoreApplication.translate
        self.titleLabel.setText(_translate("ClassificationPage", "Classification"))
        self.subtitleLabel.setText(_translate("ClassificationPage", "Import labeled datasets, compare classifiers, and inspect model performance."))
        self.newSessionButton.setText(_translate("ClassificationPage", "New Session"))
        self.loadSessionButton.setText(_translate("ClassificationPage", "Load Session"))
        self.saveSessionButton.setText(_translate("ClassificationPage", "Save Session"))
        self.helpButton.setToolTip(_translate("ClassificationPage", "Classification workflow help"))
        self.helpButton.setText(_translate("ClassificationPage", "?"))
        self.datasetStepButton.setText(_translate("ClassificationPage", "1  Dataset"))
        self.preprocessingStepButton.setText(_translate("ClassificationPage", "2  Preprocessing"))
        self.algorithmsStepButton.setText(_translate("ClassificationPage", "3  Algorithms"))
        self.resultsStepButton.setText(_translate("ClassificationPage", "4  Results"))
        self.stateBadgeLabel.setText(_translate("ClassificationPage", "EMPTY"))
        self.classificationInputTitle.setText(_translate("ClassificationPage", "Input"))
        self.classificationInputDescription.setText(_translate("ClassificationPage", "Create labeled classes, scan files and review dataset quality before training."))
        self.classificationPreviewTitle.setText(_translate("ClassificationPage", "Preview"))
        self.classificationPreviewDescription.setText(_translate("ClassificationPage", "Inspect the selected sample and its quality checks."))
        self.classificationConfigureTitle.setText(_translate("ClassificationPage", "Configure"))
        self.classificationConfigureDescription.setText(_translate("ClassificationPage", "Build the shared preprocessing pipeline used by every selected classifier."))
        self.classificationAlgorithmTitle.setText(_translate("ClassificationPage", "Configure"))
        self.classificationAlgorithmDescription.setText(_translate("ClassificationPage", "Select classifiers and keep validation/projection options in the Advanced section."))
        self.classificationResultsTitle.setText(_translate("ClassificationPage", "Results"))
        self.classificationResultsDescription.setText(_translate("ClassificationPage", "Compare ranked models, confusion matrices, class metrics and predictions."))
        self.classificationExportTitle.setText(_translate("ClassificationPage", "Export"))
        self.classificationExportDescription.setText(_translate("ClassificationPage", "Save the active model, experiment summary or prediction CSV with the original commands."))
        self.logToggleButton.setText(_translate("ClassificationPage", "Log"))
        self.classificationLogDescription.setText(_translate("ClassificationPage", "Dataset import, training, prediction and export messages."))
