"""Port for the persisted manual fitting model parameters."""

from __future__ import annotations

from pathlib import Path
from typing import Protocol


class FittingModelParametersPort(Protocol):
    @property
    def config_path(self) -> Path: ...

    def load(self) -> bool: ...

    def save(self) -> bool: ...

    def section(self, module: str, default=None): ...

    def replace_section(self, module: str, values: dict) -> None: ...

    def ensure_particle(self, module: str, particle_id: str, shape: str): ...

    def remove_particle(self, module: str, particle_id: str) -> bool: ...

    def particles(self, module: str) -> dict: ...

    def particle_parameter(self, module, particle_id, shape=None, param=None): ...

    def set_particle_parameter(self, module, particle_id, shape, param, value) -> bool: ...

    def particle_shape(self, module: str, particle_id: str) -> str: ...

    def set_particle_shape(self, module: str, particle_id: str, shape: str) -> bool: ...

    def particle_enabled(self, module: str, particle_id: str) -> bool: ...

    def set_particle_enabled(self, module: str, particle_id: str, enabled: bool) -> bool: ...

    def global_parameter(self, module: str, name: str, default=None): ...

    def set_global_parameter(self, module: str, name: str, value) -> bool: ...

    def global_parameters(self, module: str) -> dict: ...
