"""Hand-maintained layout for the geometry calibration dialog.

Left pane: the inputs scroll (Input, Advanced configuration, Manual refinement) with the Run
section pinned below it, so Auto Calibration, Cancel and the job status are always visible.
Right pane: Preview above Results in a splitter whose children cannot collapse; the preview
canvas keeps a usable minimum height.  A one-row footer holds Import, Export, Apply and Close.
"""

from PyQt5 import QtCore, QtWidgets


from .geometry_calibration_translations import GeometryCalibrationTranslations


from .geometry_calibration_sections import GeometryCalibrationSections

# The canvas never shrinks below this; the results area and the footer give way first.
PREVIEW_CANVAS_MIN_HEIGHT = 240


class GeometryCalibrationDialogView(GeometryCalibrationSections, GeometryCalibrationTranslations):
    def setupUi(self, GeometryCalibrationDialog):
        GeometryCalibrationDialog.setObjectName("GeometryCalibrationDialog")
        GeometryCalibrationDialog.resize(1180, 760)
        GeometryCalibrationDialog.setMinimumSize(QtCore.QSize(900, 560))
        GeometryCalibrationDialog.setModal(False)
        self.rootLayout = QtWidgets.QVBoxLayout(GeometryCalibrationDialog)
        self.rootLayout.setContentsMargins(12, 12, 12, 12)
        self.rootLayout.setSpacing(8)
        self.rootLayout.setObjectName("rootLayout")
        self.main_splitter = QtWidgets.QSplitter(GeometryCalibrationDialog)
        self.main_splitter.setOrientation(QtCore.Qt.Horizontal)
        self.main_splitter.setChildrenCollapsible(False)
        self.main_splitter.setObjectName("main_splitter")
        self.calibrationLeftPane = QtWidgets.QWidget(self.main_splitter)
        # Wide enough for the form labels and the path placeholder in the narrowest window.
        self.calibrationLeftPane.setMinimumSize(QtCore.QSize(372, 0))
        self.calibrationLeftPane.setMaximumSize(QtCore.QSize(600, 16777215))
        self.calibrationLeftPane.setObjectName("calibrationLeftPane")
        self.calibrationLeftLayout = QtWidgets.QVBoxLayout(self.calibrationLeftPane)
        self.calibrationLeftLayout.setContentsMargins(0, 0, 6, 0)
        self.calibrationLeftLayout.setSpacing(8)
        self.calibrationLeftLayout.setObjectName("calibrationLeftLayout")
        self.calibrationControlsScroll = QtWidgets.QScrollArea(self.calibrationLeftPane)
        self.calibrationControlsScroll.setMinimumSize(QtCore.QSize(280, 0))
        self.calibrationControlsScroll.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.calibrationControlsScroll.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.calibrationControlsScroll.setWidgetResizable(True)
        self.calibrationControlsScroll.setObjectName("calibrationControlsScroll")
        self.controls = QtWidgets.QWidget()
        self.controls.setGeometry(QtCore.QRect(0, 0, 390, 720))
        self.controls.setMinimumSize(QtCore.QSize(260, 0))
        self.controls.setObjectName("controls")
        self.controlsLayout = QtWidgets.QVBoxLayout(self.controls)
        self.controlsLayout.setContentsMargins(0, 0, 6, 0)
        self.controlsLayout.setSpacing(8)
        self.controlsLayout.setObjectName("controlsLayout")
        self.calibration_input_section = QtWidgets.QFrame(self.controls)
        self.calibration_input_section.setProperty("gimapSection", True)
        self.calibration_input_section.setObjectName("calibration_input_section")
        self.calibrationInputSectionLayout = QtWidgets.QVBoxLayout(self.calibration_input_section)
        self.calibrationInputSectionLayout.setContentsMargins(12, 10, 12, 12)
        self.calibrationInputSectionLayout.setSpacing(8)
        self.calibrationInputSectionLayout.setObjectName("calibrationInputSectionLayout")
        self.calibrationInputTitle = QtWidgets.QLabel(self.calibration_input_section)
        self.calibrationInputTitle.setProperty("gimapSectionTitle", True)
        self.calibrationInputTitle.setObjectName("calibrationInputTitle")
        self.calibrationInputSectionLayout.addWidget(self.calibrationInputTitle)
        self.calibrationInputDescription = QtWidgets.QLabel(self.calibration_input_section)
        self.calibrationInputDescription.setProperty("gimapSectionDescription", True)
        self.calibrationInputDescription.setWordWrap(True)
        self.calibrationInputDescription.setObjectName("calibrationInputDescription")
        self.calibrationInputSectionLayout.addWidget(self.calibrationInputDescription)
        self.calibrationInputContent = QtWidgets.QWidget(self.calibration_input_section)
        self.calibrationInputContent.setObjectName("calibrationInputContent")
        self.calibrationInputContentLayout = QtWidgets.QVBoxLayout(self.calibrationInputContent)
        self.calibrationInputContentLayout.setContentsMargins(0, 0, 0, 0)
        self.calibrationInputContentLayout.setSpacing(8)
        self.calibrationInputContentLayout.setObjectName("calibrationInputContentLayout")
        self.calibration_file_group = QtWidgets.QGroupBox(self.calibrationInputContent)
        self.calibration_file_group.setObjectName("calibration_file_group")
        self.calibrationFileLayout = QtWidgets.QHBoxLayout(self.calibration_file_group)
        self.calibrationFileLayout.setObjectName("calibrationFileLayout")
        self.path_edit = QtWidgets.QLineEdit(self.calibration_file_group)
        self.path_edit.setObjectName("path_edit")
        self.calibrationFileLayout.addWidget(self.path_edit)
        self.open_button = QtWidgets.QPushButton(self.calibration_file_group)
        self.open_button.setObjectName("open_button")
        self.calibrationFileLayout.addWidget(self.open_button)
        self.calibrationInputContentLayout.addWidget(self.calibration_file_group)
        self.calibration_input_group = QtWidgets.QGroupBox(self.calibrationInputContent)
        self.calibration_input_group.setObjectName("calibration_input_group")
        self.calibrationInputForm = QtWidgets.QFormLayout(self.calibration_input_group)
        self.calibrationInputForm.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.calibrationInputForm.setObjectName("calibrationInputForm")
        self.energyLabel = QtWidgets.QLabel(self.calibration_input_group)
        self.energyLabel.setObjectName("energyLabel")
        self.calibrationInputForm.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.energyLabel)
        self.energy_spin = QtWidgets.QDoubleSpinBox(self.calibration_input_group)
        self.energy_spin.setDecimals(5)
        self.energy_spin.setMinimum(0.1)
        self.energy_spin.setMaximum(200.0)
        self.energy_spin.setProperty("value", 12.0)
        self.energy_spin.setKeyboardTracking(False)
        self.energy_spin.setObjectName("energy_spin")
        self.calibrationInputForm.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.energy_spin)
        self.standardLabel = QtWidgets.QLabel(self.calibration_input_group)
        self.standardLabel.setObjectName("standardLabel")
        self.calibrationInputForm.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.standardLabel)
        self.standard_combo = QtWidgets.QComboBox(self.calibration_input_group)
        self._compact_combo(self.standard_combo)
        self.standard_combo.setObjectName("standard_combo")
        self.calibrationInputForm.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.standard_combo)
        self.estimatedDistanceLabel = QtWidgets.QLabel(self.calibration_input_group)
        self.estimatedDistanceLabel.setObjectName("estimatedDistanceLabel")
        self.calibrationInputForm.setWidget(
            2, QtWidgets.QFormLayout.LabelRole, self.estimatedDistanceLabel
        )
        self.estimated_distance_spin = QtWidgets.QDoubleSpinBox(self.calibration_input_group)
        self.estimated_distance_spin.setDecimals(2)
        self.estimated_distance_spin.setMaximum(100000.0)
        self.estimated_distance_spin.setKeyboardTracking(False)
        self.estimated_distance_spin.setObjectName("estimated_distance_spin")
        self.calibrationInputForm.setWidget(
            2, QtWidgets.QFormLayout.FieldRole, self.estimated_distance_spin
        )
        self.rangeLabel = QtWidgets.QLabel(self.calibration_input_group)
        self.rangeLabel.setObjectName("rangeLabel")
        self.calibrationInputForm.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.rangeLabel)
        self.range_combo = QtWidgets.QComboBox(self.calibration_input_group)
        self._compact_combo(self.range_combo)
        self.range_combo.setObjectName("range_combo")
        self.range_combo.addItem("")
        self.range_combo.addItem("")
        self.range_combo.addItem("")
        self.range_combo.addItem("")
        self.calibrationInputForm.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.range_combo)
        self.pixelSizeLabel = QtWidgets.QLabel(self.calibration_input_group)
        self.pixelSizeLabel.setObjectName("pixelSizeLabel")
        self.calibrationInputForm.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.pixelSizeLabel)
        self.pixel_label = QtWidgets.QLabel(self.calibration_input_group)
        self.pixel_label.setWordWrap(True)
        self.pixel_label.setObjectName("pixel_label")
        self.calibrationInputForm.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.pixel_label)
        self.detectorLabel = QtWidgets.QLabel(self.calibration_input_group)
        self.detectorLabel.setObjectName("detectorLabel")
        self.calibrationInputForm.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.detectorLabel)
        self.detector_label = QtWidgets.QLabel(self.calibration_input_group)
        self.detector_label.setWordWrap(True)
        self.detector_label.setObjectName("detector_label")
        self.calibrationInputForm.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.detector_label)
        self.detectorModelLabel = QtWidgets.QLabel(self.calibration_input_group)
        self.detectorModelLabel.setObjectName("detectorModelLabel")
        self.calibrationInputForm.setWidget(
            6, QtWidgets.QFormLayout.LabelRole, self.detectorModelLabel
        )
        self.detector_combo = QtWidgets.QComboBox(self.calibration_input_group)
        self._compact_combo(self.detector_combo)
        self.detector_combo.setObjectName("detector_combo")
        self.calibrationInputForm.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.detector_combo)
        self.calibrationInputContentLayout.addWidget(self.calibration_input_group)
        self.calibrationInputSectionLayout.addWidget(self.calibrationInputContent)
        self.controlsLayout.addWidget(self.calibration_input_section)
        self.calibration_advanced_section = QtWidgets.QFrame(self.controls)
        self.calibration_advanced_section.setProperty("gimapSection", True)
        self.calibration_advanced_section.setObjectName("calibration_advanced_section")
        self.calibrationAdvancedSectionLayout = QtWidgets.QVBoxLayout(
            self.calibration_advanced_section
        )
        self.calibrationAdvancedSectionLayout.setContentsMargins(8, 8, 8, 8)
        self.calibrationAdvancedSectionLayout.setSpacing(7)
        self.calibrationAdvancedSectionLayout.setObjectName("calibrationAdvancedSectionLayout")
        self.calibrationAdvancedToggle = QtWidgets.QToolButton(self.calibration_advanced_section)
        self.calibrationAdvancedToggle.setProperty("gimapAdvancedToggle", True)
        self.calibrationAdvancedToggle.setCheckable(True)
        self.calibrationAdvancedToggle.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.calibrationAdvancedToggle.setArrowType(QtCore.Qt.RightArrow)
        self.calibrationAdvancedToggle.setObjectName("calibrationAdvancedToggle")
        self.calibrationAdvancedSectionLayout.addWidget(self.calibrationAdvancedToggle)
        self.calibrationAdvancedDescription = QtWidgets.QLabel(self.calibration_advanced_section)
        self.calibrationAdvancedDescription.setVisible(False)
        self.calibrationAdvancedDescription.setProperty("gimapSectionDescription", True)
        self.calibrationAdvancedDescription.setWordWrap(True)
        self.calibrationAdvancedDescription.setObjectName("calibrationAdvancedDescription")
        self.calibrationAdvancedSectionLayout.addWidget(self.calibrationAdvancedDescription)
        self.calibrationAdvancedContent = QtWidgets.QWidget(self.calibration_advanced_section)
        self.calibrationAdvancedContent.setVisible(False)
        self.calibrationAdvancedContent.setObjectName("calibrationAdvancedContent")
        self.calibrationAdvancedContentLayout = QtWidgets.QVBoxLayout(
            self.calibrationAdvancedContent
        )
        self.calibrationAdvancedContentLayout.setContentsMargins(4, 2, 4, 4)
        self.calibrationAdvancedContentLayout.setSpacing(8)
        self.calibrationAdvancedContentLayout.setObjectName("calibrationAdvancedContentLayout")
        self.advanced_group = QtWidgets.QGroupBox(self.calibrationAdvancedContent)
        self.advanced_group.setObjectName("advanced_group")
        self.advancedForm = QtWidgets.QFormLayout(self.advanced_group)
        self.advancedForm.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.advancedForm.setObjectName("advancedForm")
        self.pixelXLabel = QtWidgets.QLabel(self.advanced_group)
        self.pixelXLabel.setObjectName("pixelXLabel")
        self.advancedForm.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pixelXLabel)
        self.pixel_x_spin = QtWidgets.QDoubleSpinBox(self.advanced_group)
        self.pixel_x_spin.setDecimals(4)
        self.pixel_x_spin.setMinimum(1.0)
        self.pixel_x_spin.setMaximum(1000.0)
        self.pixel_x_spin.setProperty("value", 172.0)
        self.pixel_x_spin.setKeyboardTracking(False)
        self.pixel_x_spin.setObjectName("pixel_x_spin")
        self.advancedForm.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.pixel_x_spin)
        self.pixelYLabel = QtWidgets.QLabel(self.advanced_group)
        self.pixelYLabel.setObjectName("pixelYLabel")
        self.advancedForm.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pixelYLabel)
        self.pixel_y_spin = QtWidgets.QDoubleSpinBox(self.advanced_group)
        self.pixel_y_spin.setDecimals(4)
        self.pixel_y_spin.setMinimum(1.0)
        self.pixel_y_spin.setMaximum(1000.0)
        self.pixel_y_spin.setProperty("value", 172.0)
        self.pixel_y_spin.setKeyboardTracking(False)
        self.pixel_y_spin.setObjectName("pixel_y_spin")
        self.advancedForm.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.pixel_y_spin)
        self.customMinLabel = QtWidgets.QLabel(self.advanced_group)
        self.customMinLabel.setObjectName("customMinLabel")
        self.advancedForm.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.customMinLabel)
        self.custom_min_spin = QtWidgets.QDoubleSpinBox(self.advanced_group)
        self.custom_min_spin.setDecimals(1)
        self.custom_min_spin.setMinimum(1.0)
        self.custom_min_spin.setMaximum(100000.0)
        self.custom_min_spin.setProperty("value", 30.0)
        self.custom_min_spin.setKeyboardTracking(False)
        self.custom_min_spin.setObjectName("custom_min_spin")
        self.advancedForm.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.custom_min_spin)
        self.customMaxLabel = QtWidgets.QLabel(self.advanced_group)
        self.customMaxLabel.setObjectName("customMaxLabel")
        self.advancedForm.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.customMaxLabel)
        self.custom_max_spin = QtWidgets.QDoubleSpinBox(self.advanced_group)
        self.custom_max_spin.setDecimals(1)
        self.custom_max_spin.setMinimum(1.0)
        self.custom_max_spin.setMaximum(100000.0)
        self.custom_max_spin.setProperty("value", 10000.0)
        self.custom_max_spin.setKeyboardTracking(False)
        self.custom_max_spin.setObjectName("custom_max_spin")
        self.advancedForm.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.custom_max_spin)
        self.background_check = QtWidgets.QCheckBox(self.advanced_group)
        self.background_check.setChecked(True)
        self.background_check.setObjectName("background_check")
        self.advancedForm.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.background_check)
        self.log_check = QtWidgets.QCheckBox(self.advanced_group)
        self.log_check.setChecked(True)
        self.log_check.setObjectName("log_check")
        self.advancedForm.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.log_check)
        self.mask_check = QtWidgets.QCheckBox(self.advanced_group)
        self.mask_check.setObjectName("mask_check")
        self.advancedForm.setWidget(6, QtWidgets.QFormLayout.SpanningRole, self.mask_check)
        self.rings_check = QtWidgets.QCheckBox(self.advanced_group)
        self.rings_check.setChecked(True)
        self.rings_check.setObjectName("rings_check")
        self.advancedForm.setWidget(7, QtWidgets.QFormLayout.SpanningRole, self.rings_check)
        self.center_check = QtWidgets.QCheckBox(self.advanced_group)
        self.center_check.setChecked(True)
        self.center_check.setObjectName("center_check")
        self.advancedForm.setWidget(8, QtWidgets.QFormLayout.SpanningRole, self.center_check)
        self.calibrationAdvancedContentLayout.addWidget(self.advanced_group)
        self.calibrationAdvancedSectionLayout.addWidget(self.calibrationAdvancedContent)
        self.controlsLayout.addWidget(self.calibration_advanced_section)
        self._setup_manual_section(self.controls)
        self.controlsLayout.addWidget(self.calibration_manual_section)
        spacerItem = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.controlsLayout.addItem(spacerItem)
        self.calibrationControlsScroll.setWidget(self.controls)
        self.calibrationLeftLayout.addWidget(self.calibrationControlsScroll, 1)
        # Pinned below the scroll area: the primary action and its status never scroll away.
        self.calibration_run_section = QtWidgets.QFrame(self.calibrationLeftPane)
        self.calibration_run_section.setProperty("gimapSection", True)
        self.calibration_run_section.setObjectName("calibration_run_section")
        self.calibrationRunSectionLayout = QtWidgets.QVBoxLayout(self.calibration_run_section)
        self.calibrationRunSectionLayout.setContentsMargins(12, 10, 12, 12)
        self.calibrationRunSectionLayout.setSpacing(8)
        self.calibrationRunSectionLayout.setObjectName("calibrationRunSectionLayout")
        self.calibrationRunTitle = QtWidgets.QLabel(self.calibration_run_section)
        self.calibrationRunTitle.setProperty("gimapSectionTitle", True)
        self.calibrationRunTitle.setObjectName("calibrationRunTitle")
        self.calibrationRunSectionLayout.addWidget(self.calibrationRunTitle)
        self.calibrationRunDescription = QtWidgets.QLabel(self.calibration_run_section)
        self.calibrationRunDescription.setProperty("gimapSectionDescription", True)
        self.calibrationRunDescription.setWordWrap(True)
        self.calibrationRunDescription.setObjectName("calibrationRunDescription")
        self.calibrationRunSectionLayout.addWidget(self.calibrationRunDescription)
        self.calibrationRunContent = QtWidgets.QWidget(self.calibration_run_section)
        self.calibrationRunContent.setObjectName("calibrationRunContent")
        self.calibrationRunContentLayout = QtWidgets.QVBoxLayout(self.calibrationRunContent)
        self.calibrationRunContentLayout.setContentsMargins(0, 0, 0, 0)
        self.calibrationRunContentLayout.setSpacing(8)
        self.calibrationRunContentLayout.setObjectName("calibrationRunContentLayout")
        self.calibrationRunActions = QtWidgets.QHBoxLayout()
        self.calibrationRunActions.setObjectName("calibrationRunActions")
        self.calibrate_button = QtWidgets.QPushButton(self.calibrationRunContent)
        self.calibrate_button.setDefault(True)
        self.calibrate_button.setObjectName("calibrate_button")
        self.calibrationRunActions.addWidget(self.calibrate_button, 1)
        self.cancel_button = QtWidgets.QPushButton(self.calibrationRunContent)
        self.cancel_button.setObjectName("cancel_button")
        self.calibrationRunActions.addWidget(self.cancel_button)
        self.calibrationRunContentLayout.addLayout(self.calibrationRunActions)
        self.job_status = JobStatus(self.calibrationRunContent)
        self.job_status.setObjectName("job_status")
        self.calibrationRunContentLayout.addWidget(self.job_status)
        self.calibrationRunSectionLayout.addWidget(self.calibrationRunContent)
        self.calibrationLeftLayout.addWidget(self.calibration_run_section, 0)
        self.right = QtWidgets.QWidget(self.main_splitter)
        self.right.setObjectName("right")
        self.rightLayout = QtWidgets.QVBoxLayout(self.right)
        self.rightLayout.setContentsMargins(6, 0, 0, 0)
        self.rightLayout.setObjectName("rightLayout")
        self.right_splitter = QtWidgets.QSplitter(self.right)
        self.right_splitter.setOrientation(QtCore.Qt.Vertical)
        self.right_splitter.setChildrenCollapsible(False)
        self.right_splitter.setObjectName("right_splitter")
        self.calibration_preview_panel = QtWidgets.QFrame(self.right_splitter)
        self.calibration_preview_panel.setProperty("gimapSection", True)
        self.calibration_preview_panel.setObjectName("calibration_preview_panel")
        self.calibrationPreviewSectionLayout = QtWidgets.QVBoxLayout(self.calibration_preview_panel)
        self.calibrationPreviewSectionLayout.setContentsMargins(12, 10, 12, 12)
        self.calibrationPreviewSectionLayout.setSpacing(8)
        self.calibrationPreviewSectionLayout.setObjectName("calibrationPreviewSectionLayout")
        self.calibrationPreviewTitle = QtWidgets.QLabel(self.calibration_preview_panel)
        self.calibrationPreviewTitle.setProperty("gimapSectionTitle", True)
        self.calibrationPreviewTitle.setObjectName("calibrationPreviewTitle")
        self.calibrationPreviewSectionLayout.addWidget(self.calibrationPreviewTitle)
        self.calibrationPreviewDescription = QtWidgets.QLabel(self.calibration_preview_panel)
        self.calibrationPreviewDescription.setProperty("gimapSectionDescription", True)
        self.calibrationPreviewDescription.setWordWrap(True)
        self.calibrationPreviewDescription.setObjectName("calibrationPreviewDescription")
        self.calibrationPreviewSectionLayout.addWidget(self.calibrationPreviewDescription)
        self.calibrationPreviewContent = QtWidgets.QWidget(self.calibration_preview_panel)
        self.calibrationPreviewContent.setObjectName("calibrationPreviewContent")
        self.calibrationPreviewContentLayout = QtWidgets.QVBoxLayout(self.calibrationPreviewContent)
        self.calibrationPreviewContentLayout.setContentsMargins(0, 0, 0, 0)
        self.calibrationPreviewContentLayout.setSpacing(6)
        self.calibrationPreviewContentLayout.setObjectName("calibrationPreviewContentLayout")
        # One row: the preview actions, then the matplotlib navigation toolbar (zoom, pan…).
        self.previewActionsLayout = QtWidgets.QHBoxLayout()
        self.previewActionsLayout.setObjectName("previewActionsLayout")
        self.fit_image_button = QtWidgets.QPushButton(self.calibrationPreviewContent)
        self.fit_image_button.setObjectName("fit_image_button")
        self.previewActionsLayout.addWidget(self.fit_image_button)
        self.clean_preview_button = QtWidgets.QPushButton(self.calibrationPreviewContent)
        self.clean_preview_button.setCheckable(True)
        self.clean_preview_button.setEnabled(False)
        self.clean_preview_button.setObjectName("clean_preview_button")
        self.previewActionsLayout.addWidget(self.clean_preview_button)
        self.expand_preview_button = QtWidgets.QPushButton(self.calibrationPreviewContent)
        self.expand_preview_button.setObjectName("expand_preview_button")
        self.previewActionsLayout.addWidget(self.expand_preview_button)
        self.manual_refine_button = QtWidgets.QPushButton(self.calibrationPreviewContent)
        self.manual_refine_button.setCheckable(True)
        self.manual_refine_button.setEnabled(False)
        self.manual_refine_button.setObjectName("manual_refine_button")
        self.previewActionsLayout.addWidget(self.manual_refine_button)
        spacerItem1 = QtWidgets.QSpacerItem(
            12, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.previewActionsLayout.addItem(spacerItem1)
        self.calibrationToolbarHost = QtWidgets.QWidget(self.calibrationPreviewContent)
        self.calibrationToolbarHost.setObjectName("calibrationToolbarHost")
        self.calibrationToolbarHostLayout = QtWidgets.QHBoxLayout(self.calibrationToolbarHost)
        self.calibrationToolbarHostLayout.setContentsMargins(0, 0, 0, 0)
        self.calibrationToolbarHostLayout.setObjectName("calibrationToolbarHostLayout")
        self.previewActionsLayout.addWidget(self.calibrationToolbarHost)
        self.calibrationPreviewContentLayout.addLayout(self.previewActionsLayout)
        # The toolbar moves to this row (empty otherwise) when the actions row is too narrow.
        self.previewToolbarRowLayout = QtWidgets.QHBoxLayout()
        self.previewToolbarRowLayout.setObjectName("previewToolbarRowLayout")
        self.previewToolbarRowLayout.addStretch(1)
        self.calibrationPreviewContentLayout.addLayout(self.previewToolbarRowLayout)
        self.previewInfoLayout = QtWidgets.QHBoxLayout()
        self.previewInfoLayout.setObjectName("previewInfoLayout")
        self.preview_info_label = QtWidgets.QLabel(self.calibrationPreviewContent)
        self.preview_info_label.setWordWrap(True)
        self.preview_info_label.setObjectName("preview_info_label")
        self.previewInfoLayout.addWidget(self.preview_info_label, 1)
        # Cursor position and pixel value under the mouse (numbers only, never translated).
        self.preview_cursor_label = QtWidgets.QLabel(self.calibrationPreviewContent)
        self.preview_cursor_label.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignVCenter)
        self.preview_cursor_label.setObjectName("preview_cursor_label")
        self.previewInfoLayout.addWidget(self.preview_cursor_label)
        self.calibrationPreviewContentLayout.addLayout(self.previewInfoLayout)
        self.overlay_legend = QtWidgets.QLabel(self.calibrationPreviewContent)
        self.overlay_legend.setVisible(False)
        self.overlay_legend.setText("")
        self.overlay_legend.setTextFormat(QtCore.Qt.RichText)
        self.overlay_legend.setObjectName("overlay_legend")
        self.calibrationPreviewContentLayout.addWidget(self.overlay_legend)
        self.calibrationFigureHost = QtWidgets.QWidget(self.calibrationPreviewContent)
        self.calibrationFigureHost.setMinimumSize(QtCore.QSize(0, PREVIEW_CANVAS_MIN_HEIGHT))
        self.calibrationFigureHost.setObjectName("calibrationFigureHost")
        # The canvas goes into cell (0, 0); the empty-state text lies over it in the same cell.
        self.calibrationFigureHostLayout = QtWidgets.QGridLayout(self.calibrationFigureHost)
        self.calibrationFigureHostLayout.setContentsMargins(0, 0, 0, 0)
        self.calibrationFigureHostLayout.setObjectName("calibrationFigureHostLayout")
        # A Qt label, not figure text, so every interface language renders with Qt's fonts.
        self.preview_empty_label = QtWidgets.QLabel(self.calibrationFigureHost)
        self.preview_empty_label.setAlignment(QtCore.Qt.AlignCenter)
        self.preview_empty_label.setWordWrap(True)
        self.preview_empty_label.setAttribute(QtCore.Qt.WA_TransparentForMouseEvents, True)
        self.preview_empty_label.setObjectName("preview_empty_label")
        self.calibrationFigureHostLayout.addWidget(self.preview_empty_label, 0, 0)
        self.calibrationPreviewContentLayout.addWidget(self.calibrationFigureHost, 1)
        self.calibrationPreviewSectionLayout.addWidget(self.calibrationPreviewContent, 1)
        self._setup_results_section(self.right_splitter)
        self.rightLayout.addWidget(self.right_splitter)
        self.rootLayout.addWidget(self.main_splitter, 1)
        self._setup_export_footer(GeometryCalibrationDialog)
        self.rootLayout.addWidget(self.calibration_export_section, 0)

        self.retranslateUi(GeometryCalibrationDialog)
        QtCore.QMetaObject.connectSlotsByName(GeometryCalibrationDialog)
        GeometryCalibrationDialog.setTabOrder(self.path_edit, self.open_button)
        GeometryCalibrationDialog.setTabOrder(self.open_button, self.energy_spin)
        GeometryCalibrationDialog.setTabOrder(self.energy_spin, self.standard_combo)
        GeometryCalibrationDialog.setTabOrder(self.standard_combo, self.estimated_distance_spin)
        GeometryCalibrationDialog.setTabOrder(self.estimated_distance_spin, self.range_combo)
        GeometryCalibrationDialog.setTabOrder(self.range_combo, self.detector_combo)
        GeometryCalibrationDialog.setTabOrder(self.detector_combo, self.calibrate_button)
        GeometryCalibrationDialog.setTabOrder(self.calibrate_button, self.cancel_button)
        GeometryCalibrationDialog.setTabOrder(self.cancel_button, self.fit_image_button)
        GeometryCalibrationDialog.setTabOrder(self.fit_image_button, self.clean_preview_button)
        GeometryCalibrationDialog.setTabOrder(self.clean_preview_button, self.expand_preview_button)
        GeometryCalibrationDialog.setTabOrder(self.expand_preview_button, self.manual_refine_button)
        GeometryCalibrationDialog.setTabOrder(self.manual_refine_button, self.candidate_table)
        GeometryCalibrationDialog.setTabOrder(self.candidate_table, self.import_button)
        GeometryCalibrationDialog.setTabOrder(self.import_button, self.export_button)
        GeometryCalibrationDialog.setTabOrder(self.export_button, self.apply_button)
        GeometryCalibrationDialog.setTabOrder(self.apply_button, self.close_button)


from src.gimap.app.presentation import JobStatus
