"""Semantic section builders for the calibration Python view."""

from PyQt5 import QtCore, QtWidgets


class GeometryCalibrationSections:
    """Build independently maintainable calibration layout sections."""

    def _setup_manual_section(self, GeometryCalibrationDialog):
        self.calibration_manual_section = QtWidgets.QFrame(GeometryCalibrationDialog)
        self.calibration_manual_section.setProperty("gimapSection", True)
        self.calibration_manual_section.setObjectName("calibration_manual_section")
        self.calibrationManualSectionLayout = QtWidgets.QVBoxLayout(self.calibration_manual_section)
        self.calibrationManualSectionLayout.setContentsMargins(8, 8, 8, 8)
        self.calibrationManualSectionLayout.setSpacing(7)
        self.calibrationManualSectionLayout.setObjectName("calibrationManualSectionLayout")
        self.calibrationManualToggle = QtWidgets.QToolButton(self.calibration_manual_section)
        self.calibrationManualToggle.setProperty("gimapAdvancedToggle", True)
        self.calibrationManualToggle.setCheckable(True)
        self.calibrationManualToggle.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.calibrationManualToggle.setArrowType(QtCore.Qt.RightArrow)
        self.calibrationManualToggle.setObjectName("calibrationManualToggle")
        self.calibrationManualSectionLayout.addWidget(self.calibrationManualToggle)
        self.calibrationManualDescription = QtWidgets.QLabel(self.calibration_manual_section)
        self.calibrationManualDescription.setVisible(False)
        self.calibrationManualDescription.setProperty("gimapSectionDescription", True)
        self.calibrationManualDescription.setWordWrap(True)
        self.calibrationManualDescription.setObjectName("calibrationManualDescription")
        self.calibrationManualSectionLayout.addWidget(self.calibrationManualDescription)
        self.calibrationManualContent = QtWidgets.QWidget(self.calibration_manual_section)
        self.calibrationManualContent.setVisible(False)
        self.calibrationManualContent.setObjectName("calibrationManualContent")
        self.calibrationManualContentLayout = QtWidgets.QVBoxLayout(self.calibrationManualContent)
        self.calibrationManualContentLayout.setContentsMargins(4, 2, 4, 4)
        self.calibrationManualContentLayout.setSpacing(8)
        self.calibrationManualContentLayout.setObjectName("calibrationManualContentLayout")
        self.manual_group = QtWidgets.QGroupBox(self.calibrationManualContent)
        self.manual_group.setEnabled(False)
        self.manual_group.setMaximumSize(QtCore.QSize(16777215, 40))
        self.manual_group.setCheckable(True)
        self.manual_group.setChecked(False)
        self.manual_group.setObjectName("manual_group")
        self.manualGroupLayout = QtWidgets.QVBoxLayout(self.manual_group)
        self.manualGroupLayout.setObjectName("manualGroupLayout")
        self.manual_panel = QtWidgets.QWidget(self.manual_group)
        self.manual_panel.setVisible(False)
        self.manual_panel.setObjectName("manual_panel")
        self.manualGridLayout = QtWidgets.QGridLayout(self.manual_panel)
        self.manualGridLayout.setContentsMargins(4, 2, 4, 4)
        self.manualGridLayout.setObjectName("manualGridLayout")
        self.manual_hint = QtWidgets.QLabel(self.manual_panel)
        self.manual_hint.setObjectName("manual_hint")
        self.manualGridLayout.addWidget(self.manual_hint, 0, 0, 1, 6)
        self.manualXLabel = QtWidgets.QLabel(self.manual_panel)
        self.manualXLabel.setObjectName("manualXLabel")
        self.manualGridLayout.addWidget(self.manualXLabel, 1, 0, 1, 1)
        self.manual_x = QtWidgets.QDoubleSpinBox(self.manual_panel)
        self.manual_x.setDecimals(3)
        self.manual_x.setMinimum(-100000.0)
        self.manual_x.setMaximum(100000.0)
        self.manual_x.setKeyboardTracking(False)
        self.manual_x.setObjectName("manual_x")
        self.manualGridLayout.addWidget(self.manual_x, 1, 1, 1, 1)
        self.manualYLabel = QtWidgets.QLabel(self.manual_panel)
        self.manualYLabel.setObjectName("manualYLabel")
        self.manualGridLayout.addWidget(self.manualYLabel, 1, 2, 1, 1)
        self.manual_y = QtWidgets.QDoubleSpinBox(self.manual_panel)
        self.manual_y.setDecimals(3)
        self.manual_y.setMinimum(-100000.0)
        self.manual_y.setMaximum(100000.0)
        self.manual_y.setKeyboardTracking(False)
        self.manual_y.setObjectName("manual_y")
        self.manualGridLayout.addWidget(self.manual_y, 1, 3, 1, 1)
        self.manualDistanceLabel = QtWidgets.QLabel(self.manual_panel)
        self.manualDistanceLabel.setObjectName("manualDistanceLabel")
        self.manualGridLayout.addWidget(self.manualDistanceLabel, 1, 4, 1, 1)
        self.manual_distance = QtWidgets.QDoubleSpinBox(self.manual_panel)
        self.manual_distance.setDecimals(3)
        self.manual_distance.setMinimum(0.01)
        self.manual_distance.setMaximum(100000.0)
        self.manual_distance.setProperty("value", 1000.0)
        self.manual_distance.setKeyboardTracking(False)
        self.manual_distance.setObjectName("manual_distance")
        self.manualGridLayout.addWidget(self.manual_distance, 1, 5, 1, 1)
        self.detectedRingLabel = QtWidgets.QLabel(self.manual_panel)
        self.detectedRingLabel.setObjectName("detectedRingLabel")
        self.manualGridLayout.addWidget(self.detectedRingLabel, 2, 0, 1, 1)
        self.experimental_ring_combo = QtWidgets.QComboBox(self.manual_panel)
        self.experimental_ring_combo.setObjectName("experimental_ring_combo")
        self.manualGridLayout.addWidget(self.experimental_ring_combo, 2, 1, 1, 2)
        self.theoryPeakLabel = QtWidgets.QLabel(self.manual_panel)
        self.theoryPeakLabel.setObjectName("theoryPeakLabel")
        self.manualGridLayout.addWidget(self.theoryPeakLabel, 2, 3, 1, 1)
        self.theory_ring_combo = QtWidgets.QComboBox(self.manual_panel)
        self.theory_ring_combo.setObjectName("theory_ring_combo")
        self.manualGridLayout.addWidget(self.theory_ring_combo, 2, 4, 1, 1)
        self.refine_ring_button = QtWidgets.QPushButton(self.manual_panel)
        self.refine_ring_button.setObjectName("refine_ring_button")
        self.manualGridLayout.addWidget(self.refine_ring_button, 2, 5, 1, 1)
        self.manualGroupLayout.addWidget(self.manual_panel)
        self.calibrationManualContentLayout.addWidget(self.manual_group)
        self.calibrationManualSectionLayout.addWidget(self.calibrationManualContent)
        self.rootLayout.addWidget(self.calibration_manual_section)
