"""Hand-maintained layout for the geometry calibration dialog."""


from PyQt5 import QtCore, QtGui, QtWidgets


class GeometryCalibrationDialogView:
    def setupUi(self, GeometryCalibrationDialog):
        GeometryCalibrationDialog.setObjectName("GeometryCalibrationDialog")
        GeometryCalibrationDialog.resize(1180, 760)
        GeometryCalibrationDialog.setMinimumSize(QtCore.QSize(900, 560))
        GeometryCalibrationDialog.setModal(False)
        self.rootLayout = QtWidgets.QVBoxLayout(GeometryCalibrationDialog)
        self.rootLayout.setContentsMargins(12, 12, 12, 12)
        self.rootLayout.setSpacing(8)
        self.rootLayout.setObjectName("rootLayout")
        self.main_splitter = QtWidgets.QSplitter(GeometryCalibrationDialog)
        self.main_splitter.setOrientation(QtCore.Qt.Horizontal)
        self.main_splitter.setObjectName("main_splitter")
        self.calibrationControlsScroll = QtWidgets.QScrollArea(self.main_splitter)
        self.calibrationControlsScroll.setMinimumSize(QtCore.QSize(280, 0))
        self.calibrationControlsScroll.setMaximumSize(QtCore.QSize(430, 16777215))
        self.calibrationControlsScroll.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.calibrationControlsScroll.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.calibrationControlsScroll.setWidgetResizable(True)
        self.calibrationControlsScroll.setObjectName("calibrationControlsScroll")
        self.controls = QtWidgets.QWidget()
        self.controls.setGeometry(QtCore.QRect(0, 0, 390, 720))
        self.controls.setMinimumSize(QtCore.QSize(280, 0))
        self.controls.setMaximumSize(QtCore.QSize(410, 16777215))
        self.controls.setObjectName("controls")
        self.controlsLayout = QtWidgets.QVBoxLayout(self.controls)
        self.controlsLayout.setContentsMargins(0, 0, 6, 0)
        self.controlsLayout.setSpacing(8)
        self.controlsLayout.setObjectName("controlsLayout")
        self.calibration_input_section = QtWidgets.QFrame(self.controls)
        self.calibration_input_section.setProperty("gimapSection", True)
        self.calibration_input_section.setObjectName("calibration_input_section")
        self.calibrationInputSectionLayout = QtWidgets.QVBoxLayout(self.calibration_input_section)
        self.calibrationInputSectionLayout.setContentsMargins(12, 10, 12, 12)
        self.calibrationInputSectionLayout.setSpacing(8)
        self.calibrationInputSectionLayout.setObjectName("calibrationInputSectionLayout")
        self.calibrationInputTitle = QtWidgets.QLabel(self.calibration_input_section)
        self.calibrationInputTitle.setProperty("gimapSectionTitle", True)
        self.calibrationInputTitle.setObjectName("calibrationInputTitle")
        self.calibrationInputSectionLayout.addWidget(self.calibrationInputTitle)
        self.calibrationInputDescription = QtWidgets.QLabel(self.calibration_input_section)
        self.calibrationInputDescription.setProperty("gimapSectionDescription", True)
        self.calibrationInputDescription.setWordWrap(True)
        self.calibrationInputDescription.setObjectName("calibrationInputDescription")
        self.calibrationInputSectionLayout.addWidget(self.calibrationInputDescription)
        self.calibrationInputContent = QtWidgets.QWidget(self.calibration_input_section)
        self.calibrationInputContent.setObjectName("calibrationInputContent")
        self.calibrationInputContentLayout = QtWidgets.QVBoxLayout(self.calibrationInputContent)
        self.calibrationInputContentLayout.setContentsMargins(0, 0, 0, 0)
        self.calibrationInputContentLayout.setSpacing(8)
        self.calibrationInputContentLayout.setObjectName("calibrationInputContentLayout")
        self.calibration_file_group = QtWidgets.QGroupBox(self.calibrationInputContent)
        self.calibration_file_group.setObjectName("calibration_file_group")
        self.calibrationFileLayout = QtWidgets.QHBoxLayout(self.calibration_file_group)
        self.calibrationFileLayout.setObjectName("calibrationFileLayout")
        self.path_edit = QtWidgets.QLineEdit(self.calibration_file_group)
        self.path_edit.setObjectName("path_edit")
        self.calibrationFileLayout.addWidget(self.path_edit)
        self.open_button = QtWidgets.QPushButton(self.calibration_file_group)
        self.open_button.setObjectName("open_button")
        self.calibrationFileLayout.addWidget(self.open_button)
        self.calibrationInputContentLayout.addWidget(self.calibration_file_group)
        self.calibration_input_group = QtWidgets.QGroupBox(self.calibrationInputContent)
        self.calibration_input_group.setObjectName("calibration_input_group")
        self.calibrationInputForm = QtWidgets.QFormLayout(self.calibration_input_group)
        self.calibrationInputForm.setObjectName("calibrationInputForm")
        self.energyLabel = QtWidgets.QLabel(self.calibration_input_group)
        self.energyLabel.setObjectName("energyLabel")
        self.calibrationInputForm.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.energyLabel)
        self.energy_spin = QtWidgets.QDoubleSpinBox(self.calibration_input_group)
        self.energy_spin.setDecimals(5)
        self.energy_spin.setMinimum(0.1)
        self.energy_spin.setMaximum(200.0)
        self.energy_spin.setProperty("value", 12.0)
        self.energy_spin.setKeyboardTracking(False)
        self.energy_spin.setObjectName("energy_spin")
        self.calibrationInputForm.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.energy_spin)
        self.standardLabel = QtWidgets.QLabel(self.calibration_input_group)
        self.standardLabel.setObjectName("standardLabel")
        self.calibrationInputForm.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.standardLabel)
        self.standard_combo = QtWidgets.QComboBox(self.calibration_input_group)
        self.standard_combo.setObjectName("standard_combo")
        self.calibrationInputForm.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.standard_combo)
        self.estimatedDistanceLabel = QtWidgets.QLabel(self.calibration_input_group)
        self.estimatedDistanceLabel.setObjectName("estimatedDistanceLabel")
        self.calibrationInputForm.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.estimatedDistanceLabel)
        self.estimated_distance_spin = QtWidgets.QDoubleSpinBox(self.calibration_input_group)
        self.estimated_distance_spin.setDecimals(2)
        self.estimated_distance_spin.setMaximum(100000.0)
        self.estimated_distance_spin.setKeyboardTracking(False)
        self.estimated_distance_spin.setObjectName("estimated_distance_spin")
        self.calibrationInputForm.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.estimated_distance_spin)
        self.rangeLabel = QtWidgets.QLabel(self.calibration_input_group)
        self.rangeLabel.setObjectName("rangeLabel")
        self.calibrationInputForm.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.rangeLabel)
        self.range_combo = QtWidgets.QComboBox(self.calibration_input_group)
        self.range_combo.setObjectName("range_combo")
        self.range_combo.addItem("")
        self.range_combo.addItem("")
        self.range_combo.addItem("")
        self.range_combo.addItem("")
        self.calibrationInputForm.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.range_combo)
        self.pixelSizeLabel = QtWidgets.QLabel(self.calibration_input_group)
        self.pixelSizeLabel.setObjectName("pixelSizeLabel")
        self.calibrationInputForm.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.pixelSizeLabel)
        self.pixel_label = QtWidgets.QLabel(self.calibration_input_group)
        self.pixel_label.setWordWrap(True)
        self.pixel_label.setObjectName("pixel_label")
        self.calibrationInputForm.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.pixel_label)
        self.detectorLabel = QtWidgets.QLabel(self.calibration_input_group)
        self.detectorLabel.setObjectName("detectorLabel")
        self.calibrationInputForm.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.detectorLabel)
        self.detector_label = QtWidgets.QLabel(self.calibration_input_group)
        self.detector_label.setObjectName("detector_label")
        self.calibrationInputForm.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.detector_label)
        self.detectorModelLabel = QtWidgets.QLabel(self.calibration_input_group)
        self.detectorModelLabel.setObjectName("detectorModelLabel")
        self.calibrationInputForm.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.detectorModelLabel)
        self.detector_combo = QtWidgets.QComboBox(self.calibration_input_group)
        self.detector_combo.setObjectName("detector_combo")
        self.calibrationInputForm.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.detector_combo)
        self.calibrationInputContentLayout.addWidget(self.calibration_input_group)
        self.calibrationInputSectionLayout.addWidget(self.calibrationInputContent)
        self.controlsLayout.addWidget(self.calibration_input_section)
        self.calibration_advanced_section = QtWidgets.QFrame(self.controls)
        self.calibration_advanced_section.setProperty("gimapSection", True)
        self.calibration_advanced_section.setObjectName("calibration_advanced_section")
        self.calibrationAdvancedSectionLayout = QtWidgets.QVBoxLayout(self.calibration_advanced_section)
        self.calibrationAdvancedSectionLayout.setContentsMargins(8, 8, 8, 8)
        self.calibrationAdvancedSectionLayout.setSpacing(7)
        self.calibrationAdvancedSectionLayout.setObjectName("calibrationAdvancedSectionLayout")
        self.calibrationAdvancedToggle = QtWidgets.QToolButton(self.calibration_advanced_section)
        self.calibrationAdvancedToggle.setProperty("gimapAdvancedToggle", True)
        self.calibrationAdvancedToggle.setCheckable(True)
        self.calibrationAdvancedToggle.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.calibrationAdvancedToggle.setArrowType(QtCore.Qt.RightArrow)
        self.calibrationAdvancedToggle.setObjectName("calibrationAdvancedToggle")
        self.calibrationAdvancedSectionLayout.addWidget(self.calibrationAdvancedToggle)
        self.calibrationAdvancedDescription = QtWidgets.QLabel(self.calibration_advanced_section)
        self.calibrationAdvancedDescription.setVisible(False)
        self.calibrationAdvancedDescription.setProperty("gimapSectionDescription", True)
        self.calibrationAdvancedDescription.setWordWrap(True)
        self.calibrationAdvancedDescription.setObjectName("calibrationAdvancedDescription")
        self.calibrationAdvancedSectionLayout.addWidget(self.calibrationAdvancedDescription)
        self.calibrationAdvancedContent = QtWidgets.QWidget(self.calibration_advanced_section)
        self.calibrationAdvancedContent.setVisible(False)
        self.calibrationAdvancedContent.setObjectName("calibrationAdvancedContent")
        self.calibrationAdvancedContentLayout = QtWidgets.QVBoxLayout(self.calibrationAdvancedContent)
        self.calibrationAdvancedContentLayout.setContentsMargins(4, 2, 4, 4)
        self.calibrationAdvancedContentLayout.setSpacing(8)
        self.calibrationAdvancedContentLayout.setObjectName("calibrationAdvancedContentLayout")
        self.advanced_group = QtWidgets.QGroupBox(self.calibrationAdvancedContent)
        self.advanced_group.setObjectName("advanced_group")
        self.advancedForm = QtWidgets.QFormLayout(self.advanced_group)
        self.advancedForm.setObjectName("advancedForm")
        self.pixelXLabel = QtWidgets.QLabel(self.advanced_group)
        self.pixelXLabel.setObjectName("pixelXLabel")
        self.advancedForm.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pixelXLabel)
        self.pixel_x_spin = QtWidgets.QDoubleSpinBox(self.advanced_group)
        self.pixel_x_spin.setDecimals(4)
        self.pixel_x_spin.setMinimum(1.0)
        self.pixel_x_spin.setMaximum(1000.0)
        self.pixel_x_spin.setProperty("value", 172.0)
        self.pixel_x_spin.setKeyboardTracking(False)
        self.pixel_x_spin.setObjectName("pixel_x_spin")
        self.advancedForm.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.pixel_x_spin)
        self.pixelYLabel = QtWidgets.QLabel(self.advanced_group)
        self.pixelYLabel.setObjectName("pixelYLabel")
        self.advancedForm.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pixelYLabel)
        self.pixel_y_spin = QtWidgets.QDoubleSpinBox(self.advanced_group)
        self.pixel_y_spin.setDecimals(4)
        self.pixel_y_spin.setMinimum(1.0)
        self.pixel_y_spin.setMaximum(1000.0)
        self.pixel_y_spin.setProperty("value", 172.0)
        self.pixel_y_spin.setKeyboardTracking(False)
        self.pixel_y_spin.setObjectName("pixel_y_spin")
        self.advancedForm.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.pixel_y_spin)
        self.customMinLabel = QtWidgets.QLabel(self.advanced_group)
        self.customMinLabel.setObjectName("customMinLabel")
        self.advancedForm.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.customMinLabel)
        self.custom_min_spin = QtWidgets.QDoubleSpinBox(self.advanced_group)
        self.custom_min_spin.setDecimals(1)
        self.custom_min_spin.setMinimum(1.0)
        self.custom_min_spin.setMaximum(100000.0)
        self.custom_min_spin.setProperty("value", 30.0)
        self.custom_min_spin.setKeyboardTracking(False)
        self.custom_min_spin.setObjectName("custom_min_spin")
        self.advancedForm.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.custom_min_spin)
        self.customMaxLabel = QtWidgets.QLabel(self.advanced_group)
        self.customMaxLabel.setObjectName("customMaxLabel")
        self.advancedForm.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.customMaxLabel)
        self.custom_max_spin = QtWidgets.QDoubleSpinBox(self.advanced_group)
        self.custom_max_spin.setDecimals(1)
        self.custom_max_spin.setMinimum(1.0)
        self.custom_max_spin.setMaximum(100000.0)
        self.custom_max_spin.setProperty("value", 10000.0)
        self.custom_max_spin.setKeyboardTracking(False)
        self.custom_max_spin.setObjectName("custom_max_spin")
        self.advancedForm.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.custom_max_spin)
        self.background_check = QtWidgets.QCheckBox(self.advanced_group)
        self.background_check.setChecked(True)
        self.background_check.setObjectName("background_check")
        self.advancedForm.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.background_check)
        self.log_check = QtWidgets.QCheckBox(self.advanced_group)
        self.log_check.setChecked(True)
        self.log_check.setObjectName("log_check")
        self.advancedForm.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.log_check)
        self.mask_check = QtWidgets.QCheckBox(self.advanced_group)
        self.mask_check.setObjectName("mask_check")
        self.advancedForm.setWidget(6, QtWidgets.QFormLayout.SpanningRole, self.mask_check)
        self.rings_check = QtWidgets.QCheckBox(self.advanced_group)
        self.rings_check.setChecked(True)
        self.rings_check.setObjectName("rings_check")
        self.advancedForm.setWidget(7, QtWidgets.QFormLayout.SpanningRole, self.rings_check)
        self.calibrationAdvancedContentLayout.addWidget(self.advanced_group)
        self.calibrationAdvancedSectionLayout.addWidget(self.calibrationAdvancedContent)
        self.controlsLayout.addWidget(self.calibration_advanced_section)
        self.calibration_run_section = QtWidgets.QFrame(self.controls)
        self.calibration_run_section.setProperty("gimapSection", True)
        self.calibration_run_section.setObjectName("calibration_run_section")
        self.calibrationRunSectionLayout = QtWidgets.QVBoxLayout(self.calibration_run_section)
        self.calibrationRunSectionLayout.setContentsMargins(12, 10, 12, 12)
        self.calibrationRunSectionLayout.setSpacing(8)
        self.calibrationRunSectionLayout.setObjectName("calibrationRunSectionLayout")
        self.calibrationRunTitle = QtWidgets.QLabel(self.calibration_run_section)
        self.calibrationRunTitle.setProperty("gimapSectionTitle", True)
        self.calibrationRunTitle.setObjectName("calibrationRunTitle")
        self.calibrationRunSectionLayout.addWidget(self.calibrationRunTitle)
        self.calibrationRunDescription = QtWidgets.QLabel(self.calibration_run_section)
        self.calibrationRunDescription.setProperty("gimapSectionDescription", True)
        self.calibrationRunDescription.setWordWrap(True)
        self.calibrationRunDescription.setObjectName("calibrationRunDescription")
        self.calibrationRunSectionLayout.addWidget(self.calibrationRunDescription)
        self.calibrationRunContent = QtWidgets.QWidget(self.calibration_run_section)
        self.calibrationRunContent.setObjectName("calibrationRunContent")
        self.calibrationRunContentLayout = QtWidgets.QVBoxLayout(self.calibrationRunContent)
        self.calibrationRunContentLayout.setContentsMargins(0, 0, 0, 0)
        self.calibrationRunContentLayout.setSpacing(8)
        self.calibrationRunContentLayout.setObjectName("calibrationRunContentLayout")
        self.calibrationRunActions = QtWidgets.QHBoxLayout()
        self.calibrationRunActions.setObjectName("calibrationRunActions")
        self.calibrate_button = QtWidgets.QPushButton(self.calibrationRunContent)
        self.calibrate_button.setDefault(True)
        self.calibrate_button.setObjectName("calibrate_button")
        self.calibrationRunActions.addWidget(self.calibrate_button)
        self.cancel_button = QtWidgets.QPushButton(self.calibrationRunContent)
        self.cancel_button.setObjectName("cancel_button")
        self.calibrationRunActions.addWidget(self.cancel_button)
        self.calibrationRunContentLayout.addLayout(self.calibrationRunActions)
        self.job_status = JobStatus(self.calibrationRunContent)
        self.job_status.setObjectName("job_status")
        self.calibrationRunContentLayout.addWidget(self.job_status)
        self.calibrationRunSectionLayout.addWidget(self.calibrationRunContent)
        self.controlsLayout.addWidget(self.calibration_run_section)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.controlsLayout.addItem(spacerItem)
        self.calibrationControlsScroll.setWidget(self.controls)
        self.right = QtWidgets.QWidget(self.main_splitter)
        self.right.setObjectName("right")
        self.rightLayout = QtWidgets.QVBoxLayout(self.right)
        self.rightLayout.setContentsMargins(6, 0, 0, 0)
        self.rightLayout.setObjectName("rightLayout")
        self.right_splitter = QtWidgets.QSplitter(self.right)
        self.right_splitter.setOrientation(QtCore.Qt.Vertical)
        self.right_splitter.setObjectName("right_splitter")
        self.calibration_preview_panel = QtWidgets.QFrame(self.right_splitter)
        self.calibration_preview_panel.setProperty("gimapSection", True)
        self.calibration_preview_panel.setObjectName("calibration_preview_panel")
        self.calibrationPreviewSectionLayout = QtWidgets.QVBoxLayout(self.calibration_preview_panel)
        self.calibrationPreviewSectionLayout.setContentsMargins(12, 10, 12, 12)
        self.calibrationPreviewSectionLayout.setSpacing(8)
        self.calibrationPreviewSectionLayout.setObjectName("calibrationPreviewSectionLayout")
        self.calibrationPreviewTitle = QtWidgets.QLabel(self.calibration_preview_panel)
        self.calibrationPreviewTitle.setProperty("gimapSectionTitle", True)
        self.calibrationPreviewTitle.setObjectName("calibrationPreviewTitle")
        self.calibrationPreviewSectionLayout.addWidget(self.calibrationPreviewTitle)
        self.calibrationPreviewDescription = QtWidgets.QLabel(self.calibration_preview_panel)
        self.calibrationPreviewDescription.setProperty("gimapSectionDescription", True)
        self.calibrationPreviewDescription.setWordWrap(True)
        self.calibrationPreviewDescription.setObjectName("calibrationPreviewDescription")
        self.calibrationPreviewSectionLayout.addWidget(self.calibrationPreviewDescription)
        self.calibrationPreviewContent = QtWidgets.QWidget(self.calibration_preview_panel)
        self.calibrationPreviewContent.setObjectName("calibrationPreviewContent")
        self.calibrationPreviewContentLayout = QtWidgets.QVBoxLayout(self.calibrationPreviewContent)
        self.calibrationPreviewContentLayout.setContentsMargins(0, 0, 0, 0)
        self.calibrationPreviewContentLayout.setSpacing(8)
        self.calibrationPreviewContentLayout.setObjectName("calibrationPreviewContentLayout")
        self.calibrationToolbarHost = QtWidgets.QWidget(self.calibrationPreviewContent)
        self.calibrationToolbarHost.setObjectName("calibrationToolbarHost")
        self.calibrationToolbarHostLayout = QtWidgets.QVBoxLayout(self.calibrationToolbarHost)
        self.calibrationToolbarHostLayout.setContentsMargins(0, 0, 0, 0)
        self.calibrationToolbarHostLayout.setObjectName("calibrationToolbarHostLayout")
        self.calibrationPreviewContentLayout.addWidget(self.calibrationToolbarHost)
        self.previewActionsLayout = QtWidgets.QHBoxLayout()
        self.previewActionsLayout.setObjectName("previewActionsLayout")
        self.fit_image_button = QtWidgets.QPushButton(self.calibrationPreviewContent)
        self.fit_image_button.setObjectName("fit_image_button")
        self.previewActionsLayout.addWidget(self.fit_image_button)
        self.clean_preview_button = QtWidgets.QPushButton(self.calibrationPreviewContent)
        self.clean_preview_button.setCheckable(True)
        self.clean_preview_button.setEnabled(False)
        self.clean_preview_button.setObjectName("clean_preview_button")
        self.previewActionsLayout.addWidget(self.clean_preview_button)
        self.expand_preview_button = QtWidgets.QPushButton(self.calibrationPreviewContent)
        self.expand_preview_button.setObjectName("expand_preview_button")
        self.previewActionsLayout.addWidget(self.expand_preview_button)
        self.manual_refine_button = QtWidgets.QPushButton(self.calibrationPreviewContent)
        self.manual_refine_button.setCheckable(True)
        self.manual_refine_button.setEnabled(False)
        self.manual_refine_button.setObjectName("manual_refine_button")
        self.previewActionsLayout.addWidget(self.manual_refine_button)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.previewActionsLayout.addItem(spacerItem1)
        self.calibrationPreviewContentLayout.addLayout(self.previewActionsLayout)
        self.preview_info_label = QtWidgets.QLabel(self.calibrationPreviewContent)
        self.preview_info_label.setWordWrap(True)
        self.preview_info_label.setObjectName("preview_info_label")
        self.calibrationPreviewContentLayout.addWidget(self.preview_info_label)
        self.overlay_legend = QtWidgets.QLabel(self.calibrationPreviewContent)
        self.overlay_legend.setVisible(False)
        self.overlay_legend.setText("")
        self.overlay_legend.setTextFormat(QtCore.Qt.RichText)
        self.overlay_legend.setObjectName("overlay_legend")
        self.calibrationPreviewContentLayout.addWidget(self.overlay_legend)
        self.calibrationFigureHost = QtWidgets.QWidget(self.calibrationPreviewContent)
        self.calibrationFigureHost.setObjectName("calibrationFigureHost")
        self.calibrationFigureHostLayout = QtWidgets.QVBoxLayout(self.calibrationFigureHost)
        self.calibrationFigureHostLayout.setContentsMargins(0, 0, 0, 0)
        self.calibrationFigureHostLayout.setObjectName("calibrationFigureHostLayout")
        self.calibrationPreviewContentLayout.addWidget(self.calibrationFigureHost)
        self.calibrationPreviewContentLayout.setStretch(4, 1)
        self.calibrationPreviewSectionLayout.addWidget(self.calibrationPreviewContent)
        self.calibration_results_section = QtWidgets.QFrame(self.right_splitter)
        self.calibration_results_section.setProperty("gimapSection", True)
        self.calibration_results_section.setObjectName("calibration_results_section")
        self.calibrationResultsSectionLayout = QtWidgets.QVBoxLayout(self.calibration_results_section)
        self.calibrationResultsSectionLayout.setContentsMargins(12, 10, 12, 12)
        self.calibrationResultsSectionLayout.setSpacing(8)
        self.calibrationResultsSectionLayout.setObjectName("calibrationResultsSectionLayout")
        self.calibrationResultsTitle = QtWidgets.QLabel(self.calibration_results_section)
        self.calibrationResultsTitle.setProperty("gimapSectionTitle", True)
        self.calibrationResultsTitle.setObjectName("calibrationResultsTitle")
        self.calibrationResultsSectionLayout.addWidget(self.calibrationResultsTitle)
        self.calibrationResultsDescription = QtWidgets.QLabel(self.calibration_results_section)
        self.calibrationResultsDescription.setProperty("gimapSectionDescription", True)
        self.calibrationResultsDescription.setWordWrap(True)
        self.calibrationResultsDescription.setObjectName("calibrationResultsDescription")
        self.calibrationResultsSectionLayout.addWidget(self.calibrationResultsDescription)
        self.calibrationResultsContent = QtWidgets.QWidget(self.calibration_results_section)
        self.calibrationResultsContent.setObjectName("calibrationResultsContent")
        self.calibrationResultsContentLayout = QtWidgets.QVBoxLayout(self.calibrationResultsContent)
        self.calibrationResultsContentLayout.setContentsMargins(0, 0, 0, 0)
        self.calibrationResultsContentLayout.setSpacing(8)
        self.calibrationResultsContentLayout.setObjectName("calibrationResultsContentLayout")
        self.results_splitter = QtWidgets.QSplitter(self.calibrationResultsContent)
        self.results_splitter.setOrientation(QtCore.Qt.Horizontal)
        self.results_splitter.setObjectName("results_splitter")
        self.result_group = QtWidgets.QGroupBox(self.results_splitter)
        self.result_group.setObjectName("result_group")
        self.resultForm = QtWidgets.QFormLayout(self.result_group)
        self.resultForm.setObjectName("resultForm")
        self.resultCenterXTitle = QtWidgets.QLabel(self.result_group)
        self.resultCenterXTitle.setObjectName("resultCenterXTitle")
        self.resultForm.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.resultCenterXTitle)
        self.result_center_x = QtWidgets.QLabel(self.result_group)
        self.result_center_x.setObjectName("result_center_x")
        self.resultForm.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.result_center_x)
        self.resultCenterYTitle = QtWidgets.QLabel(self.result_group)
        self.resultCenterYTitle.setObjectName("resultCenterYTitle")
        self.resultForm.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.resultCenterYTitle)
        self.result_center_y = QtWidgets.QLabel(self.result_group)
        self.result_center_y.setObjectName("result_center_y")
        self.resultForm.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.result_center_y)
        self.resultDistanceTitle = QtWidgets.QLabel(self.result_group)
        self.resultDistanceTitle.setObjectName("resultDistanceTitle")
        self.resultForm.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.resultDistanceTitle)
        self.result_distance = QtWidgets.QLabel(self.result_group)
        self.result_distance.setObjectName("result_distance")
        self.resultForm.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.result_distance)
        self.resultRotationTitle = QtWidgets.QLabel(self.result_group)
        self.resultRotationTitle.setObjectName("resultRotationTitle")
        self.resultForm.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.resultRotationTitle)
        self.result_rotation = QtWidgets.QLabel(self.result_group)
        self.result_rotation.setObjectName("result_rotation")
        self.resultForm.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.result_rotation)
        self.resultRingsTitle = QtWidgets.QLabel(self.result_group)
        self.resultRingsTitle.setObjectName("resultRingsTitle")
        self.resultForm.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.resultRingsTitle)
        self.result_rings = QtWidgets.QLabel(self.result_group)
        self.result_rings.setObjectName("result_rings")
        self.resultForm.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.result_rings)
        self.resultRmsTitle = QtWidgets.QLabel(self.result_group)
        self.resultRmsTitle.setObjectName("resultRmsTitle")
        self.resultForm.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.resultRmsTitle)
        self.result_rms = QtWidgets.QLabel(self.result_group)
        self.result_rms.setObjectName("result_rms")
        self.resultForm.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.result_rms)
        self.resultConfidenceTitle = QtWidgets.QLabel(self.result_group)
        self.resultConfidenceTitle.setObjectName("resultConfidenceTitle")
        self.resultForm.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.resultConfidenceTitle)
        self.result_confidence = QtWidgets.QLabel(self.result_group)
        self.result_confidence.setObjectName("result_confidence")
        self.resultForm.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.result_confidence)
        self.resultWarningTitle = QtWidgets.QLabel(self.result_group)
        self.resultWarningTitle.setObjectName("resultWarningTitle")
        self.resultForm.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.resultWarningTitle)
        self.result_warning = QtWidgets.QLabel(self.result_group)
        self.result_warning.setWordWrap(True)
        self.result_warning.setObjectName("result_warning")
        self.resultForm.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.result_warning)
        self.candidates_group = QtWidgets.QGroupBox(self.results_splitter)
        self.candidates_group.setObjectName("candidates_group")
        self.candidatesLayout = QtWidgets.QVBoxLayout(self.candidates_group)
        self.candidatesLayout.setObjectName("candidatesLayout")
        self.candidate_table = QtWidgets.QTableWidget(self.candidates_group)
        self.candidate_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.candidate_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.candidate_table.setObjectName("candidate_table")
        self.candidate_table.setColumnCount(6)
        self.candidate_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.candidate_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.candidate_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.candidate_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.candidate_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.candidate_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.candidate_table.setHorizontalHeaderItem(5, item)
        self.candidatesLayout.addWidget(self.candidate_table)
        self.calibrationResultsContentLayout.addWidget(self.results_splitter)
        self.calibrationResultsSectionLayout.addWidget(self.calibrationResultsContent)
        self.rightLayout.addWidget(self.right_splitter)
        self.rootLayout.addWidget(self.main_splitter)
        self.calibration_manual_section = QtWidgets.QFrame(GeometryCalibrationDialog)
        self.calibration_manual_section.setProperty("gimapSection", True)
        self.calibration_manual_section.setObjectName("calibration_manual_section")
        self.calibrationManualSectionLayout = QtWidgets.QVBoxLayout(self.calibration_manual_section)
        self.calibrationManualSectionLayout.setContentsMargins(8, 8, 8, 8)
        self.calibrationManualSectionLayout.setSpacing(7)
        self.calibrationManualSectionLayout.setObjectName("calibrationManualSectionLayout")
        self.calibrationManualToggle = QtWidgets.QToolButton(self.calibration_manual_section)
        self.calibrationManualToggle.setProperty("gimapAdvancedToggle", True)
        self.calibrationManualToggle.setCheckable(True)
        self.calibrationManualToggle.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.calibrationManualToggle.setArrowType(QtCore.Qt.RightArrow)
        self.calibrationManualToggle.setObjectName("calibrationManualToggle")
        self.calibrationManualSectionLayout.addWidget(self.calibrationManualToggle)
        self.calibrationManualDescription = QtWidgets.QLabel(self.calibration_manual_section)
        self.calibrationManualDescription.setVisible(False)
        self.calibrationManualDescription.setProperty("gimapSectionDescription", True)
        self.calibrationManualDescription.setWordWrap(True)
        self.calibrationManualDescription.setObjectName("calibrationManualDescription")
        self.calibrationManualSectionLayout.addWidget(self.calibrationManualDescription)
        self.calibrationManualContent = QtWidgets.QWidget(self.calibration_manual_section)
        self.calibrationManualContent.setVisible(False)
        self.calibrationManualContent.setObjectName("calibrationManualContent")
        self.calibrationManualContentLayout = QtWidgets.QVBoxLayout(self.calibrationManualContent)
        self.calibrationManualContentLayout.setContentsMargins(4, 2, 4, 4)
        self.calibrationManualContentLayout.setSpacing(8)
        self.calibrationManualContentLayout.setObjectName("calibrationManualContentLayout")
        self.manual_group = QtWidgets.QGroupBox(self.calibrationManualContent)
        self.manual_group.setEnabled(False)
        self.manual_group.setMaximumSize(QtCore.QSize(16777215, 40))
        self.manual_group.setCheckable(True)
        self.manual_group.setChecked(False)
        self.manual_group.setObjectName("manual_group")
        self.manualGroupLayout = QtWidgets.QVBoxLayout(self.manual_group)
        self.manualGroupLayout.setObjectName("manualGroupLayout")
        self.manual_panel = QtWidgets.QWidget(self.manual_group)
        self.manual_panel.setVisible(False)
        self.manual_panel.setObjectName("manual_panel")
        self.manualGridLayout = QtWidgets.QGridLayout(self.manual_panel)
        self.manualGridLayout.setContentsMargins(4, 2, 4, 4)
        self.manualGridLayout.setObjectName("manualGridLayout")
        self.manual_hint = QtWidgets.QLabel(self.manual_panel)
        self.manual_hint.setObjectName("manual_hint")
        self.manualGridLayout.addWidget(self.manual_hint, 0, 0, 1, 6)
        self.manualXLabel = QtWidgets.QLabel(self.manual_panel)
        self.manualXLabel.setObjectName("manualXLabel")
        self.manualGridLayout.addWidget(self.manualXLabel, 1, 0, 1, 1)
        self.manual_x = QtWidgets.QDoubleSpinBox(self.manual_panel)
        self.manual_x.setDecimals(3)
        self.manual_x.setMinimum(-100000.0)
        self.manual_x.setMaximum(100000.0)
        self.manual_x.setKeyboardTracking(False)
        self.manual_x.setObjectName("manual_x")
        self.manualGridLayout.addWidget(self.manual_x, 1, 1, 1, 1)
        self.manualYLabel = QtWidgets.QLabel(self.manual_panel)
        self.manualYLabel.setObjectName("manualYLabel")
        self.manualGridLayout.addWidget(self.manualYLabel, 1, 2, 1, 1)
        self.manual_y = QtWidgets.QDoubleSpinBox(self.manual_panel)
        self.manual_y.setDecimals(3)
        self.manual_y.setMinimum(-100000.0)
        self.manual_y.setMaximum(100000.0)
        self.manual_y.setKeyboardTracking(False)
        self.manual_y.setObjectName("manual_y")
        self.manualGridLayout.addWidget(self.manual_y, 1, 3, 1, 1)
        self.manualDistanceLabel = QtWidgets.QLabel(self.manual_panel)
        self.manualDistanceLabel.setObjectName("manualDistanceLabel")
        self.manualGridLayout.addWidget(self.manualDistanceLabel, 1, 4, 1, 1)
        self.manual_distance = QtWidgets.QDoubleSpinBox(self.manual_panel)
        self.manual_distance.setDecimals(3)
        self.manual_distance.setMinimum(0.01)
        self.manual_distance.setMaximum(100000.0)
        self.manual_distance.setProperty("value", 1000.0)
        self.manual_distance.setKeyboardTracking(False)
        self.manual_distance.setObjectName("manual_distance")
        self.manualGridLayout.addWidget(self.manual_distance, 1, 5, 1, 1)
        self.detectedRingLabel = QtWidgets.QLabel(self.manual_panel)
        self.detectedRingLabel.setObjectName("detectedRingLabel")
        self.manualGridLayout.addWidget(self.detectedRingLabel, 2, 0, 1, 1)
        self.experimental_ring_combo = QtWidgets.QComboBox(self.manual_panel)
        self.experimental_ring_combo.setObjectName("experimental_ring_combo")
        self.manualGridLayout.addWidget(self.experimental_ring_combo, 2, 1, 1, 2)
        self.theoryPeakLabel = QtWidgets.QLabel(self.manual_panel)
        self.theoryPeakLabel.setObjectName("theoryPeakLabel")
        self.manualGridLayout.addWidget(self.theoryPeakLabel, 2, 3, 1, 1)
        self.theory_ring_combo = QtWidgets.QComboBox(self.manual_panel)
        self.theory_ring_combo.setObjectName("theory_ring_combo")
        self.manualGridLayout.addWidget(self.theory_ring_combo, 2, 4, 1, 1)
        self.refine_ring_button = QtWidgets.QPushButton(self.manual_panel)
        self.refine_ring_button.setObjectName("refine_ring_button")
        self.manualGridLayout.addWidget(self.refine_ring_button, 2, 5, 1, 1)
        self.manualGroupLayout.addWidget(self.manual_panel)
        self.calibrationManualContentLayout.addWidget(self.manual_group)
        self.calibrationManualSectionLayout.addWidget(self.calibrationManualContent)
        self.rootLayout.addWidget(self.calibration_manual_section)
        self.calibration_export_section = QtWidgets.QFrame(GeometryCalibrationDialog)
        self.calibration_export_section.setProperty("gimapSection", True)
        self.calibration_export_section.setObjectName("calibration_export_section")
        self.calibrationExportSectionLayout = QtWidgets.QVBoxLayout(self.calibration_export_section)
        self.calibrationExportSectionLayout.setContentsMargins(12, 10, 12, 12)
        self.calibrationExportSectionLayout.setSpacing(8)
        self.calibrationExportSectionLayout.setObjectName("calibrationExportSectionLayout")
        self.calibrationExportTitle = QtWidgets.QLabel(self.calibration_export_section)
        self.calibrationExportTitle.setProperty("gimapSectionTitle", True)
        self.calibrationExportTitle.setObjectName("calibrationExportTitle")
        self.calibrationExportSectionLayout.addWidget(self.calibrationExportTitle)
        self.calibrationExportDescription = QtWidgets.QLabel(self.calibration_export_section)
        self.calibrationExportDescription.setProperty("gimapSectionDescription", True)
        self.calibrationExportDescription.setWordWrap(True)
        self.calibrationExportDescription.setObjectName("calibrationExportDescription")
        self.calibrationExportSectionLayout.addWidget(self.calibrationExportDescription)
        self.calibrationExportContent = QtWidgets.QWidget(self.calibration_export_section)
        self.calibrationExportContent.setObjectName("calibrationExportContent")
        self.calibrationExportContentLayout = QtWidgets.QHBoxLayout(self.calibrationExportContent)
        self.calibrationExportContentLayout.setContentsMargins(0, 0, 0, 0)
        self.calibrationExportContentLayout.setObjectName("calibrationExportContentLayout")
        self.import_button = QtWidgets.QPushButton(self.calibrationExportContent)
        self.import_button.setObjectName("import_button")
        self.calibrationExportContentLayout.addWidget(self.import_button)
        self.export_button = QtWidgets.QPushButton(self.calibrationExportContent)
        self.export_button.setObjectName("export_button")
        self.calibrationExportContentLayout.addWidget(self.export_button)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.calibrationExportContentLayout.addItem(spacerItem2)
        self.apply_button = QtWidgets.QPushButton(self.calibrationExportContent)
        self.apply_button.setObjectName("apply_button")
        self.calibrationExportContentLayout.addWidget(self.apply_button)
        self.close_button = QtWidgets.QPushButton(self.calibrationExportContent)
        self.close_button.setObjectName("close_button")
        self.calibrationExportContentLayout.addWidget(self.close_button)
        self.calibrationExportSectionLayout.addWidget(self.calibrationExportContent)
        self.rootLayout.addWidget(self.calibration_export_section)
        self.rootLayout.setStretch(0, 1)

        self.retranslateUi(GeometryCalibrationDialog)
        QtCore.QMetaObject.connectSlotsByName(GeometryCalibrationDialog)
        GeometryCalibrationDialog.setTabOrder(self.path_edit, self.open_button)
        GeometryCalibrationDialog.setTabOrder(self.open_button, self.energy_spin)
        GeometryCalibrationDialog.setTabOrder(self.energy_spin, self.standard_combo)
        GeometryCalibrationDialog.setTabOrder(self.standard_combo, self.estimated_distance_spin)
        GeometryCalibrationDialog.setTabOrder(self.estimated_distance_spin, self.range_combo)
        GeometryCalibrationDialog.setTabOrder(self.range_combo, self.detector_combo)
        GeometryCalibrationDialog.setTabOrder(self.detector_combo, self.calibrate_button)
        GeometryCalibrationDialog.setTabOrder(self.calibrate_button, self.cancel_button)
        GeometryCalibrationDialog.setTabOrder(self.cancel_button, self.fit_image_button)
        GeometryCalibrationDialog.setTabOrder(self.fit_image_button, self.clean_preview_button)
        GeometryCalibrationDialog.setTabOrder(self.clean_preview_button, self.expand_preview_button)
        GeometryCalibrationDialog.setTabOrder(self.expand_preview_button, self.manual_refine_button)
        GeometryCalibrationDialog.setTabOrder(self.manual_refine_button, self.candidate_table)
        GeometryCalibrationDialog.setTabOrder(self.candidate_table, self.import_button)
        GeometryCalibrationDialog.setTabOrder(self.import_button, self.export_button)
        GeometryCalibrationDialog.setTabOrder(self.export_button, self.apply_button)
        GeometryCalibrationDialog.setTabOrder(self.apply_button, self.close_button)

    def retranslateUi(self, GeometryCalibrationDialog):
        _translate = QtCore.QCoreApplication.translate
        GeometryCalibrationDialog.setWindowTitle(_translate("GeometryCalibrationDialog", "Geometry Calibration"))
        self.calibrationInputTitle.setText(_translate("GeometryCalibrationDialog", "Input"))
        self.calibrationInputDescription.setText(_translate("GeometryCalibrationDialog", "Choose a calibration image and the essential experiment metadata."))
        self.calibration_file_group.setTitle(_translate("GeometryCalibrationDialog", "Calibration image"))
        self.path_edit.setPlaceholderText(_translate("GeometryCalibrationDialog", "Paste a .cbf/.nxs path or use Open..."))
        self.open_button.setText(_translate("GeometryCalibrationDialog", "Open..."))
        self.calibration_input_group.setTitle(_translate("GeometryCalibrationDialog", "Input"))
        self.energyLabel.setText(_translate("GeometryCalibrationDialog", "Energy:"))
        self.energy_spin.setSuffix(_translate("GeometryCalibrationDialog", " keV"))
        self.standardLabel.setText(_translate("GeometryCalibrationDialog", "Standard:"))
        self.estimatedDistanceLabel.setText(_translate("GeometryCalibrationDialog", "Estimated distance:"))
        self.estimated_distance_spin.setSuffix(_translate("GeometryCalibrationDialog", " mm"))
        self.estimated_distance_spin.setSpecialValueText(_translate("GeometryCalibrationDialog", "Optional"))
        self.rangeLabel.setText(_translate("GeometryCalibrationDialog", "Distance range:"))
        self.range_combo.setItemText(0, _translate("GeometryCalibrationDialog", "Auto (30-10000 mm)"))
        self.range_combo.setItemText(1, _translate("GeometryCalibrationDialog", "SAXS (500-10000 mm)"))
        self.range_combo.setItemText(2, _translate("GeometryCalibrationDialog", "WAXS (30-1500 mm)"))
        self.range_combo.setItemText(3, _translate("GeometryCalibrationDialog", "Custom"))
        self.pixelSizeLabel.setText(_translate("GeometryCalibrationDialog", "Pixel size:"))
        self.pixel_label.setText(_translate("GeometryCalibrationDialog", "Open an image"))
        self.detectorLabel.setText(_translate("GeometryCalibrationDialog", "Detector:"))
        self.detector_label.setText(_translate("GeometryCalibrationDialog", "Open an image"))
        self.detectorModelLabel.setText(_translate("GeometryCalibrationDialog", "Detector model:"))
        self.calibrationAdvancedToggle.setText(_translate("GeometryCalibrationDialog", "Advanced configuration"))
        self.calibrationAdvancedDescription.setText(_translate("GeometryCalibrationDialog", "Detector overrides, custom search bounds and preview overlays."))
        self.advanced_group.setTitle(_translate("GeometryCalibrationDialog", "Detector and display overrides"))
        self.pixelXLabel.setText(_translate("GeometryCalibrationDialog", "Pixel X:"))
        self.pixel_x_spin.setSuffix(_translate("GeometryCalibrationDialog", " µm"))
        self.pixelYLabel.setText(_translate("GeometryCalibrationDialog", "Pixel Y:"))
        self.pixel_y_spin.setSuffix(_translate("GeometryCalibrationDialog", " µm"))
        self.customMinLabel.setText(_translate("GeometryCalibrationDialog", "Custom minimum:"))
        self.custom_min_spin.setSuffix(_translate("GeometryCalibrationDialog", " mm"))
        self.customMaxLabel.setText(_translate("GeometryCalibrationDialog", "Custom maximum:"))
        self.custom_max_spin.setSuffix(_translate("GeometryCalibrationDialog", " mm"))
        self.background_check.setText(_translate("GeometryCalibrationDialog", "Subtract slowly varying background"))
        self.log_check.setText(_translate("GeometryCalibrationDialog", "Log intensity"))
        self.mask_check.setText(_translate("GeometryCalibrationDialog", "Show invalid-pixel mask"))
        self.rings_check.setText(_translate("GeometryCalibrationDialog", "Show ring overlays"))
        self.calibrationRunTitle.setText(_translate("GeometryCalibrationDialog", "Run"))
        self.calibrationRunDescription.setText(_translate("GeometryCalibrationDialog", "Run automatic calibration, monitor the current stage, or cancel safely."))
        self.calibrate_button.setText(_translate("GeometryCalibrationDialog", "Auto Calibration"))
        self.cancel_button.setText(_translate("GeometryCalibrationDialog", "Cancel"))
        self.calibrationPreviewTitle.setText(_translate("GeometryCalibrationDialog", "Preview"))
        self.calibrationPreviewDescription.setText(_translate("GeometryCalibrationDialog", "Inspect the detector image, detected rings and candidate overlays."))
        self.fit_image_button.setText(_translate("GeometryCalibrationDialog", "Reset view"))
        self.clean_preview_button.setText(_translate("GeometryCalibrationDialog", "Clean image"))
        self.expand_preview_button.setText(_translate("GeometryCalibrationDialog", "Focus image"))
        self.manual_refine_button.setText(_translate("GeometryCalibrationDialog", "Manual refine"))
        self.preview_info_label.setText(_translate("GeometryCalibrationDialog", "Open a calibration image to begin"))
        self.calibrationResultsTitle.setText(_translate("GeometryCalibrationDialog", "Results"))
        self.calibrationResultsDescription.setText(_translate("GeometryCalibrationDialog", "Review the selected solution and alternative candidates before applying it."))
        self.result_group.setTitle(_translate("GeometryCalibrationDialog", "Results"))
        self.resultCenterXTitle.setText(_translate("GeometryCalibrationDialog", "Beam center X:"))
        self.result_center_x.setText(_translate("GeometryCalibrationDialog", "—"))
        self.resultCenterYTitle.setText(_translate("GeometryCalibrationDialog", "Beam center Y:"))
        self.result_center_y.setText(_translate("GeometryCalibrationDialog", "—"))
        self.resultDistanceTitle.setText(_translate("GeometryCalibrationDialog", "Distance:"))
        self.result_distance.setText(_translate("GeometryCalibrationDialog", "—"))
        self.resultRotationTitle.setText(_translate("GeometryCalibrationDialog", "Detector rotation:"))
        self.result_rotation.setText(_translate("GeometryCalibrationDialog", "—"))
        self.resultRingsTitle.setText(_translate("GeometryCalibrationDialog", "Matched rings:"))
        self.result_rings.setText(_translate("GeometryCalibrationDialog", "—"))
        self.resultRmsTitle.setText(_translate("GeometryCalibrationDialog", "RMS residual:"))
        self.result_rms.setText(_translate("GeometryCalibrationDialog", "—"))
        self.resultConfidenceTitle.setText(_translate("GeometryCalibrationDialog", "Confidence:"))
        self.result_confidence.setText(_translate("GeometryCalibrationDialog", "—"))
        self.resultWarningTitle.setText(_translate("GeometryCalibrationDialog", "Warning:"))
        self.result_warning.setText(_translate("GeometryCalibrationDialog", "—"))
        self.candidates_group.setTitle(_translate("GeometryCalibrationDialog", "Candidate solutions"))
        item = self.candidate_table.horizontalHeaderItem(0)
        item.setText(_translate("GeometryCalibrationDialog", "Standard"))
        item = self.candidate_table.horizontalHeaderItem(1)
        item.setText(_translate("GeometryCalibrationDialog", "Distance"))
        item = self.candidate_table.horizontalHeaderItem(2)
        item.setText(_translate("GeometryCalibrationDialog", "Center"))
        item = self.candidate_table.horizontalHeaderItem(3)
        item.setText(_translate("GeometryCalibrationDialog", "Rings"))
        item = self.candidate_table.horizontalHeaderItem(4)
        item.setText(_translate("GeometryCalibrationDialog", "RMS"))
        item = self.candidate_table.horizontalHeaderItem(5)
        item.setText(_translate("GeometryCalibrationDialog", "Confidence"))
        self.calibrationManualToggle.setText(_translate("GeometryCalibrationDialog", "Advanced manual refinement"))
        self.calibrationManualDescription.setText(_translate("GeometryCalibrationDialog", "Fine-tune the selected center, distance or ring correspondence."))
        self.manual_group.setTitle(_translate("GeometryCalibrationDialog", "Manual refinement · drag the center marker or edit values"))
        self.manual_hint.setText(_translate("GeometryCalibrationDialog", "Fine-tune only when the overlay needs correction. Changes are previewed immediately."))
        self.manualXLabel.setText(_translate("GeometryCalibrationDialog", "Center X:"))
        self.manualYLabel.setText(_translate("GeometryCalibrationDialog", "Center Y:"))
        self.manualDistanceLabel.setText(_translate("GeometryCalibrationDialog", "Distance (mm):"))
        self.detectedRingLabel.setText(_translate("GeometryCalibrationDialog", "Detected ring:"))
        self.theoryPeakLabel.setText(_translate("GeometryCalibrationDialog", "Theoretical peak:"))
        self.refine_ring_button.setText(_translate("GeometryCalibrationDialog", "Fit selected ring"))
        self.calibrationExportTitle.setText(_translate("GeometryCalibrationDialog", "Export"))
        self.calibrationExportDescription.setText(_translate("GeometryCalibrationDialog", "Import or save a calibration, or apply the selected result to the project."))
        self.import_button.setText(_translate("GeometryCalibrationDialog", "Import Calibration..."))
        self.export_button.setText(_translate("GeometryCalibrationDialog", "Export Calibration..."))
        self.apply_button.setText(_translate("GeometryCalibrationDialog", "Apply"))
        self.close_button.setText(_translate("GeometryCalibrationDialog", "Close"))
from src.gimap.app.presentation import JobStatus
