"""Hand-maintained Python View for Trainset model configuration."""


from PyQt5 import QtCore, QtGui, QtWidgets


class TrainsetModelPageView(object):
    def setupUi(self, trainsetModelPage):
        trainsetModelPage.setObjectName("trainsetModelPage")
        self.pageLayout = QtWidgets.QVBoxLayout(trainsetModelPage)
        self.pageLayout.setContentsMargins(0, 0, 0, 0)
        self.pageLayout.setObjectName("pageLayout")
        self.modelPageScroll = QtWidgets.QScrollArea(trainsetModelPage)
        self.modelPageScroll.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.modelPageScroll.setWidgetResizable(True)
        self.modelPageScroll.setObjectName("modelPageScroll")
        self.modelPageContent = QtWidgets.QWidget()
        self.modelPageContent.setGeometry(QtCore.QRect(0, 0, 760, 900))
        self.modelPageContent.setObjectName("modelPageContent")
        self.modelPageContentLayout = QtWidgets.QVBoxLayout(self.modelPageContent)
        self.modelPageContentLayout.setContentsMargins(0, 0, 0, 0)
        self.modelPageContentLayout.setSpacing(8)
        self.modelPageContentLayout.setObjectName("modelPageContentLayout")
        self.trainsetModelConfigureSection = QtWidgets.QFrame(self.modelPageContent)
        self.trainsetModelConfigureSection.setProperty("gimapSection", True)
        self.trainsetModelConfigureSection.setObjectName("trainsetModelConfigureSection")
        self.modelConfigureLayout = QtWidgets.QVBoxLayout(self.trainsetModelConfigureSection)
        self.modelConfigureLayout.setContentsMargins(12, 10, 12, 12)
        self.modelConfigureLayout.setObjectName("modelConfigureLayout")
        self.modelConfigureTitle = QtWidgets.QLabel(self.trainsetModelConfigureSection)
        self.modelConfigureTitle.setProperty("gimapSectionTitle", True)
        self.modelConfigureTitle.setObjectName("modelConfigureTitle")
        self.modelConfigureLayout.addWidget(self.modelConfigureTitle)
        self.modelConfigureDescription = QtWidgets.QLabel(self.trainsetModelConfigureSection)
        self.modelConfigureDescription.setProperty("gimapSectionDescription", True)
        self.modelConfigureDescription.setWordWrap(True)
        self.modelConfigureDescription.setObjectName("modelConfigureDescription")
        self.modelConfigureLayout.addWidget(self.modelConfigureDescription)
        self.modelConfigureContent = QtWidgets.QWidget(self.trainsetModelConfigureSection)
        self.modelConfigureContent.setObjectName("modelConfigureContent")
        self.modelConfigureContentLayout = QtWidgets.QVBoxLayout(self.modelConfigureContent)
        self.modelConfigureContentLayout.setContentsMargins(0, 0, 0, 0)
        self.modelConfigureContentLayout.setObjectName("modelConfigureContentLayout")
        self.modelConfigureLayout.addWidget(self.modelConfigureContent)
        self.modelPageContentLayout.addWidget(self.trainsetModelConfigureSection)
        self.trainsetModelAdvancedSection = QtWidgets.QFrame(self.modelPageContent)
        self.trainsetModelAdvancedSection.setProperty("gimapSection", True)
        self.trainsetModelAdvancedSection.setObjectName("trainsetModelAdvancedSection")
        self.modelAdvancedLayout = QtWidgets.QVBoxLayout(self.trainsetModelAdvancedSection)
        self.modelAdvancedLayout.setContentsMargins(8, 8, 8, 8)
        self.modelAdvancedLayout.setObjectName("modelAdvancedLayout")
        self.modelAdvancedToggle = QtWidgets.QToolButton(self.trainsetModelAdvancedSection)
        self.modelAdvancedToggle.setProperty("gimapAdvancedToggle", True)
        self.modelAdvancedToggle.setCheckable(True)
        self.modelAdvancedToggle.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.modelAdvancedToggle.setArrowType(QtCore.Qt.RightArrow)
        self.modelAdvancedToggle.setObjectName("modelAdvancedToggle")
        self.modelAdvancedLayout.addWidget(self.modelAdvancedToggle)
        self.modelAdvancedDescription = QtWidgets.QLabel(self.trainsetModelAdvancedSection)
        self.modelAdvancedDescription.setVisible(False)
        self.modelAdvancedDescription.setProperty("gimapSectionDescription", True)
        self.modelAdvancedDescription.setWordWrap(True)
        self.modelAdvancedDescription.setObjectName("modelAdvancedDescription")
        self.modelAdvancedLayout.addWidget(self.modelAdvancedDescription)
        self.modelAdvancedContent = QtWidgets.QWidget(self.trainsetModelAdvancedSection)
        self.modelAdvancedContent.setVisible(False)
        self.modelAdvancedContent.setObjectName("modelAdvancedContent")
        self.modelAdvancedContentLayout = QtWidgets.QVBoxLayout(self.modelAdvancedContent)
        self.modelAdvancedContentLayout.setContentsMargins(4, 2, 4, 4)
        self.modelAdvancedContentLayout.setObjectName("modelAdvancedContentLayout")
        self.modelIntro = QtWidgets.QLabel(self.modelAdvancedContent)
        self.modelIntro.setWordWrap(True)
        self.modelIntro.setObjectName("modelIntro")
        self.modelAdvancedContentLayout.addWidget(self.modelIntro)
        self.model_layer_table = QtWidgets.QTableWidget(self.modelAdvancedContent)
        self.model_layer_table.setMinimumSize(QtCore.QSize(0, 280))
        self.model_layer_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.model_layer_table.setColumnCount(5)
        self.model_layer_table.setObjectName("model_layer_table")
        self.model_layer_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.model_layer_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.model_layer_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.model_layer_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.model_layer_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.model_layer_table.setHorizontalHeaderItem(4, item)
        self.modelAdvancedContentLayout.addWidget(self.model_layer_table)
        self.layerActionsLayout = QtWidgets.QHBoxLayout()
        self.layerActionsLayout.setObjectName("layerActionsLayout")
        self.add_model_layer_button = QtWidgets.QPushButton(self.modelAdvancedContent)
        self.add_model_layer_button.setObjectName("add_model_layer_button")
        self.layerActionsLayout.addWidget(self.add_model_layer_button)
        self.remove_model_layer_button = QtWidgets.QPushButton(self.modelAdvancedContent)
        self.remove_model_layer_button.setObjectName("remove_model_layer_button")
        self.layerActionsLayout.addWidget(self.remove_model_layer_button)
        self.move_model_layer_up_button = QtWidgets.QPushButton(self.modelAdvancedContent)
        self.move_model_layer_up_button.setObjectName("move_model_layer_up_button")
        self.layerActionsLayout.addWidget(self.move_model_layer_up_button)
        self.move_model_layer_down_button = QtWidgets.QPushButton(self.modelAdvancedContent)
        self.move_model_layer_down_button.setObjectName("move_model_layer_down_button")
        self.layerActionsLayout.addWidget(self.move_model_layer_down_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layerActionsLayout.addItem(spacerItem)
        self.modelAdvancedContentLayout.addLayout(self.layerActionsLayout)
        self.modelAdvancedLayout.addWidget(self.modelAdvancedContent)
        self.modelPageContentLayout.addWidget(self.trainsetModelAdvancedSection)
        self.trainsetModelPreviewSection = QtWidgets.QFrame(self.modelPageContent)
        self.trainsetModelPreviewSection.setProperty("gimapSection", True)
        self.trainsetModelPreviewSection.setObjectName("trainsetModelPreviewSection")
        self.modelPreviewLayout = QtWidgets.QVBoxLayout(self.trainsetModelPreviewSection)
        self.modelPreviewLayout.setContentsMargins(12, 10, 12, 12)
        self.modelPreviewLayout.setObjectName("modelPreviewLayout")
        self.modelPreviewTitle = QtWidgets.QLabel(self.trainsetModelPreviewSection)
        self.modelPreviewTitle.setProperty("gimapSectionTitle", True)
        self.modelPreviewTitle.setObjectName("modelPreviewTitle")
        self.modelPreviewLayout.addWidget(self.modelPreviewTitle)
        self.modelPreviewDescription = QtWidgets.QLabel(self.trainsetModelPreviewSection)
        self.modelPreviewDescription.setProperty("gimapSectionDescription", True)
        self.modelPreviewDescription.setWordWrap(True)
        self.modelPreviewDescription.setObjectName("modelPreviewDescription")
        self.modelPreviewLayout.addWidget(self.modelPreviewDescription)
        self.modelPreviewContent = QtWidgets.QWidget(self.trainsetModelPreviewSection)
        self.modelPreviewContent.setObjectName("modelPreviewContent")
        self.modelPreviewContentLayout = QtWidgets.QVBoxLayout(self.modelPreviewContent)
        self.modelPreviewContentLayout.setContentsMargins(0, 0, 0, 0)
        self.modelPreviewContentLayout.setObjectName("modelPreviewContentLayout")
        self.model_summary = QtWidgets.QTextEdit(self.modelPreviewContent)
        self.model_summary.setReadOnly(True)
        self.model_summary.setObjectName("model_summary")
        self.modelPreviewContentLayout.addWidget(self.model_summary)
        self.modelPreviewLayout.addWidget(self.modelPreviewContent)
        self.modelPageContentLayout.addWidget(self.trainsetModelPreviewSection)
        self.trainsetModelRunSection = QtWidgets.QFrame(self.modelPageContent)
        self.trainsetModelRunSection.setProperty("gimapSection", True)
        self.trainsetModelRunSection.setObjectName("trainsetModelRunSection")
        self.modelRunLayout = QtWidgets.QVBoxLayout(self.trainsetModelRunSection)
        self.modelRunLayout.setContentsMargins(12, 10, 12, 12)
        self.modelRunLayout.setObjectName("modelRunLayout")
        self.modelRunTitle = QtWidgets.QLabel(self.trainsetModelRunSection)
        self.modelRunTitle.setProperty("gimapSectionTitle", True)
        self.modelRunTitle.setObjectName("modelRunTitle")
        self.modelRunLayout.addWidget(self.modelRunTitle)
        self.modelRunDescription = QtWidgets.QLabel(self.trainsetModelRunSection)
        self.modelRunDescription.setProperty("gimapSectionDescription", True)
        self.modelRunDescription.setText("")
        self.modelRunDescription.setObjectName("modelRunDescription")
        self.modelRunLayout.addWidget(self.modelRunDescription)
        self.modelRunContent = QtWidgets.QWidget(self.trainsetModelRunSection)
        self.modelRunContent.setObjectName("modelRunContent")
        self.modelRunContentLayout = QtWidgets.QVBoxLayout(self.modelRunContent)
        self.modelRunContentLayout.setContentsMargins(0, 0, 0, 0)
        self.modelRunContentLayout.setObjectName("modelRunContentLayout")
        self.model_validate_button = QtWidgets.QPushButton(self.modelRunContent)
        self.model_validate_button.setProperty("primaryAction", True)
        self.model_validate_button.setObjectName("model_validate_button")
        self.modelRunContentLayout.addWidget(self.model_validate_button)
        self.modelRunLayout.addWidget(self.modelRunContent)
        self.modelPageContentLayout.addWidget(self.trainsetModelRunSection)
        self.modelPageScroll.setWidget(self.modelPageContent)
        self.pageLayout.addWidget(self.modelPageScroll)

        self.retranslateUi(trainsetModelPage)
        QtCore.QMetaObject.connectSlotsByName(trainsetModelPage)

    def retranslateUi(self, trainsetModelPage):
        _translate = QtCore.QCoreApplication.translate
        self.modelConfigureTitle.setText(_translate("TrainsetModelPage", "Configure"))
        self.modelConfigureDescription.setText(_translate("TrainsetModelPage", "Set the training controls independently of the model architecture."))
        self.modelAdvancedToggle.setText(_translate("TrainsetModelPage", "Advanced model architecture"))
        self.modelAdvancedDescription.setText(_translate("TrainsetModelPage", "Edit, remove and reorder the feature-extractor layers."))
        self.modelIntro.setText(_translate("TrainsetModelPage", "Build the feature extractor row by row. The regression output size is added automatically from the variable physics parameters."))
        item = self.model_layer_table.horizontalHeaderItem(0)
        item.setText(_translate("TrainsetModelPage", "Layer type"))
        item = self.model_layer_table.horizontalHeaderItem(1)
        item.setText(_translate("TrainsetModelPage", "Filters / units"))
        item = self.model_layer_table.horizontalHeaderItem(2)
        item.setText(_translate("TrainsetModelPage", "Kernel / pool"))
        item = self.model_layer_table.horizontalHeaderItem(3)
        item.setText(_translate("TrainsetModelPage", "Activation"))
        item = self.model_layer_table.horizontalHeaderItem(4)
        item.setText(_translate("TrainsetModelPage", "Dropout rate"))
        self.add_model_layer_button.setText(_translate("TrainsetModelPage", "Add layer"))
        self.remove_model_layer_button.setText(_translate("TrainsetModelPage", "Remove selected"))
        self.move_model_layer_up_button.setText(_translate("TrainsetModelPage", "Move up"))
        self.move_model_layer_down_button.setText(_translate("TrainsetModelPage", "Move down"))
        self.modelPreviewTitle.setText(_translate("TrainsetModelPage", "Preview"))
        self.modelPreviewDescription.setText(_translate("TrainsetModelPage", "Review the tensor contract before starting a local run."))
        self.model_summary.setPlainText(_translate("TrainsetModelPage", "Add, remove and reorder layers, then validate the real tensor contract.\n"
"\n"
"Supported: Conv2D, MaxPool2D, BatchNormalization, Dropout, GlobalAveragePooling2D, Flatten and Dense."))
        self.modelRunTitle.setText(_translate("TrainsetModelPage", "Run"))
        self.model_validate_button.setText(_translate("TrainsetModelPage", "Build model and validate one forward pass"))
