"""Hand-maintained Python View for Trainset job monitoring."""


from PyQt5 import QtCore, QtGui, QtWidgets


class TrainsetMonitorPageView(object):
    def setupUi(self, trainsetMonitorPage):
        trainsetMonitorPage.setObjectName("trainsetMonitorPage")
        self.pageLayout = QtWidgets.QVBoxLayout(trainsetMonitorPage)
        self.pageLayout.setContentsMargins(0, 0, 0, 0)
        self.pageLayout.setObjectName("pageLayout")
        self.statusLayout = QtWidgets.QHBoxLayout()
        self.statusLayout.setObjectName("statusLayout")
        self.job_state = QtWidgets.QLabel(trainsetMonitorPage)
        self.job_state.setObjectName("job_state")
        self.statusLayout.addWidget(self.job_state)
        self.job_id_label = QtWidgets.QLabel(trainsetMonitorPage)
        self.job_id_label.setObjectName("job_id_label")
        self.statusLayout.addWidget(self.job_id_label)
        self.refresh_job_button = QtWidgets.QPushButton(trainsetMonitorPage)
        self.refresh_job_button.setObjectName("refresh_job_button")
        self.statusLayout.addWidget(self.refresh_job_button)
        self.sync_results_button = QtWidgets.QPushButton(trainsetMonitorPage)
        self.sync_results_button.setObjectName("sync_results_button")
        self.statusLayout.addWidget(self.sync_results_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.statusLayout.addItem(spacerItem)
        self.pageLayout.addLayout(self.statusLayout)
        self.monitor_splitter = QtWidgets.QSplitter(trainsetMonitorPage)
        self.monitor_splitter.setOrientation(QtCore.Qt.Horizontal)
        self.monitor_splitter.setObjectName("monitor_splitter")
        self.trainsetLogSection = QtWidgets.QFrame(self.monitor_splitter)
        self.trainsetLogSection.setProperty("gimapSection", True)
        self.trainsetLogSection.setObjectName("trainsetLogSection")
        self.logSectionLayout = QtWidgets.QVBoxLayout(self.trainsetLogSection)
        self.logSectionLayout.setContentsMargins(8, 8, 8, 8)
        self.logSectionLayout.setObjectName("logSectionLayout")
        self.logToggle = QtWidgets.QToolButton(self.trainsetLogSection)
        self.logToggle.setProperty("gimapAdvancedToggle", True)
        self.logToggle.setCheckable(True)
        self.logToggle.setChecked(True)
        self.logToggle.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.logToggle.setArrowType(QtCore.Qt.DownArrow)
        self.logToggle.setObjectName("logToggle")
        self.logSectionLayout.addWidget(self.logToggle)
        self.logDescription = QtWidgets.QLabel(self.trainsetLogSection)
        self.logDescription.setProperty("gimapSectionDescription", True)
        self.logDescription.setWordWrap(True)
        self.logDescription.setObjectName("logDescription")
        self.logSectionLayout.addWidget(self.logDescription)
        self.logContent = QtWidgets.QWidget(self.trainsetLogSection)
        self.logContent.setObjectName("logContent")
        self.logContentLayout = QtWidgets.QVBoxLayout(self.logContent)
        self.logContentLayout.setContentsMargins(4, 2, 4, 4)
        self.logContentLayout.setObjectName("logContentLayout")
        self.job_log = QtWidgets.QTextEdit(self.logContent)
        self.job_log.setReadOnly(True)
        self.job_log.setObjectName("job_log")
        self.logContentLayout.addWidget(self.job_log)
        self.logSectionLayout.addWidget(self.logContent)
        self.trainsetResultsSection = QtWidgets.QFrame(self.monitor_splitter)
        self.trainsetResultsSection.setProperty("gimapSection", True)
        self.trainsetResultsSection.setObjectName("trainsetResultsSection")
        self.resultsSectionLayout = QtWidgets.QVBoxLayout(self.trainsetResultsSection)
        self.resultsSectionLayout.setContentsMargins(12, 10, 12, 12)
        self.resultsSectionLayout.setObjectName("resultsSectionLayout")
        self.resultsTitle = QtWidgets.QLabel(self.trainsetResultsSection)
        self.resultsTitle.setProperty("gimapSectionTitle", True)
        self.resultsTitle.setObjectName("resultsTitle")
        self.resultsSectionLayout.addWidget(self.resultsTitle)
        self.resultsDescription = QtWidgets.QLabel(self.trainsetResultsSection)
        self.resultsDescription.setProperty("gimapSectionDescription", True)
        self.resultsDescription.setWordWrap(True)
        self.resultsDescription.setObjectName("resultsDescription")
        self.resultsSectionLayout.addWidget(self.resultsDescription)
        self.resultsContent = QtWidgets.QWidget(self.trainsetResultsSection)
        self.resultsContent.setObjectName("resultsContent")
        self.resultsContentLayout = QtWidgets.QVBoxLayout(self.resultsContent)
        self.resultsContentLayout.setContentsMargins(0, 0, 0, 0)
        self.resultsContentLayout.setObjectName("resultsContentLayout")
        self.metrics_table = QtWidgets.QTableWidget(self.resultsContent)
        self.metrics_table.setColumnCount(4)
        self.metrics_table.setObjectName("metrics_table")
        self.metrics_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.metrics_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.metrics_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.metrics_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.metrics_table.setHorizontalHeaderItem(3, item)
        self.resultsContentLayout.addWidget(self.metrics_table)
        self.register_model_button = QtWidgets.QPushButton(self.resultsContent)
        self.register_model_button.setObjectName("register_model_button")
        self.resultsContentLayout.addWidget(self.register_model_button)
        self.resultsSectionLayout.addWidget(self.resultsContent)
        self.pageLayout.addWidget(self.monitor_splitter)

        self.retranslateUi(trainsetMonitorPage)
        QtCore.QMetaObject.connectSlotsByName(trainsetMonitorPage)

    def retranslateUi(self, trainsetMonitorPage):
        _translate = QtCore.QCoreApplication.translate
        self.job_state.setText(_translate("TrainsetMonitorPage", "NO JOB"))
        self.job_id_label.setText(_translate("TrainsetMonitorPage", "Job ID: —"))
        self.refresh_job_button.setText(_translate("TrainsetMonitorPage", "Refresh"))
        self.sync_results_button.setText(_translate("TrainsetMonitorPage", "Sync results"))
        self.logToggle.setText(_translate("TrainsetMonitorPage", "Log"))
        self.logDescription.setText(_translate("TrainsetMonitorPage", "Local process and future remote scheduler output."))
        self.job_log.setPlaceholderText(_translate("TrainsetMonitorPage", "Slurm/local process output will appear here. Closing the GUI does not stop remote jobs."))
        self.resultsTitle.setText(_translate("TrainsetMonitorPage", "Results"))
        self.resultsDescription.setText(_translate("TrainsetMonitorPage", "Inspect training metrics and register the selected model for Prediction."))
        item = self.metrics_table.horizontalHeaderItem(0)
        item.setText(_translate("TrainsetMonitorPage", "Epoch"))
        item = self.metrics_table.horizontalHeaderItem(1)
        item.setText(_translate("TrainsetMonitorPage", "Train loss"))
        item = self.metrics_table.horizontalHeaderItem(2)
        item.setText(_translate("TrainsetMonitorPage", "Validation loss"))
        item = self.metrics_table.horizontalHeaderItem(3)
        item.setText(_translate("TrainsetMonitorPage", "Learning rate"))
        self.register_model_button.setText(_translate("TrainsetMonitorPage", "Register best model in 2D Prediction"))
