"""Hand-maintained Python View for the Trainset workflow shell."""


from PyQt5 import QtCore, QtGui, QtWidgets


class TrainsetPageView(object):
    def setupUi(self, freshTrainsetBuildPage):
        freshTrainsetBuildPage.setObjectName("freshTrainsetBuildPage")
        self.trainsetRootLayout = QtWidgets.QVBoxLayout(freshTrainsetBuildPage)
        self.trainsetRootLayout.setContentsMargins(18, 14, 18, 14)
        self.trainsetRootLayout.setSpacing(10)
        self.trainsetRootLayout.setObjectName("trainsetRootLayout")
        self.trainsetHeaderLayout = QtWidgets.QGridLayout()
        self.trainsetHeaderLayout.setObjectName("trainsetHeaderLayout")
        self.trainsetTitleLayout = QtWidgets.QVBoxLayout()
        self.trainsetTitleLayout.setObjectName("trainsetTitleLayout")
        self.pageTitle = QtWidgets.QLabel(freshTrainsetBuildPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pageTitle.sizePolicy().hasHeightForWidth())
        self.pageTitle.setSizePolicy(sizePolicy)
        self.pageTitle.setObjectName("pageTitle")
        self.trainsetTitleLayout.addWidget(self.pageTitle)
        self.pageSubtitle = QtWidgets.QLabel(freshTrainsetBuildPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pageSubtitle.sizePolicy().hasHeightForWidth())
        self.pageSubtitle.setSizePolicy(sizePolicy)
        self.pageSubtitle.setWordWrap(True)
        self.pageSubtitle.setObjectName("pageSubtitle")
        self.trainsetTitleLayout.addWidget(self.pageSubtitle)
        self.trainsetHeaderLayout.addLayout(self.trainsetTitleLayout, 0, 0, 1, 4)
        self.projectNameLabel = QtWidgets.QLabel(freshTrainsetBuildPage)
        self.projectNameLabel.setObjectName("projectNameLabel")
        self.trainsetHeaderLayout.addWidget(self.projectNameLabel, 1, 0, 1, 1)
        self.project_name = QtWidgets.QLineEdit(freshTrainsetBuildPage)
        self.project_name.setMinimumSize(QtCore.QSize(130, 0))
        self.project_name.setMaximumSize(QtCore.QSize(220, 16777215))
        self.project_name.setObjectName("project_name")
        self.trainsetHeaderLayout.addWidget(self.project_name, 1, 1, 1, 1)
        self.validationBadge = QtWidgets.QLabel(freshTrainsetBuildPage)
        self.validationBadge.setObjectName("validationBadge")
        self.trainsetHeaderLayout.addWidget(self.validationBadge, 1, 2, 1, 1)
        self.auto_remember_check = QtWidgets.QCheckBox(freshTrainsetBuildPage)
        self.auto_remember_check.setChecked(True)
        self.auto_remember_check.setObjectName("auto_remember_check")
        self.trainsetHeaderLayout.addWidget(self.auto_remember_check, 2, 0, 1, 2)
        self.reset_defaults_button = QtWidgets.QPushButton(freshTrainsetBuildPage)
        self.reset_defaults_button.setObjectName("reset_defaults_button")
        self.trainsetHeaderLayout.addWidget(self.reset_defaults_button, 2, 2, 1, 1)
        self.trainsetHeaderLayout.setColumnStretch(3, 1)
        self.trainsetRootLayout.addLayout(self.trainsetHeaderLayout)
        self.trainsetContentSplitter = QtWidgets.QSplitter(freshTrainsetBuildPage)
        self.trainsetContentSplitter.setOrientation(QtCore.Qt.Horizontal)
        self.trainsetContentSplitter.setObjectName("trainsetContentSplitter")
        self.trainsetStepList = QtWidgets.QListWidget(self.trainsetContentSplitter)
        self.trainsetStepList.setMinimumSize(QtCore.QSize(176, 0))
        self.trainsetStepList.setMaximumSize(QtCore.QSize(218, 16777215))
        self.trainsetStepList.setWordWrap(True)
        self.trainsetStepList.setObjectName("trainsetStepList")
        item = QtWidgets.QListWidgetItem()
        self.trainsetStepList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.trainsetStepList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.trainsetStepList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.trainsetStepList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.trainsetStepList.addItem(item)
        self.trainsetWorkflowStack = QtWidgets.QStackedWidget(self.trainsetContentSplitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trainsetWorkflowStack.sizePolicy().hasHeightForWidth())
        self.trainsetWorkflowStack.setSizePolicy(sizePolicy)
        self.trainsetWorkflowStack.setObjectName("trainsetWorkflowStack")
        self.datasetPageHost = QtWidgets.QWidget()
        self.datasetPageHost.setObjectName("datasetPageHost")
        self.datasetPageHostLayout = QtWidgets.QVBoxLayout(self.datasetPageHost)
        self.datasetPageHostLayout.setContentsMargins(0, 0, 0, 0)
        self.datasetPageHostLayout.setObjectName("datasetPageHostLayout")
        self.trainsetWorkflowStack.addWidget(self.datasetPageHost)
        self.previewPageHost = QtWidgets.QWidget()
        self.previewPageHost.setObjectName("previewPageHost")
        self.previewPageHostLayout = QtWidgets.QVBoxLayout(self.previewPageHost)
        self.previewPageHostLayout.setContentsMargins(0, 0, 0, 0)
        self.previewPageHostLayout.setObjectName("previewPageHostLayout")
        self.trainsetWorkflowStack.addWidget(self.previewPageHost)
        self.modelPageHost = QtWidgets.QWidget()
        self.modelPageHost.setObjectName("modelPageHost")
        self.modelPageHostLayout = QtWidgets.QVBoxLayout(self.modelPageHost)
        self.modelPageHostLayout.setContentsMargins(0, 0, 0, 0)
        self.modelPageHostLayout.setObjectName("modelPageHostLayout")
        self.trainsetWorkflowStack.addWidget(self.modelPageHost)
        self.runPageHost = QtWidgets.QWidget()
        self.runPageHost.setObjectName("runPageHost")
        self.runPageHostLayout = QtWidgets.QVBoxLayout(self.runPageHost)
        self.runPageHostLayout.setContentsMargins(0, 0, 0, 0)
        self.runPageHostLayout.setObjectName("runPageHostLayout")
        self.trainsetWorkflowStack.addWidget(self.runPageHost)
        self.monitorPageHost = QtWidgets.QWidget()
        self.monitorPageHost.setObjectName("monitorPageHost")
        self.monitorPageHostLayout = QtWidgets.QVBoxLayout(self.monitorPageHost)
        self.monitorPageHostLayout.setContentsMargins(0, 0, 0, 0)
        self.monitorPageHostLayout.setObjectName("monitorPageHostLayout")
        self.trainsetWorkflowStack.addWidget(self.monitorPageHost)
        self.trainsetRootLayout.addWidget(self.trainsetContentSplitter)
        self.trainsetActionsLayout = QtWidgets.QHBoxLayout()
        self.trainsetActionsLayout.setObjectName("trainsetActionsLayout")
        self.back_button = QtWidgets.QPushButton(freshTrainsetBuildPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.back_button.sizePolicy().hasHeightForWidth())
        self.back_button.setSizePolicy(sizePolicy)
        self.back_button.setMinimumSize(QtCore.QSize(76, 0))
        self.back_button.setObjectName("back_button")
        self.trainsetActionsLayout.addWidget(self.back_button)
        self.trainsetActionGrid = QtWidgets.QGridLayout()
        self.trainsetActionGrid.setHorizontalSpacing(6)
        self.trainsetActionGrid.setVerticalSpacing(4)
        self.trainsetActionGrid.setObjectName("trainsetActionGrid")
        self.validate_button = QtWidgets.QPushButton(freshTrainsetBuildPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.validate_button.sizePolicy().hasHeightForWidth())
        self.validate_button.setSizePolicy(sizePolicy)
        self.validate_button.setMinimumSize(QtCore.QSize(76, 0))
        self.validate_button.setObjectName("validate_button")
        self.trainsetActionGrid.addWidget(self.validate_button, 0, 0, 1, 1)
        self.load_button = QtWidgets.QPushButton(freshTrainsetBuildPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.load_button.sizePolicy().hasHeightForWidth())
        self.load_button.setSizePolicy(sizePolicy)
        self.load_button.setMinimumSize(QtCore.QSize(76, 0))
        self.load_button.setObjectName("load_button")
        self.trainsetActionGrid.addWidget(self.load_button, 0, 1, 1, 1)
        self.save_button = QtWidgets.QPushButton(freshTrainsetBuildPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_button.sizePolicy().hasHeightForWidth())
        self.save_button.setSizePolicy(sizePolicy)
        self.save_button.setMinimumSize(QtCore.QSize(76, 0))
        self.save_button.setObjectName("save_button")
        self.trainsetActionGrid.addWidget(self.save_button, 0, 2, 1, 1)
        self.preview_button = QtWidgets.QPushButton(freshTrainsetBuildPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.preview_button.sizePolicy().hasHeightForWidth())
        self.preview_button.setSizePolicy(sizePolicy)
        self.preview_button.setMinimumSize(QtCore.QSize(76, 0))
        self.preview_button.setObjectName("preview_button")
        self.trainsetActionGrid.addWidget(self.preview_button, 1, 0, 1, 1)
        self.prepare_button = QtWidgets.QPushButton(freshTrainsetBuildPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prepare_button.sizePolicy().hasHeightForWidth())
        self.prepare_button.setSizePolicy(sizePolicy)
        self.prepare_button.setMinimumSize(QtCore.QSize(76, 0))
        self.prepare_button.setObjectName("prepare_button")
        self.trainsetActionGrid.addWidget(self.prepare_button, 1, 1, 1, 1)
        self.submit_button = QtWidgets.QPushButton(freshTrainsetBuildPage)
        self.submit_button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.submit_button.sizePolicy().hasHeightForWidth())
        self.submit_button.setSizePolicy(sizePolicy)
        self.submit_button.setMinimumSize(QtCore.QSize(76, 0))
        self.submit_button.setObjectName("submit_button")
        self.trainsetActionGrid.addWidget(self.submit_button, 1, 2, 1, 1)
        self.trainsetActionsLayout.addLayout(self.trainsetActionGrid)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.trainsetActionsLayout.addItem(spacerItem)
        self.trainsetRootLayout.addLayout(self.trainsetActionsLayout)
        self.trainsetRootLayout.setStretch(1, 1)

        self.retranslateUi(freshTrainsetBuildPage)
        self.trainsetWorkflowStack.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(freshTrainsetBuildPage)
        freshTrainsetBuildPage.setTabOrder(self.project_name, self.auto_remember_check)
        freshTrainsetBuildPage.setTabOrder(self.auto_remember_check, self.reset_defaults_button)
        freshTrainsetBuildPage.setTabOrder(self.reset_defaults_button, self.trainsetStepList)
        freshTrainsetBuildPage.setTabOrder(self.trainsetStepList, self.back_button)
        freshTrainsetBuildPage.setTabOrder(self.back_button, self.validate_button)
        freshTrainsetBuildPage.setTabOrder(self.validate_button, self.load_button)
        freshTrainsetBuildPage.setTabOrder(self.load_button, self.save_button)
        freshTrainsetBuildPage.setTabOrder(self.save_button, self.preview_button)
        freshTrainsetBuildPage.setTabOrder(self.preview_button, self.prepare_button)
        freshTrainsetBuildPage.setTabOrder(self.prepare_button, self.submit_button)

    def retranslateUi(self, freshTrainsetBuildPage):
        _translate = QtCore.QCoreApplication.translate
        self.pageTitle.setText(_translate("TrainsetPage", "2D Trainset & Model Workspace"))
        self.pageSubtitle.setText(_translate("TrainsetPage", "Design locally · validate with real scattering data · run a lightweight test · export for Maxwell later"))
        self.projectNameLabel.setText(_translate("TrainsetPage", "Project"))
        self.project_name.setText(_translate("TrainsetPage", "gisaxs_2d_project"))
        self.project_name.setPlaceholderText(_translate("TrainsetPage", "Project name"))
        self.validationBadge.setText(_translate("TrainsetPage", "Not validated"))
        self.auto_remember_check.setToolTip(_translate("TrainsetPage", "Automatically save TrainSet settings after edits and restore them at the next GUI launch. Turn this off to experiment without replacing the remembered configuration."))
        self.auto_remember_check.setText(_translate("TrainsetPage", "Remember changes"))
        self.reset_defaults_button.setToolTip(_translate("TrainsetPage", "Restore built-in TrainSet defaults. Generated datasets are not deleted."))
        self.reset_defaults_button.setText(_translate("TrainsetPage", "Reset defaults"))
        __sortingEnabled = self.trainsetStepList.isSortingEnabled()
        self.trainsetStepList.setSortingEnabled(False)
        item = self.trainsetStepList.item(0)
        item.setText(_translate("TrainsetPage", "1.  Dataset Design"))
        item = self.trainsetStepList.item(1)
        item.setText(_translate("TrainsetPage", "2.  Local Preview"))
        item = self.trainsetStepList.item(2)
        item.setText(_translate("TrainsetPage", "3.  Model Design"))
        item = self.trainsetStepList.item(3)
        item.setText(_translate("TrainsetPage", "4.  Local Run"))
        item = self.trainsetStepList.item(4)
        item.setText(_translate("TrainsetPage", "5.  Monitor & Results"))
        self.trainsetStepList.setSortingEnabled(__sortingEnabled)
        self.back_button.setText(_translate("TrainsetPage", "Back"))
        self.validate_button.setText(_translate("TrainsetPage", "Validate"))
        self.load_button.setToolTip(_translate("TrainsetPage", "Load trainset project"))
        self.load_button.setText(_translate("TrainsetPage", "Load"))
        self.save_button.setToolTip(_translate("TrainsetPage", "Save trainset project"))
        self.save_button.setText(_translate("TrainsetPage", "Save"))
        self.preview_button.setText(_translate("TrainsetPage", "Preview"))
        self.prepare_button.setToolTip(_translate("TrainsetPage", "Prepare a portable local/Maxwell job package"))
        self.prepare_button.setText(_translate("TrainsetPage", "Prepare job"))
        self.submit_button.setToolTip(_translate("TrainsetPage", "SSH submission is intentionally disabled in the local demo. The portable Slurm package interface is retained."))
        self.submit_button.setText(_translate("TrainsetPage", "Maxwell"))
