"""Hand-maintained Python View for Trainset previews."""


from PyQt5 import QtCore, QtGui, QtWidgets


class TrainsetPreviewPageView(object):
    def setupUi(self, trainsetPreviewPage):
        trainsetPreviewPage.setObjectName("trainsetPreviewPage")
        self.pageLayout = QtWidgets.QVBoxLayout(trainsetPreviewPage)
        self.pageLayout.setContentsMargins(0, 0, 0, 0)
        self.pageLayout.setObjectName("pageLayout")
        self.previewPageScroll = QtWidgets.QScrollArea(trainsetPreviewPage)
        self.previewPageScroll.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.previewPageScroll.setWidgetResizable(True)
        self.previewPageScroll.setObjectName("previewPageScroll")
        self.previewPageContent = QtWidgets.QWidget()
        self.previewPageContent.setGeometry(QtCore.QRect(0, 0, 760, 1100))
        self.previewPageContent.setObjectName("previewPageContent")
        self.previewPageContentLayout = QtWidgets.QVBoxLayout(self.previewPageContent)
        self.previewPageContentLayout.setContentsMargins(0, 0, 0, 0)
        self.previewPageContentLayout.setSpacing(8)
        self.previewPageContentLayout.setObjectName("previewPageContentLayout")
        self.trainsetPreviewRunSection = QtWidgets.QFrame(self.previewPageContent)
        self.trainsetPreviewRunSection.setProperty("gimapSection", True)
        self.trainsetPreviewRunSection.setObjectName("trainsetPreviewRunSection")
        self.previewRunSectionLayout = QtWidgets.QVBoxLayout(self.trainsetPreviewRunSection)
        self.previewRunSectionLayout.setContentsMargins(12, 10, 12, 12)
        self.previewRunSectionLayout.setSpacing(8)
        self.previewRunSectionLayout.setObjectName("previewRunSectionLayout")
        self.previewRunTitle = QtWidgets.QLabel(self.trainsetPreviewRunSection)
        self.previewRunTitle.setProperty("gimapSectionTitle", True)
        self.previewRunTitle.setObjectName("previewRunTitle")
        self.previewRunSectionLayout.addWidget(self.previewRunTitle)
        self.previewRunDescription = QtWidgets.QLabel(self.trainsetPreviewRunSection)
        self.previewRunDescription.setProperty("gimapSectionDescription", True)
        self.previewRunDescription.setWordWrap(True)
        self.previewRunDescription.setObjectName("previewRunDescription")
        self.previewRunSectionLayout.addWidget(self.previewRunDescription)
        self.previewRunContent = QtWidgets.QWidget(self.trainsetPreviewRunSection)
        self.previewRunContent.setObjectName("previewRunContent")
        self.previewRunContentLayout = QtWidgets.QVBoxLayout(self.previewRunContent)
        self.previewRunContentLayout.setContentsMargins(0, 0, 0, 0)
        self.previewRunContentLayout.setSpacing(8)
        self.previewRunContentLayout.setObjectName("previewRunContentLayout")
        self.previewRunSectionLayout.addWidget(self.previewRunContent)
        self.previewPageContentLayout.addWidget(self.trainsetPreviewRunSection)
        self.trainsetPreviewAdvancedSection = QtWidgets.QFrame(self.previewPageContent)
        self.trainsetPreviewAdvancedSection.setProperty("gimapSection", True)
        self.trainsetPreviewAdvancedSection.setObjectName("trainsetPreviewAdvancedSection")
        self.previewAdvancedSectionLayout = QtWidgets.QVBoxLayout(self.trainsetPreviewAdvancedSection)
        self.previewAdvancedSectionLayout.setContentsMargins(8, 8, 8, 8)
        self.previewAdvancedSectionLayout.setSpacing(7)
        self.previewAdvancedSectionLayout.setObjectName("previewAdvancedSectionLayout")
        self.previewAdvancedToggle = QtWidgets.QToolButton(self.trainsetPreviewAdvancedSection)
        self.previewAdvancedToggle.setProperty("gimapAdvancedToggle", True)
        self.previewAdvancedToggle.setCheckable(True)
        self.previewAdvancedToggle.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.previewAdvancedToggle.setArrowType(QtCore.Qt.RightArrow)
        self.previewAdvancedToggle.setObjectName("previewAdvancedToggle")
        self.previewAdvancedSectionLayout.addWidget(self.previewAdvancedToggle)
        self.previewAdvancedDescription = QtWidgets.QLabel(self.trainsetPreviewAdvancedSection)
        self.previewAdvancedDescription.setVisible(False)
        self.previewAdvancedDescription.setProperty("gimapSectionDescription", True)
        self.previewAdvancedDescription.setWordWrap(True)
        self.previewAdvancedDescription.setObjectName("previewAdvancedDescription")
        self.previewAdvancedSectionLayout.addWidget(self.previewAdvancedDescription)
        self.previewAdvancedContent = QtWidgets.QWidget(self.trainsetPreviewAdvancedSection)
        self.previewAdvancedContent.setVisible(False)
        self.previewAdvancedContent.setObjectName("previewAdvancedContent")
        self.previewAdvancedContentLayout = QtWidgets.QVBoxLayout(self.previewAdvancedContent)
        self.previewAdvancedContentLayout.setContentsMargins(4, 2, 4, 4)
        self.previewAdvancedContentLayout.setSpacing(8)
        self.previewAdvancedContentLayout.setObjectName("previewAdvancedContentLayout")
        self.previewAdvancedSectionLayout.addWidget(self.previewAdvancedContent)
        self.previewPageContentLayout.addWidget(self.trainsetPreviewAdvancedSection)
        self.trainsetPreviewPanel = QtWidgets.QFrame(self.previewPageContent)
        self.trainsetPreviewPanel.setProperty("gimapSection", True)
        self.trainsetPreviewPanel.setObjectName("trainsetPreviewPanel")
        self.previewPanelLayout = QtWidgets.QVBoxLayout(self.trainsetPreviewPanel)
        self.previewPanelLayout.setContentsMargins(12, 10, 12, 12)
        self.previewPanelLayout.setSpacing(8)
        self.previewPanelLayout.setObjectName("previewPanelLayout")
        self.previewPanelTitle = QtWidgets.QLabel(self.trainsetPreviewPanel)
        self.previewPanelTitle.setProperty("gimapSectionTitle", True)
        self.previewPanelTitle.setObjectName("previewPanelTitle")
        self.previewPanelLayout.addWidget(self.previewPanelTitle)
        self.previewPanelDescription = QtWidgets.QLabel(self.trainsetPreviewPanel)
        self.previewPanelDescription.setProperty("gimapSectionDescription", True)
        self.previewPanelDescription.setWordWrap(True)
        self.previewPanelDescription.setObjectName("previewPanelDescription")
        self.previewPanelLayout.addWidget(self.previewPanelDescription)
        self.previewPanelContent = QtWidgets.QWidget(self.trainsetPreviewPanel)
        self.previewPanelContent.setObjectName("previewPanelContent")
        self.previewPanelContentLayout = QtWidgets.QVBoxLayout(self.previewPanelContent)
        self.previewPanelContentLayout.setContentsMargins(0, 0, 0, 0)
        self.previewPanelContentLayout.setSpacing(8)
        self.previewPanelContentLayout.setObjectName("previewPanelContentLayout")
        self.previewPanelLayout.addWidget(self.previewPanelContent)
        self.previewPageContentLayout.addWidget(self.trainsetPreviewPanel)
        self.previewPageScroll.setWidget(self.previewPageContent)
        self.pageLayout.addWidget(self.previewPageScroll)

        self.retranslateUi(trainsetPreviewPage)
        QtCore.QMetaObject.connectSlotsByName(trainsetPreviewPage)

    def retranslateUi(self, trainsetPreviewPage):
        _translate = QtCore.QCoreApplication.translate
        self.previewRunTitle.setText(_translate("TrainsetPreviewPage", "Run"))
        self.previewRunDescription.setText(_translate("TrainsetPreviewPage", "Generate a cached BornAgain comparison or refresh only the stochastic preprocessing realization."))
        self.previewAdvancedToggle.setText(_translate("TrainsetPreviewPage", "Advanced preprocessing"))
        self.previewAdvancedDescription.setText(_translate("TrainsetPreviewPage", "Physical background, noise, masking and transforms apply exactly as before."))
        self.previewPanelTitle.setText(_translate("TrainsetPreviewPage", "Preview"))
        self.previewPanelDescription.setText(_translate("TrainsetPreviewPage", "Orientation: detector x increases to the right and detector y downward; exit angle/qz is higher at the top. BornAgain is flipped vertically once to match the experimental detector display."))
