"""Hand-maintained Python View for Trainset execution and export."""


from PyQt5 import QtCore, QtGui, QtWidgets


class TrainsetRunPageView(object):
    def setupUi(self, trainsetRunPage):
        trainsetRunPage.setObjectName("trainsetRunPage")
        self.pageLayout = QtWidgets.QVBoxLayout(trainsetRunPage)
        self.pageLayout.setContentsMargins(0, 0, 0, 0)
        self.pageLayout.setObjectName("pageLayout")
        self.runPageScroll = QtWidgets.QScrollArea(trainsetRunPage)
        self.runPageScroll.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.runPageScroll.setWidgetResizable(True)
        self.runPageScroll.setObjectName("runPageScroll")
        self.runPageContent = QtWidgets.QWidget()
        self.runPageContent.setGeometry(QtCore.QRect(0, 0, 760, 950))
        self.runPageContent.setObjectName("runPageContent")
        self.runPageContentLayout = QtWidgets.QVBoxLayout(self.runPageContent)
        self.runPageContentLayout.setContentsMargins(0, 0, 0, 0)
        self.runPageContentLayout.setSpacing(8)
        self.runPageContentLayout.setObjectName("runPageContentLayout")
        self.trainsetRunSection = QtWidgets.QFrame(self.runPageContent)
        self.trainsetRunSection.setProperty("gimapSection", True)
        self.trainsetRunSection.setObjectName("trainsetRunSection")
        self.runSectionLayout = QtWidgets.QVBoxLayout(self.trainsetRunSection)
        self.runSectionLayout.setContentsMargins(12, 10, 12, 12)
        self.runSectionLayout.setObjectName("runSectionLayout")
        self.runTitle = QtWidgets.QLabel(self.trainsetRunSection)
        self.runTitle.setProperty("gimapSectionTitle", True)
        self.runTitle.setObjectName("runTitle")
        self.runSectionLayout.addWidget(self.runTitle)
        self.runDescription = QtWidgets.QLabel(self.trainsetRunSection)
        self.runDescription.setProperty("gimapSectionDescription", True)
        self.runDescription.setWordWrap(True)
        self.runDescription.setObjectName("runDescription")
        self.runSectionLayout.addWidget(self.runDescription)
        self.runContent = QtWidgets.QWidget(self.trainsetRunSection)
        self.runContent.setObjectName("runContent")
        self.runContentLayout = QtWidgets.QVBoxLayout(self.runContent)
        self.runContentLayout.setContentsMargins(0, 0, 0, 0)
        self.runContentLayout.setObjectName("runContentLayout")
        self.runSectionLayout.addWidget(self.runContent)
        self.runPageContentLayout.addWidget(self.trainsetRunSection)
        self.trainsetExportSection = QtWidgets.QFrame(self.runPageContent)
        self.trainsetExportSection.setProperty("gimapSection", True)
        self.trainsetExportSection.setObjectName("trainsetExportSection")
        self.exportSectionLayout = QtWidgets.QVBoxLayout(self.trainsetExportSection)
        self.exportSectionLayout.setContentsMargins(12, 10, 12, 12)
        self.exportSectionLayout.setObjectName("exportSectionLayout")
        self.exportTitle = QtWidgets.QLabel(self.trainsetExportSection)
        self.exportTitle.setProperty("gimapSectionTitle", True)
        self.exportTitle.setObjectName("exportTitle")
        self.exportSectionLayout.addWidget(self.exportTitle)
        self.exportDescription = QtWidgets.QLabel(self.trainsetExportSection)
        self.exportDescription.setProperty("gimapSectionDescription", True)
        self.exportDescription.setWordWrap(True)
        self.exportDescription.setObjectName("exportDescription")
        self.exportSectionLayout.addWidget(self.exportDescription)
        self.exportContent = QtWidgets.QWidget(self.trainsetExportSection)
        self.exportContent.setObjectName("exportContent")
        self.exportContentLayout = QtWidgets.QVBoxLayout(self.exportContent)
        self.exportContentLayout.setContentsMargins(0, 0, 0, 0)
        self.exportContentLayout.setObjectName("exportContentLayout")
        self.exportSectionLayout.addWidget(self.exportContent)
        self.runPageContentLayout.addWidget(self.trainsetExportSection)
        self.runPageScroll.setWidget(self.runPageContent)
        self.pageLayout.addWidget(self.runPageScroll)

        self.retranslateUi(trainsetRunPage)
        QtCore.QMetaObject.connectSlotsByName(trainsetRunPage)

    def retranslateUi(self, trainsetRunPage):
        _translate = QtCore.QCoreApplication.translate
        self.runTitle.setText(_translate("TrainsetRunPage", "Run"))
        self.runDescription.setText(_translate("TrainsetRunPage", "Prepare and execute the local workflow, or export the same reproducible package for Maxwell."))
        self.exportTitle.setText(_translate("TrainsetRunPage", "Export"))
        self.exportDescription.setText(_translate("TrainsetRunPage", "The package manifest and generated job files appear here."))
