"""Hand-maintained Python View for the application shell."""


from PyQt5 import QtCore, QtGui, QtWidgets


class MainWindowView(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1203, 1014)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sideBarScrollArea = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sideBarScrollArea.sizePolicy().hasHeightForWidth())
        self.sideBarScrollArea.setSizePolicy(sizePolicy)
        self.sideBarScrollArea.setMinimumSize(QtCore.QSize(150, 0))
        self.sideBarScrollArea.setMaximumSize(QtCore.QSize(150, 16777215))
        self.sideBarScrollArea.setWidgetResizable(True)
        self.sideBarScrollArea.setObjectName("sideBarScrollArea")
        self.mainAreaWidgetContents = QtWidgets.QWidget()
        self.mainAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 150, 936))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.mainAreaWidgetContents.setSizePolicy(sizePolicy)
        self.mainAreaWidgetContents.setMinimumSize(QtCore.QSize(150, 0))
        self.mainAreaWidgetContents.setMaximumSize(QtCore.QSize(150, 16777215))
        self.mainAreaWidgetContents.setObjectName("mainAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.mainAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cutAndFittingButton = QtWidgets.QPushButton(self.mainAreaWidgetContents)
        self.cutAndFittingButton.setMinimumSize(QtCore.QSize(0, 60))
        self.cutAndFittingButton.setObjectName("cutAndFittingButton")
        self.verticalLayout.addWidget(self.cutAndFittingButton)
        self.gisaxsPredictButton = QtWidgets.QPushButton(self.mainAreaWidgetContents)
        self.gisaxsPredictButton.setMinimumSize(QtCore.QSize(0, 60))
        self.gisaxsPredictButton.setObjectName("gisaxsPredictButton")
        self.verticalLayout.addWidget(self.gisaxsPredictButton)
        self.trainsetBuildButton = QtWidgets.QPushButton(self.mainAreaWidgetContents)
        self.trainsetBuildButton.setMinimumSize(QtCore.QSize(0, 60))
        self.trainsetBuildButton.setObjectName("trainsetBuildButton")
        self.verticalLayout.addWidget(self.trainsetBuildButton)
        self.ClassficationButton = QtWidgets.QPushButton(self.mainAreaWidgetContents)
        self.ClassficationButton.setMinimumSize(QtCore.QSize(0, 60))
        self.ClassficationButton.setObjectName("ClassficationButton")
        self.verticalLayout.addWidget(self.ClassficationButton)
        self.WAXSButton = QtWidgets.QPushButton(self.mainAreaWidgetContents)
        self.WAXSButton.setMinimumSize(QtCore.QSize(0, 60))
        self.WAXSButton.setObjectName("WAXSButton")
        self.verticalLayout.addWidget(self.WAXSButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.sideBarScrollArea.setWidget(self.mainAreaWidgetContents)
        self.horizontalLayout.addWidget(self.sideBarScrollArea)
        self.mainContentWidget = QtWidgets.QWidget(self.centralwidget)
        self.mainContentWidget.setStyleSheet("QWidget#mainContentWidget {\n"
"    border: 0.5px solid black;\n"
"}")
        self.mainContentWidget.setObjectName("mainContentWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.mainContentWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.mainWindowWidget = QtWidgets.QStackedWidget(self.mainContentWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainWindowWidget.sizePolicy().hasHeightForWidth())
        self.mainWindowWidget.setSizePolicy(sizePolicy)
        self.mainWindowWidget.setObjectName("mainWindowWidget")
        self.trainsetBuildPage = QtWidgets.QWidget()
        self.trainsetBuildPage.setObjectName("trainsetBuildPage")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.trainsetBuildPage)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.mainWindowWidget.addWidget(self.trainsetBuildPage)
        self.gisaxsPredictPageHost = QtWidgets.QWidget()
        self.gisaxsPredictPageHost.setObjectName("gisaxsPredictPageHost")
        self.mainWindowWidget.addWidget(self.gisaxsPredictPageHost)
        self.gisaxsFittingPageHost = QtWidgets.QWidget()
        self.gisaxsFittingPageHost.setObjectName("gisaxsFittingPageHost")
        self.mainWindowWidget.addWidget(self.gisaxsFittingPageHost)
        self.classificationPage = QtWidgets.QWidget()
        self.classificationPage.setObjectName("classificationPage")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.classificationPage)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.mainWindowWidget.addWidget(self.classificationPage)
        self.waxsPageHost = QtWidgets.QWidget()
        self.waxsPageHost.setObjectName("waxsPageHost")
        self.mainWindowWidget.addWidget(self.waxsPageHost)
        self.verticalLayout_2.addWidget(self.mainWindowWidget)
        self.horizontalLayout.addWidget(self.mainContentWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1203, 21))
        self.menubar.setObjectName("menubar")
        self.menuSetting = QtWidgets.QMenu(self.menubar)
        self.menuSetting.setObjectName("menuSetting")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionDisplay = QtWidgets.QAction(MainWindow)
        self.actionDisplay.setObjectName("actionDisplay")
        self.menuSetting.addAction(self.actionDisplay)
        self.menubar.addAction(self.menuSetting.menuAction())

        self.retranslateUi(MainWindow)
        self.mainWindowWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.cutAndFittingButton, self.gisaxsPredictButton)
        MainWindow.setTabOrder(self.gisaxsPredictButton, self.trainsetBuildButton)
        MainWindow.setTabOrder(self.trainsetBuildButton, self.ClassficationButton)
        MainWindow.setTabOrder(self.ClassficationButton, self.WAXSButton)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GIMaP"))
        self.cutAndFittingButton.setText(_translate("MainWindow", "Cut &&  Fitting"))
        self.gisaxsPredictButton.setText(_translate("MainWindow", "GIMaP Predict"))
        self.trainsetBuildButton.setText(_translate("MainWindow", "Trainset Build"))
        self.ClassficationButton.setText(_translate("MainWindow", "Classification"))
        self.WAXSButton.setText(_translate("MainWindow", "WAXS"))
        self.menuSetting.setTitle(_translate("MainWindow", "Setting"))
        self.actionDisplay.setText(_translate("MainWindow", "Display"))
