"""Hand-maintained Python View for display settings."""


from PyQt5 import QtCore, QtGui, QtWidgets


class SettingsDialogView(object):
    def setupUi(self, SettingsDialog):
        SettingsDialog.setObjectName("SettingsDialog")
        SettingsDialog.setMinimumSize(QtCore.QSize(500, 420))
        self.dialog_layout = QtWidgets.QVBoxLayout(SettingsDialog)
        self.dialog_layout.setContentsMargins(12, 12, 12, 12)
        self.dialog_layout.setSpacing(10)
        self.dialog_layout.setObjectName("dialog_layout")
        self.scroll_area = QtWidgets.QScrollArea(SettingsDialog)
        self.scroll_area.setWidgetResizable(True)
        self.scroll_area.setObjectName("scroll_area")
        self.displaySettingsContent = QtWidgets.QWidget()
        self.displaySettingsContent.setObjectName("displaySettingsContent")
        self.content_layout = QtWidgets.QVBoxLayout(self.displaySettingsContent)
        self.content_layout.setContentsMargins(4, 4, 4, 4)
        self.content_layout.setSpacing(12)
        self.content_layout.setObjectName("content_layout")
        self.summary_card = QtWidgets.QFrame(self.displaySettingsContent)
        self.summary_card.setProperty("card", True)
        self.summary_card.setObjectName("summary_card")
        self.summary_layout = QtWidgets.QFormLayout(self.summary_card)
        self.summary_layout.setContentsMargins(14, 12, 14, 12)
        self.summary_layout.setHorizontalSpacing(14)
        self.summary_layout.setVerticalSpacing(8)
        self.summary_layout.setObjectName("summary_layout")
        self.summary_title = QtWidgets.QLabel(self.summary_card)
        self.summary_title.setProperty("cardTitle", True)
        self.summary_title.setObjectName("summary_title")
        self.summary_layout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.summary_title)
        self.screen_name_caption = QtWidgets.QLabel(self.summary_card)
        self.screen_name_caption.setObjectName("screen_name_caption")
        self.summary_layout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.screen_name_caption)
        self.screen_name_label = QtWidgets.QLabel(self.summary_card)
        self.screen_name_label.setText("")
        self.screen_name_label.setProperty("cardBody", True)
        self.screen_name_label.setObjectName("screen_name_label")
        self.summary_layout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.screen_name_label)
        self.logical_size_caption = QtWidgets.QLabel(self.summary_card)
        self.logical_size_caption.setObjectName("logical_size_caption")
        self.summary_layout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.logical_size_caption)
        self.logical_size_label = QtWidgets.QLabel(self.summary_card)
        self.logical_size_label.setText("")
        self.logical_size_label.setProperty("cardBody", True)
        self.logical_size_label.setObjectName("logical_size_label")
        self.summary_layout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.logical_size_label)
        self.dpr_caption = QtWidgets.QLabel(self.summary_card)
        self.dpr_caption.setObjectName("dpr_caption")
        self.summary_layout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.dpr_caption)
        self.dpr_label = QtWidgets.QLabel(self.summary_card)
        self.dpr_label.setText("")
        self.dpr_label.setProperty("cardBody", True)
        self.dpr_label.setObjectName("dpr_label")
        self.summary_layout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.dpr_label)
        self.physical_size_caption = QtWidgets.QLabel(self.summary_card)
        self.physical_size_caption.setObjectName("physical_size_caption")
        self.summary_layout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.physical_size_caption)
        self.physical_size_label = QtWidgets.QLabel(self.summary_card)
        self.physical_size_label.setText("")
        self.physical_size_label.setProperty("cardBody", True)
        self.physical_size_label.setObjectName("physical_size_label")
        self.summary_layout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.physical_size_label)
        self.scaling_caption = QtWidgets.QLabel(self.summary_card)
        self.scaling_caption.setObjectName("scaling_caption")
        self.summary_layout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.scaling_caption)
        self.scaling_label = QtWidgets.QLabel(self.summary_card)
        self.scaling_label.setText("")
        self.scaling_label.setProperty("cardBody", True)
        self.scaling_label.setObjectName("scaling_label")
        self.summary_layout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.scaling_label)
        self.actual_screen_caption = QtWidgets.QLabel(self.summary_card)
        self.actual_screen_caption.setObjectName("actual_screen_caption")
        self.summary_layout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.actual_screen_caption)
        self.actual_screen_label = QtWidgets.QLabel(self.summary_card)
        self.actual_screen_label.setText("")
        self.actual_screen_label.setProperty("cardBody", True)
        self.actual_screen_label.setObjectName("actual_screen_label")
        self.summary_layout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.actual_screen_label)
        self.layout_target_caption = QtWidgets.QLabel(self.summary_card)
        self.layout_target_caption.setObjectName("layout_target_caption")
        self.summary_layout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.layout_target_caption)
        self.layout_target_label = QtWidgets.QLabel(self.summary_card)
        self.layout_target_label.setText("")
        self.layout_target_label.setProperty("cardBody", True)
        self.layout_target_label.setObjectName("layout_target_label")
        self.summary_layout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.layout_target_label)
        self.effective_scale_caption = QtWidgets.QLabel(self.summary_card)
        self.effective_scale_caption.setObjectName("effective_scale_caption")
        self.summary_layout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.effective_scale_caption)
        self.effective_scale_label = QtWidgets.QLabel(self.summary_card)
        self.effective_scale_label.setText("")
        self.effective_scale_label.setProperty("cardBody", True)
        self.effective_scale_label.setObjectName("effective_scale_label")
        self.summary_layout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.effective_scale_label)
        self.profile_caption = QtWidgets.QLabel(self.summary_card)
        self.profile_caption.setObjectName("profile_caption")
        self.summary_layout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.profile_caption)
        self.profile_label = QtWidgets.QLabel(self.summary_card)
        self.profile_label.setText("")
        self.profile_label.setProperty("cardBody", True)
        self.profile_label.setObjectName("profile_label")
        self.summary_layout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.profile_label)
        self.warning_label = QtWidgets.QLabel(self.summary_card)
        self.warning_label.setStyleSheet("color: #b45309;")
        self.warning_label.setText("")
        self.warning_label.setWordWrap(True)
        self.warning_label.setObjectName("warning_label")
        self.summary_layout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.warning_label)
        self.content_layout.addWidget(self.summary_card)
        self.scale_group = QtWidgets.QGroupBox(self.displaySettingsContent)
        self.scale_group.setObjectName("scale_group")
        self.scale_form = QtWidgets.QFormLayout(self.scale_group)
        self.scale_form.setHorizontalSpacing(14)
        self.scale_form.setVerticalSpacing(10)
        self.scale_form.setObjectName("scale_form")
        self.ui_scale_caption = QtWidgets.QLabel(self.scale_group)
        self.ui_scale_caption.setObjectName("ui_scale_caption")
        self.scale_form.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.ui_scale_caption)
        self.scale_row = QtWidgets.QHBoxLayout()
        self.scale_row.setObjectName("scale_row")
        self.ui_scale_slider = QtWidgets.QSlider(self.scale_group)
        self.ui_scale_slider.setMinimum(40)
        self.ui_scale_slider.setMaximum(140)
        self.ui_scale_slider.setSingleStep(5)
        self.ui_scale_slider.setPageStep(10)
        self.ui_scale_slider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.ui_scale_slider.setTickInterval(10)
        self.ui_scale_slider.setOrientation(QtCore.Qt.Horizontal)
        self.ui_scale_slider.setObjectName("ui_scale_slider")
        self.scale_row.addWidget(self.ui_scale_slider)
        self.ui_scale_label = QtWidgets.QLabel(self.scale_group)
        self.ui_scale_label.setMinimumSize(QtCore.QSize(48, 0))
        self.ui_scale_label.setText("")
        self.ui_scale_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ui_scale_label.setObjectName("ui_scale_label")
        self.scale_row.addWidget(self.ui_scale_label)
        self.scale_form.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.scale_row)
        self.content_layout.addWidget(self.scale_group)
        self.layout_group = QtWidgets.QGroupBox(self.displaySettingsContent)
        self.layout_group.setObjectName("layout_group")
        self.layout_form = QtWidgets.QFormLayout(self.layout_group)
        self.layout_form.setHorizontalSpacing(14)
        self.layout_form.setVerticalSpacing(10)
        self.layout_form.setObjectName("layout_form")
        self.auto_dpi_cb = QtWidgets.QCheckBox(self.layout_group)
        self.auto_dpi_cb.setObjectName("auto_dpi_cb")
        self.layout_form.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.auto_dpi_cb)
        self.adaptive_layout_cb = QtWidgets.QCheckBox(self.layout_group)
        self.adaptive_layout_cb.setObjectName("adaptive_layout_cb")
        self.layout_form.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.adaptive_layout_cb)
        self.layout_target_caption_2 = QtWidgets.QLabel(self.layout_group)
        self.layout_target_caption_2.setObjectName("layout_target_caption_2")
        self.layout_form.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.layout_target_caption_2)
        self.layout_target_combo = QtWidgets.QComboBox(self.layout_group)
        self.layout_target_combo.setObjectName("layout_target_combo")
        self.layout_form.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.layout_target_combo)
        self.custom_target_caption = QtWidgets.QLabel(self.layout_group)
        self.custom_target_caption.setObjectName("custom_target_caption")
        self.layout_form.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.custom_target_caption)
        self.custom_target_combo = QtWidgets.QComboBox(self.layout_group)
        self.custom_target_combo.setEditable(True)
        self.custom_target_combo.setObjectName("custom_target_combo")
        self.layout_form.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.custom_target_combo)
        self.auto_fit_cb = QtWidgets.QCheckBox(self.layout_group)
        self.auto_fit_cb.setObjectName("auto_fit_cb")
        self.layout_form.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.auto_fit_cb)
        self.override_caption = QtWidgets.QLabel(self.layout_group)
        self.override_caption.setObjectName("override_caption")
        self.layout_form.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.override_caption)
        self.override_combo = QtWidgets.QComboBox(self.layout_group)
        self.override_combo.setObjectName("override_combo")
        self.layout_form.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.override_combo)
        self.content_layout.addWidget(self.layout_group)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.content_layout.addItem(spacerItem)
        self.scroll_area.setWidget(self.displaySettingsContent)
        self.dialog_layout.addWidget(self.scroll_area)
        self.button_row = QtWidgets.QHBoxLayout()
        self.button_row.setObjectName("button_row")
        self.apply_button = QtWidgets.QPushButton(SettingsDialog)
        self.apply_button.setMinimumSize(QtCore.QSize(0, 32))
        self.apply_button.setObjectName("apply_button")
        self.button_row.addWidget(self.apply_button)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.button_row.addItem(spacerItem1)
        self.cancel_button = QtWidgets.QPushButton(SettingsDialog)
        self.cancel_button.setMinimumSize(QtCore.QSize(0, 32))
        self.cancel_button.setObjectName("cancel_button")
        self.button_row.addWidget(self.cancel_button)
        self.ok_button = QtWidgets.QPushButton(SettingsDialog)
        self.ok_button.setMinimumSize(QtCore.QSize(0, 32))
        self.ok_button.setDefault(True)
        self.ok_button.setObjectName("ok_button")
        self.button_row.addWidget(self.ok_button)
        self.dialog_layout.addLayout(self.button_row)

        self.retranslateUi(SettingsDialog)
        QtCore.QMetaObject.connectSlotsByName(SettingsDialog)

    def retranslateUi(self, SettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        SettingsDialog.setWindowTitle(_translate("SettingsDialog", "Display Settings"))
        self.summary_title.setText(_translate("SettingsDialog", "Display Settings"))
        self.screen_name_caption.setText(_translate("SettingsDialog", "Current screen:"))
        self.logical_size_caption.setText(_translate("SettingsDialog", "Logical size:"))
        self.dpr_caption.setText(_translate("SettingsDialog", "Device pixel ratio:"))
        self.physical_size_caption.setText(_translate("SettingsDialog", "Estimated physical size:"))
        self.scaling_caption.setText(_translate("SettingsDialog", "Windows scaling estimate:"))
        self.actual_screen_caption.setText(_translate("SettingsDialog", "Actual screen:"))
        self.layout_target_caption.setText(_translate("SettingsDialog", "Layout target:"))
        self.effective_scale_caption.setText(_translate("SettingsDialog", "Effective UI scale:"))
        self.profile_caption.setText(_translate("SettingsDialog", "Current profile:"))
        self.scale_group.setTitle(_translate("SettingsDialog", "UI Scale"))
        self.ui_scale_caption.setText(_translate("SettingsDialog", "UI Scale:"))
        self.layout_group.setTitle(_translate("SettingsDialog", "Adaptive Layout"))
        self.auto_dpi_cb.setText(_translate("SettingsDialog", "Auto detect monitor DPI"))
        self.adaptive_layout_cb.setText(_translate("SettingsDialog", "Adaptive layout"))
        self.layout_target_caption_2.setText(_translate("SettingsDialog", "Layout target:"))
        self.custom_target_caption.setText(_translate("SettingsDialog", "Custom target:"))
        self.auto_fit_cb.setText(_translate("SettingsDialog", "Auto-fit layout target to current screen"))
        self.override_caption.setText(_translate("SettingsDialog", "Advanced override:"))
        self.apply_button.setText(_translate("SettingsDialog", "Apply"))
        self.cancel_button.setText(_translate("SettingsDialog", "Cancel"))
        self.ok_button.setText(_translate("SettingsDialog", "OK"))
