"""Build the Fitting fit scaffold section."""

from PyQt5 import QtCore, QtWidgets


class FitScaffoldMixin:
    """Own the Fitting fit scaffold widgets."""

    def _setup_fit_scaffold(self):
        self.fitBox = QtWidgets.QGroupBox(self.gisaxsFittingPageScrollAreaWidgetContents)
        self.fitBox.setMinimumSize(QtCore.QSize(1000, 0))
        self.fitBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.fitBox.setStyleSheet("QGroupBox {\n    font-weight: bold;\n}")
        self.fitBox.setObjectName("fitBox")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.fitBox)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.fitImport1dFileValue = QtWidgets.QLineEdit(self.fitBox)
        self.fitImport1dFileValue.setMinimumSize(QtCore.QSize(0, 20))
        self.fitImport1dFileValue.setObjectName("fitImport1dFileValue")
        self.gridLayout_24.addWidget(self.fitImport1dFileValue, 1, 1, 1, 2)
        self.fitMethodWidget_2 = QtWidgets.QWidget(self.fitBox)
        self.fitMethodWidget_2.setMinimumSize(QtCore.QSize(0, 100))
        self.fitMethodWidget_2.setObjectName("fitMethodWidget_2")
        self.gridLayout_39 = QtWidgets.QGridLayout(self.fitMethodWidget_2)
        self.gridLayout_39.setObjectName("gridLayout_39")
        self.fitKValue = QtWidgets.QDoubleSpinBox(self.fitMethodWidget_2)
        self.fitKValue.setMinimumSize(QtCore.QSize(0, 20))
        self.fitKValue.setObjectName("fitKValue")
        self.gridLayout_39.addWidget(self.fitKValue, 1, 1, 1, 1)
        self.fitKLabel = QtWidgets.QLabel(self.fitMethodWidget_2)
        self.fitKLabel.setMinimumSize(QtCore.QSize(0, 20))
        self.fitKLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.fitKLabel.setObjectName("fitKLabel")
        self.gridLayout_39.addWidget(self.fitKLabel, 1, 0, 1, 1)
        self.FittingManualFittingButton = QtWidgets.QPushButton(self.fitMethodWidget_2)
        self.FittingManualFittingButton.setMinimumSize(QtCore.QSize(50, 20))
        self.FittingManualFittingButton.setObjectName("FittingManualFittingButton")
        self.gridLayout_39.addWidget(self.FittingManualFittingButton, 2, 0, 1, 2)
        self.fitIntResLabel = QtWidgets.QLabel(self.fitMethodWidget_2)
        self.fitIntResLabel.setObjectName("fitIntResLabel")
        self.gridLayout_39.addWidget(self.fitIntResLabel, 0, 0, 1, 1)
        self.fitIntResValue = QtWidgets.QDoubleSpinBox(self.fitMethodWidget_2)
        self.fitIntResValue.setMinimumSize(QtCore.QSize(0, 20))
        self.fitIntResValue.setObjectName("fitIntResValue")
        self.gridLayout_39.addWidget(self.fitIntResValue, 0, 1, 1, 1)
        self.gridLayout_24.addWidget(self.fitMethodWidget_2, 5, 0, 1, 1)
        self.fitImport1dFileButton = QtWidgets.QPushButton(self.fitBox)
        self.fitImport1dFileButton.setMinimumSize(QtCore.QSize(50, 20))
        self.fitImport1dFileButton.setObjectName("fitImport1dFileButton")
        self.gridLayout_24.addWidget(self.fitImport1dFileButton, 1, 0, 1, 1)
        self.fitCurrentDataCheckBox = QtWidgets.QCheckBox(self.fitBox)
        self.fitCurrentDataCheckBox.setMinimumSize(QtCore.QSize(0, 20))
        self.fitCurrentDataCheckBox.setObjectName("fitCurrentDataCheckBox")
        self.gridLayout_24.addWidget(self.fitCurrentDataCheckBox, 0, 0, 1, 1)
        self.widget = QtWidgets.QWidget(self.fitBox)
        self.widget.setObjectName("widget")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.fitLogXCheckBox = QtWidgets.QCheckBox(self.widget)
        self.fitLogXCheckBox.setMinimumSize(QtCore.QSize(0, 20))
        self.fitLogXCheckBox.setObjectName("fitLogXCheckBox")
        self.horizontalLayout_13.addWidget(self.fitLogXCheckBox)
        self.fitLogYCheckBox = QtWidgets.QCheckBox(self.widget)
        self.fitLogYCheckBox.setMinimumSize(QtCore.QSize(0, 20))
        self.fitLogYCheckBox.setObjectName("fitLogYCheckBox")
        self.horizontalLayout_13.addWidget(self.fitLogYCheckBox)
        self.fitNormCheckBox = QtWidgets.QCheckBox(self.widget)
        self.fitNormCheckBox.setMinimumSize(QtCore.QSize(0, 20))
        self.fitNormCheckBox.setObjectName("fitNormCheckBox")
        self.horizontalLayout_13.addWidget(self.fitNormCheckBox)
        self.FittingExportButton = QtWidgets.QPushButton(self.widget)
        self.FittingExportButton.setMinimumSize(QtCore.QSize(50, 0))
        self.FittingExportButton.setObjectName("FittingExportButton")
        self.horizontalLayout_13.addWidget(self.FittingExportButton)
        self.gridLayout_24.addWidget(self.widget, 0, 1, 1, 2)
        self.widget_7 = QtWidgets.QWidget(self.fitBox)
        self.widget_7.setMinimumSize(QtCore.QSize(0, 400))
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.scrollArea = QtWidgets.QScrollArea(self.widget_7)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 762, 363))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
