"""Build the Fitting input section section."""

from PyQt5 import QtCore, QtWidgets


class InputSectionMixin:
    """Own the Fitting input section widgets."""

    def _setup_input_section(self):
        self.gisaxsInputBox.setMinimumSize(QtCore.QSize(0, 0))
        self.gisaxsInputBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gisaxsInputBox.setStyleSheet("QGroupBox {\n    font-weight: bold;\n}")
        self.gisaxsInputBox.setObjectName("gisaxsInputBox")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.gisaxsInputBox)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.gisaxsInputCutLineLabel = QtWidgets.QLabel(self.gisaxsInputBox)
        self.gisaxsInputCutLineLabel.setMinimumSize(QtCore.QSize(0, 20))
        self.gisaxsInputCutLineLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        self.gisaxsInputCutLineLabel.setObjectName("gisaxsInputCutLineLabel")
        self.gridLayout_23.addWidget(self.gisaxsInputCutLineLabel, 4, 0, 1, 1)
        self.gisaxsInputColorScaleLabel = QtWidgets.QLabel(self.gisaxsInputBox)
        self.gisaxsInputColorScaleLabel.setMinimumSize(QtCore.QSize(0, 20))
        self.gisaxsInputColorScaleLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        self.gisaxsInputColorScaleLabel.setObjectName("gisaxsInputColorScaleLabel")
        self.gridLayout_23.addWidget(self.gisaxsInputColorScaleLabel, 2, 0, 1, 1)
        self.gisaxsInputImportButton = QtWidgets.QPushButton(self.gisaxsInputBox)
        self.gisaxsInputImportButton.setMinimumSize(QtCore.QSize(50, 0))
        self.gisaxsInputImportButton.setObjectName("gisaxsInputImportButton")
        self.gridLayout_23.addWidget(self.gisaxsInputImportButton, 0, 0, 1, 1)
        self.gisaxsInputCenterAutoFindingButton = QtWidgets.QPushButton(self.gisaxsInputBox)
        self.gisaxsInputCenterAutoFindingButton.setMinimumSize(QtCore.QSize(50, 20))
        self.gisaxsInputCenterAutoFindingButton.setObjectName("gisaxsInputCenterAutoFindingButton")
        self.gridLayout_23.addWidget(self.gisaxsInputCenterAutoFindingButton, 6, 4, 1, 1)
        self.gisaxsInputVminLabel = QtWidgets.QLabel(self.gisaxsInputBox)
        self.gisaxsInputVminLabel.setObjectName("gisaxsInputVminLabel")
        self.gridLayout_23.addWidget(self.gisaxsInputVminLabel, 3, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.gisaxsInputStackWidget = QtWidgets.QWidget(self.gisaxsInputBox)
        self.gisaxsInputStackWidget.setMinimumSize(QtCore.QSize(0, 40))
        self.gisaxsInputStackWidget.setObjectName("gisaxsInputStackWidget")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.gisaxsInputStackWidget)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.gisaxsInputStackValue = QtWidgets.QLineEdit(self.gisaxsInputStackWidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gisaxsInputStackValue.sizePolicy().hasHeightForWidth())
        self.gisaxsInputStackValue.setSizePolicy(sizePolicy)
        self.gisaxsInputStackValue.setMinimumSize(QtCore.QSize(0, 20))
        self.gisaxsInputStackValue.setMaximumSize(QtCore.QSize(50, 16777215))
        self.gisaxsInputStackValue.setObjectName("gisaxsInputStackValue")
        self.horizontalLayout_11.addWidget(self.gisaxsInputStackValue)
        self.gisaxsInputStackDisplayLabel = QtWidgets.QLabel(self.gisaxsInputStackWidget)
        self.gisaxsInputStackDisplayLabel.setMinimumSize(QtCore.QSize(0, 25))
        self.gisaxsInputStackDisplayLabel.setText("")
        self.gisaxsInputStackDisplayLabel.setObjectName("gisaxsInputStackDisplayLabel")
        self.horizontalLayout_11.addWidget(self.gisaxsInputStackDisplayLabel)
        self.gridLayout_23.addWidget(self.gisaxsInputStackWidget, 1, 2, 1, 3)
        self.gisaxsInputGraphicsView = QtWidgets.QGraphicsView(self.gisaxsInputBox)
        self.gisaxsInputGraphicsView.setMaximumSize(QtCore.QSize(300, 16777215))
        self.gisaxsInputGraphicsView.setStyleSheet(
            "QGraphicsView {\n"
            "    background: transparent;\n"
            "    border: 1px solid #888888; \n"
            "    border-radius: 4px;  \n"
            "}"
        )
        self.gisaxsInputGraphicsView.setObjectName("gisaxsInputGraphicsView")
        self.gridLayout_23.addWidget(self.gisaxsInputGraphicsView, 0, 5, 8, 1)
        self.gisaxsInputCutLineCenterWidget = QtWidgets.QWidget(self.gisaxsInputBox)
        self.gisaxsInputCutLineCenterWidget.setObjectName("gisaxsInputCutLineCenterWidget")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.gisaxsInputCutLineCenterWidget)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.gisaxsInputCenterVerticalLabel = QtWidgets.QLabel(self.gisaxsInputCutLineCenterWidget)
        self.gisaxsInputCenterVerticalLabel.setMinimumSize(QtCore.QSize(0, 20))
        self.gisaxsInputCenterVerticalLabel.setObjectName("gisaxsInputCenterVerticalLabel")
        self.horizontalLayout_10.addWidget(
            self.gisaxsInputCenterVerticalLabel, 0, QtCore.Qt.AlignHCenter
        )
        self.gisaxsInputCenterVerticalValue = QtWidgets.QDoubleSpinBox(
            self.gisaxsInputCutLineCenterWidget
        )
        self.gisaxsInputCenterVerticalValue.setMinimumSize(QtCore.QSize(0, 20))
        self.gisaxsInputCenterVerticalValue.setObjectName("gisaxsInputCenterVerticalValue")
        self.horizontalLayout_10.addWidget(self.gisaxsInputCenterVerticalValue)
        self.gisaxsInputCenterParallelLabel = QtWidgets.QLabel(self.gisaxsInputCutLineCenterWidget)
        self.gisaxsInputCenterParallelLabel.setMinimumSize(QtCore.QSize(0, 20))
        self.gisaxsInputCenterParallelLabel.setObjectName("gisaxsInputCenterParallelLabel")
        self.horizontalLayout_10.addWidget(
            self.gisaxsInputCenterParallelLabel, 0, QtCore.Qt.AlignHCenter
        )
        self.gisaxsInputCenterParallelValue = QtWidgets.QDoubleSpinBox(
            self.gisaxsInputCutLineCenterWidget
        )
        self.gisaxsInputCenterParallelValue.setMinimumSize(QtCore.QSize(0, 20))
        self.gisaxsInputCenterParallelValue.setObjectName("gisaxsInputCenterParallelValue")
        self.horizontalLayout_10.addWidget(self.gisaxsInputCenterParallelValue)
        self.gridLayout_23.addWidget(self.gisaxsInputCutLineCenterWidget, 6, 2, 1, 2)
        self.gisaxsInputCutLineParallelValue = QtWidgets.QDoubleSpinBox(self.gisaxsInputBox)
        self.gisaxsInputCutLineParallelValue.setMinimumSize(QtCore.QSize(0, 20))
        self.gisaxsInputCutLineParallelValue.setObjectName("gisaxsInputCutLineParallelValue")
        self.gridLayout_23.addWidget(self.gisaxsInputCutLineParallelValue, 5, 4, 1, 1)
        self.gisaxsInputCutLineVerticalValue = QtWidgets.QDoubleSpinBox(self.gisaxsInputBox)
        self.gisaxsInputCutLineVerticalValue.setMinimumSize(QtCore.QSize(0, 20))
        self.gisaxsInputCutLineVerticalValue.setObjectName("gisaxsInputCutLineVerticalValue")
        self.gridLayout_23.addWidget(self.gisaxsInputCutLineVerticalValue, 5, 2, 1, 1)
        self.gisaxsInputVmaxValue = QtWidgets.QDoubleSpinBox(self.gisaxsInputBox)
        self.gisaxsInputVmaxValue.setMinimumSize(QtCore.QSize(0, 20))
        self.gisaxsInputVmaxValue.setObjectName("gisaxsInputVmaxValue")
        self.gridLayout_23.addWidget(self.gisaxsInputVmaxValue, 3, 4, 1, 1)
        self.gisaxsInputVminValue = QtWidgets.QDoubleSpinBox(self.gisaxsInputBox)
        self.gisaxsInputVminValue.setMinimumSize(QtCore.QSize(0, 20))
        self.gisaxsInputVminValue.setObjectName("gisaxsInputVminValue")
        self.gridLayout_23.addWidget(self.gisaxsInputVminValue, 3, 2, 1, 1)
        self.gisaxsInputColorScaleWidget = QtWidgets.QWidget(self.gisaxsInputBox)
        self.gisaxsInputColorScaleWidget.setMinimumSize(QtCore.QSize(0, 40))
        self.gisaxsInputColorScaleWidget.setObjectName("gisaxsInputColorScaleWidget")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.gisaxsInputColorScaleWidget)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.gisaxsInputAutoScaleCheckBox = QtWidgets.QCheckBox(self.gisaxsInputColorScaleWidget)
        self.gisaxsInputAutoScaleCheckBox.setMinimumSize(QtCore.QSize(0, 20))
        self.gisaxsInputAutoScaleCheckBox.setChecked(True)
        self.gisaxsInputAutoScaleCheckBox.setObjectName("gisaxsInputAutoScaleCheckBox")
        self.horizontalLayout_12.addWidget(self.gisaxsInputAutoScaleCheckBox)
        self.gisaxsInputIntLogCheckBox = QtWidgets.QCheckBox(self.gisaxsInputColorScaleWidget)
        self.gisaxsInputIntLogCheckBox.setMinimumSize(QtCore.QSize(0, 20))
        self.gisaxsInputIntLogCheckBox.setChecked(True)
        self.gisaxsInputIntLogCheckBox.setObjectName("gisaxsInputIntLogCheckBox")
        self.horizontalLayout_12.addWidget(self.gisaxsInputIntLogCheckBox)
        self.gisaxsInputAutoShowCheckBox = QtWidgets.QCheckBox(self.gisaxsInputColorScaleWidget)
        self.gisaxsInputAutoShowCheckBox.setMinimumSize(QtCore.QSize(0, 20))
        self.gisaxsInputAutoShowCheckBox.setObjectName("gisaxsInputAutoShowCheckBox")
        self.horizontalLayout_12.addWidget(self.gisaxsInputAutoShowCheckBox)
        self.gisaxsInputShowButton = QtWidgets.QPushButton(self.gisaxsInputColorScaleWidget)
        self.gisaxsInputShowButton.setMinimumSize(QtCore.QSize(50, 25))
        self.gisaxsInputShowButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.gisaxsInputShowButton.setObjectName("gisaxsInputShowButton")
        self.horizontalLayout_12.addWidget(self.gisaxsInputShowButton)
        self.gridLayout_23.addWidget(self.gisaxsInputColorScaleWidget, 2, 2, 1, 3)
        self.gisaxsInputCutButton = QtWidgets.QPushButton(self.gisaxsInputBox)
        self.gisaxsInputCutButton.setMinimumSize(QtCore.QSize(50, 0))
        self.gisaxsInputCutButton.setObjectName("gisaxsInputCutButton")
        self.gridLayout_23.addWidget(self.gisaxsInputCutButton, 7, 2, 1, 1)
        self.gisaxsInputImportButtonValue = QtWidgets.QLineEdit(self.gisaxsInputBox)
        self.gisaxsInputImportButtonValue.setMinimumSize(QtCore.QSize(0, 20))
        self.gisaxsInputImportButtonValue.setObjectName("gisaxsInputImportButtonValue")
        self.gridLayout_23.addWidget(self.gisaxsInputImportButtonValue, 0, 2, 1, 3)
        self.gisaxsInputVmaxLabel = QtWidgets.QLabel(self.gisaxsInputBox)
        self.gisaxsInputVmaxLabel.setObjectName("gisaxsInputVmaxLabel")
        self.gridLayout_23.addWidget(self.gisaxsInputVmaxLabel, 3, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.gisaxsInputCutLineVerticalLabel = QtWidgets.QLabel(self.gisaxsInputBox)
        self.gisaxsInputCutLineVerticalLabel.setObjectName("gisaxsInputCutLineVerticalLabel")
        self.gridLayout_23.addWidget(
            self.gisaxsInputCutLineVerticalLabel, 5, 0, 1, 1, QtCore.Qt.AlignHCenter
        )
        self.gisaxsInputCutLineParallelLabel = QtWidgets.QLabel(self.gisaxsInputBox)
        self.gisaxsInputCutLineParallelLabel.setObjectName("gisaxsInputCutLineParallelLabel")
        self.gridLayout_23.addWidget(
            self.gisaxsInputCutLineParallelLabel, 5, 3, 1, 1, QtCore.Qt.AlignHCenter
        )
        self.gisaxsInputCenterLabel = QtWidgets.QLabel(self.gisaxsInputBox)
        self.gisaxsInputCenterLabel.setObjectName("gisaxsInputCenterLabel")
        self.gridLayout_23.addWidget(self.gisaxsInputCenterLabel, 6, 0, 1, 1)
        self.gisaxsInputDetectorParaButton = QtWidgets.QPushButton(self.gisaxsInputBox)
        self.gisaxsInputDetectorParaButton.setMinimumSize(QtCore.QSize(50, 0))
        self.gisaxsInputDetectorParaButton.setObjectName("gisaxsInputDetectorParaButton")
        self.gridLayout_23.addWidget(self.gisaxsInputDetectorParaButton, 7, 0, 1, 1)
        self.gisaxsInputModelCombox = QtWidgets.QComboBox(self.gisaxsInputBox)
        self.gisaxsInputModelCombox.setObjectName("gisaxsInputModelCombox")
        self.gisaxsInputModelCombox.addItem("")
        self.gisaxsInputModelCombox.addItem("")
        self.gisaxsInputModelCombox.addItem("")
        self.gridLayout_23.addWidget(self.gisaxsInputModelCombox, 1, 0, 1, 1)
        self.gridLayout_38.addWidget(self.gisaxsInputBox, 0, 0, 1, 1)
