"""Build the Fitting particle three section."""

from PyQt5 import QtCore, QtWidgets


class ParticleThreeMixin:
    """Own the Fitting particle three widgets."""

    def _setup_particle_three(self):
        self.fitParticleWidget_3 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.fitParticleWidget_3.setMinimumSize(QtCore.QSize(230, 300))
        self.fitParticleWidget_3.setStyleSheet(
            "#fitParticleWidget_3 {\n"
            "  border: 1px solid rgba(0,0,0,0.12);  /* 细外框 */\n"
            "  border-radius: 12px;                 /* 圆角大小可改 */\n"
            "  padding: 8px;                        /* 让内容不贴边 */\n"
            "  /* 伪“阴影”：用浅色外描边模拟（Qt 没有 box-shadow） */\n"
            "  outline: 6px solid rgba(0,0,0,0.03);\n"
            "  outline-offset: -6px;                /* 紧贴边缘 */\n"
            "}"
        )
        self.fitParticleWidget_3.setObjectName("fitParticleWidget_3")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.fitParticleWidget_3)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.fitParticleShapeCombox_3 = QtWidgets.QComboBox(self.fitParticleWidget_3)
        self.fitParticleShapeCombox_3.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleShapeCombox_3.setObjectName("fitParticleShapeCombox_3")
        self.fitParticleShapeCombox_3.addItem("")
        self.fitParticleShapeCombox_3.addItem("")
        self.fitParticleShapeCombox_3.addItem("")
        self.verticalLayout_22.addWidget(self.fitParticleShapeCombox_3)
        self.fitParticleStackWidget_3 = QtWidgets.QStackedWidget(self.fitParticleWidget_3)
        self.fitParticleStackWidget_3.setObjectName("fitParticleStackWidget_3")
        self.fitParticleSpherePage_3 = QtWidgets.QWidget()
        self.fitParticleSpherePage_3.setObjectName("fitParticleSpherePage_3")
        self.gridLayout_29 = QtWidgets.QGridLayout(self.fitParticleSpherePage_3)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.fitParticleSphereRValue_3 = QtWidgets.QDoubleSpinBox(self.fitParticleSpherePage_3)
        self.fitParticleSphereRValue_3.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleSphereRValue_3.setObjectName("fitParticleSphereRValue_3")
        self.gridLayout_29.addWidget(self.fitParticleSphereRValue_3, 1, 1, 1, 1)
        self.fitParticleSphereBGValue_3 = QtWidgets.QDoubleSpinBox(self.fitParticleSpherePage_3)
        self.fitParticleSphereBGValue_3.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleSphereBGValue_3.setObjectName("fitParticleSphereBGValue_3")
        self.gridLayout_29.addWidget(self.fitParticleSphereBGValue_3, 5, 1, 1, 1)
        self.fitParticleSphereRLabel_3 = QtWidgets.QLabel(self.fitParticleSpherePage_3)
        self.fitParticleSphereRLabel_3.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleSphereRLabel_3.setObjectName("fitParticleSphereRLabel_3")
        self.gridLayout_29.addWidget(self.fitParticleSphereRLabel_3, 1, 0, 1, 1)
        self.fitParticleSphereSigmaDValue_3 = QtWidgets.QDoubleSpinBox(self.fitParticleSpherePage_3)
        self.fitParticleSphereSigmaDValue_3.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleSphereSigmaDValue_3.setObjectName("fitParticleSphereSigmaDValue_3")
        self.gridLayout_29.addWidget(self.fitParticleSphereSigmaDValue_3, 4, 1, 1, 1)
        self.fitParticleSphereIntValue_3 = QtWidgets.QDoubleSpinBox(self.fitParticleSpherePage_3)
        self.fitParticleSphereIntValue_3.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleSphereIntValue_3.setObjectName("fitParticleSphereIntValue_3")
        self.gridLayout_29.addWidget(self.fitParticleSphereIntValue_3, 0, 1, 1, 1)
        self.fitParticleSphereSigmaRValue_3 = QtWidgets.QDoubleSpinBox(self.fitParticleSpherePage_3)
        self.fitParticleSphereSigmaRValue_3.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleSphereSigmaRValue_3.setObjectName("fitParticleSphereSigmaRValue_3")
        self.gridLayout_29.addWidget(self.fitParticleSphereSigmaRValue_3, 2, 1, 1, 1)
        self.fitParticleSphereIntLabel_3 = QtWidgets.QLabel(self.fitParticleSpherePage_3)
        self.fitParticleSphereIntLabel_3.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleSphereIntLabel_3.setObjectName("fitParticleSphereIntLabel_3")
        self.gridLayout_29.addWidget(self.fitParticleSphereIntLabel_3, 0, 0, 1, 1)
        self.fitParticleSphereDValue_3 = QtWidgets.QDoubleSpinBox(self.fitParticleSpherePage_3)
        self.fitParticleSphereDValue_3.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleSphereDValue_3.setObjectName("fitParticleSphereDValue_3")
        self.gridLayout_29.addWidget(self.fitParticleSphereDValue_3, 3, 1, 1, 1)
        self.fitParticleSphereSigmaDLabel_3 = QtWidgets.QLabel(self.fitParticleSpherePage_3)
        self.fitParticleSphereSigmaDLabel_3.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleSphereSigmaDLabel_3.setObjectName("fitParticleSphereSigmaDLabel_3")
        self.gridLayout_29.addWidget(self.fitParticleSphereSigmaDLabel_3, 4, 0, 1, 1)
        self.fitParticleSphereSigmaRLabel_3 = QtWidgets.QLabel(self.fitParticleSpherePage_3)
        self.fitParticleSphereSigmaRLabel_3.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleSphereSigmaRLabel_3.setObjectName("fitParticleSphereSigmaRLabel_3")
        self.gridLayout_29.addWidget(self.fitParticleSphereSigmaRLabel_3, 2, 0, 1, 1)
        self.fitParticleSphereDLabel_3 = QtWidgets.QLabel(self.fitParticleSpherePage_3)
        self.fitParticleSphereDLabel_3.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleSphereDLabel_3.setObjectName("fitParticleSphereDLabel_3")
        self.gridLayout_29.addWidget(self.fitParticleSphereDLabel_3, 3, 0, 1, 1)
        self.fitParticleSphereBGLabel_3 = QtWidgets.QLabel(self.fitParticleSpherePage_3)
        self.fitParticleSphereBGLabel_3.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleSphereBGLabel_3.setObjectName("fitParticleSphereBGLabel_3")
        self.gridLayout_29.addWidget(self.fitParticleSphereBGLabel_3, 5, 0, 1, 1)
        self.fitParticleStackWidget_3.addWidget(self.fitParticleSpherePage_3)
        self.fitParticleCylinderPage_3 = QtWidgets.QWidget()
        self.fitParticleCylinderPage_3.setObjectName("fitParticleCylinderPage_3")
        self.gridLayout_30 = QtWidgets.QGridLayout(self.fitParticleCylinderPage_3)
        self.gridLayout_30.setObjectName("gridLayout_30")
        self.fitParticleCylinderSigmaRLabel_3 = QtWidgets.QLabel(self.fitParticleCylinderPage_3)
        self.fitParticleCylinderSigmaRLabel_3.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderSigmaRLabel_3.setObjectName("fitParticleCylinderSigmaRLabel_3")
        self.gridLayout_30.addWidget(self.fitParticleCylinderSigmaRLabel_3, 2, 0, 1, 1)
        self.fitParticleCylinderBGLabel_3 = QtWidgets.QLabel(self.fitParticleCylinderPage_3)
        self.fitParticleCylinderBGLabel_3.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderBGLabel_3.setObjectName("fitParticleCylinderBGLabel_3")
        self.gridLayout_30.addWidget(self.fitParticleCylinderBGLabel_3, 9, 0, 1, 1)
        self.fitParticleCylinderSigmahValue_3 = QtWidgets.QDoubleSpinBox(
            self.fitParticleCylinderPage_3
        )
        self.fitParticleCylinderSigmahValue_3.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderSigmahValue_3.setObjectName("fitParticleCylinderSigmahValue_3")
        self.gridLayout_30.addWidget(self.fitParticleCylinderSigmahValue_3, 4, 1, 1, 1)
        self.fitParticleCylinderDValue_3 = QtWidgets.QDoubleSpinBox(self.fitParticleCylinderPage_3)
        self.fitParticleCylinderDValue_3.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderDValue_3.setObjectName("fitParticleCylinderDValue_3")
        self.gridLayout_30.addWidget(self.fitParticleCylinderDValue_3, 7, 1, 1, 1)
        self.fitParticleCylinderBGValue_3 = QtWidgets.QDoubleSpinBox(self.fitParticleCylinderPage_3)
        self.fitParticleCylinderBGValue_3.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderBGValue_3.setObjectName("fitParticleCylinderBGValue_3")
        self.gridLayout_30.addWidget(self.fitParticleCylinderBGValue_3, 9, 1, 1, 1)
        self.fitParticleCylinderRValue_3 = QtWidgets.QDoubleSpinBox(self.fitParticleCylinderPage_3)
        self.fitParticleCylinderRValue_3.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderRValue_3.setObjectName("fitParticleCylinderRValue_3")
        self.gridLayout_30.addWidget(self.fitParticleCylinderRValue_3, 1, 1, 1, 1)
        self.fitParticleCylinderIntValue_3 = QtWidgets.QDoubleSpinBox(
            self.fitParticleCylinderPage_3
        )
        self.fitParticleCylinderIntValue_3.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderIntValue_3.setObjectName("fitParticleCylinderIntValue_3")
        self.gridLayout_30.addWidget(self.fitParticleCylinderIntValue_3, 0, 1, 1, 1)
        self.fitParticleCylinderIntLabel_3 = QtWidgets.QLabel(self.fitParticleCylinderPage_3)
        self.fitParticleCylinderIntLabel_3.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderIntLabel_3.setObjectName("fitParticleCylinderIntLabel_3")
        self.gridLayout_30.addWidget(self.fitParticleCylinderIntLabel_3, 0, 0, 1, 1)
        self.fitParticleCylinderRLabel_3 = QtWidgets.QLabel(self.fitParticleCylinderPage_3)
        self.fitParticleCylinderRLabel_3.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderRLabel_3.setObjectName("fitParticleCylinderRLabel_3")
        self.gridLayout_30.addWidget(self.fitParticleCylinderRLabel_3, 1, 0, 1, 1)
        self.fitParticleCylinderhLabel_3 = QtWidgets.QLabel(self.fitParticleCylinderPage_3)
        self.fitParticleCylinderhLabel_3.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderhLabel_3.setObjectName("fitParticleCylinderhLabel_3")
        self.gridLayout_30.addWidget(self.fitParticleCylinderhLabel_3, 3, 0, 1, 1)
        self.fitParticleCylinderSigmahLabel_3 = QtWidgets.QLabel(self.fitParticleCylinderPage_3)
        self.fitParticleCylinderSigmahLabel_3.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderSigmahLabel_3.setObjectName("fitParticleCylinderSigmahLabel_3")
        self.gridLayout_30.addWidget(self.fitParticleCylinderSigmahLabel_3, 4, 0, 1, 1)
        self.fitParticleCylinderSigmaDLabel_3 = QtWidgets.QLabel(self.fitParticleCylinderPage_3)
        self.fitParticleCylinderSigmaDLabel_3.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderSigmaDLabel_3.setObjectName("fitParticleCylinderSigmaDLabel_3")
        self.gridLayout_30.addWidget(self.fitParticleCylinderSigmaDLabel_3, 8, 0, 1, 1)
        self.fitParticleCylinderSigmaRValue_3 = QtWidgets.QDoubleSpinBox(
            self.fitParticleCylinderPage_3
        )
        self.fitParticleCylinderSigmaRValue_3.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderSigmaRValue_3.setObjectName("fitParticleCylinderSigmaRValue_3")
        self.gridLayout_30.addWidget(self.fitParticleCylinderSigmaRValue_3, 2, 1, 1, 1)
        self.fitParticleCylinderSigmaDValue_3 = QtWidgets.QDoubleSpinBox(
            self.fitParticleCylinderPage_3
        )
        self.fitParticleCylinderSigmaDValue_3.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderSigmaDValue_3.setObjectName("fitParticleCylinderSigmaDValue_3")
        self.gridLayout_30.addWidget(self.fitParticleCylinderSigmaDValue_3, 8, 1, 1, 1)
        self.fitParticleCylinderDLabel_3 = QtWidgets.QLabel(self.fitParticleCylinderPage_3)
        self.fitParticleCylinderDLabel_3.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderDLabel_3.setObjectName("fitParticleCylinderDLabel_3")
        self.gridLayout_30.addWidget(self.fitParticleCylinderDLabel_3, 7, 0, 1, 1)
        self.fitParticleCylinderhValue_3 = QtWidgets.QDoubleSpinBox(self.fitParticleCylinderPage_3)
        self.fitParticleCylinderhValue_3.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderhValue_3.setObjectName("fitParticleCylinderhValue_3")
        self.gridLayout_30.addWidget(self.fitParticleCylinderhValue_3, 3, 1, 1, 1)
        self.fitParticleStackWidget_3.addWidget(self.fitParticleCylinderPage_3)
        self.verticalLayout_22.addWidget(self.fitParticleStackWidget_3)
        self.horizontalLayout_18.addWidget(self.fitParticleWidget_3)
