"""Build the Fitting particle two section."""

from PyQt5 import QtCore, QtWidgets


class ParticleTwoMixin:
    """Own the Fitting particle two widgets."""

    def _setup_particle_two(self):
        self.fitParticleWidget_2 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.fitParticleWidget_2.setMinimumSize(QtCore.QSize(230, 300))
        self.fitParticleWidget_2.setStyleSheet(
            "#fitParticleWidget_2 {\n"
            "  border: 1px solid rgba(0,0,0,0.12);  /* 细外框 */\n"
            "  border-radius: 12px;                 /* 圆角大小可改 */\n"
            "  padding: 8px;                        /* 让内容不贴边 */\n"
            "  /* 伪“阴影”：用浅色外描边模拟（Qt 没有 box-shadow） */\n"
            "  outline: 6px solid rgba(0,0,0,0.03);\n"
            "  outline-offset: -6px;                /* 紧贴边缘 */\n"
            "}"
        )
        self.fitParticleWidget_2.setObjectName("fitParticleWidget_2")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.fitParticleWidget_2)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.fitParticleShapeCombox_2 = QtWidgets.QComboBox(self.fitParticleWidget_2)
        self.fitParticleShapeCombox_2.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleShapeCombox_2.setObjectName("fitParticleShapeCombox_2")
        self.fitParticleShapeCombox_2.addItem("")
        self.fitParticleShapeCombox_2.addItem("")
        self.fitParticleShapeCombox_2.addItem("")
        self.verticalLayout_21.addWidget(self.fitParticleShapeCombox_2)
        self.fitParticleStackWidget_2 = QtWidgets.QStackedWidget(self.fitParticleWidget_2)
        self.fitParticleStackWidget_2.setMinimumSize(QtCore.QSize(0, 0))
        self.fitParticleStackWidget_2.setObjectName("fitParticleStackWidget_2")
        self.fitParticleSpherePage_2 = QtWidgets.QWidget()
        self.fitParticleSpherePage_2.setObjectName("fitParticleSpherePage_2")
        self.gridLayout_27 = QtWidgets.QGridLayout(self.fitParticleSpherePage_2)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.fitParticleSphereDLabel_2 = QtWidgets.QLabel(self.fitParticleSpherePage_2)
        self.fitParticleSphereDLabel_2.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleSphereDLabel_2.setObjectName("fitParticleSphereDLabel_2")
        self.gridLayout_27.addWidget(self.fitParticleSphereDLabel_2, 3, 0, 1, 1)
        self.fitParticleSphereDValue_2 = QtWidgets.QDoubleSpinBox(self.fitParticleSpherePage_2)
        self.fitParticleSphereDValue_2.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleSphereDValue_2.setObjectName("fitParticleSphereDValue_2")
        self.gridLayout_27.addWidget(self.fitParticleSphereDValue_2, 3, 1, 1, 1)
        self.fitParticleSphereSigmaDLabel_2 = QtWidgets.QLabel(self.fitParticleSpherePage_2)
        self.fitParticleSphereSigmaDLabel_2.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleSphereSigmaDLabel_2.setObjectName("fitParticleSphereSigmaDLabel_2")
        self.gridLayout_27.addWidget(self.fitParticleSphereSigmaDLabel_2, 4, 0, 1, 1)
        self.fitParticleSphereRLabel_2 = QtWidgets.QLabel(self.fitParticleSpherePage_2)
        self.fitParticleSphereRLabel_2.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleSphereRLabel_2.setObjectName("fitParticleSphereRLabel_2")
        self.gridLayout_27.addWidget(self.fitParticleSphereRLabel_2, 1, 0, 1, 1)
        self.fitParticleSphereBGValue_2 = QtWidgets.QDoubleSpinBox(self.fitParticleSpherePage_2)
        self.fitParticleSphereBGValue_2.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleSphereBGValue_2.setObjectName("fitParticleSphereBGValue_2")
        self.gridLayout_27.addWidget(self.fitParticleSphereBGValue_2, 5, 1, 1, 1)
        self.fitParticleSphereIntValue_2 = QtWidgets.QDoubleSpinBox(self.fitParticleSpherePage_2)
        self.fitParticleSphereIntValue_2.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleSphereIntValue_2.setObjectName("fitParticleSphereIntValue_2")
        self.gridLayout_27.addWidget(self.fitParticleSphereIntValue_2, 0, 1, 1, 1)
        self.fitParticleSphereSigmaRValue_2 = QtWidgets.QDoubleSpinBox(self.fitParticleSpherePage_2)
        self.fitParticleSphereSigmaRValue_2.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleSphereSigmaRValue_2.setObjectName("fitParticleSphereSigmaRValue_2")
        self.gridLayout_27.addWidget(self.fitParticleSphereSigmaRValue_2, 2, 1, 1, 1)
        self.fitParticleSphereSigmaRLabel_2 = QtWidgets.QLabel(self.fitParticleSpherePage_2)
        self.fitParticleSphereSigmaRLabel_2.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleSphereSigmaRLabel_2.setObjectName("fitParticleSphereSigmaRLabel_2")
        self.gridLayout_27.addWidget(self.fitParticleSphereSigmaRLabel_2, 2, 0, 1, 1)
        self.fitParticleSphereIntLabel_2 = QtWidgets.QLabel(self.fitParticleSpherePage_2)
        self.fitParticleSphereIntLabel_2.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleSphereIntLabel_2.setObjectName("fitParticleSphereIntLabel_2")
        self.gridLayout_27.addWidget(self.fitParticleSphereIntLabel_2, 0, 0, 1, 1)
        self.fitParticleSphereBGLabel_2 = QtWidgets.QLabel(self.fitParticleSpherePage_2)
        self.fitParticleSphereBGLabel_2.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleSphereBGLabel_2.setObjectName("fitParticleSphereBGLabel_2")
        self.gridLayout_27.addWidget(self.fitParticleSphereBGLabel_2, 5, 0, 1, 1)
        self.fitParticleSphereSigmaDValue_2 = QtWidgets.QDoubleSpinBox(self.fitParticleSpherePage_2)
        self.fitParticleSphereSigmaDValue_2.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleSphereSigmaDValue_2.setObjectName("fitParticleSphereSigmaDValue_2")
        self.gridLayout_27.addWidget(self.fitParticleSphereSigmaDValue_2, 4, 1, 1, 1)
        self.fitParticleSphereRValue_2 = QtWidgets.QDoubleSpinBox(self.fitParticleSpherePage_2)
        self.fitParticleSphereRValue_2.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleSphereRValue_2.setObjectName("fitParticleSphereRValue_2")
        self.gridLayout_27.addWidget(self.fitParticleSphereRValue_2, 1, 1, 1, 1)
        self.fitParticleStackWidget_2.addWidget(self.fitParticleSpherePage_2)
        self.fitParticleCylinderPage_2 = QtWidgets.QWidget()
        self.fitParticleCylinderPage_2.setObjectName("fitParticleCylinderPage_2")
        self.gridLayout_28 = QtWidgets.QGridLayout(self.fitParticleCylinderPage_2)
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.fitParticleCylinderRLabel_2 = QtWidgets.QLabel(self.fitParticleCylinderPage_2)
        self.fitParticleCylinderRLabel_2.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderRLabel_2.setObjectName("fitParticleCylinderRLabel_2")
        self.gridLayout_28.addWidget(self.fitParticleCylinderRLabel_2, 1, 0, 1, 1)
        self.fitParticleCylinderhValue_2 = QtWidgets.QDoubleSpinBox(self.fitParticleCylinderPage_2)
        self.fitParticleCylinderhValue_2.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderhValue_2.setObjectName("fitParticleCylinderhValue_2")
        self.gridLayout_28.addWidget(self.fitParticleCylinderhValue_2, 3, 1, 1, 1)
        self.fitParticleCylinderRValue_2 = QtWidgets.QDoubleSpinBox(self.fitParticleCylinderPage_2)
        self.fitParticleCylinderRValue_2.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderRValue_2.setObjectName("fitParticleCylinderRValue_2")
        self.gridLayout_28.addWidget(self.fitParticleCylinderRValue_2, 1, 1, 1, 1)
        self.fitParticleCylinderIntLabel_2 = QtWidgets.QLabel(self.fitParticleCylinderPage_2)
        self.fitParticleCylinderIntLabel_2.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderIntLabel_2.setObjectName("fitParticleCylinderIntLabel_2")
        self.gridLayout_28.addWidget(self.fitParticleCylinderIntLabel_2, 0, 0, 1, 1)
        self.fitParticleCylinderIntValue_2 = QtWidgets.QDoubleSpinBox(
            self.fitParticleCylinderPage_2
        )
        self.fitParticleCylinderIntValue_2.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderIntValue_2.setObjectName("fitParticleCylinderIntValue_2")
        self.gridLayout_28.addWidget(self.fitParticleCylinderIntValue_2, 0, 1, 1, 1)
        self.fitParticleCylinderSigmaDLabel_2 = QtWidgets.QLabel(self.fitParticleCylinderPage_2)
        self.fitParticleCylinderSigmaDLabel_2.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderSigmaDLabel_2.setObjectName("fitParticleCylinderSigmaDLabel_2")
        self.gridLayout_28.addWidget(self.fitParticleCylinderSigmaDLabel_2, 8, 0, 1, 1)
        self.fitParticleCylinderSigmaRValue_2 = QtWidgets.QDoubleSpinBox(
            self.fitParticleCylinderPage_2
        )
        self.fitParticleCylinderSigmaRValue_2.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderSigmaRValue_2.setObjectName("fitParticleCylinderSigmaRValue_2")
        self.gridLayout_28.addWidget(self.fitParticleCylinderSigmaRValue_2, 2, 1, 1, 1)
        self.fitParticleCylinderSigmaDValue_2 = QtWidgets.QDoubleSpinBox(
            self.fitParticleCylinderPage_2
        )
        self.fitParticleCylinderSigmaDValue_2.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderSigmaDValue_2.setObjectName("fitParticleCylinderSigmaDValue_2")
        self.gridLayout_28.addWidget(self.fitParticleCylinderSigmaDValue_2, 8, 1, 1, 1)
        self.fitParticleCylinderDLabel_2 = QtWidgets.QLabel(self.fitParticleCylinderPage_2)
        self.fitParticleCylinderDLabel_2.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderDLabel_2.setObjectName("fitParticleCylinderDLabel_2")
        self.gridLayout_28.addWidget(self.fitParticleCylinderDLabel_2, 7, 0, 1, 1)
        self.fitParticleCylinderSigmahValue_2 = QtWidgets.QDoubleSpinBox(
            self.fitParticleCylinderPage_2
        )
        self.fitParticleCylinderSigmahValue_2.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderSigmahValue_2.setObjectName("fitParticleCylinderSigmahValue_2")
        self.gridLayout_28.addWidget(self.fitParticleCylinderSigmahValue_2, 4, 1, 1, 1)
        self.fitParticleCylinderSigmahLabel_2 = QtWidgets.QLabel(self.fitParticleCylinderPage_2)
        self.fitParticleCylinderSigmahLabel_2.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderSigmahLabel_2.setObjectName("fitParticleCylinderSigmahLabel_2")
        self.gridLayout_28.addWidget(self.fitParticleCylinderSigmahLabel_2, 4, 0, 1, 1)
        self.fitParticleCylinderSigmaRLabel_2 = QtWidgets.QLabel(self.fitParticleCylinderPage_2)
        self.fitParticleCylinderSigmaRLabel_2.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderSigmaRLabel_2.setObjectName("fitParticleCylinderSigmaRLabel_2")
        self.gridLayout_28.addWidget(self.fitParticleCylinderSigmaRLabel_2, 2, 0, 1, 1)
        self.fitParticleCylinderDValue_2 = QtWidgets.QDoubleSpinBox(self.fitParticleCylinderPage_2)
        self.fitParticleCylinderDValue_2.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderDValue_2.setObjectName("fitParticleCylinderDValue_2")
        self.gridLayout_28.addWidget(self.fitParticleCylinderDValue_2, 7, 1, 1, 1)
        self.fitParticleCylinderhLabel_2 = QtWidgets.QLabel(self.fitParticleCylinderPage_2)
        self.fitParticleCylinderhLabel_2.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderhLabel_2.setObjectName("fitParticleCylinderhLabel_2")
        self.gridLayout_28.addWidget(self.fitParticleCylinderhLabel_2, 3, 0, 1, 1)
        self.fitParticleCylinderBGLabel_2 = QtWidgets.QLabel(self.fitParticleCylinderPage_2)
        self.fitParticleCylinderBGLabel_2.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderBGLabel_2.setObjectName("fitParticleCylinderBGLabel_2")
        self.gridLayout_28.addWidget(self.fitParticleCylinderBGLabel_2, 9, 0, 1, 1)
        self.fitParticleCylinderBGValue_2 = QtWidgets.QDoubleSpinBox(self.fitParticleCylinderPage_2)
        self.fitParticleCylinderBGValue_2.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderBGValue_2.setObjectName("fitParticleCylinderBGValue_2")
        self.gridLayout_28.addWidget(self.fitParticleCylinderBGValue_2, 9, 1, 1, 1)
        self.fitParticleStackWidget_2.addWidget(self.fitParticleCylinderPage_2)
        self.verticalLayout_21.addWidget(self.fitParticleStackWidget_2)
        self.horizontalLayout_18.addWidget(self.fitParticleWidget_2)
