"""Build the Fitting particle one section."""

from PyQt5 import QtCore, QtWidgets


class ParticleOneMixin:
    """Own the Fitting particle one widgets."""

    def _setup_particle_one(self):
        self.fitParticleWidget_1 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.fitParticleWidget_1.setMinimumSize(QtCore.QSize(230, 300))
        self.fitParticleWidget_1.setStyleSheet(
            "#fitParticleWidget_1 {\n"
            "  border: 1px solid rgba(0,0,0,0.12);  /* 细外框 */\n"
            "  border-radius: 12px;                 /* 圆角大小可改 */\n"
            "  padding: 8px;                        /* 让内容不贴边 */\n"
            "  /* 伪“阴影”：用浅色外描边模拟（Qt 没有 box-shadow） */\n"
            "  outline: 6px solid rgba(0,0,0,0.03);\n"
            "  outline-offset: -6px;                /* 紧贴边缘 */\n"
            "}"
        )
        self.fitParticleWidget_1.setObjectName("fitParticleWidget_1")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.fitParticleWidget_1)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.fitParticleShapeCombox_1 = QtWidgets.QComboBox(self.fitParticleWidget_1)
        self.fitParticleShapeCombox_1.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleShapeCombox_1.setObjectName("fitParticleShapeCombox_1")
        self.fitParticleShapeCombox_1.addItem("")
        self.fitParticleShapeCombox_1.addItem("")
        self.fitParticleShapeCombox_1.addItem("")
        self.verticalLayout_20.addWidget(self.fitParticleShapeCombox_1)
        self.fitParticleStackWidget_1 = QtWidgets.QStackedWidget(self.fitParticleWidget_1)
        self.fitParticleStackWidget_1.setObjectName("fitParticleStackWidget_1")
        self.fitParticleSpherePage_1 = QtWidgets.QWidget()
        self.fitParticleSpherePage_1.setObjectName("fitParticleSpherePage_1")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.fitParticleSpherePage_1)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.fitParticleSphereDLabel_1 = QtWidgets.QLabel(self.fitParticleSpherePage_1)
        self.fitParticleSphereDLabel_1.setObjectName("fitParticleSphereDLabel_1")
        self.gridLayout_25.addWidget(self.fitParticleSphereDLabel_1, 3, 0, 1, 1)
        self.fitParticleSphereDValue_1 = QtWidgets.QDoubleSpinBox(self.fitParticleSpherePage_1)
        self.fitParticleSphereDValue_1.setObjectName("fitParticleSphereDValue_1")
        self.gridLayout_25.addWidget(self.fitParticleSphereDValue_1, 3, 1, 1, 1)
        self.fitParticleSphereIntValue_1 = QtWidgets.QDoubleSpinBox(self.fitParticleSpherePage_1)
        self.fitParticleSphereIntValue_1.setObjectName("fitParticleSphereIntValue_1")
        self.gridLayout_25.addWidget(self.fitParticleSphereIntValue_1, 0, 1, 1, 1)
        self.fitParticleSphereSigmaRValue_1 = QtWidgets.QDoubleSpinBox(self.fitParticleSpherePage_1)
        self.fitParticleSphereSigmaRValue_1.setObjectName("fitParticleSphereSigmaRValue_1")
        self.gridLayout_25.addWidget(self.fitParticleSphereSigmaRValue_1, 2, 1, 1, 1)
        self.fitParticleSphereRValue_1 = QtWidgets.QDoubleSpinBox(self.fitParticleSpherePage_1)
        self.fitParticleSphereRValue_1.setObjectName("fitParticleSphereRValue_1")
        self.gridLayout_25.addWidget(self.fitParticleSphereRValue_1, 1, 1, 1, 1)
        self.fitParticleSphereBGValue_1 = QtWidgets.QDoubleSpinBox(self.fitParticleSpherePage_1)
        self.fitParticleSphereBGValue_1.setObjectName("fitParticleSphereBGValue_1")
        self.gridLayout_25.addWidget(self.fitParticleSphereBGValue_1, 5, 1, 1, 1)
        self.fitParticleSphereSigmaDValue_1 = QtWidgets.QDoubleSpinBox(self.fitParticleSpherePage_1)
        self.fitParticleSphereSigmaDValue_1.setObjectName("fitParticleSphereSigmaDValue_1")
        self.gridLayout_25.addWidget(self.fitParticleSphereSigmaDValue_1, 4, 1, 1, 1)
        self.fitParticleSphereSigmaDLabel_1 = QtWidgets.QLabel(self.fitParticleSpherePage_1)
        self.fitParticleSphereSigmaDLabel_1.setObjectName("fitParticleSphereSigmaDLabel_1")
        self.gridLayout_25.addWidget(self.fitParticleSphereSigmaDLabel_1, 4, 0, 1, 1)
        self.fitParticleSphereRLabel_1 = QtWidgets.QLabel(self.fitParticleSpherePage_1)
        self.fitParticleSphereRLabel_1.setObjectName("fitParticleSphereRLabel_1")
        self.gridLayout_25.addWidget(self.fitParticleSphereRLabel_1, 1, 0, 1, 1)
        self.fitParticleSphereBGLabel_1 = QtWidgets.QLabel(self.fitParticleSpherePage_1)
        self.fitParticleSphereBGLabel_1.setObjectName("fitParticleSphereBGLabel_1")
        self.gridLayout_25.addWidget(self.fitParticleSphereBGLabel_1, 5, 0, 1, 1)
        self.fitParticleSphereSigmaRLabel_1 = QtWidgets.QLabel(self.fitParticleSpherePage_1)
        self.fitParticleSphereSigmaRLabel_1.setObjectName("fitParticleSphereSigmaRLabel_1")
        self.gridLayout_25.addWidget(self.fitParticleSphereSigmaRLabel_1, 2, 0, 1, 1)
        self.fitParticleSphereIntLabel_1 = QtWidgets.QLabel(self.fitParticleSpherePage_1)
        self.fitParticleSphereIntLabel_1.setObjectName("fitParticleSphereIntLabel_1")
        self.gridLayout_25.addWidget(self.fitParticleSphereIntLabel_1, 0, 0, 1, 1)
        self.fitParticleStackWidget_1.addWidget(self.fitParticleSpherePage_1)
        self.fitParticleCylinderPage_1 = QtWidgets.QWidget()
        self.fitParticleCylinderPage_1.setObjectName("fitParticleCylinderPage_1")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.fitParticleCylinderPage_1)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.fitParticleCylinderSigmaDLabel_1 = QtWidgets.QLabel(self.fitParticleCylinderPage_1)
        self.fitParticleCylinderSigmaDLabel_1.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderSigmaDLabel_1.setObjectName("fitParticleCylinderSigmaDLabel_1")
        self.gridLayout_26.addWidget(self.fitParticleCylinderSigmaDLabel_1, 8, 0, 1, 1)
        self.fitParticleCylinderRLabel_1 = QtWidgets.QLabel(self.fitParticleCylinderPage_1)
        self.fitParticleCylinderRLabel_1.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderRLabel_1.setObjectName("fitParticleCylinderRLabel_1")
        self.gridLayout_26.addWidget(self.fitParticleCylinderRLabel_1, 1, 0, 1, 1)
        self.fitParticleCylinderRValue_1 = QtWidgets.QDoubleSpinBox(self.fitParticleCylinderPage_1)
        self.fitParticleCylinderRValue_1.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderRValue_1.setObjectName("fitParticleCylinderRValue_1")
        self.gridLayout_26.addWidget(self.fitParticleCylinderRValue_1, 1, 1, 1, 1)
        self.fitParticleCylinderDLabel_1 = QtWidgets.QLabel(self.fitParticleCylinderPage_1)
        self.fitParticleCylinderDLabel_1.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderDLabel_1.setObjectName("fitParticleCylinderDLabel_1")
        self.gridLayout_26.addWidget(self.fitParticleCylinderDLabel_1, 7, 0, 1, 1)
        self.fitParticleCylinderBGValue_1 = QtWidgets.QDoubleSpinBox(self.fitParticleCylinderPage_1)
        self.fitParticleCylinderBGValue_1.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderBGValue_1.setObjectName("fitParticleCylinderBGValue_1")
        self.gridLayout_26.addWidget(self.fitParticleCylinderBGValue_1, 9, 1, 1, 1)
        self.fitParticleCylinderIntLabel_1 = QtWidgets.QLabel(self.fitParticleCylinderPage_1)
        self.fitParticleCylinderIntLabel_1.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderIntLabel_1.setObjectName("fitParticleCylinderIntLabel_1")
        self.gridLayout_26.addWidget(self.fitParticleCylinderIntLabel_1, 0, 0, 1, 1)
        self.fitParticleCylinderSigmahValue_1 = QtWidgets.QDoubleSpinBox(
            self.fitParticleCylinderPage_1
        )
        self.fitParticleCylinderSigmahValue_1.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderSigmahValue_1.setObjectName("fitParticleCylinderSigmahValue_1")
        self.gridLayout_26.addWidget(self.fitParticleCylinderSigmahValue_1, 4, 1, 1, 1)
        self.fitParticleCylinderhLabel_1 = QtWidgets.QLabel(self.fitParticleCylinderPage_1)
        self.fitParticleCylinderhLabel_1.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderhLabel_1.setObjectName("fitParticleCylinderhLabel_1")
        self.gridLayout_26.addWidget(self.fitParticleCylinderhLabel_1, 3, 0, 1, 1)
        self.fitParticleCylinderSigmaRLabel_1 = QtWidgets.QLabel(self.fitParticleCylinderPage_1)
        self.fitParticleCylinderSigmaRLabel_1.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderSigmaRLabel_1.setObjectName("fitParticleCylinderSigmaRLabel_1")
        self.gridLayout_26.addWidget(self.fitParticleCylinderSigmaRLabel_1, 2, 0, 1, 1)
        self.fitParticleCylinderDValue_1 = QtWidgets.QDoubleSpinBox(self.fitParticleCylinderPage_1)
        self.fitParticleCylinderDValue_1.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderDValue_1.setObjectName("fitParticleCylinderDValue_1")
        self.gridLayout_26.addWidget(self.fitParticleCylinderDValue_1, 7, 1, 1, 1)
        self.fitParticleCylinderSigmaRValue_1 = QtWidgets.QDoubleSpinBox(
            self.fitParticleCylinderPage_1
        )
        self.fitParticleCylinderSigmaRValue_1.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderSigmaRValue_1.setObjectName("fitParticleCylinderSigmaRValue_1")
        self.gridLayout_26.addWidget(self.fitParticleCylinderSigmaRValue_1, 2, 1, 1, 1)
        self.fitParticleCylinderSigmaDValue_1 = QtWidgets.QDoubleSpinBox(
            self.fitParticleCylinderPage_1
        )
        self.fitParticleCylinderSigmaDValue_1.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderSigmaDValue_1.setObjectName("fitParticleCylinderSigmaDValue_1")
        self.gridLayout_26.addWidget(self.fitParticleCylinderSigmaDValue_1, 8, 1, 1, 1)
        self.fitParticleCylinderBGLabel_1 = QtWidgets.QLabel(self.fitParticleCylinderPage_1)
        self.fitParticleCylinderBGLabel_1.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderBGLabel_1.setObjectName("fitParticleCylinderBGLabel_1")
        self.gridLayout_26.addWidget(self.fitParticleCylinderBGLabel_1, 9, 0, 1, 1)
        self.fitParticleCylinderhValue_1 = QtWidgets.QDoubleSpinBox(self.fitParticleCylinderPage_1)
        self.fitParticleCylinderhValue_1.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderhValue_1.setObjectName("fitParticleCylinderhValue_1")
        self.gridLayout_26.addWidget(self.fitParticleCylinderhValue_1, 3, 1, 1, 1)
        self.fitParticleCylinderSigmahLabel_1 = QtWidgets.QLabel(self.fitParticleCylinderPage_1)
        self.fitParticleCylinderSigmahLabel_1.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderSigmahLabel_1.setObjectName("fitParticleCylinderSigmahLabel_1")
        self.gridLayout_26.addWidget(self.fitParticleCylinderSigmahLabel_1, 4, 0, 1, 1)
        self.fitParticleCylinderIntValue_1 = QtWidgets.QDoubleSpinBox(
            self.fitParticleCylinderPage_1
        )
        self.fitParticleCylinderIntValue_1.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderIntValue_1.setObjectName("fitParticleCylinderIntValue_1")
        self.gridLayout_26.addWidget(self.fitParticleCylinderIntValue_1, 0, 1, 1, 1)
        self.fitParticleStackWidget_1.addWidget(self.fitParticleCylinderPage_1)
        self.verticalLayout_20.addWidget(self.fitParticleStackWidget_1)
        self.horizontalLayout_18.addWidget(self.fitParticleWidget_1)
