"""Analyze domain: automatic GISAXS/GIWAXS reductions on the canonical geometry."""

from .bad_pixels import BadPixels, find_bad_pixels
from .intensity import describe_intensity_corrections, film_absorption_on, has_intensity_corrections, intensity_factor
from .cake import CakeMap, cake_map
from .preprocess import POLYGON, RECTANGLE, MaskShape, mirror_fill, rasterize
from .regions import CutRegion, default_region_near, region_key, region_outline
from .peak_fit import PROFILES, PeakFit, fit_peak
from .region_pick import PICK_KINDS, RING, SECTOR, SPOT, Peak, Pick, pick_region, region_kind, snap_region
from .binning import BinnedMean, binned_mean, binned_mean_2d, native_profile
from .classification import (
    WIDE_ANGLE_LIMIT_DEG,
    classify_measurement,
    max_scattering_angle_deg,
)
from .gisaxs import (
    GisaxsMaps,
    gisaxs_maps,
    gisaxs_q_map,
    exit_angle_deg_at_row,
    horizontal_cut,
    locate_yoneda,
    reduce_gisaxs,
    vertical_cut,
)
from .corrections import (
    MAX_GAP_GUARD_PX,
    Corrections,
    apply_valid_range,
    guard_invalid,
    subtract_background,
    sum_frames,
)
from .series import (
    SeriesCorrection,
    aligned_distance,
    locate_reference_peak,
    normalization_factor,
)
from .giwaxs import (
    GiwaxsMaps,
    giwaxs_maps,
    q_from_two_theta,
    reduce_giwaxs,
    strongest_ring,
    two_theta_deg,
)
from .models import (
    GISAXS,
    GIWAXS,
    MEASUREMENT_KINDS,
    Curve,
    GisaxsCutSettings,
    GiwaxsSettings,
    QBox,
    ReciprocalSpaceMap,
    Reduction,
    Sector,
    X_AXIS_Q,
    X_AXIS_TWO_THETA,
    YonedaEstimate,
)
from .series_map import PeakTrack, SeriesMap, series_map, stack_curves, track_peak
from .sources import curve_source_mask, source_labels
from .symmetry import SymmetryCenter, symmetric_center_x
from .validity import valid_pixels

__all__ = [
    "PROFILES",
    "PeakFit",
    "fit_peak",
    "PICK_KINDS",
    "Peak",
    "Pick",
    "RING",
    "SECTOR",
    "SPOT",
    "pick_region",
    "region_kind",
    "snap_region",
    "CakeMap",
    "CutRegion",
    "MaskShape",
    "POLYGON",
    "PeakTrack",
    "RECTANGLE",
    "cake_map",
    "default_region_near",
    "mirror_fill",
    "rasterize",
    "region_key",
    "region_outline",
    "track_peak",
    "BadPixels",
    "find_bad_pixels",
    "SeriesMap",
    "series_map",
    "stack_curves",
    "BinnedMean",
    "describe_intensity_corrections",
    "film_absorption_on",
    "has_intensity_corrections",
    "intensity_factor",
    "Corrections",
    "Curve",
    "MAX_GAP_GUARD_PX",
    "SymmetryCenter",
    "curve_source_mask",
    "source_labels",
    "guard_invalid",
    "sum_frames",
    "symmetric_center_x",
    "QBox",
    "Sector",
    "SeriesCorrection",
    "aligned_distance",
    "locate_reference_peak",
    "normalization_factor",
    "X_AXIS_Q",
    "X_AXIS_TWO_THETA",
    "apply_valid_range",
    "q_from_two_theta",
    "subtract_background",
    "two_theta_deg",
    "GISAXS",
    "GIWAXS",
    "GisaxsCutSettings",
    "GiwaxsMaps",
    "GisaxsMaps",
    "gisaxs_maps",
    "gisaxs_q_map",
    "GiwaxsSettings",
    "MEASUREMENT_KINDS",
    "ReciprocalSpaceMap",
    "Reduction",
    "WIDE_ANGLE_LIMIT_DEG",
    "YonedaEstimate",
    "binned_mean",
    "binned_mean_2d",
    "native_profile",
    "classify_measurement",
    "exit_angle_deg_at_row",
    "giwaxs_maps",
    "horizontal_cut",
    "locate_yoneda",
    "max_scattering_angle_deg",
    "reduce_giwaxs",
    "reduce_gisaxs",
    "strongest_ring",
    "valid_pixels",
    "vertical_cut",
]
