name: gimap-trainset
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - scipy
  - h5py
  - pyyaml
  - fabio
  - tensorflow=2.15
  - keras=2.15
  - matplotlib
  - pip
  - pip:
      - BornAgain==24.1
