"""Hand-maintained Python View for detector parameters."""


from PyQt5 import QtCore, QtGui, QtWidgets


class DetectorParametersDialogView(object):
    def setupUi(self, DetectorParametersDialog):
        DetectorParametersDialog.setObjectName("DetectorParametersDialog")
        DetectorParametersDialog.resize(400, 350)
        self.dialog_layout = QtWidgets.QVBoxLayout(DetectorParametersDialog)
        self.dialog_layout.setObjectName("dialog_layout")
        self.main_group = QtWidgets.QGroupBox(DetectorParametersDialog)
        self.main_group.setObjectName("main_group")
        self.main_layout = QtWidgets.QFormLayout(self.main_group)
        self.main_layout.setObjectName("main_layout")
        self.distance_label = QtWidgets.QLabel(self.main_group)
        self.distance_label.setObjectName("distance_label")
        self.main_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.distance_label)
        self.distance_spinbox = QtWidgets.QDoubleSpinBox(self.main_group)
        self.distance_spinbox.setMinimum(100.0)
        self.distance_spinbox.setMaximum(10000.0)
        self.distance_spinbox.setSingleStep(0.1)
        self.distance_spinbox.setProperty("value", 2000.0)
        self.distance_spinbox.setObjectName("distance_spinbox")
        self.main_layout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.distance_spinbox)
        self.angle_label = QtWidgets.QLabel(self.main_group)
        self.angle_label.setObjectName("angle_label")
        self.main_layout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.angle_label)
        self.angle_spinbox = QtWidgets.QDoubleSpinBox(self.main_group)
        self.angle_spinbox.setDecimals(3)
        self.angle_spinbox.setMinimum(0.01)
        self.angle_spinbox.setMaximum(10.0)
        self.angle_spinbox.setSingleStep(0.01)
        self.angle_spinbox.setProperty("value", 0.4)
        self.angle_spinbox.setObjectName("angle_spinbox")
        self.main_layout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.angle_spinbox)
        self.wavelength_label = QtWidgets.QLabel(self.main_group)
        self.wavelength_label.setObjectName("wavelength_label")
        self.main_layout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.wavelength_label)
        self.wavelength_spinbox = QtWidgets.QDoubleSpinBox(self.main_group)
        self.wavelength_spinbox.setDecimals(4)
        self.wavelength_spinbox.setMinimum(0.001)
        self.wavelength_spinbox.setMaximum(1.0)
        self.wavelength_spinbox.setSingleStep(0.001)
        self.wavelength_spinbox.setProperty("value", 0.015)
        self.wavelength_spinbox.setObjectName("wavelength_spinbox")
        self.main_layout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.wavelength_spinbox)
        self.energy_label = QtWidgets.QLabel(self.main_group)
        self.energy_label.setObjectName("energy_label")
        self.main_layout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.energy_label)
        self.energy_spinbox = QtWidgets.QDoubleSpinBox(self.main_group)
        self.energy_spinbox.setDecimals(4)
        self.energy_spinbox.setMinimum(0.1)
        self.energy_spinbox.setMaximum(200.0)
        self.energy_spinbox.setSingleStep(0.01)
        self.energy_spinbox.setProperty("value", 82.6561322666667)
        self.energy_spinbox.setObjectName("energy_spinbox")
        self.main_layout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.energy_spinbox)
        self.energy_relation_label = QtWidgets.QLabel(self.main_group)
        self.energy_relation_label.setStyleSheet("color: #555;")
        self.energy_relation_label.setObjectName("energy_relation_label")
        self.main_layout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.energy_relation_label)
        self.beam_center_x_label = QtWidgets.QLabel(self.main_group)
        self.beam_center_x_label.setObjectName("beam_center_x_label")
        self.main_layout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.beam_center_x_label)
        self.beam_center_x_spinbox = QtWidgets.QDoubleSpinBox(self.main_group)
        self.beam_center_x_spinbox.setDecimals(2)
        self.beam_center_x_spinbox.setMinimum(0.0)
        self.beam_center_x_spinbox.setMaximum(2000.0)
        self.beam_center_x_spinbox.setSingleStep(0.01)
        self.beam_center_x_spinbox.setProperty("value", 50.0)
        self.beam_center_x_spinbox.setObjectName("beam_center_x_spinbox")
        self.main_layout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.beam_center_x_spinbox)
        self.beam_center_y_label = QtWidgets.QLabel(self.main_group)
        self.beam_center_y_label.setObjectName("beam_center_y_label")
        self.main_layout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.beam_center_y_label)
        self.beam_center_y_spinbox = QtWidgets.QDoubleSpinBox(self.main_group)
        self.beam_center_y_spinbox.setDecimals(2)
        self.beam_center_y_spinbox.setMinimum(0.0)
        self.beam_center_y_spinbox.setMaximum(2000.0)
        self.beam_center_y_spinbox.setSingleStep(0.01)
        self.beam_center_y_spinbox.setProperty("value", 50.0)
        self.beam_center_y_spinbox.setObjectName("beam_center_y_spinbox")
        self.main_layout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.beam_center_y_spinbox)
        self.pixel_size_x_label = QtWidgets.QLabel(self.main_group)
        self.pixel_size_x_label.setObjectName("pixel_size_x_label")
        self.main_layout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.pixel_size_x_label)
        self.pixel_size_x_spinbox = QtWidgets.QDoubleSpinBox(self.main_group)
        self.pixel_size_x_spinbox.setDecimals(1)
        self.pixel_size_x_spinbox.setMinimum(1.0)
        self.pixel_size_x_spinbox.setMaximum(1000.0)
        self.pixel_size_x_spinbox.setSingleStep(0.1)
        self.pixel_size_x_spinbox.setProperty("value", 172.0)
        self.pixel_size_x_spinbox.setObjectName("pixel_size_x_spinbox")
        self.main_layout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.pixel_size_x_spinbox)
        self.pixel_size_y_label = QtWidgets.QLabel(self.main_group)
        self.pixel_size_y_label.setObjectName("pixel_size_y_label")
        self.main_layout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.pixel_size_y_label)
        self.pixel_size_y_spinbox = QtWidgets.QDoubleSpinBox(self.main_group)
        self.pixel_size_y_spinbox.setDecimals(1)
        self.pixel_size_y_spinbox.setMinimum(1.0)
        self.pixel_size_y_spinbox.setMaximum(1000.0)
        self.pixel_size_y_spinbox.setSingleStep(0.1)
        self.pixel_size_y_spinbox.setProperty("value", 172.0)
        self.pixel_size_y_spinbox.setObjectName("pixel_size_y_spinbox")
        self.main_layout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.pixel_size_y_spinbox)
        self.dialog_layout.addWidget(self.main_group)
        self.display_group = QtWidgets.QGroupBox(DetectorParametersDialog)
        self.display_group.setObjectName("display_group")
        self.display_layout = QtWidgets.QVBoxLayout(self.display_group)
        self.display_layout.setObjectName("display_layout")
        self.show_q_axis_checkbox = QtWidgets.QCheckBox(self.display_group)
        self.show_q_axis_checkbox.setObjectName("show_q_axis_checkbox")
        self.display_layout.addWidget(self.show_q_axis_checkbox)
        self.dialog_layout.addWidget(self.display_group)
        self.button_layout = QtWidgets.QHBoxLayout()
        self.button_layout.setObjectName("button_layout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.button_layout.addItem(spacerItem)
        self.apply_button = QtWidgets.QPushButton(DetectorParametersDialog)
        self.apply_button.setObjectName("apply_button")
        self.button_layout.addWidget(self.apply_button)
        self.ok_button = QtWidgets.QPushButton(DetectorParametersDialog)
        self.ok_button.setObjectName("ok_button")
        self.button_layout.addWidget(self.ok_button)
        self.cancel_button = QtWidgets.QPushButton(DetectorParametersDialog)
        self.cancel_button.setObjectName("cancel_button")
        self.button_layout.addWidget(self.cancel_button)
        self.dialog_layout.addLayout(self.button_layout)

        self.retranslateUi(DetectorParametersDialog)
        QtCore.QMetaObject.connectSlotsByName(DetectorParametersDialog)

    def retranslateUi(self, DetectorParametersDialog):
        _translate = QtCore.QCoreApplication.translate
        DetectorParametersDialog.setWindowTitle(_translate("DetectorParametersDialog", "Detector Parameters"))
        self.main_group.setTitle(_translate("DetectorParametersDialog", "Detector Parameters"))
        self.distance_label.setText(_translate("DetectorParametersDialog", "Distance (mm):"))
        self.angle_label.setText(_translate("DetectorParametersDialog", "Grazing Angle (deg):"))
        self.wavelength_label.setText(_translate("DetectorParametersDialog", "Wavelength (nm):"))
        self.energy_label.setText(_translate("DetectorParametersDialog", "Energy (keV):"))
        self.energy_relation_label.setText(_translate("DetectorParametersDialog", "E (keV) = 1.239841984 / λ (nm)"))
        self.beam_center_x_label.setText(_translate("DetectorParametersDialog", "Beam Center X (px):"))
        self.beam_center_y_label.setText(_translate("DetectorParametersDialog", "Beam Center Y (px):"))
        self.pixel_size_x_label.setText(_translate("DetectorParametersDialog", "Pixel Size X (μm):"))
        self.pixel_size_y_label.setText(_translate("DetectorParametersDialog", "Pixel Size Y (μm):"))
        self.display_group.setTitle(_translate("DetectorParametersDialog", "Display Options"))
        self.show_q_axis_checkbox.setText(_translate("DetectorParametersDialog", "Show in q axis"))
        self.apply_button.setText(_translate("DetectorParametersDialog", "Apply"))
        self.ok_button.setText(_translate("DetectorParametersDialog", "OK"))
        self.cancel_button.setText(_translate("DetectorParametersDialog", "Cancel"))
