"""Hand-maintained Python View for the Fitting workspace layout."""


from PyQt5 import QtCore, QtWidgets


class FittingWorkspaceView(object):
    def setupUi(self, gisaxsFittingWorkspaceSplitter):
        gisaxsFittingWorkspaceSplitter.setObjectName("gisaxsFittingWorkspaceSplitter")
        gisaxsFittingWorkspaceSplitter.setOrientation(QtCore.Qt.Horizontal)
        gisaxsFittingWorkspaceSplitter.setChildrenCollapsible(False)
        gisaxsFittingWorkspaceSplitter.setHandleWidth(8)
        gisaxsFittingWorkspaceSplitter.setOpaqueResize(True)
        self.gisaxsFittingPageScrollArea = QtWidgets.QScrollArea(gisaxsFittingWorkspaceSplitter)
        self.gisaxsFittingPageScrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.gisaxsFittingPageScrollArea.setWidgetResizable(True)
        self.gisaxsFittingPageScrollArea.setObjectName("gisaxsFittingPageScrollArea")
        self.gisaxsWorkAreaContents = QtWidgets.QWidget()
        self.gisaxsWorkAreaContents.setGeometry(QtCore.QRect(0, 0, 760, 1400))
        self.gisaxsWorkAreaContents.setObjectName("gisaxsWorkAreaContents")
        self.fittingWorkAreaLayout = QtWidgets.QVBoxLayout(self.gisaxsWorkAreaContents)
        self.fittingWorkAreaLayout.setContentsMargins(12, 12, 12, 12)
        self.fittingWorkAreaLayout.setSpacing(8)
        self.fittingWorkAreaLayout.setObjectName("fittingWorkAreaLayout")
        self.gisaxsFixedControlsStack = QtWidgets.QWidget(self.gisaxsWorkAreaContents)
        self.gisaxsFixedControlsStack.setObjectName("gisaxsFixedControlsStack")
        self.fittingFixedControlsLayout = QtWidgets.QVBoxLayout(self.gisaxsFixedControlsStack)
        self.fittingFixedControlsLayout.setContentsMargins(0, 0, 0, 0)
        self.fittingFixedControlsLayout.setSpacing(8)
        self.fittingFixedControlsLayout.setObjectName("fittingFixedControlsLayout")
        self.fittingInputSection = QtWidgets.QFrame(self.gisaxsFixedControlsStack)
        self.fittingInputSection.setProperty("gimapSection", True)
        self.fittingInputSection.setObjectName("fittingInputSection")
        self.fittingInputSectionLayout = QtWidgets.QVBoxLayout(self.fittingInputSection)
        self.fittingInputSectionLayout.setContentsMargins(12, 10, 12, 12)
        self.fittingInputSectionLayout.setSpacing(8)
        self.fittingInputSectionLayout.setObjectName("fittingInputSectionLayout")
        self.fittingInputTitle = QtWidgets.QLabel(self.fittingInputSection)
        self.fittingInputTitle.setProperty("gimapSectionTitle", True)
        self.fittingInputTitle.setObjectName("fittingInputTitle")
        self.fittingInputSectionLayout.addWidget(self.fittingInputTitle)
        self.fittingInputDescription = QtWidgets.QLabel(self.fittingInputSection)
        self.fittingInputDescription.setProperty("gimapSectionDescription", True)
        self.fittingInputDescription.setWordWrap(True)
        self.fittingInputDescription.setObjectName("fittingInputDescription")
        self.fittingInputSectionLayout.addWidget(self.fittingInputDescription)
        self.fittingInputContent = QtWidgets.QWidget(self.fittingInputSection)
        self.fittingInputContent.setObjectName("fittingInputContent")
        self.fittingInputContentLayout = QtWidgets.QVBoxLayout(self.fittingInputContent)
        self.fittingInputContentLayout.setContentsMargins(0, 0, 0, 0)
        self.fittingInputContentLayout.setSpacing(8)
        self.fittingInputContentLayout.setObjectName("fittingInputContentLayout")
        self.fittingInputSectionLayout.addWidget(self.fittingInputContent)
        self.fittingFixedControlsLayout.addWidget(self.fittingInputSection)
        self.fittingConfigureSection = QtWidgets.QFrame(self.gisaxsFixedControlsStack)
        self.fittingConfigureSection.setProperty("gimapSection", True)
        self.fittingConfigureSection.setObjectName("fittingConfigureSection")
        self.fittingConfigureSectionLayout = QtWidgets.QVBoxLayout(self.fittingConfigureSection)
        self.fittingConfigureSectionLayout.setContentsMargins(12, 10, 12, 12)
        self.fittingConfigureSectionLayout.setSpacing(8)
        self.fittingConfigureSectionLayout.setObjectName("fittingConfigureSectionLayout")
        self.fittingConfigureTitle = QtWidgets.QLabel(self.fittingConfigureSection)
        self.fittingConfigureTitle.setProperty("gimapSectionTitle", True)
        self.fittingConfigureTitle.setObjectName("fittingConfigureTitle")
        self.fittingConfigureSectionLayout.addWidget(self.fittingConfigureTitle)
        self.fittingConfigureDescription = QtWidgets.QLabel(self.fittingConfigureSection)
        self.fittingConfigureDescription.setProperty("gimapSectionDescription", True)
        self.fittingConfigureDescription.setWordWrap(True)
        self.fittingConfigureDescription.setObjectName("fittingConfigureDescription")
        self.fittingConfigureSectionLayout.addWidget(self.fittingConfigureDescription)
        self.fittingConfigureContent = QtWidgets.QWidget(self.fittingConfigureSection)
        self.fittingConfigureContent.setObjectName("fittingConfigureContent")
        self.fittingConfigureContentLayout = QtWidgets.QVBoxLayout(self.fittingConfigureContent)
        self.fittingConfigureContentLayout.setContentsMargins(0, 0, 0, 0)
        self.fittingConfigureContentLayout.setSpacing(8)
        self.fittingConfigureContentLayout.setObjectName("fittingConfigureContentLayout")
        self.fittingConfigureSectionLayout.addWidget(self.fittingConfigureContent)
        self.fittingFixedControlsLayout.addWidget(self.fittingConfigureSection)
        self.fittingAdvancedSection = QtWidgets.QFrame(self.gisaxsFixedControlsStack)
        self.fittingAdvancedSection.setProperty("gimapSection", True)
        self.fittingAdvancedSection.setObjectName("fittingAdvancedSection")
        self.fittingAdvancedSectionLayout = QtWidgets.QVBoxLayout(self.fittingAdvancedSection)
        self.fittingAdvancedSectionLayout.setContentsMargins(8, 8, 8, 8)
        self.fittingAdvancedSectionLayout.setSpacing(7)
        self.fittingAdvancedSectionLayout.setObjectName("fittingAdvancedSectionLayout")
        self.fittingAdvancedToggle = QtWidgets.QToolButton(self.fittingAdvancedSection)
        self.fittingAdvancedToggle.setProperty("gimapAdvancedToggle", True)
        self.fittingAdvancedToggle.setCheckable(True)
        self.fittingAdvancedToggle.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.fittingAdvancedToggle.setArrowType(QtCore.Qt.RightArrow)
        self.fittingAdvancedToggle.setObjectName("fittingAdvancedToggle")
        self.fittingAdvancedSectionLayout.addWidget(self.fittingAdvancedToggle)
        self.fittingAdvancedDescription = QtWidgets.QLabel(self.fittingAdvancedSection)
        self.fittingAdvancedDescription.setVisible(False)
        self.fittingAdvancedDescription.setProperty("gimapSectionDescription", True)
        self.fittingAdvancedDescription.setWordWrap(True)
        self.fittingAdvancedDescription.setObjectName("fittingAdvancedDescription")
        self.fittingAdvancedSectionLayout.addWidget(self.fittingAdvancedDescription)
        self.fittingAdvancedContent = QtWidgets.QWidget(self.fittingAdvancedSection)
        self.fittingAdvancedContent.setVisible(False)
        self.fittingAdvancedContent.setObjectName("fittingAdvancedContent")
        self.fittingAdvancedContentLayout = QtWidgets.QVBoxLayout(self.fittingAdvancedContent)
        self.fittingAdvancedContentLayout.setContentsMargins(4, 2, 4, 4)
        self.fittingAdvancedContentLayout.setSpacing(8)
        self.fittingAdvancedContentLayout.setObjectName("fittingAdvancedContentLayout")
        self.fittingAdvancedSectionLayout.addWidget(self.fittingAdvancedContent)
        self.fittingFixedControlsLayout.addWidget(self.fittingAdvancedSection)
        self.fittingRunSection = QtWidgets.QFrame(self.gisaxsFixedControlsStack)
        self.fittingRunSection.setProperty("gimapSection", True)
        self.fittingRunSection.setObjectName("fittingRunSection")
        self.fittingRunSectionLayout = QtWidgets.QVBoxLayout(self.fittingRunSection)
        self.fittingRunSectionLayout.setContentsMargins(12, 10, 12, 12)
        self.fittingRunSectionLayout.setSpacing(8)
        self.fittingRunSectionLayout.setObjectName("fittingRunSectionLayout")
        self.fittingRunTitle = QtWidgets.QLabel(self.fittingRunSection)
        self.fittingRunTitle.setProperty("gimapSectionTitle", True)
        self.fittingRunTitle.setObjectName("fittingRunTitle")
        self.fittingRunSectionLayout.addWidget(self.fittingRunTitle)
        self.fittingRunDescription = QtWidgets.QLabel(self.fittingRunSection)
        self.fittingRunDescription.setProperty("gimapSectionDescription", True)
        self.fittingRunDescription.setWordWrap(True)
        self.fittingRunDescription.setObjectName("fittingRunDescription")
        self.fittingRunSectionLayout.addWidget(self.fittingRunDescription)
        self.fittingRunContent = QtWidgets.QWidget(self.fittingRunSection)
        self.fittingRunContent.setObjectName("fittingRunContent")
        self.fittingRunContentLayout = QtWidgets.QVBoxLayout(self.fittingRunContent)
        self.fittingRunContentLayout.setContentsMargins(0, 0, 0, 0)
        self.fittingRunContentLayout.setSpacing(8)
        self.fittingRunContentLayout.setObjectName("fittingRunContentLayout")
        self.fittingRunSectionLayout.addWidget(self.fittingRunContent)
        self.fittingFixedControlsLayout.addWidget(self.fittingRunSection)
        self.fittingExportSection = QtWidgets.QFrame(self.gisaxsFixedControlsStack)
        self.fittingExportSection.setProperty("gimapSection", True)
        self.fittingExportSection.setObjectName("fittingExportSection")
        self.fittingExportSectionLayout = QtWidgets.QVBoxLayout(self.fittingExportSection)
        self.fittingExportSectionLayout.setContentsMargins(12, 10, 12, 12)
        self.fittingExportSectionLayout.setSpacing(8)
        self.fittingExportSectionLayout.setObjectName("fittingExportSectionLayout")
        self.fittingExportTitle = QtWidgets.QLabel(self.fittingExportSection)
        self.fittingExportTitle.setProperty("gimapSectionTitle", True)
        self.fittingExportTitle.setObjectName("fittingExportTitle")
        self.fittingExportSectionLayout.addWidget(self.fittingExportTitle)
        self.fittingExportDescription = QtWidgets.QLabel(self.fittingExportSection)
        self.fittingExportDescription.setProperty("gimapSectionDescription", True)
        self.fittingExportDescription.setWordWrap(True)
        self.fittingExportDescription.setObjectName("fittingExportDescription")
        self.fittingExportSectionLayout.addWidget(self.fittingExportDescription)
        self.fittingExportContent = QtWidgets.QWidget(self.fittingExportSection)
        self.fittingExportContent.setObjectName("fittingExportContent")
        self.fittingExportContentLayout = QtWidgets.QHBoxLayout(self.fittingExportContent)
        self.fittingExportContentLayout.setContentsMargins(0, 0, 0, 0)
        self.fittingExportContentLayout.setSpacing(8)
        self.fittingExportContentLayout.setObjectName("fittingExportContentLayout")
        self.fittingExportSectionLayout.addWidget(self.fittingExportContent)
        self.fittingFixedControlsLayout.addWidget(self.fittingExportSection)
        self.fittingWorkAreaLayout.addWidget(self.gisaxsFixedControlsStack)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.fittingWorkAreaLayout.addItem(spacerItem)
        self.gisaxsFittingPageScrollArea.setWidget(self.gisaxsWorkAreaContents)
        self.gisaxsPreviewScrollArea = QtWidgets.QScrollArea(gisaxsFittingWorkspaceSplitter)
        self.gisaxsPreviewScrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.gisaxsPreviewScrollArea.setWidgetResizable(True)
        self.gisaxsPreviewScrollArea.setObjectName("gisaxsPreviewScrollArea")
        self.gisaxsRightCollapsiblePanel = QtWidgets.QWidget()
        self.gisaxsRightCollapsiblePanel.setGeometry(QtCore.QRect(0, 0, 520, 1500))
        self.gisaxsRightCollapsiblePanel.setObjectName("gisaxsRightCollapsiblePanel")
        self.fittingPreviewAreaLayout = QtWidgets.QVBoxLayout(self.gisaxsRightCollapsiblePanel)
        self.fittingPreviewAreaLayout.setContentsMargins(12, 12, 12, 12)
        self.fittingPreviewAreaLayout.setSpacing(8)
        self.fittingPreviewAreaLayout.setObjectName("fittingPreviewAreaLayout")
        self.fittingPreviewPanel = QtWidgets.QFrame(self.gisaxsRightCollapsiblePanel)
        self.fittingPreviewPanel.setProperty("gimapSection", True)
        self.fittingPreviewPanel.setObjectName("fittingPreviewPanel")
        self.fittingPreviewPanelLayout = QtWidgets.QVBoxLayout(self.fittingPreviewPanel)
        self.fittingPreviewPanelLayout.setContentsMargins(12, 10, 12, 12)
        self.fittingPreviewPanelLayout.setSpacing(8)
        self.fittingPreviewPanelLayout.setObjectName("fittingPreviewPanelLayout")
        self.fittingPreviewTitle = QtWidgets.QLabel(self.fittingPreviewPanel)
        self.fittingPreviewTitle.setProperty("gimapSectionTitle", True)
        self.fittingPreviewTitle.setObjectName("fittingPreviewTitle")
        self.fittingPreviewPanelLayout.addWidget(self.fittingPreviewTitle)
        self.fittingPreviewDescription = QtWidgets.QLabel(self.fittingPreviewPanel)
        self.fittingPreviewDescription.setProperty("gimapSectionDescription", True)
        self.fittingPreviewDescription.setWordWrap(True)
        self.fittingPreviewDescription.setObjectName("fittingPreviewDescription")
        self.fittingPreviewPanelLayout.addWidget(self.fittingPreviewDescription)
        self.fittingPreviewContent = QtWidgets.QWidget(self.fittingPreviewPanel)
        self.fittingPreviewContent.setObjectName("fittingPreviewContent")
        self.fittingPreviewContentLayout = QtWidgets.QVBoxLayout(self.fittingPreviewContent)
        self.fittingPreviewContentLayout.setContentsMargins(0, 0, 0, 0)
        self.fittingPreviewContentLayout.setSpacing(8)
        self.fittingPreviewContentLayout.setObjectName("fittingPreviewContentLayout")
        self.fittingPreviewPanelLayout.addWidget(self.fittingPreviewContent)
        self.fittingPreviewAreaLayout.addWidget(self.fittingPreviewPanel)
        self.fittingResultsPanel = QtWidgets.QFrame(self.gisaxsRightCollapsiblePanel)
        self.fittingResultsPanel.setProperty("gimapSection", True)
        self.fittingResultsPanel.setObjectName("fittingResultsPanel")
        self.fittingResultsPanelLayout = QtWidgets.QVBoxLayout(self.fittingResultsPanel)
        self.fittingResultsPanelLayout.setContentsMargins(12, 10, 12, 12)
        self.fittingResultsPanelLayout.setSpacing(8)
        self.fittingResultsPanelLayout.setObjectName("fittingResultsPanelLayout")
        self.fittingResultsTitle = QtWidgets.QLabel(self.fittingResultsPanel)
        self.fittingResultsTitle.setProperty("gimapSectionTitle", True)
        self.fittingResultsTitle.setObjectName("fittingResultsTitle")
        self.fittingResultsPanelLayout.addWidget(self.fittingResultsTitle)
        self.fittingResultsDescription = QtWidgets.QLabel(self.fittingResultsPanel)
        self.fittingResultsDescription.setProperty("gimapSectionDescription", True)
        self.fittingResultsDescription.setWordWrap(True)
        self.fittingResultsDescription.setObjectName("fittingResultsDescription")
        self.fittingResultsPanelLayout.addWidget(self.fittingResultsDescription)
        self.fittingResultsContent = QtWidgets.QWidget(self.fittingResultsPanel)
        self.fittingResultsContent.setObjectName("fittingResultsContent")
        self.fittingResultsContentLayout = QtWidgets.QVBoxLayout(self.fittingResultsContent)
        self.fittingResultsContentLayout.setContentsMargins(0, 0, 0, 0)
        self.fittingResultsContentLayout.setSpacing(8)
        self.fittingResultsContentLayout.setObjectName("fittingResultsContentLayout")
        self.fittingResultsPanelLayout.addWidget(self.fittingResultsContent)
        self.fittingPreviewAreaLayout.addWidget(self.fittingResultsPanel)
        self.fittingPlotAdvancedSection = QtWidgets.QFrame(self.gisaxsRightCollapsiblePanel)
        self.fittingPlotAdvancedSection.setProperty("gimapSection", True)
        self.fittingPlotAdvancedSection.setObjectName("fittingPlotAdvancedSection")
        self.fittingPlotAdvancedSectionLayout = QtWidgets.QVBoxLayout(self.fittingPlotAdvancedSection)
        self.fittingPlotAdvancedSectionLayout.setContentsMargins(8, 8, 8, 8)
        self.fittingPlotAdvancedSectionLayout.setSpacing(7)
        self.fittingPlotAdvancedSectionLayout.setObjectName("fittingPlotAdvancedSectionLayout")
        self.fittingPlotAdvancedToggle = QtWidgets.QToolButton(self.fittingPlotAdvancedSection)
        self.fittingPlotAdvancedToggle.setProperty("gimapAdvancedToggle", True)
        self.fittingPlotAdvancedToggle.setCheckable(True)
        self.fittingPlotAdvancedToggle.setChecked(True)
        self.fittingPlotAdvancedToggle.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.fittingPlotAdvancedToggle.setArrowType(QtCore.Qt.DownArrow)
        self.fittingPlotAdvancedToggle.setObjectName("fittingPlotAdvancedToggle")
        self.fittingPlotAdvancedSectionLayout.addWidget(self.fittingPlotAdvancedToggle)
        self.fittingPlotAdvancedDescription = QtWidgets.QLabel(self.fittingPlotAdvancedSection)
        self.fittingPlotAdvancedDescription.setProperty("gimapSectionDescription", True)
        self.fittingPlotAdvancedDescription.setWordWrap(True)
        self.fittingPlotAdvancedDescription.setObjectName("fittingPlotAdvancedDescription")
        self.fittingPlotAdvancedSectionLayout.addWidget(self.fittingPlotAdvancedDescription)
        self.fittingPlotAdvancedContent = QtWidgets.QWidget(self.fittingPlotAdvancedSection)
        self.fittingPlotAdvancedContent.setObjectName("fittingPlotAdvancedContent")
        self.fittingPlotAdvancedContentLayout = QtWidgets.QVBoxLayout(self.fittingPlotAdvancedContent)
        self.fittingPlotAdvancedContentLayout.setContentsMargins(4, 2, 4, 4)
        self.fittingPlotAdvancedContentLayout.setSpacing(8)
        self.fittingPlotAdvancedContentLayout.setObjectName("fittingPlotAdvancedContentLayout")
        self.fittingPlotAdvancedSectionLayout.addWidget(self.fittingPlotAdvancedContent)
        self.fittingPreviewAreaLayout.addWidget(self.fittingPlotAdvancedSection)
        self.fittingLogSection = QtWidgets.QFrame(self.gisaxsRightCollapsiblePanel)
        self.fittingLogSection.setProperty("gimapSection", True)
        self.fittingLogSection.setObjectName("fittingLogSection")
        self.fittingLogSectionLayout = QtWidgets.QVBoxLayout(self.fittingLogSection)
        self.fittingLogSectionLayout.setContentsMargins(8, 8, 8, 8)
        self.fittingLogSectionLayout.setSpacing(7)
        self.fittingLogSectionLayout.setObjectName("fittingLogSectionLayout")
        self.fittingLogToggle = QtWidgets.QToolButton(self.fittingLogSection)
        self.fittingLogToggle.setProperty("gimapAdvancedToggle", True)
        self.fittingLogToggle.setCheckable(True)
        self.fittingLogToggle.setChecked(True)
        self.fittingLogToggle.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.fittingLogToggle.setArrowType(QtCore.Qt.DownArrow)
        self.fittingLogToggle.setObjectName("fittingLogToggle")
        self.fittingLogSectionLayout.addWidget(self.fittingLogToggle)
        self.fittingLogDescription = QtWidgets.QLabel(self.fittingLogSection)
        self.fittingLogDescription.setProperty("gimapSectionDescription", True)
        self.fittingLogDescription.setWordWrap(True)
        self.fittingLogDescription.setObjectName("fittingLogDescription")
        self.fittingLogSectionLayout.addWidget(self.fittingLogDescription)
        self.fittingLogContent = QtWidgets.QWidget(self.fittingLogSection)
        self.fittingLogContent.setObjectName("fittingLogContent")
        self.fittingLogContentLayout = QtWidgets.QVBoxLayout(self.fittingLogContent)
        self.fittingLogContentLayout.setContentsMargins(4, 2, 4, 4)
        self.fittingLogContentLayout.setSpacing(8)
        self.fittingLogContentLayout.setObjectName("fittingLogContentLayout")
        self.fittingLogSectionLayout.addWidget(self.fittingLogContent)
        self.fittingPreviewAreaLayout.addWidget(self.fittingLogSection)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.fittingPreviewAreaLayout.addItem(spacerItem1)
        self.gisaxsPreviewScrollArea.setWidget(self.gisaxsRightCollapsiblePanel)

        self.retranslateUi(gisaxsFittingWorkspaceSplitter)
        QtCore.QMetaObject.connectSlotsByName(gisaxsFittingWorkspaceSplitter)
        gisaxsFittingWorkspaceSplitter.setTabOrder(self.fittingAdvancedToggle, self.fittingPlotAdvancedToggle)
        gisaxsFittingWorkspaceSplitter.setTabOrder(self.fittingPlotAdvancedToggle, self.fittingLogToggle)

    def retranslateUi(self, gisaxsFittingWorkspaceSplitter):
        _translate = QtCore.QCoreApplication.translate
        self.fittingInputTitle.setText(_translate("FittingWorkspace", "Input"))
        self.fittingInputDescription.setText(_translate("FittingWorkspace", "Load the current detector image or stack before defining the cut."))
        self.fittingConfigureTitle.setText(_translate("FittingWorkspace", "Configure"))
        self.fittingConfigureDescription.setText(_translate("FittingWorkspace", "Define detector center and cut geometry using the existing pixel-based controls."))
        self.fittingAdvancedToggle.setText(_translate("FittingWorkspace", "Advanced model configuration"))
        self.fittingAdvancedDescription.setText(_translate("FittingWorkspace", "Edit the component model and its scientific parameters."))
        self.fittingRunTitle.setText(_translate("FittingWorkspace", "Run"))
        self.fittingRunDescription.setText(_translate("FittingWorkspace", "Use the existing manual, AI and refinement commands without changing their profiles or constraints."))
        self.fittingExportTitle.setText(_translate("FittingWorkspace", "Export"))
        self.fittingExportDescription.setText(_translate("FittingWorkspace", "Export the fitted data or the current plot using the original actions."))
        self.fittingPreviewTitle.setText(_translate("FittingWorkspace", "Preview"))
        self.fittingPreviewDescription.setText(_translate("FittingWorkspace", "Inspect the detector image and selected cut region."))
        self.fittingResultsTitle.setText(_translate("FittingWorkspace", "Results"))
        self.fittingResultsDescription.setText(_translate("FittingWorkspace", "Compare the measured curve, components and fitted result."))
        self.fittingPlotAdvancedToggle.setText(_translate("FittingWorkspace", "Advanced plot controls"))
        self.fittingPlotAdvancedDescription.setText(_translate("FittingWorkspace", "Adjust fitting region, sampling and plot display without changing the calculated data."))
        self.fittingLogToggle.setText(_translate("FittingWorkspace", "Log"))
        self.fittingLogDescription.setText(_translate("FittingWorkspace", "Manual fitting, AI fitting and in-situ progress messages."))
