"""Hand-maintained Python View for the Fitting control surface."""


from PyQt5 import QtCore, QtGui, QtWidgets


class FittingPageView(object):
    def setupUi(self, gisaxsFittingPage):
        gisaxsFittingPage.setObjectName("gisaxsFittingPage")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(gisaxsFittingPage)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.gisaxsFittingPageScrollArea = QtWidgets.QScrollArea(gisaxsFittingPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gisaxsFittingPageScrollArea.sizePolicy().hasHeightForWidth())
        self.gisaxsFittingPageScrollArea.setSizePolicy(sizePolicy)
        self.gisaxsFittingPageScrollArea.setWidgetResizable(True)
        self.gisaxsFittingPageScrollArea.setObjectName("gisaxsFittingPageScrollArea")
        self.gisaxsFittingPageScrollAreaWidgetContents = QtWidgets.QWidget()
        self.gisaxsFittingPageScrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1018, 1005))
        self.gisaxsFittingPageScrollAreaWidgetContents.setObjectName("gisaxsFittingPageScrollAreaWidgetContents")
        self.gridLayout_38 = QtWidgets.QGridLayout(self.gisaxsFittingPageScrollAreaWidgetContents)
        self.gridLayout_38.setObjectName("gridLayout_38")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_38.addItem(spacerItem, 2, 0, 1, 1)
        self.gisaxsInputBox = QtWidgets.QGroupBox(self.gisaxsFittingPageScrollAreaWidgetContents)
        self.gisaxsInputBox.setMinimumSize(QtCore.QSize(0, 0))
        self.gisaxsInputBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gisaxsInputBox.setStyleSheet("QGroupBox {\n"
"    font-weight: bold;\n"
"}")
        self.gisaxsInputBox.setObjectName("gisaxsInputBox")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.gisaxsInputBox)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.gisaxsInputCutLineLabel = QtWidgets.QLabel(self.gisaxsInputBox)
        self.gisaxsInputCutLineLabel.setMinimumSize(QtCore.QSize(0, 20))
        self.gisaxsInputCutLineLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        self.gisaxsInputCutLineLabel.setObjectName("gisaxsInputCutLineLabel")
        self.gridLayout_23.addWidget(self.gisaxsInputCutLineLabel, 4, 0, 1, 1)
        self.gisaxsInputColorScaleLabel = QtWidgets.QLabel(self.gisaxsInputBox)
        self.gisaxsInputColorScaleLabel.setMinimumSize(QtCore.QSize(0, 20))
        self.gisaxsInputColorScaleLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        self.gisaxsInputColorScaleLabel.setObjectName("gisaxsInputColorScaleLabel")
        self.gridLayout_23.addWidget(self.gisaxsInputColorScaleLabel, 2, 0, 1, 1)
        self.gisaxsInputImportButton = QtWidgets.QPushButton(self.gisaxsInputBox)
        self.gisaxsInputImportButton.setMinimumSize(QtCore.QSize(50, 0))
        self.gisaxsInputImportButton.setObjectName("gisaxsInputImportButton")
        self.gridLayout_23.addWidget(self.gisaxsInputImportButton, 0, 0, 1, 1)
        self.gisaxsInputCenterAutoFindingButton = QtWidgets.QPushButton(self.gisaxsInputBox)
        self.gisaxsInputCenterAutoFindingButton.setMinimumSize(QtCore.QSize(50, 20))
        self.gisaxsInputCenterAutoFindingButton.setObjectName("gisaxsInputCenterAutoFindingButton")
        self.gridLayout_23.addWidget(self.gisaxsInputCenterAutoFindingButton, 6, 4, 1, 1)
        self.gisaxsInputVminLabel = QtWidgets.QLabel(self.gisaxsInputBox)
        self.gisaxsInputVminLabel.setObjectName("gisaxsInputVminLabel")
        self.gridLayout_23.addWidget(self.gisaxsInputVminLabel, 3, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.gisaxsInputStackWidget = QtWidgets.QWidget(self.gisaxsInputBox)
        self.gisaxsInputStackWidget.setMinimumSize(QtCore.QSize(0, 40))
        self.gisaxsInputStackWidget.setObjectName("gisaxsInputStackWidget")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.gisaxsInputStackWidget)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.gisaxsInputStackValue = QtWidgets.QLineEdit(self.gisaxsInputStackWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gisaxsInputStackValue.sizePolicy().hasHeightForWidth())
        self.gisaxsInputStackValue.setSizePolicy(sizePolicy)
        self.gisaxsInputStackValue.setMinimumSize(QtCore.QSize(0, 20))
        self.gisaxsInputStackValue.setMaximumSize(QtCore.QSize(50, 16777215))
        self.gisaxsInputStackValue.setObjectName("gisaxsInputStackValue")
        self.horizontalLayout_11.addWidget(self.gisaxsInputStackValue)
        self.gisaxsInputStackDisplayLabel = QtWidgets.QLabel(self.gisaxsInputStackWidget)
        self.gisaxsInputStackDisplayLabel.setMinimumSize(QtCore.QSize(0, 25))
        self.gisaxsInputStackDisplayLabel.setText("")
        self.gisaxsInputStackDisplayLabel.setObjectName("gisaxsInputStackDisplayLabel")
        self.horizontalLayout_11.addWidget(self.gisaxsInputStackDisplayLabel)
        self.gridLayout_23.addWidget(self.gisaxsInputStackWidget, 1, 2, 1, 3)
        self.gisaxsInputGraphicsView = QtWidgets.QGraphicsView(self.gisaxsInputBox)
        self.gisaxsInputGraphicsView.setMaximumSize(QtCore.QSize(300, 16777215))
        self.gisaxsInputGraphicsView.setStyleSheet("QGraphicsView {\n"
"    background: transparent;\n"
"    border: 1px solid #888888; \n"
"    border-radius: 4px;  \n"
"}")
        self.gisaxsInputGraphicsView.setObjectName("gisaxsInputGraphicsView")
        self.gridLayout_23.addWidget(self.gisaxsInputGraphicsView, 0, 5, 8, 1)
        self.gisaxsInputCutLineCenterWidget = QtWidgets.QWidget(self.gisaxsInputBox)
        self.gisaxsInputCutLineCenterWidget.setObjectName("gisaxsInputCutLineCenterWidget")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.gisaxsInputCutLineCenterWidget)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.gisaxsInputCenterVerticalLabel = QtWidgets.QLabel(self.gisaxsInputCutLineCenterWidget)
        self.gisaxsInputCenterVerticalLabel.setMinimumSize(QtCore.QSize(0, 20))
        self.gisaxsInputCenterVerticalLabel.setObjectName("gisaxsInputCenterVerticalLabel")
        self.horizontalLayout_10.addWidget(self.gisaxsInputCenterVerticalLabel, 0, QtCore.Qt.AlignHCenter)
        self.gisaxsInputCenterVerticalValue = QtWidgets.QDoubleSpinBox(self.gisaxsInputCutLineCenterWidget)
        self.gisaxsInputCenterVerticalValue.setMinimumSize(QtCore.QSize(0, 20))
        self.gisaxsInputCenterVerticalValue.setObjectName("gisaxsInputCenterVerticalValue")
        self.horizontalLayout_10.addWidget(self.gisaxsInputCenterVerticalValue)
        self.gisaxsInputCenterParallelLabel = QtWidgets.QLabel(self.gisaxsInputCutLineCenterWidget)
        self.gisaxsInputCenterParallelLabel.setMinimumSize(QtCore.QSize(0, 20))
        self.gisaxsInputCenterParallelLabel.setObjectName("gisaxsInputCenterParallelLabel")
        self.horizontalLayout_10.addWidget(self.gisaxsInputCenterParallelLabel, 0, QtCore.Qt.AlignHCenter)
        self.gisaxsInputCenterParallelValue = QtWidgets.QDoubleSpinBox(self.gisaxsInputCutLineCenterWidget)
        self.gisaxsInputCenterParallelValue.setMinimumSize(QtCore.QSize(0, 20))
        self.gisaxsInputCenterParallelValue.setObjectName("gisaxsInputCenterParallelValue")
        self.horizontalLayout_10.addWidget(self.gisaxsInputCenterParallelValue)
        self.gridLayout_23.addWidget(self.gisaxsInputCutLineCenterWidget, 6, 2, 1, 2)
        self.gisaxsInputCutLineParallelValue = QtWidgets.QDoubleSpinBox(self.gisaxsInputBox)
        self.gisaxsInputCutLineParallelValue.setMinimumSize(QtCore.QSize(0, 20))
        self.gisaxsInputCutLineParallelValue.setObjectName("gisaxsInputCutLineParallelValue")
        self.gridLayout_23.addWidget(self.gisaxsInputCutLineParallelValue, 5, 4, 1, 1)
        self.gisaxsInputCutLineVerticalValue = QtWidgets.QDoubleSpinBox(self.gisaxsInputBox)
        self.gisaxsInputCutLineVerticalValue.setMinimumSize(QtCore.QSize(0, 20))
        self.gisaxsInputCutLineVerticalValue.setObjectName("gisaxsInputCutLineVerticalValue")
        self.gridLayout_23.addWidget(self.gisaxsInputCutLineVerticalValue, 5, 2, 1, 1)
        self.gisaxsInputVmaxValue = QtWidgets.QDoubleSpinBox(self.gisaxsInputBox)
        self.gisaxsInputVmaxValue.setMinimumSize(QtCore.QSize(0, 20))
        self.gisaxsInputVmaxValue.setObjectName("gisaxsInputVmaxValue")
        self.gridLayout_23.addWidget(self.gisaxsInputVmaxValue, 3, 4, 1, 1)
        self.gisaxsInputVminValue = QtWidgets.QDoubleSpinBox(self.gisaxsInputBox)
        self.gisaxsInputVminValue.setMinimumSize(QtCore.QSize(0, 20))
        self.gisaxsInputVminValue.setObjectName("gisaxsInputVminValue")
        self.gridLayout_23.addWidget(self.gisaxsInputVminValue, 3, 2, 1, 1)
        self.gisaxsInputColorScaleWidget = QtWidgets.QWidget(self.gisaxsInputBox)
        self.gisaxsInputColorScaleWidget.setMinimumSize(QtCore.QSize(0, 40))
        self.gisaxsInputColorScaleWidget.setObjectName("gisaxsInputColorScaleWidget")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.gisaxsInputColorScaleWidget)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.gisaxsInputAutoScaleCheckBox = QtWidgets.QCheckBox(self.gisaxsInputColorScaleWidget)
        self.gisaxsInputAutoScaleCheckBox.setMinimumSize(QtCore.QSize(0, 20))
        self.gisaxsInputAutoScaleCheckBox.setChecked(True)
        self.gisaxsInputAutoScaleCheckBox.setObjectName("gisaxsInputAutoScaleCheckBox")
        self.horizontalLayout_12.addWidget(self.gisaxsInputAutoScaleCheckBox)
        self.gisaxsInputIntLogCheckBox = QtWidgets.QCheckBox(self.gisaxsInputColorScaleWidget)
        self.gisaxsInputIntLogCheckBox.setMinimumSize(QtCore.QSize(0, 20))
        self.gisaxsInputIntLogCheckBox.setChecked(True)
        self.gisaxsInputIntLogCheckBox.setObjectName("gisaxsInputIntLogCheckBox")
        self.horizontalLayout_12.addWidget(self.gisaxsInputIntLogCheckBox)
        self.gisaxsInputAutoShowCheckBox = QtWidgets.QCheckBox(self.gisaxsInputColorScaleWidget)
        self.gisaxsInputAutoShowCheckBox.setMinimumSize(QtCore.QSize(0, 20))
        self.gisaxsInputAutoShowCheckBox.setObjectName("gisaxsInputAutoShowCheckBox")
        self.horizontalLayout_12.addWidget(self.gisaxsInputAutoShowCheckBox)
        self.gisaxsInputShowButton = QtWidgets.QPushButton(self.gisaxsInputColorScaleWidget)
        self.gisaxsInputShowButton.setMinimumSize(QtCore.QSize(50, 25))
        self.gisaxsInputShowButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.gisaxsInputShowButton.setObjectName("gisaxsInputShowButton")
        self.horizontalLayout_12.addWidget(self.gisaxsInputShowButton)
        self.gridLayout_23.addWidget(self.gisaxsInputColorScaleWidget, 2, 2, 1, 3)
        self.gisaxsInputCutButton = QtWidgets.QPushButton(self.gisaxsInputBox)
        self.gisaxsInputCutButton.setMinimumSize(QtCore.QSize(50, 0))
        self.gisaxsInputCutButton.setObjectName("gisaxsInputCutButton")
        self.gridLayout_23.addWidget(self.gisaxsInputCutButton, 7, 2, 1, 1)
        self.gisaxsInputImportButtonValue = QtWidgets.QLineEdit(self.gisaxsInputBox)
        self.gisaxsInputImportButtonValue.setMinimumSize(QtCore.QSize(0, 20))
        self.gisaxsInputImportButtonValue.setObjectName("gisaxsInputImportButtonValue")
        self.gridLayout_23.addWidget(self.gisaxsInputImportButtonValue, 0, 2, 1, 3)
        self.gisaxsInputVmaxLabel = QtWidgets.QLabel(self.gisaxsInputBox)
        self.gisaxsInputVmaxLabel.setObjectName("gisaxsInputVmaxLabel")
        self.gridLayout_23.addWidget(self.gisaxsInputVmaxLabel, 3, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.gisaxsInputCutLineVerticalLabel = QtWidgets.QLabel(self.gisaxsInputBox)
        self.gisaxsInputCutLineVerticalLabel.setObjectName("gisaxsInputCutLineVerticalLabel")
        self.gridLayout_23.addWidget(self.gisaxsInputCutLineVerticalLabel, 5, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.gisaxsInputCutLineParallelLabel = QtWidgets.QLabel(self.gisaxsInputBox)
        self.gisaxsInputCutLineParallelLabel.setObjectName("gisaxsInputCutLineParallelLabel")
        self.gridLayout_23.addWidget(self.gisaxsInputCutLineParallelLabel, 5, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.gisaxsInputCenterLabel = QtWidgets.QLabel(self.gisaxsInputBox)
        self.gisaxsInputCenterLabel.setObjectName("gisaxsInputCenterLabel")
        self.gridLayout_23.addWidget(self.gisaxsInputCenterLabel, 6, 0, 1, 1)
        self.gisaxsInputDetectorParaButton = QtWidgets.QPushButton(self.gisaxsInputBox)
        self.gisaxsInputDetectorParaButton.setMinimumSize(QtCore.QSize(50, 0))
        self.gisaxsInputDetectorParaButton.setObjectName("gisaxsInputDetectorParaButton")
        self.gridLayout_23.addWidget(self.gisaxsInputDetectorParaButton, 7, 0, 1, 1)
        self.gisaxsInputModelCombox = QtWidgets.QComboBox(self.gisaxsInputBox)
        self.gisaxsInputModelCombox.setObjectName("gisaxsInputModelCombox")
        self.gisaxsInputModelCombox.addItem("")
        self.gisaxsInputModelCombox.addItem("")
        self.gisaxsInputModelCombox.addItem("")
        self.gridLayout_23.addWidget(self.gisaxsInputModelCombox, 1, 0, 1, 1)
        self.gridLayout_38.addWidget(self.gisaxsInputBox, 0, 0, 1, 1)
        self.fitBox = QtWidgets.QGroupBox(self.gisaxsFittingPageScrollAreaWidgetContents)
        self.fitBox.setMinimumSize(QtCore.QSize(1000, 0))
        self.fitBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.fitBox.setStyleSheet("QGroupBox {\n"
"    font-weight: bold;\n"
"}")
        self.fitBox.setObjectName("fitBox")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.fitBox)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.fitImport1dFileValue = QtWidgets.QLineEdit(self.fitBox)
        self.fitImport1dFileValue.setMinimumSize(QtCore.QSize(0, 20))
        self.fitImport1dFileValue.setObjectName("fitImport1dFileValue")
        self.gridLayout_24.addWidget(self.fitImport1dFileValue, 1, 1, 1, 2)
        self.fitMethodWidget_2 = QtWidgets.QWidget(self.fitBox)
        self.fitMethodWidget_2.setMinimumSize(QtCore.QSize(0, 100))
        self.fitMethodWidget_2.setObjectName("fitMethodWidget_2")
        self.gridLayout_39 = QtWidgets.QGridLayout(self.fitMethodWidget_2)
        self.gridLayout_39.setObjectName("gridLayout_39")
        self.fitKValue = QtWidgets.QDoubleSpinBox(self.fitMethodWidget_2)
        self.fitKValue.setMinimumSize(QtCore.QSize(0, 20))
        self.fitKValue.setObjectName("fitKValue")
        self.gridLayout_39.addWidget(self.fitKValue, 1, 1, 1, 1)
        self.fitKLabel = QtWidgets.QLabel(self.fitMethodWidget_2)
        self.fitKLabel.setMinimumSize(QtCore.QSize(0, 20))
        self.fitKLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.fitKLabel.setObjectName("fitKLabel")
        self.gridLayout_39.addWidget(self.fitKLabel, 1, 0, 1, 1)
        self.FittingManualFittingButton = QtWidgets.QPushButton(self.fitMethodWidget_2)
        self.FittingManualFittingButton.setMinimumSize(QtCore.QSize(50, 20))
        self.FittingManualFittingButton.setObjectName("FittingManualFittingButton")
        self.gridLayout_39.addWidget(self.FittingManualFittingButton, 2, 0, 1, 2)
        self.fitIntResLabel = QtWidgets.QLabel(self.fitMethodWidget_2)
        self.fitIntResLabel.setObjectName("fitIntResLabel")
        self.gridLayout_39.addWidget(self.fitIntResLabel, 0, 0, 1, 1)
        self.fitIntResValue = QtWidgets.QDoubleSpinBox(self.fitMethodWidget_2)
        self.fitIntResValue.setMinimumSize(QtCore.QSize(0, 20))
        self.fitIntResValue.setObjectName("fitIntResValue")
        self.gridLayout_39.addWidget(self.fitIntResValue, 0, 1, 1, 1)
        self.gridLayout_24.addWidget(self.fitMethodWidget_2, 5, 0, 1, 1)
        self.fitImport1dFileButton = QtWidgets.QPushButton(self.fitBox)
        self.fitImport1dFileButton.setMinimumSize(QtCore.QSize(50, 20))
        self.fitImport1dFileButton.setObjectName("fitImport1dFileButton")
        self.gridLayout_24.addWidget(self.fitImport1dFileButton, 1, 0, 1, 1)
        self.fitCurrentDataCheckBox = QtWidgets.QCheckBox(self.fitBox)
        self.fitCurrentDataCheckBox.setMinimumSize(QtCore.QSize(0, 20))
        self.fitCurrentDataCheckBox.setObjectName("fitCurrentDataCheckBox")
        self.gridLayout_24.addWidget(self.fitCurrentDataCheckBox, 0, 0, 1, 1)
        self.widget = QtWidgets.QWidget(self.fitBox)
        self.widget.setObjectName("widget")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.fitLogXCheckBox = QtWidgets.QCheckBox(self.widget)
        self.fitLogXCheckBox.setMinimumSize(QtCore.QSize(0, 20))
        self.fitLogXCheckBox.setObjectName("fitLogXCheckBox")
        self.horizontalLayout_13.addWidget(self.fitLogXCheckBox)
        self.fitLogYCheckBox = QtWidgets.QCheckBox(self.widget)
        self.fitLogYCheckBox.setMinimumSize(QtCore.QSize(0, 20))
        self.fitLogYCheckBox.setObjectName("fitLogYCheckBox")
        self.horizontalLayout_13.addWidget(self.fitLogYCheckBox)
        self.fitNormCheckBox = QtWidgets.QCheckBox(self.widget)
        self.fitNormCheckBox.setMinimumSize(QtCore.QSize(0, 20))
        self.fitNormCheckBox.setObjectName("fitNormCheckBox")
        self.horizontalLayout_13.addWidget(self.fitNormCheckBox)
        self.FittingExportButton = QtWidgets.QPushButton(self.widget)
        self.FittingExportButton.setMinimumSize(QtCore.QSize(50, 0))
        self.FittingExportButton.setObjectName("FittingExportButton")
        self.horizontalLayout_13.addWidget(self.FittingExportButton)
        self.gridLayout_24.addWidget(self.widget, 0, 1, 1, 2)
        self.widget_7 = QtWidgets.QWidget(self.fitBox)
        self.widget_7.setMinimumSize(QtCore.QSize(0, 400))
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.scrollArea = QtWidgets.QScrollArea(self.widget_7)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 762, 363))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.fitParticleWidget_1 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.fitParticleWidget_1.setMinimumSize(QtCore.QSize(230, 300))
        self.fitParticleWidget_1.setStyleSheet("#fitParticleWidget_1 {\n"
"  border: 1px solid rgba(0,0,0,0.12);  /* 细外框 */\n"
"  border-radius: 12px;                 /* 圆角大小可改 */\n"
"  padding: 8px;                        /* 让内容不贴边 */\n"
"  /* 伪“阴影”：用浅色外描边模拟（Qt 没有 box-shadow） */\n"
"  outline: 6px solid rgba(0,0,0,0.03);\n"
"  outline-offset: -6px;                /* 紧贴边缘 */\n"
"}")
        self.fitParticleWidget_1.setObjectName("fitParticleWidget_1")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.fitParticleWidget_1)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.fitParticleShapeCombox_1 = QtWidgets.QComboBox(self.fitParticleWidget_1)
        self.fitParticleShapeCombox_1.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleShapeCombox_1.setObjectName("fitParticleShapeCombox_1")
        self.fitParticleShapeCombox_1.addItem("")
        self.fitParticleShapeCombox_1.addItem("")
        self.fitParticleShapeCombox_1.addItem("")
        self.verticalLayout_20.addWidget(self.fitParticleShapeCombox_1)
        self.fitParticleStackWidget_1 = QtWidgets.QStackedWidget(self.fitParticleWidget_1)
        self.fitParticleStackWidget_1.setObjectName("fitParticleStackWidget_1")
        self.fitParticleSpherePage_1 = QtWidgets.QWidget()
        self.fitParticleSpherePage_1.setObjectName("fitParticleSpherePage_1")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.fitParticleSpherePage_1)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.fitParticleSphereDLabel_1 = QtWidgets.QLabel(self.fitParticleSpherePage_1)
        self.fitParticleSphereDLabel_1.setObjectName("fitParticleSphereDLabel_1")
        self.gridLayout_25.addWidget(self.fitParticleSphereDLabel_1, 3, 0, 1, 1)
        self.fitParticleSphereDValue_1 = QtWidgets.QDoubleSpinBox(self.fitParticleSpherePage_1)
        self.fitParticleSphereDValue_1.setObjectName("fitParticleSphereDValue_1")
        self.gridLayout_25.addWidget(self.fitParticleSphereDValue_1, 3, 1, 1, 1)
        self.fitParticleSphereIntValue_1 = QtWidgets.QDoubleSpinBox(self.fitParticleSpherePage_1)
        self.fitParticleSphereIntValue_1.setObjectName("fitParticleSphereIntValue_1")
        self.gridLayout_25.addWidget(self.fitParticleSphereIntValue_1, 0, 1, 1, 1)
        self.fitParticleSphereSigmaRValue_1 = QtWidgets.QDoubleSpinBox(self.fitParticleSpherePage_1)
        self.fitParticleSphereSigmaRValue_1.setObjectName("fitParticleSphereSigmaRValue_1")
        self.gridLayout_25.addWidget(self.fitParticleSphereSigmaRValue_1, 2, 1, 1, 1)
        self.fitParticleSphereRValue_1 = QtWidgets.QDoubleSpinBox(self.fitParticleSpherePage_1)
        self.fitParticleSphereRValue_1.setObjectName("fitParticleSphereRValue_1")
        self.gridLayout_25.addWidget(self.fitParticleSphereRValue_1, 1, 1, 1, 1)
        self.fitParticleSphereBGValue_1 = QtWidgets.QDoubleSpinBox(self.fitParticleSpherePage_1)
        self.fitParticleSphereBGValue_1.setObjectName("fitParticleSphereBGValue_1")
        self.gridLayout_25.addWidget(self.fitParticleSphereBGValue_1, 5, 1, 1, 1)
        self.fitParticleSphereSigmaDValue_1 = QtWidgets.QDoubleSpinBox(self.fitParticleSpherePage_1)
        self.fitParticleSphereSigmaDValue_1.setObjectName("fitParticleSphereSigmaDValue_1")
        self.gridLayout_25.addWidget(self.fitParticleSphereSigmaDValue_1, 4, 1, 1, 1)
        self.fitParticleSphereSigmaDLabel_1 = QtWidgets.QLabel(self.fitParticleSpherePage_1)
        self.fitParticleSphereSigmaDLabel_1.setObjectName("fitParticleSphereSigmaDLabel_1")
        self.gridLayout_25.addWidget(self.fitParticleSphereSigmaDLabel_1, 4, 0, 1, 1)
        self.fitParticleSphereRLabel_1 = QtWidgets.QLabel(self.fitParticleSpherePage_1)
        self.fitParticleSphereRLabel_1.setObjectName("fitParticleSphereRLabel_1")
        self.gridLayout_25.addWidget(self.fitParticleSphereRLabel_1, 1, 0, 1, 1)
        self.fitParticleSphereBGLabel_1 = QtWidgets.QLabel(self.fitParticleSpherePage_1)
        self.fitParticleSphereBGLabel_1.setObjectName("fitParticleSphereBGLabel_1")
        self.gridLayout_25.addWidget(self.fitParticleSphereBGLabel_1, 5, 0, 1, 1)
        self.fitParticleSphereSigmaRLabel_1 = QtWidgets.QLabel(self.fitParticleSpherePage_1)
        self.fitParticleSphereSigmaRLabel_1.setObjectName("fitParticleSphereSigmaRLabel_1")
        self.gridLayout_25.addWidget(self.fitParticleSphereSigmaRLabel_1, 2, 0, 1, 1)
        self.fitParticleSphereIntLabel_1 = QtWidgets.QLabel(self.fitParticleSpherePage_1)
        self.fitParticleSphereIntLabel_1.setObjectName("fitParticleSphereIntLabel_1")
        self.gridLayout_25.addWidget(self.fitParticleSphereIntLabel_1, 0, 0, 1, 1)
        self.fitParticleStackWidget_1.addWidget(self.fitParticleSpherePage_1)
        self.fitParticleCylinderPage_1 = QtWidgets.QWidget()
        self.fitParticleCylinderPage_1.setObjectName("fitParticleCylinderPage_1")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.fitParticleCylinderPage_1)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.fitParticleCylinderSigmaDLabel_1 = QtWidgets.QLabel(self.fitParticleCylinderPage_1)
        self.fitParticleCylinderSigmaDLabel_1.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderSigmaDLabel_1.setObjectName("fitParticleCylinderSigmaDLabel_1")
        self.gridLayout_26.addWidget(self.fitParticleCylinderSigmaDLabel_1, 8, 0, 1, 1)
        self.fitParticleCylinderRLabel_1 = QtWidgets.QLabel(self.fitParticleCylinderPage_1)
        self.fitParticleCylinderRLabel_1.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderRLabel_1.setObjectName("fitParticleCylinderRLabel_1")
        self.gridLayout_26.addWidget(self.fitParticleCylinderRLabel_1, 1, 0, 1, 1)
        self.fitParticleCylinderRValue_1 = QtWidgets.QDoubleSpinBox(self.fitParticleCylinderPage_1)
        self.fitParticleCylinderRValue_1.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderRValue_1.setObjectName("fitParticleCylinderRValue_1")
        self.gridLayout_26.addWidget(self.fitParticleCylinderRValue_1, 1, 1, 1, 1)
        self.fitParticleCylinderDLabel_1 = QtWidgets.QLabel(self.fitParticleCylinderPage_1)
        self.fitParticleCylinderDLabel_1.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderDLabel_1.setObjectName("fitParticleCylinderDLabel_1")
        self.gridLayout_26.addWidget(self.fitParticleCylinderDLabel_1, 7, 0, 1, 1)
        self.fitParticleCylinderBGValue_1 = QtWidgets.QDoubleSpinBox(self.fitParticleCylinderPage_1)
        self.fitParticleCylinderBGValue_1.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderBGValue_1.setObjectName("fitParticleCylinderBGValue_1")
        self.gridLayout_26.addWidget(self.fitParticleCylinderBGValue_1, 9, 1, 1, 1)
        self.fitParticleCylinderIntLabel_1 = QtWidgets.QLabel(self.fitParticleCylinderPage_1)
        self.fitParticleCylinderIntLabel_1.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderIntLabel_1.setObjectName("fitParticleCylinderIntLabel_1")
        self.gridLayout_26.addWidget(self.fitParticleCylinderIntLabel_1, 0, 0, 1, 1)
        self.fitParticleCylinderSigmahValue_1 = QtWidgets.QDoubleSpinBox(self.fitParticleCylinderPage_1)
        self.fitParticleCylinderSigmahValue_1.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderSigmahValue_1.setObjectName("fitParticleCylinderSigmahValue_1")
        self.gridLayout_26.addWidget(self.fitParticleCylinderSigmahValue_1, 4, 1, 1, 1)
        self.fitParticleCylinderhLabel_1 = QtWidgets.QLabel(self.fitParticleCylinderPage_1)
        self.fitParticleCylinderhLabel_1.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderhLabel_1.setObjectName("fitParticleCylinderhLabel_1")
        self.gridLayout_26.addWidget(self.fitParticleCylinderhLabel_1, 3, 0, 1, 1)
        self.fitParticleCylinderSigmaRLabel_1 = QtWidgets.QLabel(self.fitParticleCylinderPage_1)
        self.fitParticleCylinderSigmaRLabel_1.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderSigmaRLabel_1.setObjectName("fitParticleCylinderSigmaRLabel_1")
        self.gridLayout_26.addWidget(self.fitParticleCylinderSigmaRLabel_1, 2, 0, 1, 1)
        self.fitParticleCylinderDValue_1 = QtWidgets.QDoubleSpinBox(self.fitParticleCylinderPage_1)
        self.fitParticleCylinderDValue_1.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderDValue_1.setObjectName("fitParticleCylinderDValue_1")
        self.gridLayout_26.addWidget(self.fitParticleCylinderDValue_1, 7, 1, 1, 1)
        self.fitParticleCylinderSigmaRValue_1 = QtWidgets.QDoubleSpinBox(self.fitParticleCylinderPage_1)
        self.fitParticleCylinderSigmaRValue_1.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderSigmaRValue_1.setObjectName("fitParticleCylinderSigmaRValue_1")
        self.gridLayout_26.addWidget(self.fitParticleCylinderSigmaRValue_1, 2, 1, 1, 1)
        self.fitParticleCylinderSigmaDValue_1 = QtWidgets.QDoubleSpinBox(self.fitParticleCylinderPage_1)
        self.fitParticleCylinderSigmaDValue_1.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderSigmaDValue_1.setObjectName("fitParticleCylinderSigmaDValue_1")
        self.gridLayout_26.addWidget(self.fitParticleCylinderSigmaDValue_1, 8, 1, 1, 1)
        self.fitParticleCylinderBGLabel_1 = QtWidgets.QLabel(self.fitParticleCylinderPage_1)
        self.fitParticleCylinderBGLabel_1.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderBGLabel_1.setObjectName("fitParticleCylinderBGLabel_1")
        self.gridLayout_26.addWidget(self.fitParticleCylinderBGLabel_1, 9, 0, 1, 1)
        self.fitParticleCylinderhValue_1 = QtWidgets.QDoubleSpinBox(self.fitParticleCylinderPage_1)
        self.fitParticleCylinderhValue_1.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderhValue_1.setObjectName("fitParticleCylinderhValue_1")
        self.gridLayout_26.addWidget(self.fitParticleCylinderhValue_1, 3, 1, 1, 1)
        self.fitParticleCylinderSigmahLabel_1 = QtWidgets.QLabel(self.fitParticleCylinderPage_1)
        self.fitParticleCylinderSigmahLabel_1.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderSigmahLabel_1.setObjectName("fitParticleCylinderSigmahLabel_1")
        self.gridLayout_26.addWidget(self.fitParticleCylinderSigmahLabel_1, 4, 0, 1, 1)
        self.fitParticleCylinderIntValue_1 = QtWidgets.QDoubleSpinBox(self.fitParticleCylinderPage_1)
        self.fitParticleCylinderIntValue_1.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderIntValue_1.setObjectName("fitParticleCylinderIntValue_1")
        self.gridLayout_26.addWidget(self.fitParticleCylinderIntValue_1, 0, 1, 1, 1)
        self.fitParticleStackWidget_1.addWidget(self.fitParticleCylinderPage_1)
        self.verticalLayout_20.addWidget(self.fitParticleStackWidget_1)
        self.horizontalLayout_18.addWidget(self.fitParticleWidget_1)
        self.fitParticleWidget_2 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.fitParticleWidget_2.setMinimumSize(QtCore.QSize(230, 300))
        self.fitParticleWidget_2.setStyleSheet("#fitParticleWidget_2 {\n"
"  border: 1px solid rgba(0,0,0,0.12);  /* 细外框 */\n"
"  border-radius: 12px;                 /* 圆角大小可改 */\n"
"  padding: 8px;                        /* 让内容不贴边 */\n"
"  /* 伪“阴影”：用浅色外描边模拟（Qt 没有 box-shadow） */\n"
"  outline: 6px solid rgba(0,0,0,0.03);\n"
"  outline-offset: -6px;                /* 紧贴边缘 */\n"
"}")
        self.fitParticleWidget_2.setObjectName("fitParticleWidget_2")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.fitParticleWidget_2)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.fitParticleShapeCombox_2 = QtWidgets.QComboBox(self.fitParticleWidget_2)
        self.fitParticleShapeCombox_2.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleShapeCombox_2.setObjectName("fitParticleShapeCombox_2")
        self.fitParticleShapeCombox_2.addItem("")
        self.fitParticleShapeCombox_2.addItem("")
        self.fitParticleShapeCombox_2.addItem("")
        self.verticalLayout_21.addWidget(self.fitParticleShapeCombox_2)
        self.fitParticleStackWidget_2 = QtWidgets.QStackedWidget(self.fitParticleWidget_2)
        self.fitParticleStackWidget_2.setMinimumSize(QtCore.QSize(0, 0))
        self.fitParticleStackWidget_2.setObjectName("fitParticleStackWidget_2")
        self.fitParticleSpherePage_2 = QtWidgets.QWidget()
        self.fitParticleSpherePage_2.setObjectName("fitParticleSpherePage_2")
        self.gridLayout_27 = QtWidgets.QGridLayout(self.fitParticleSpherePage_2)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.fitParticleSphereDLabel_2 = QtWidgets.QLabel(self.fitParticleSpherePage_2)
        self.fitParticleSphereDLabel_2.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleSphereDLabel_2.setObjectName("fitParticleSphereDLabel_2")
        self.gridLayout_27.addWidget(self.fitParticleSphereDLabel_2, 3, 0, 1, 1)
        self.fitParticleSphereDValue_2 = QtWidgets.QDoubleSpinBox(self.fitParticleSpherePage_2)
        self.fitParticleSphereDValue_2.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleSphereDValue_2.setObjectName("fitParticleSphereDValue_2")
        self.gridLayout_27.addWidget(self.fitParticleSphereDValue_2, 3, 1, 1, 1)
        self.fitParticleSphereSigmaDLabel_2 = QtWidgets.QLabel(self.fitParticleSpherePage_2)
        self.fitParticleSphereSigmaDLabel_2.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleSphereSigmaDLabel_2.setObjectName("fitParticleSphereSigmaDLabel_2")
        self.gridLayout_27.addWidget(self.fitParticleSphereSigmaDLabel_2, 4, 0, 1, 1)
        self.fitParticleSphereRLabel_2 = QtWidgets.QLabel(self.fitParticleSpherePage_2)
        self.fitParticleSphereRLabel_2.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleSphereRLabel_2.setObjectName("fitParticleSphereRLabel_2")
        self.gridLayout_27.addWidget(self.fitParticleSphereRLabel_2, 1, 0, 1, 1)
        self.fitParticleSphereBGValue_2 = QtWidgets.QDoubleSpinBox(self.fitParticleSpherePage_2)
        self.fitParticleSphereBGValue_2.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleSphereBGValue_2.setObjectName("fitParticleSphereBGValue_2")
        self.gridLayout_27.addWidget(self.fitParticleSphereBGValue_2, 5, 1, 1, 1)
        self.fitParticleSphereIntValue_2 = QtWidgets.QDoubleSpinBox(self.fitParticleSpherePage_2)
        self.fitParticleSphereIntValue_2.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleSphereIntValue_2.setObjectName("fitParticleSphereIntValue_2")
        self.gridLayout_27.addWidget(self.fitParticleSphereIntValue_2, 0, 1, 1, 1)
        self.fitParticleSphereSigmaRValue_2 = QtWidgets.QDoubleSpinBox(self.fitParticleSpherePage_2)
        self.fitParticleSphereSigmaRValue_2.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleSphereSigmaRValue_2.setObjectName("fitParticleSphereSigmaRValue_2")
        self.gridLayout_27.addWidget(self.fitParticleSphereSigmaRValue_2, 2, 1, 1, 1)
        self.fitParticleSphereSigmaRLabel_2 = QtWidgets.QLabel(self.fitParticleSpherePage_2)
        self.fitParticleSphereSigmaRLabel_2.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleSphereSigmaRLabel_2.setObjectName("fitParticleSphereSigmaRLabel_2")
        self.gridLayout_27.addWidget(self.fitParticleSphereSigmaRLabel_2, 2, 0, 1, 1)
        self.fitParticleSphereIntLabel_2 = QtWidgets.QLabel(self.fitParticleSpherePage_2)
        self.fitParticleSphereIntLabel_2.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleSphereIntLabel_2.setObjectName("fitParticleSphereIntLabel_2")
        self.gridLayout_27.addWidget(self.fitParticleSphereIntLabel_2, 0, 0, 1, 1)
        self.fitParticleSphereBGLabel_2 = QtWidgets.QLabel(self.fitParticleSpherePage_2)
        self.fitParticleSphereBGLabel_2.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleSphereBGLabel_2.setObjectName("fitParticleSphereBGLabel_2")
        self.gridLayout_27.addWidget(self.fitParticleSphereBGLabel_2, 5, 0, 1, 1)
        self.fitParticleSphereSigmaDValue_2 = QtWidgets.QDoubleSpinBox(self.fitParticleSpherePage_2)
        self.fitParticleSphereSigmaDValue_2.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleSphereSigmaDValue_2.setObjectName("fitParticleSphereSigmaDValue_2")
        self.gridLayout_27.addWidget(self.fitParticleSphereSigmaDValue_2, 4, 1, 1, 1)
        self.fitParticleSphereRValue_2 = QtWidgets.QDoubleSpinBox(self.fitParticleSpherePage_2)
        self.fitParticleSphereRValue_2.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleSphereRValue_2.setObjectName("fitParticleSphereRValue_2")
        self.gridLayout_27.addWidget(self.fitParticleSphereRValue_2, 1, 1, 1, 1)
        self.fitParticleStackWidget_2.addWidget(self.fitParticleSpherePage_2)
        self.fitParticleCylinderPage_2 = QtWidgets.QWidget()
        self.fitParticleCylinderPage_2.setObjectName("fitParticleCylinderPage_2")
        self.gridLayout_28 = QtWidgets.QGridLayout(self.fitParticleCylinderPage_2)
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.fitParticleCylinderRLabel_2 = QtWidgets.QLabel(self.fitParticleCylinderPage_2)
        self.fitParticleCylinderRLabel_2.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderRLabel_2.setObjectName("fitParticleCylinderRLabel_2")
        self.gridLayout_28.addWidget(self.fitParticleCylinderRLabel_2, 1, 0, 1, 1)
        self.fitParticleCylinderhValue_2 = QtWidgets.QDoubleSpinBox(self.fitParticleCylinderPage_2)
        self.fitParticleCylinderhValue_2.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderhValue_2.setObjectName("fitParticleCylinderhValue_2")
        self.gridLayout_28.addWidget(self.fitParticleCylinderhValue_2, 3, 1, 1, 1)
        self.fitParticleCylinderRValue_2 = QtWidgets.QDoubleSpinBox(self.fitParticleCylinderPage_2)
        self.fitParticleCylinderRValue_2.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderRValue_2.setObjectName("fitParticleCylinderRValue_2")
        self.gridLayout_28.addWidget(self.fitParticleCylinderRValue_2, 1, 1, 1, 1)
        self.fitParticleCylinderIntLabel_2 = QtWidgets.QLabel(self.fitParticleCylinderPage_2)
        self.fitParticleCylinderIntLabel_2.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderIntLabel_2.setObjectName("fitParticleCylinderIntLabel_2")
        self.gridLayout_28.addWidget(self.fitParticleCylinderIntLabel_2, 0, 0, 1, 1)
        self.fitParticleCylinderIntValue_2 = QtWidgets.QDoubleSpinBox(self.fitParticleCylinderPage_2)
        self.fitParticleCylinderIntValue_2.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderIntValue_2.setObjectName("fitParticleCylinderIntValue_2")
        self.gridLayout_28.addWidget(self.fitParticleCylinderIntValue_2, 0, 1, 1, 1)
        self.fitParticleCylinderSigmaDLabel_2 = QtWidgets.QLabel(self.fitParticleCylinderPage_2)
        self.fitParticleCylinderSigmaDLabel_2.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderSigmaDLabel_2.setObjectName("fitParticleCylinderSigmaDLabel_2")
        self.gridLayout_28.addWidget(self.fitParticleCylinderSigmaDLabel_2, 8, 0, 1, 1)
        self.fitParticleCylinderSigmaRValue_2 = QtWidgets.QDoubleSpinBox(self.fitParticleCylinderPage_2)
        self.fitParticleCylinderSigmaRValue_2.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderSigmaRValue_2.setObjectName("fitParticleCylinderSigmaRValue_2")
        self.gridLayout_28.addWidget(self.fitParticleCylinderSigmaRValue_2, 2, 1, 1, 1)
        self.fitParticleCylinderSigmaDValue_2 = QtWidgets.QDoubleSpinBox(self.fitParticleCylinderPage_2)
        self.fitParticleCylinderSigmaDValue_2.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderSigmaDValue_2.setObjectName("fitParticleCylinderSigmaDValue_2")
        self.gridLayout_28.addWidget(self.fitParticleCylinderSigmaDValue_2, 8, 1, 1, 1)
        self.fitParticleCylinderDLabel_2 = QtWidgets.QLabel(self.fitParticleCylinderPage_2)
        self.fitParticleCylinderDLabel_2.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderDLabel_2.setObjectName("fitParticleCylinderDLabel_2")
        self.gridLayout_28.addWidget(self.fitParticleCylinderDLabel_2, 7, 0, 1, 1)
        self.fitParticleCylinderSigmahValue_2 = QtWidgets.QDoubleSpinBox(self.fitParticleCylinderPage_2)
        self.fitParticleCylinderSigmahValue_2.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderSigmahValue_2.setObjectName("fitParticleCylinderSigmahValue_2")
        self.gridLayout_28.addWidget(self.fitParticleCylinderSigmahValue_2, 4, 1, 1, 1)
        self.fitParticleCylinderSigmahLabel_2 = QtWidgets.QLabel(self.fitParticleCylinderPage_2)
        self.fitParticleCylinderSigmahLabel_2.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderSigmahLabel_2.setObjectName("fitParticleCylinderSigmahLabel_2")
        self.gridLayout_28.addWidget(self.fitParticleCylinderSigmahLabel_2, 4, 0, 1, 1)
        self.fitParticleCylinderSigmaRLabel_2 = QtWidgets.QLabel(self.fitParticleCylinderPage_2)
        self.fitParticleCylinderSigmaRLabel_2.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderSigmaRLabel_2.setObjectName("fitParticleCylinderSigmaRLabel_2")
        self.gridLayout_28.addWidget(self.fitParticleCylinderSigmaRLabel_2, 2, 0, 1, 1)
        self.fitParticleCylinderDValue_2 = QtWidgets.QDoubleSpinBox(self.fitParticleCylinderPage_2)
        self.fitParticleCylinderDValue_2.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderDValue_2.setObjectName("fitParticleCylinderDValue_2")
        self.gridLayout_28.addWidget(self.fitParticleCylinderDValue_2, 7, 1, 1, 1)
        self.fitParticleCylinderhLabel_2 = QtWidgets.QLabel(self.fitParticleCylinderPage_2)
        self.fitParticleCylinderhLabel_2.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderhLabel_2.setObjectName("fitParticleCylinderhLabel_2")
        self.gridLayout_28.addWidget(self.fitParticleCylinderhLabel_2, 3, 0, 1, 1)
        self.fitParticleCylinderBGLabel_2 = QtWidgets.QLabel(self.fitParticleCylinderPage_2)
        self.fitParticleCylinderBGLabel_2.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderBGLabel_2.setObjectName("fitParticleCylinderBGLabel_2")
        self.gridLayout_28.addWidget(self.fitParticleCylinderBGLabel_2, 9, 0, 1, 1)
        self.fitParticleCylinderBGValue_2 = QtWidgets.QDoubleSpinBox(self.fitParticleCylinderPage_2)
        self.fitParticleCylinderBGValue_2.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderBGValue_2.setObjectName("fitParticleCylinderBGValue_2")
        self.gridLayout_28.addWidget(self.fitParticleCylinderBGValue_2, 9, 1, 1, 1)
        self.fitParticleStackWidget_2.addWidget(self.fitParticleCylinderPage_2)
        self.verticalLayout_21.addWidget(self.fitParticleStackWidget_2)
        self.horizontalLayout_18.addWidget(self.fitParticleWidget_2)
        self.fitParticleWidget_3 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.fitParticleWidget_3.setMinimumSize(QtCore.QSize(230, 300))
        self.fitParticleWidget_3.setStyleSheet("#fitParticleWidget_3 {\n"
"  border: 1px solid rgba(0,0,0,0.12);  /* 细外框 */\n"
"  border-radius: 12px;                 /* 圆角大小可改 */\n"
"  padding: 8px;                        /* 让内容不贴边 */\n"
"  /* 伪“阴影”：用浅色外描边模拟（Qt 没有 box-shadow） */\n"
"  outline: 6px solid rgba(0,0,0,0.03);\n"
"  outline-offset: -6px;                /* 紧贴边缘 */\n"
"}")
        self.fitParticleWidget_3.setObjectName("fitParticleWidget_3")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.fitParticleWidget_3)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.fitParticleShapeCombox_3 = QtWidgets.QComboBox(self.fitParticleWidget_3)
        self.fitParticleShapeCombox_3.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleShapeCombox_3.setObjectName("fitParticleShapeCombox_3")
        self.fitParticleShapeCombox_3.addItem("")
        self.fitParticleShapeCombox_3.addItem("")
        self.fitParticleShapeCombox_3.addItem("")
        self.verticalLayout_22.addWidget(self.fitParticleShapeCombox_3)
        self.fitParticleStackWidget_3 = QtWidgets.QStackedWidget(self.fitParticleWidget_3)
        self.fitParticleStackWidget_3.setObjectName("fitParticleStackWidget_3")
        self.fitParticleSpherePage_3 = QtWidgets.QWidget()
        self.fitParticleSpherePage_3.setObjectName("fitParticleSpherePage_3")
        self.gridLayout_29 = QtWidgets.QGridLayout(self.fitParticleSpherePage_3)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.fitParticleSphereRValue_3 = QtWidgets.QDoubleSpinBox(self.fitParticleSpherePage_3)
        self.fitParticleSphereRValue_3.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleSphereRValue_3.setObjectName("fitParticleSphereRValue_3")
        self.gridLayout_29.addWidget(self.fitParticleSphereRValue_3, 1, 1, 1, 1)
        self.fitParticleSphereBGValue_3 = QtWidgets.QDoubleSpinBox(self.fitParticleSpherePage_3)
        self.fitParticleSphereBGValue_3.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleSphereBGValue_3.setObjectName("fitParticleSphereBGValue_3")
        self.gridLayout_29.addWidget(self.fitParticleSphereBGValue_3, 5, 1, 1, 1)
        self.fitParticleSphereRLabel_3 = QtWidgets.QLabel(self.fitParticleSpherePage_3)
        self.fitParticleSphereRLabel_3.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleSphereRLabel_3.setObjectName("fitParticleSphereRLabel_3")
        self.gridLayout_29.addWidget(self.fitParticleSphereRLabel_3, 1, 0, 1, 1)
        self.fitParticleSphereSigmaDValue_3 = QtWidgets.QDoubleSpinBox(self.fitParticleSpherePage_3)
        self.fitParticleSphereSigmaDValue_3.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleSphereSigmaDValue_3.setObjectName("fitParticleSphereSigmaDValue_3")
        self.gridLayout_29.addWidget(self.fitParticleSphereSigmaDValue_3, 4, 1, 1, 1)
        self.fitParticleSphereIntValue_3 = QtWidgets.QDoubleSpinBox(self.fitParticleSpherePage_3)
        self.fitParticleSphereIntValue_3.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleSphereIntValue_3.setObjectName("fitParticleSphereIntValue_3")
        self.gridLayout_29.addWidget(self.fitParticleSphereIntValue_3, 0, 1, 1, 1)
        self.fitParticleSphereSigmaRValue_3 = QtWidgets.QDoubleSpinBox(self.fitParticleSpherePage_3)
        self.fitParticleSphereSigmaRValue_3.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleSphereSigmaRValue_3.setObjectName("fitParticleSphereSigmaRValue_3")
        self.gridLayout_29.addWidget(self.fitParticleSphereSigmaRValue_3, 2, 1, 1, 1)
        self.fitParticleSphereIntLabel_3 = QtWidgets.QLabel(self.fitParticleSpherePage_3)
        self.fitParticleSphereIntLabel_3.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleSphereIntLabel_3.setObjectName("fitParticleSphereIntLabel_3")
        self.gridLayout_29.addWidget(self.fitParticleSphereIntLabel_3, 0, 0, 1, 1)
        self.fitParticleSphereDValue_3 = QtWidgets.QDoubleSpinBox(self.fitParticleSpherePage_3)
        self.fitParticleSphereDValue_3.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleSphereDValue_3.setObjectName("fitParticleSphereDValue_3")
        self.gridLayout_29.addWidget(self.fitParticleSphereDValue_3, 3, 1, 1, 1)
        self.fitParticleSphereSigmaDLabel_3 = QtWidgets.QLabel(self.fitParticleSpherePage_3)
        self.fitParticleSphereSigmaDLabel_3.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleSphereSigmaDLabel_3.setObjectName("fitParticleSphereSigmaDLabel_3")
        self.gridLayout_29.addWidget(self.fitParticleSphereSigmaDLabel_3, 4, 0, 1, 1)
        self.fitParticleSphereSigmaRLabel_3 = QtWidgets.QLabel(self.fitParticleSpherePage_3)
        self.fitParticleSphereSigmaRLabel_3.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleSphereSigmaRLabel_3.setObjectName("fitParticleSphereSigmaRLabel_3")
        self.gridLayout_29.addWidget(self.fitParticleSphereSigmaRLabel_3, 2, 0, 1, 1)
        self.fitParticleSphereDLabel_3 = QtWidgets.QLabel(self.fitParticleSpherePage_3)
        self.fitParticleSphereDLabel_3.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleSphereDLabel_3.setObjectName("fitParticleSphereDLabel_3")
        self.gridLayout_29.addWidget(self.fitParticleSphereDLabel_3, 3, 0, 1, 1)
        self.fitParticleSphereBGLabel_3 = QtWidgets.QLabel(self.fitParticleSpherePage_3)
        self.fitParticleSphereBGLabel_3.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleSphereBGLabel_3.setObjectName("fitParticleSphereBGLabel_3")
        self.gridLayout_29.addWidget(self.fitParticleSphereBGLabel_3, 5, 0, 1, 1)
        self.fitParticleStackWidget_3.addWidget(self.fitParticleSpherePage_3)
        self.fitParticleCylinderPage_3 = QtWidgets.QWidget()
        self.fitParticleCylinderPage_3.setObjectName("fitParticleCylinderPage_3")
        self.gridLayout_30 = QtWidgets.QGridLayout(self.fitParticleCylinderPage_3)
        self.gridLayout_30.setObjectName("gridLayout_30")
        self.fitParticleCylinderSigmaRLabel_3 = QtWidgets.QLabel(self.fitParticleCylinderPage_3)
        self.fitParticleCylinderSigmaRLabel_3.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderSigmaRLabel_3.setObjectName("fitParticleCylinderSigmaRLabel_3")
        self.gridLayout_30.addWidget(self.fitParticleCylinderSigmaRLabel_3, 2, 0, 1, 1)
        self.fitParticleCylinderBGLabel_3 = QtWidgets.QLabel(self.fitParticleCylinderPage_3)
        self.fitParticleCylinderBGLabel_3.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderBGLabel_3.setObjectName("fitParticleCylinderBGLabel_3")
        self.gridLayout_30.addWidget(self.fitParticleCylinderBGLabel_3, 9, 0, 1, 1)
        self.fitParticleCylinderSigmahValue_3 = QtWidgets.QDoubleSpinBox(self.fitParticleCylinderPage_3)
        self.fitParticleCylinderSigmahValue_3.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderSigmahValue_3.setObjectName("fitParticleCylinderSigmahValue_3")
        self.gridLayout_30.addWidget(self.fitParticleCylinderSigmahValue_3, 4, 1, 1, 1)
        self.fitParticleCylinderDValue_3 = QtWidgets.QDoubleSpinBox(self.fitParticleCylinderPage_3)
        self.fitParticleCylinderDValue_3.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderDValue_3.setObjectName("fitParticleCylinderDValue_3")
        self.gridLayout_30.addWidget(self.fitParticleCylinderDValue_3, 7, 1, 1, 1)
        self.fitParticleCylinderBGValue_3 = QtWidgets.QDoubleSpinBox(self.fitParticleCylinderPage_3)
        self.fitParticleCylinderBGValue_3.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderBGValue_3.setObjectName("fitParticleCylinderBGValue_3")
        self.gridLayout_30.addWidget(self.fitParticleCylinderBGValue_3, 9, 1, 1, 1)
        self.fitParticleCylinderRValue_3 = QtWidgets.QDoubleSpinBox(self.fitParticleCylinderPage_3)
        self.fitParticleCylinderRValue_3.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderRValue_3.setObjectName("fitParticleCylinderRValue_3")
        self.gridLayout_30.addWidget(self.fitParticleCylinderRValue_3, 1, 1, 1, 1)
        self.fitParticleCylinderIntValue_3 = QtWidgets.QDoubleSpinBox(self.fitParticleCylinderPage_3)
        self.fitParticleCylinderIntValue_3.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderIntValue_3.setObjectName("fitParticleCylinderIntValue_3")
        self.gridLayout_30.addWidget(self.fitParticleCylinderIntValue_3, 0, 1, 1, 1)
        self.fitParticleCylinderIntLabel_3 = QtWidgets.QLabel(self.fitParticleCylinderPage_3)
        self.fitParticleCylinderIntLabel_3.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderIntLabel_3.setObjectName("fitParticleCylinderIntLabel_3")
        self.gridLayout_30.addWidget(self.fitParticleCylinderIntLabel_3, 0, 0, 1, 1)
        self.fitParticleCylinderRLabel_3 = QtWidgets.QLabel(self.fitParticleCylinderPage_3)
        self.fitParticleCylinderRLabel_3.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderRLabel_3.setObjectName("fitParticleCylinderRLabel_3")
        self.gridLayout_30.addWidget(self.fitParticleCylinderRLabel_3, 1, 0, 1, 1)
        self.fitParticleCylinderhLabel_3 = QtWidgets.QLabel(self.fitParticleCylinderPage_3)
        self.fitParticleCylinderhLabel_3.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderhLabel_3.setObjectName("fitParticleCylinderhLabel_3")
        self.gridLayout_30.addWidget(self.fitParticleCylinderhLabel_3, 3, 0, 1, 1)
        self.fitParticleCylinderSigmahLabel_3 = QtWidgets.QLabel(self.fitParticleCylinderPage_3)
        self.fitParticleCylinderSigmahLabel_3.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderSigmahLabel_3.setObjectName("fitParticleCylinderSigmahLabel_3")
        self.gridLayout_30.addWidget(self.fitParticleCylinderSigmahLabel_3, 4, 0, 1, 1)
        self.fitParticleCylinderSigmaDLabel_3 = QtWidgets.QLabel(self.fitParticleCylinderPage_3)
        self.fitParticleCylinderSigmaDLabel_3.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderSigmaDLabel_3.setObjectName("fitParticleCylinderSigmaDLabel_3")
        self.gridLayout_30.addWidget(self.fitParticleCylinderSigmaDLabel_3, 8, 0, 1, 1)
        self.fitParticleCylinderSigmaRValue_3 = QtWidgets.QDoubleSpinBox(self.fitParticleCylinderPage_3)
        self.fitParticleCylinderSigmaRValue_3.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderSigmaRValue_3.setObjectName("fitParticleCylinderSigmaRValue_3")
        self.gridLayout_30.addWidget(self.fitParticleCylinderSigmaRValue_3, 2, 1, 1, 1)
        self.fitParticleCylinderSigmaDValue_3 = QtWidgets.QDoubleSpinBox(self.fitParticleCylinderPage_3)
        self.fitParticleCylinderSigmaDValue_3.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderSigmaDValue_3.setObjectName("fitParticleCylinderSigmaDValue_3")
        self.gridLayout_30.addWidget(self.fitParticleCylinderSigmaDValue_3, 8, 1, 1, 1)
        self.fitParticleCylinderDLabel_3 = QtWidgets.QLabel(self.fitParticleCylinderPage_3)
        self.fitParticleCylinderDLabel_3.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderDLabel_3.setObjectName("fitParticleCylinderDLabel_3")
        self.gridLayout_30.addWidget(self.fitParticleCylinderDLabel_3, 7, 0, 1, 1)
        self.fitParticleCylinderhValue_3 = QtWidgets.QDoubleSpinBox(self.fitParticleCylinderPage_3)
        self.fitParticleCylinderhValue_3.setMinimumSize(QtCore.QSize(0, 20))
        self.fitParticleCylinderhValue_3.setObjectName("fitParticleCylinderhValue_3")
        self.gridLayout_30.addWidget(self.fitParticleCylinderhValue_3, 3, 1, 1, 1)
        self.fitParticleStackWidget_3.addWidget(self.fitParticleCylinderPage_3)
        self.verticalLayout_22.addWidget(self.fitParticleStackWidget_3)
        self.horizontalLayout_18.addWidget(self.fitParticleWidget_3)
        self.addModelButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(30)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.addModelButton.sizePolicy().hasHeightForWidth())
        self.addModelButton.setSizePolicy(sizePolicy)
        self.addModelButton.setMinimumSize(QtCore.QSize(30, 30))
        self.addModelButton.setMaximumSize(QtCore.QSize(30, 30))
        self.addModelButton.setObjectName("addModelButton")
        self.horizontalLayout_18.addWidget(self.addModelButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_17.addWidget(self.scrollArea)
        self.gridLayout_24.addWidget(self.widget_7, 2, 0, 1, 3)
        self.curvePlotControlWidget = QtWidgets.QWidget(self.fitBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.curvePlotControlWidget.sizePolicy().hasHeightForWidth())
        self.curvePlotControlWidget.setSizePolicy(sizePolicy)
        self.curvePlotControlWidget.setMinimumSize(QtCore.QSize(420, 0))
        self.curvePlotControlWidget.setMaximumSize(QtCore.QSize(420, 16777215))
        self.curvePlotControlWidget.setStyleSheet("#curvePlotControlWidget {\n"
"  border: 1px solid rgba(0,0,0,0.12);  /* 细外框 */\n"
"  padding: 8px;                        /* 让内容不贴边 */\n"
"  /* 伪“阴影”：用浅色外描边模拟（Qt 没有 box-shadow） */\n"
"  outline: 6px solid rgba(0,0,0,0.03);\n"
"  outline-offset: -6px;                /* 紧贴边缘 */\n"
"}")
        self.curvePlotControlWidget.setObjectName("curvePlotControlWidget")
        self.gridLayout_33 = QtWidgets.QGridLayout(self.curvePlotControlWidget)
        self.gridLayout_33.setObjectName("gridLayout_33")
        self.fitDataPointsNumWidget = QtWidgets.QWidget(self.curvePlotControlWidget)
        self.fitDataPointsNumWidget.setMaximumSize(QtCore.QSize(100000, 16777215))
        self.fitDataPointsNumWidget.setObjectName("fitDataPointsNumWidget")
        self.gridLayout_42 = QtWidgets.QGridLayout(self.fitDataPointsNumWidget)
        self.gridLayout_42.setObjectName("gridLayout_42")
        self.fitInterpolationMethodLabel = QtWidgets.QLabel(self.fitDataPointsNumWidget)
        self.fitInterpolationMethodLabel.setObjectName("fitInterpolationMethodLabel")
        self.gridLayout_42.addWidget(self.fitInterpolationMethodLabel, 2, 0, 1, 1)
        self.fitDataPointsNumLabel = QtWidgets.QLabel(self.fitDataPointsNumWidget)
        self.fitDataPointsNumLabel.setObjectName("fitDataPointsNumLabel")
        self.gridLayout_42.addWidget(self.fitDataPointsNumLabel, 0, 0, 1, 1)
        self.fitDataPointsNumValue = QtWidgets.QSpinBox(self.fitDataPointsNumWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fitDataPointsNumValue.sizePolicy().hasHeightForWidth())
        self.fitDataPointsNumValue.setSizePolicy(sizePolicy)
        self.fitDataPointsNumValue.setMaximumSize(QtCore.QSize(80, 20))
        self.fitDataPointsNumValue.setObjectName("fitDataPointsNumValue")
        self.gridLayout_42.addWidget(self.fitDataPointsNumValue, 1, 0, 1, 1)
        self.fitInterpolationMethodValue = QtWidgets.QComboBox(self.fitDataPointsNumWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fitInterpolationMethodValue.sizePolicy().hasHeightForWidth())
        self.fitInterpolationMethodValue.setSizePolicy(sizePolicy)
        self.fitInterpolationMethodValue.setMaximumSize(QtCore.QSize(16777215, 20))
        self.fitInterpolationMethodValue.setObjectName("fitInterpolationMethodValue")
        self.gridLayout_42.addWidget(self.fitInterpolationMethodValue, 3, 0, 1, 1)
        self.gridLayout_33.addWidget(self.fitDataPointsNumWidget, 3, 0, 1, 1)
        self.fitFittingRegionwidget = QtWidgets.QWidget(self.curvePlotControlWidget)
        self.fitFittingRegionwidget.setMaximumSize(QtCore.QSize(16777215, 80))
        self.fitFittingRegionwidget.setStyleSheet("#fitFittingRegionwidget {\n"
"  border: 1px solid rgba(0,0,0,0.12);  /* 细外框 */\n"
"  border-radius: 12px;                 /* 圆角大小可改 */\n"
"  padding: 8px;                        /* 让内容不贴边 */\n"
"  /* 伪“阴影”：用浅色外描边模拟（Qt 没有 box-shadow） */\n"
"  outline: 6px solid rgba(0,0,0,0.03);\n"
"  outline-offset: -6px;                /* 紧贴边缘 */\n"
"}")
        self.fitFittingRegionwidget.setObjectName("fitFittingRegionwidget")
        self.gridLayout_41 = QtWidgets.QGridLayout(self.fitFittingRegionwidget)
        self.gridLayout_41.setObjectName("gridLayout_41")
        self.fitFittingRegionSlider = QRangeSlider(self.fitFittingRegionwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fitFittingRegionSlider.sizePolicy().hasHeightForWidth())
        self.fitFittingRegionSlider.setSizePolicy(sizePolicy)
        self.fitFittingRegionSlider.setMinimumSize(QtCore.QSize(0, 20))
        self.fitFittingRegionSlider.setOrientation(QtCore.Qt.Horizontal)
        self.fitFittingRegionSlider.setObjectName("fitFittingRegionSlider")
        self.gridLayout_41.addWidget(self.fitFittingRegionSlider, 1, 1, 1, 1)
        self.fitFittingRegionValueWidget = QtWidgets.QWidget(self.fitFittingRegionwidget)
        self.fitFittingRegionValueWidget.setMinimumSize(QtCore.QSize(0, 35))
        self.fitFittingRegionValueWidget.setObjectName("fitFittingRegionValueWidget")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.fitFittingRegionValueWidget)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.fitFittingRegionMinValue = QtWidgets.QDoubleSpinBox(self.fitFittingRegionValueWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fitFittingRegionMinValue.sizePolicy().hasHeightForWidth())
        self.fitFittingRegionMinValue.setSizePolicy(sizePolicy)
        self.fitFittingRegionMinValue.setMinimumSize(QtCore.QSize(0, 20))
        self.fitFittingRegionMinValue.setMaximumSize(QtCore.QSize(16777215, 20))
        self.fitFittingRegionMinValue.setObjectName("fitFittingRegionMinValue")
        self.horizontalLayout_14.addWidget(self.fitFittingRegionMinValue)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem2)
        self.fitFittingRegionMaxValue = QtWidgets.QDoubleSpinBox(self.fitFittingRegionValueWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fitFittingRegionMaxValue.sizePolicy().hasHeightForWidth())
        self.fitFittingRegionMaxValue.setSizePolicy(sizePolicy)
        self.fitFittingRegionMaxValue.setMinimumSize(QtCore.QSize(0, 20))
        self.fitFittingRegionMaxValue.setMaximumSize(QtCore.QSize(16777215, 20))
        self.fitFittingRegionMaxValue.setObjectName("fitFittingRegionMaxValue")
        self.horizontalLayout_14.addWidget(self.fitFittingRegionMaxValue)
        self.gridLayout_41.addWidget(self.fitFittingRegionValueWidget, 2, 1, 1, 1)
        self.fitFittingRegionLabel = QtWidgets.QLabel(self.fitFittingRegionwidget)
        self.fitFittingRegionLabel.setMinimumSize(QtCore.QSize(0, 20))
        self.fitFittingRegionLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        self.fitFittingRegionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.fitFittingRegionLabel.setObjectName("fitFittingRegionLabel")
        self.gridLayout_41.addWidget(self.fitFittingRegionLabel, 1, 0, 1, 1)
        self.gridLayout_33.addWidget(self.fitFittingRegionwidget, 1, 0, 1, 3)
        self.fitFittingShowWidget = QtWidgets.QWidget(self.curvePlotControlWidget)
        self.fitFittingShowWidget.setMinimumSize(QtCore.QSize(250, 0))
        self.fitFittingShowWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.fitFittingShowWidget.setObjectName("fitFittingShowWidget")
        self.gridLayout_40 = QtWidgets.QGridLayout(self.fitFittingShowWidget)
        self.gridLayout_40.setObjectName("gridLayout_40")
        self.fitBGShowCheckBox = QtWidgets.QCheckBox(self.fitFittingShowWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fitBGShowCheckBox.sizePolicy().hasHeightForWidth())
        self.fitBGShowCheckBox.setSizePolicy(sizePolicy)
        self.fitBGShowCheckBox.setObjectName("fitBGShowCheckBox")
        self.gridLayout_40.addWidget(self.fitBGShowCheckBox, 2, 0, 1, 1)
        self.fitDisplayOptionsLabel = QtWidgets.QLabel(self.fitFittingShowWidget)
        self.fitDisplayOptionsLabel.setObjectName("fitDisplayOptionsLabel")
        self.gridLayout_40.addWidget(self.fitDisplayOptionsLabel, 0, 0, 1, 3)
        self.fitResShowCheckBox = QtWidgets.QCheckBox(self.fitFittingShowWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fitResShowCheckBox.sizePolicy().hasHeightForWidth())
        self.fitResShowCheckBox.setSizePolicy(sizePolicy)
        self.fitResShowCheckBox.setObjectName("fitResShowCheckBox")
        self.gridLayout_40.addWidget(self.fitResShowCheckBox, 3, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_40.addItem(spacerItem3, 4, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_40.addItem(spacerItem4, 1, 0, 1, 1)
        self.ParticlesNumWidget = QtWidgets.QWidget(self.fitFittingShowWidget)
        self.ParticlesNumWidget.setObjectName("ParticlesNumWidget")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.ParticlesNumWidget)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.fitParticle1ShowCheckBox = QtWidgets.QCheckBox(self.ParticlesNumWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fitParticle1ShowCheckBox.sizePolicy().hasHeightForWidth())
        self.fitParticle1ShowCheckBox.setSizePolicy(sizePolicy)
        self.fitParticle1ShowCheckBox.setObjectName("fitParticle1ShowCheckBox")
        self.verticalLayout_26.addWidget(self.fitParticle1ShowCheckBox)
        self.fitParticle2ShowCheckBox = QtWidgets.QCheckBox(self.ParticlesNumWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fitParticle2ShowCheckBox.sizePolicy().hasHeightForWidth())
        self.fitParticle2ShowCheckBox.setSizePolicy(sizePolicy)
        self.fitParticle2ShowCheckBox.setObjectName("fitParticle2ShowCheckBox")
        self.verticalLayout_26.addWidget(self.fitParticle2ShowCheckBox)
        self.fitParticle3ShowCheckBox = QtWidgets.QCheckBox(self.ParticlesNumWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fitParticle3ShowCheckBox.sizePolicy().hasHeightForWidth())
        self.fitParticle3ShowCheckBox.setSizePolicy(sizePolicy)
        self.fitParticle3ShowCheckBox.setObjectName("fitParticle3ShowCheckBox")
        self.verticalLayout_26.addWidget(self.fitParticle3ShowCheckBox)
        self.gridLayout_40.addWidget(self.ParticlesNumWidget, 1, 1, 4, 2)
        self.gridLayout_33.addWidget(self.fitFittingShowWidget, 3, 1, 1, 2)
        self.fitGraphicsView = QtWidgets.QGraphicsView(self.curvePlotControlWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fitGraphicsView.sizePolicy().hasHeightForWidth())
        self.fitGraphicsView.setSizePolicy(sizePolicy)
        self.fitGraphicsView.setMinimumSize(QtCore.QSize(400, 300))
        self.fitGraphicsView.setMaximumSize(QtCore.QSize(400, 16777215))
        self.fitGraphicsView.setStyleSheet("QGraphicsView {\n"
"    background: transparent;\n"
"    border: 1px solid #888888; \n"
"    border-radius: 4px;  \n"
"}")
        self.fitGraphicsView.setObjectName("fitGraphicsView")
        self.gridLayout_33.addWidget(self.fitGraphicsView, 0, 0, 1, 1)
        self.gridLayout_24.addWidget(self.curvePlotControlWidget, 0, 3, 6, 1)
        self.fitMethodWidget = QtWidgets.QWidget(self.fitBox)
        self.fitMethodWidget.setMinimumSize(QtCore.QSize(0, 100))
        self.fitMethodWidget.setObjectName("fitMethodWidget")
        self.gridLayout_37 = QtWidgets.QGridLayout(self.fitMethodWidget)
        self.gridLayout_37.setObjectName("gridLayout_37")
        self.fitMethodLabel = QtWidgets.QLabel(self.fitMethodWidget)
        self.fitMethodLabel.setMinimumSize(QtCore.QSize(0, 20))
        self.fitMethodLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.fitMethodLabel.setObjectName("fitMethodLabel")
        self.gridLayout_37.addWidget(self.fitMethodLabel, 0, 0, 1, 1)
        self.FittingAutoFittingButton = QtWidgets.QPushButton(self.fitMethodWidget)
        self.FittingAutoFittingButton.setMinimumSize(QtCore.QSize(50, 20))
        self.FittingAutoFittingButton.setObjectName("FittingAutoFittingButton")
        self.gridLayout_37.addWidget(self.FittingAutoFittingButton, 2, 3, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_37.addItem(spacerItem5, 2, 2, 1, 1)
        self.fitMethodValue = QtWidgets.QComboBox(self.fitMethodWidget)
        self.fitMethodValue.setObjectName("fitMethodValue")
        self.fitMethodValue.addItem("")
        self.fitMethodValue.addItem("")
        self.fitMethodValue.addItem("")
        self.fitMethodValue.addItem("")
        self.fitMethodValue.addItem("")
        self.gridLayout_37.addWidget(self.fitMethodValue, 0, 1, 1, 3)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_37.addItem(spacerItem6, 1, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_37.addItem(spacerItem7, 2, 1, 1, 1)
        self.FittingClearFittingButton_2 = QtWidgets.QPushButton(self.fitMethodWidget)
        self.FittingClearFittingButton_2.setMinimumSize(QtCore.QSize(50, 20))
        self.FittingClearFittingButton_2.setObjectName("FittingClearFittingButton_2")
        self.gridLayout_37.addWidget(self.FittingClearFittingButton_2, 2, 0, 1, 1)
        self.FittingAutoKButton = QtWidgets.QPushButton(self.fitMethodWidget)
        self.FittingAutoKButton.setMinimumSize(QtCore.QSize(50, 20))
        self.FittingAutoKButton.setObjectName("FittingAutoKButton")
        self.gridLayout_37.addWidget(self.FittingAutoKButton, 1, 0, 1, 1)
        self.gridLayout_24.addWidget(self.fitMethodWidget, 4, 1, 2, 2)
        self.widget_8 = QtWidgets.QWidget(self.fitBox)
        self.widget_8.setMinimumSize(QtCore.QSize(0, 40))
        self.widget_8.setObjectName("widget_8")
        self.gridLayout_32 = QtWidgets.QGridLayout(self.widget_8)
        self.gridLayout_32.setObjectName("gridLayout_32")
        self.fitSigmaResLabel = QtWidgets.QLabel(self.widget_8)
        self.fitSigmaResLabel.setObjectName("fitSigmaResLabel")
        self.gridLayout_32.addWidget(self.fitSigmaResLabel, 0, 0, 1, 1)
        self.fitSigmaResValue = QtWidgets.QDoubleSpinBox(self.widget_8)
        self.fitSigmaResValue.setMinimumSize(QtCore.QSize(0, 20))
        self.fitSigmaResValue.setObjectName("fitSigmaResValue")
        self.gridLayout_32.addWidget(self.fitSigmaResValue, 0, 1, 1, 1)
        self.fitNuResLabel = QtWidgets.QLabel(self.widget_8)
        self.fitNuResLabel.setObjectName("fitNuResLabel")
        self.gridLayout_32.addWidget(self.fitNuResLabel, 0, 2, 1, 1)
        self.fitNuResValue = QtWidgets.QDoubleSpinBox(self.widget_8)
        self.fitNuResValue.setMinimumSize(QtCore.QSize(0, 20))
        self.fitNuResValue.setObjectName("fitNuResValue")
        self.gridLayout_32.addWidget(self.fitNuResValue, 0, 3, 1, 1)
        self.gridLayout_24.addWidget(self.widget_8, 3, 0, 1, 3)
        self.gridLayout_38.addWidget(self.fitBox, 1, 0, 1, 1)
        self.gisaxsFittingPageScrollArea.setWidget(self.gisaxsFittingPageScrollAreaWidgetContents)
        self.verticalLayout_19.addWidget(self.gisaxsFittingPageScrollArea)
        self.FittingTextBrowser = QtWidgets.QTextBrowser(gisaxsFittingPage)
        self.FittingTextBrowser.setMinimumSize(QtCore.QSize(0, 0))
        self.FittingTextBrowser.setMaximumSize(QtCore.QSize(16777215, 100))
        self.FittingTextBrowser.setStyleSheet("QTextBrowser {\n"
"  background: rgba(255,255,255,0.75);\n"
"  color: #1d2433;\n"
"\n"
"  font-size: 13px;\n"
"  border: 1px solid rgba(0,0,0,0.06);\n"
"  border-radius: 14px;\n"
"  padding: 14px 16px;\n"
"}\n"
"\n"
"QScrollBar:vertical { width: 8px; background: transparent; }\n"
"QScrollBar::handle:vertical { background: rgba(0,0,0,0.18); border-radius: 4px; }\n"
"QScrollBar::handle:vertical:hover { background: rgba(0,0,0,0.28); }QTextBrowser {\n"
"  background: rgba(255,255,255,0.75);\n"
"  color: #1d2433;\n"
"\n"
"  font-size: 13px;\n"
"  border: 1px solid rgba(0,0,0,0.06);\n"
"  border-radius: 14px;\n"
"  padding: 14px 16px;\n"
"}\n"
"\n"
"QScrollBar:vertical { width: 8px; background: transparent; }\n"
"QScrollBar::handle:vertical { background: rgba(0,0,0,0.18); border-radius: 4px; }\n"
"QScrollBar::handle:vertical:hover { background: rgba(0,0,0,0.28); }")
        self.FittingTextBrowser.setObjectName("FittingTextBrowser")
        self.verticalLayout_19.addWidget(self.FittingTextBrowser)

        self.retranslateUi(gisaxsFittingPage)
        self.fitParticleStackWidget_1.setCurrentIndex(1)
        self.fitParticleStackWidget_2.setCurrentIndex(0)
        self.fitParticleStackWidget_3.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(gisaxsFittingPage)

    def retranslateUi(self, gisaxsFittingPage):
        _translate = QtCore.QCoreApplication.translate
        self.gisaxsInputBox.setTitle(_translate("FittingPage", "GIMaP Input"))
        self.gisaxsInputCutLineLabel.setText(_translate("FittingPage", "Cut line:"))
        self.gisaxsInputColorScaleLabel.setText(_translate("FittingPage", "Color Scale:"))
        self.gisaxsInputImportButton.setText(_translate("FittingPage", "Import GISAXS"))
        self.gisaxsInputCenterAutoFindingButton.setText(_translate("FittingPage", "Auto Finding"))
        self.gisaxsInputVminLabel.setText(_translate("FittingPage", "Vmin:"))
        self.gisaxsInputStackValue.setText(_translate("FittingPage", "1"))
        self.gisaxsInputCenterVerticalLabel.setText(_translate("FittingPage", "Vertical."))
        self.gisaxsInputCenterParallelLabel.setText(_translate("FittingPage", "Parallel."))
        self.gisaxsInputAutoScaleCheckBox.setText(_translate("FittingPage", "Auto Scale"))
        self.gisaxsInputIntLogCheckBox.setText(_translate("FittingPage", "Int. Log"))
        self.gisaxsInputAutoShowCheckBox.setText(_translate("FittingPage", "Auto Show"))
        self.gisaxsInputShowButton.setText(_translate("FittingPage", "Show >"))
        self.gisaxsInputCutButton.setText(_translate("FittingPage", "Cut"))
        self.gisaxsInputVmaxLabel.setText(_translate("FittingPage", "Vmax:"))
        self.gisaxsInputCutLineVerticalLabel.setText(_translate("FittingPage", "Vertical."))
        self.gisaxsInputCutLineParallelLabel.setText(_translate("FittingPage", "Parallel."))
        self.gisaxsInputCenterLabel.setText(_translate("FittingPage", "Center:"))
        self.gisaxsInputDetectorParaButton.setText(_translate("FittingPage", "Detector Para."))
        self.gisaxsInputModelCombox.setItemText(0, _translate("FittingPage", "Single"))
        self.gisaxsInputModelCombox.setItemText(1, _translate("FittingPage", "Stack"))
        self.gisaxsInputModelCombox.setItemText(2, _translate("FittingPage", "In-situ"))
        self.fitBox.setTitle(_translate("FittingPage", "Fitting"))
        self.fitKLabel.setText(_translate("FittingPage", "k"))
        self.FittingManualFittingButton.setText(_translate("FittingPage", "Manual Fitting"))
        self.fitIntResLabel.setText(_translate("FittingPage", "Int [Res.]"))
        self.fitImport1dFileButton.setText(_translate("FittingPage", "Import 1D File"))
        self.fitCurrentDataCheckBox.setText(_translate("FittingPage", "GISAXS Data"))
        self.fitLogXCheckBox.setText(_translate("FittingPage", "Log-x"))
        self.fitLogYCheckBox.setText(_translate("FittingPage", "Log-y"))
        self.fitNormCheckBox.setText(_translate("FittingPage", "Norm"))
        self.FittingExportButton.setText(_translate("FittingPage", "Export"))
        self.fitParticleShapeCombox_1.setItemText(0, _translate("FittingPage", "Sphere"))
        self.fitParticleShapeCombox_1.setItemText(1, _translate("FittingPage", "Cylinder"))
        self.fitParticleShapeCombox_1.setItemText(2, _translate("FittingPage", "None"))
        self.fitParticleSphereDLabel_1.setText(_translate("FittingPage", "D [nm]"))
        self.fitParticleSphereSigmaDLabel_1.setText(_translate("FittingPage", "σ [D]"))
        self.fitParticleSphereRLabel_1.setText(_translate("FittingPage", "R [nm]"))
        self.fitParticleSphereBGLabel_1.setText(_translate("FittingPage", "BG"))
        self.fitParticleSphereSigmaRLabel_1.setText(_translate("FittingPage", "σ [R]"))
        self.fitParticleSphereIntLabel_1.setText(_translate("FittingPage", "Int."))
        self.fitParticleCylinderSigmaDLabel_1.setText(_translate("FittingPage", "σ [D]"))
        self.fitParticleCylinderRLabel_1.setText(_translate("FittingPage", "R [nm]"))
        self.fitParticleCylinderDLabel_1.setText(_translate("FittingPage", "D [nm]"))
        self.fitParticleCylinderIntLabel_1.setText(_translate("FittingPage", "Int."))
        self.fitParticleCylinderhLabel_1.setText(_translate("FittingPage", "h [nm]"))
        self.fitParticleCylinderSigmaRLabel_1.setText(_translate("FittingPage", "σ [R]"))
        self.fitParticleCylinderBGLabel_1.setText(_translate("FittingPage", "BG"))
        self.fitParticleCylinderSigmahLabel_1.setText(_translate("FittingPage", "σ [h]"))
        self.fitParticleShapeCombox_2.setItemText(0, _translate("FittingPage", "Sphere"))
        self.fitParticleShapeCombox_2.setItemText(1, _translate("FittingPage", "Cylinder"))
        self.fitParticleShapeCombox_2.setItemText(2, _translate("FittingPage", "None"))
        self.fitParticleSphereDLabel_2.setText(_translate("FittingPage", "D [nm]"))
        self.fitParticleSphereSigmaDLabel_2.setText(_translate("FittingPage", "σ [D]"))
        self.fitParticleSphereRLabel_2.setText(_translate("FittingPage", "R [nm]"))
        self.fitParticleSphereSigmaRLabel_2.setText(_translate("FittingPage", "σ [R]"))
        self.fitParticleSphereIntLabel_2.setText(_translate("FittingPage", "Int."))
        self.fitParticleSphereBGLabel_2.setText(_translate("FittingPage", "BG"))
        self.fitParticleCylinderRLabel_2.setText(_translate("FittingPage", "R [nm]"))
        self.fitParticleCylinderIntLabel_2.setText(_translate("FittingPage", "Int."))
        self.fitParticleCylinderSigmaDLabel_2.setText(_translate("FittingPage", "σ [D]"))
        self.fitParticleCylinderDLabel_2.setText(_translate("FittingPage", "D [nm]"))
        self.fitParticleCylinderSigmahLabel_2.setText(_translate("FittingPage", "σ [h]"))
        self.fitParticleCylinderSigmaRLabel_2.setText(_translate("FittingPage", "σ [R]"))
        self.fitParticleCylinderhLabel_2.setText(_translate("FittingPage", "h [nm]"))
        self.fitParticleCylinderBGLabel_2.setText(_translate("FittingPage", "BG"))
        self.fitParticleShapeCombox_3.setItemText(0, _translate("FittingPage", "Sphere"))
        self.fitParticleShapeCombox_3.setItemText(1, _translate("FittingPage", "Cylinder"))
        self.fitParticleShapeCombox_3.setItemText(2, _translate("FittingPage", "None"))
        self.fitParticleSphereRLabel_3.setText(_translate("FittingPage", "R [nm]"))
        self.fitParticleSphereIntLabel_3.setText(_translate("FittingPage", "Int."))
        self.fitParticleSphereSigmaDLabel_3.setText(_translate("FittingPage", "σ [D]"))
        self.fitParticleSphereSigmaRLabel_3.setText(_translate("FittingPage", "σ [R]"))
        self.fitParticleSphereDLabel_3.setText(_translate("FittingPage", "D [nm]"))
        self.fitParticleSphereBGLabel_3.setText(_translate("FittingPage", "BG"))
        self.fitParticleCylinderSigmaRLabel_3.setText(_translate("FittingPage", "σ [R]"))
        self.fitParticleCylinderBGLabel_3.setText(_translate("FittingPage", "BG"))
        self.fitParticleCylinderIntLabel_3.setText(_translate("FittingPage", "Int."))
        self.fitParticleCylinderRLabel_3.setText(_translate("FittingPage", "R [nm]"))
        self.fitParticleCylinderhLabel_3.setText(_translate("FittingPage", "h [nm]"))
        self.fitParticleCylinderSigmahLabel_3.setText(_translate("FittingPage", "σ [h]"))
        self.fitParticleCylinderSigmaDLabel_3.setText(_translate("FittingPage", "σ [D]"))
        self.fitParticleCylinderDLabel_3.setText(_translate("FittingPage", "D [nm]"))
        self.addModelButton.setText(_translate("FittingPage", "+"))
        self.fitInterpolationMethodLabel.setText(_translate("FittingPage", "Interpolation method:"))
        self.fitDataPointsNumLabel.setText(_translate("FittingPage", "Data Points Num.:"))
        self.fitFittingRegionLabel.setText(_translate("FittingPage", "Fitting Region"))
        self.fitBGShowCheckBox.setText(_translate("FittingPage", "BG"))
        self.fitDisplayOptionsLabel.setText(_translate("FittingPage", "Options displayed in the figure:"))
        self.fitResShowCheckBox.setText(_translate("FittingPage", "Res. Function"))
        self.fitParticle1ShowCheckBox.setText(_translate("FittingPage", "Particle 1"))
        self.fitParticle2ShowCheckBox.setText(_translate("FittingPage", "Particle 2"))
        self.fitParticle3ShowCheckBox.setText(_translate("FittingPage", "Particle 3"))
        self.fitMethodLabel.setText(_translate("FittingPage", "Method"))
        self.FittingAutoFittingButton.setText(_translate("FittingPage", "Auto Fitting"))
        self.fitMethodValue.setItemText(0, _translate("FittingPage", "Model: 1 Sphere"))
        self.fitMethodValue.setItemText(1, _translate("FittingPage", "Model: 2 Sphere"))
        self.fitMethodValue.setItemText(2, _translate("FittingPage", "Model: 3 Sphere"))
        self.fitMethodValue.setItemText(3, _translate("FittingPage", "Model: 1 Sphere + 1Cylinder"))
        self.fitMethodValue.setItemText(4, _translate("FittingPage", "Genetic Algorithm, GA"))
        self.FittingClearFittingButton_2.setText(_translate("FittingPage", "Clear Fitting"))
        self.FittingAutoKButton.setText(_translate("FittingPage", "<- Auto-K: OFF"))
        self.fitSigmaResLabel.setText(_translate("FittingPage", "σ [Res.]"))
        self.fitNuResLabel.setText(_translate("FittingPage", "v [Res.]"))
from src.gimap.features.fitting.presentation.range_slider import QRangeSlider
