"""Hand-maintained Python View for the independent fit window."""


from PyQt5 import QtCore, QtWidgets


class IndependentFitWindowView(object):
    def setupUi(self, IndependentFitWindow):
        IndependentFitWindow.setObjectName("IndependentFitWindow")
        IndependentFitWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(IndependentFitWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.fitWindowLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.fitWindowLayout.setObjectName("fitWindowLayout")
        self.toolbarHost = QtWidgets.QWidget(self.centralwidget)
        self.toolbarHost.setObjectName("toolbarHost")
        self.toolbarHostLayout = QtWidgets.QVBoxLayout(self.toolbarHost)
        self.toolbarHostLayout.setContentsMargins(0, 0, 0, 0)
        self.toolbarHostLayout.setObjectName("toolbarHostLayout")
        self.fitWindowLayout.addWidget(self.toolbarHost)
        self.fitControls = QtWidgets.QWidget(self.centralwidget)
        self.fitControls.setObjectName("fitControls")
        self.fitControlsLayout = QtWidgets.QHBoxLayout(self.fitControls)
        self.fitControlsLayout.setObjectName("fitControlsLayout")
        self.dataFilterLabel = QtWidgets.QLabel(self.fitControls)
        self.dataFilterLabel.setObjectName("dataFilterLabel")
        self.fitControlsLayout.addWidget(self.dataFilterLabel)
        self.show_positive_cb = QtWidgets.QCheckBox(self.fitControls)
        self.show_positive_cb.setObjectName("show_positive_cb")
        self.fitControlsLayout.addWidget(self.show_positive_cb)
        self.show_negative_cb = QtWidgets.QCheckBox(self.fitControls)
        self.show_negative_cb.setObjectName("show_negative_cb")
        self.fitControlsLayout.addWidget(self.show_negative_cb)
        spacerItem = QtWidgets.QSpacerItem(12, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.fitControlsLayout.addItem(spacerItem)
        self.qUnitLabel = QtWidgets.QLabel(self.fitControls)
        self.qUnitLabel.setObjectName("qUnitLabel")
        self.fitControlsLayout.addWidget(self.qUnitLabel)
        self.q_unit_combo = QtWidgets.QComboBox(self.fitControls)
        self.q_unit_combo.setObjectName("q_unit_combo")
        self.q_unit_combo.addItem("")
        self.q_unit_combo.addItem("")
        self.fitControlsLayout.addWidget(self.q_unit_combo)
        spacerItem1 = QtWidgets.QSpacerItem(12, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.fitControlsLayout.addItem(spacerItem1)
        self.yRangeLabel = QtWidgets.QLabel(self.fitControls)
        self.yRangeLabel.setObjectName("yRangeLabel")
        self.fitControlsLayout.addWidget(self.yRangeLabel)
        self.y_range_combo = QtWidgets.QComboBox(self.fitControls)
        self.y_range_combo.setObjectName("y_range_combo")
        self.y_range_combo.addItem("")
        self.y_range_combo.addItem("")
        self.y_range_combo.addItem("")
        self.fitControlsLayout.addWidget(self.y_range_combo)
        spacerItem2 = QtWidgets.QSpacerItem(12, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.fitControlsLayout.addItem(spacerItem2)
        self.delete_input_points_cb = QtWidgets.QCheckBox(self.fitControls)
        self.delete_input_points_cb.setObjectName("delete_input_points_cb")
        self.fitControlsLayout.addWidget(self.delete_input_points_cb)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.fitControlsLayout.addItem(spacerItem3)
        self.fitWindowLayout.addWidget(self.fitControls)
        self.canvasHost = QtWidgets.QWidget(self.centralwidget)
        self.canvasHost.setObjectName("canvasHost")
        self.canvasHostLayout = QtWidgets.QVBoxLayout(self.canvasHost)
        self.canvasHostLayout.setContentsMargins(0, 0, 0, 0)
        self.canvasHostLayout.setObjectName("canvasHostLayout")
        self.fitWindowLayout.addWidget(self.canvasHost)
        IndependentFitWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(IndependentFitWindow)
        QtCore.QMetaObject.connectSlotsByName(IndependentFitWindow)
        IndependentFitWindow.setTabOrder(self.show_positive_cb, self.show_negative_cb)
        IndependentFitWindow.setTabOrder(self.show_negative_cb, self.q_unit_combo)
        IndependentFitWindow.setTabOrder(self.q_unit_combo, self.y_range_combo)
        IndependentFitWindow.setTabOrder(self.y_range_combo, self.delete_input_points_cb)

    def retranslateUi(self, IndependentFitWindow):
        _translate = QtCore.QCoreApplication.translate
        IndependentFitWindow.setWindowTitle(_translate("IndependentFitWindow", "GIMaP Cut Analysis - Independent Fit Window"))
        self.dataFilterLabel.setText(_translate("IndependentFitWindow", "Data Filter:"))
        self.show_positive_cb.setText(_translate("IndependentFitWindow", "Positive Only"))
        self.show_negative_cb.setText(_translate("IndependentFitWindow", "Negative Only"))
        self.qUnitLabel.setText(_translate("IndependentFitWindow", "q Unit:"))
        self.q_unit_combo.setItemText(0, _translate("IndependentFitWindow", "q (Angstrom^-1)"))
        self.q_unit_combo.setItemText(1, _translate("IndependentFitWindow", "q (nm^-1)"))
        self.yRangeLabel.setText(_translate("IndependentFitWindow", "Y Range:"))
        self.y_range_combo.setItemText(0, _translate("IndependentFitWindow", "Experiment"))
        self.y_range_combo.setItemText(1, _translate("IndependentFitWindow", "Fit"))
        self.y_range_combo.setItemText(2, _translate("IndependentFitWindow", "All"))
        self.delete_input_points_cb.setToolTip(_translate("IndependentFitWindow", "Enable, then left-click a plotted input point to exclude it from AI fitting input."))
        self.delete_input_points_cb.setText(_translate("IndependentFitWindow", "Delete Points"))
