"""Hand-maintained layout for the folder import dialog."""


from PyQt5 import QtCore, QtGui, QtWidgets


class FolderImportDialogView:
    def setupUi(self, FolderImportDialog):
        FolderImportDialog.setObjectName("FolderImportDialog")
        FolderImportDialog.resize(560, 230)
        self.dialog_layout = QtWidgets.QVBoxLayout(FolderImportDialog)
        self.dialog_layout.setObjectName("dialog_layout")
        self.folder_form = QtWidgets.QFormLayout()
        self.folder_form.setObjectName("folder_form")
        self.folder_label = QtWidgets.QLabel(FolderImportDialog)
        self.folder_label.setObjectName("folder_label")
        self.folder_form.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.folder_label)
        self.path_row = QtWidgets.QHBoxLayout()
        self.path_row.setObjectName("path_row")
        self.path_edit = QtWidgets.QLineEdit(FolderImportDialog)
        self.path_edit.setObjectName("path_edit")
        self.path_row.addWidget(self.path_edit)
        self.browse_button = QtWidgets.QPushButton(FolderImportDialog)
        self.browse_button.setObjectName("browse_button")
        self.path_row.addWidget(self.browse_button)
        self.folder_form.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.path_row)
        self.include_label = QtWidgets.QLabel(FolderImportDialog)
        self.include_label.setObjectName("include_label")
        self.folder_form.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.include_label)
        self.include_row = QtWidgets.QHBoxLayout()
        self.include_row.setObjectName("include_row")
        self.cbf = QtWidgets.QCheckBox(FolderImportDialog)
        self.cbf.setChecked(True)
        self.cbf.setObjectName("cbf")
        self.include_row.addWidget(self.cbf)
        self.tiff = QtWidgets.QCheckBox(FolderImportDialog)
        self.tiff.setChecked(True)
        self.tiff.setObjectName("tiff")
        self.include_row.addWidget(self.tiff)
        self.nxs = QtWidgets.QCheckBox(FolderImportDialog)
        self.nxs.setChecked(True)
        self.nxs.setObjectName("nxs")
        self.include_row.addWidget(self.nxs)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.include_row.addItem(spacerItem)
        self.folder_form.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.include_row)
        self.recursive = QtWidgets.QCheckBox(FolderImportDialog)
        self.recursive.setObjectName("recursive")
        self.folder_form.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.recursive)
        self.dialog_layout.addLayout(self.folder_form)
        self.subfolder_note = QtWidgets.QLabel(FolderImportDialog)
        self.subfolder_note.setStyleSheet("color: #64748b;")
        self.subfolder_note.setObjectName("subfolder_note")
        self.dialog_layout.addWidget(self.subfolder_note)
        self.buttons = QtWidgets.QDialogButtonBox(FolderImportDialog)
        self.buttons.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttons.setObjectName("buttons")
        self.dialog_layout.addWidget(self.buttons)

        self.retranslateUi(FolderImportDialog)
        QtCore.QMetaObject.connectSlotsByName(FolderImportDialog)

    def retranslateUi(self, FolderImportDialog):
        _translate = QtCore.QCoreApplication.translate
        FolderImportDialog.setWindowTitle(_translate("FolderImportDialog", "Add Folder"))
        self.folder_label.setText(_translate("FolderImportDialog", "Folder:"))
        self.browse_button.setText(_translate("FolderImportDialog", "Browse…"))
        self.include_label.setText(_translate("FolderImportDialog", "Include:"))
        self.cbf.setText(_translate("FolderImportDialog", "CBF"))
        self.tiff.setText(_translate("FolderImportDialog", "TIFF"))
        self.nxs.setText(_translate("FolderImportDialog", "NXS"))
        self.recursive.setToolTip(_translate("FolderImportDialog", "Disabled by default to avoid accidentally loading very large folder trees."))
        self.recursive.setText(_translate("FolderImportDialog", "Include subfolders"))
        self.subfolder_note.setText(_translate("FolderImportDialog", "Subfolders are not scanned unless you explicitly enable the option."))
