"""Hand-maintained layout for the Format Converter workspace dialog."""


from PyQt5 import QtCore, QtGui, QtWidgets


class FormatConverterDialogView:
    def setupUi(self, FormatConverterDialog):
        FormatConverterDialog.setObjectName("FormatConverterDialog")
        FormatConverterDialog.resize(1080, 760)
        FormatConverterDialog.setMinimumSize(QtCore.QSize(920, 650))
        self.outerLayout = QtWidgets.QVBoxLayout(FormatConverterDialog)
        self.outerLayout.setContentsMargins(18, 16, 18, 16)
        self.outerLayout.setObjectName("outerLayout")
        self.step_header = QtWidgets.QHBoxLayout()
        self.step_header.setObjectName("step_header")
        self.step_input_label = QtWidgets.QLabel(FormatConverterDialog)
        self.step_input_label.setMinimumSize(QtCore.QSize(0, 38))
        self.step_input_label.setAlignment(QtCore.Qt.AlignCenter)
        self.step_input_label.setObjectName("step_input_label")
        self.step_header.addWidget(self.step_input_label)
        self.step_configure_label = QtWidgets.QLabel(FormatConverterDialog)
        self.step_configure_label.setMinimumSize(QtCore.QSize(0, 38))
        self.step_configure_label.setAlignment(QtCore.Qt.AlignCenter)
        self.step_configure_label.setObjectName("step_configure_label")
        self.step_header.addWidget(self.step_configure_label)
        self.step_output_label = QtWidgets.QLabel(FormatConverterDialog)
        self.step_output_label.setMinimumSize(QtCore.QSize(0, 38))
        self.step_output_label.setAlignment(QtCore.Qt.AlignCenter)
        self.step_output_label.setObjectName("step_output_label")
        self.step_header.addWidget(self.step_output_label)
        self.outerLayout.addLayout(self.step_header)
        self.stack = QtWidgets.QStackedWidget(FormatConverterDialog)
        self.stack.setObjectName("stack")
        self.input_page = QtWidgets.QWidget()
        self.input_page.setObjectName("input_page")
        self.inputPageLayout = QtWidgets.QVBoxLayout(self.input_page)
        self.inputPageLayout.setObjectName("inputPageLayout")
        self.format_input_section = QtWidgets.QFrame(self.input_page)
        self.format_input_section.setProperty("gimapSection", True)
        self.format_input_section.setObjectName("format_input_section")
        self.formatInputSectionLayout = QtWidgets.QVBoxLayout(self.format_input_section)
        self.formatInputSectionLayout.setContentsMargins(12, 10, 12, 12)
        self.formatInputSectionLayout.setSpacing(8)
        self.formatInputSectionLayout.setObjectName("formatInputSectionLayout")
        self.formatInputTitle = QtWidgets.QLabel(self.format_input_section)
        self.formatInputTitle.setProperty("gimapSectionTitle", True)
        self.formatInputTitle.setObjectName("formatInputTitle")
        self.formatInputSectionLayout.addWidget(self.formatInputTitle)
        self.formatInputDescription = QtWidgets.QLabel(self.format_input_section)
        self.formatInputDescription.setProperty("gimapSectionDescription", True)
        self.formatInputDescription.setWordWrap(True)
        self.formatInputDescription.setObjectName("formatInputDescription")
        self.formatInputSectionLayout.addWidget(self.formatInputDescription)
        self.formatInputContent = QtWidgets.QWidget(self.format_input_section)
        self.formatInputContent.setObjectName("formatInputContent")
        self.formatInputContentLayout = QtWidgets.QVBoxLayout(self.formatInputContent)
        self.formatInputContentLayout.setContentsMargins(0, 0, 0, 0)
        self.formatInputContentLayout.setSpacing(8)
        self.formatInputContentLayout.setObjectName("formatInputContentLayout")
        self.input_intro = QtWidgets.QLabel(self.formatInputContent)
        self.input_intro.setWordWrap(True)
        self.input_intro.setObjectName("input_intro")
        self.formatInputContentLayout.addWidget(self.input_intro)
        self.inputActionsLayout = QtWidgets.QHBoxLayout()
        self.inputActionsLayout.setObjectName("inputActionsLayout")
        self.add_files_button = QtWidgets.QPushButton(self.formatInputContent)
        self.add_files_button.setObjectName("add_files_button")
        self.inputActionsLayout.addWidget(self.add_files_button)
        self.add_folder_button = QtWidgets.QPushButton(self.formatInputContent)
        self.add_folder_button.setObjectName("add_folder_button")
        self.inputActionsLayout.addWidget(self.add_folder_button)
        self.current_button = QtWidgets.QPushButton(self.formatInputContent)
        self.current_button.setObjectName("current_button")
        self.inputActionsLayout.addWidget(self.current_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.inputActionsLayout.addItem(spacerItem)
        self.formatInputContentLayout.addLayout(self.inputActionsLayout)
        self.input_tree = QtWidgets.QTreeWidget(self.formatInputContent)
        self.input_tree.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.input_tree.setObjectName("input_tree")
        self.formatInputContentLayout.addWidget(self.input_tree)
        self.datasetLayout = QtWidgets.QHBoxLayout()
        self.datasetLayout.setObjectName("datasetLayout")
        self.dataset_label = QtWidgets.QLabel(self.formatInputContent)
        self.dataset_label.setVisible(False)
        self.dataset_label.setObjectName("dataset_label")
        self.datasetLayout.addWidget(self.dataset_label)
        self.dataset_combo = QtWidgets.QComboBox(self.formatInputContent)
        self.dataset_combo.setVisible(False)
        self.dataset_combo.setObjectName("dataset_combo")
        self.datasetLayout.addWidget(self.dataset_combo)
        self.dataset_note = QtWidgets.QLabel(self.formatInputContent)
        self.dataset_note.setVisible(False)
        self.dataset_note.setStyleSheet("color: #64748b;")
        self.dataset_note.setObjectName("dataset_note")
        self.datasetLayout.addWidget(self.dataset_note)
        self.formatInputContentLayout.addLayout(self.datasetLayout)
        self.input_note = QtWidgets.QLabel(self.formatInputContent)
        self.input_note.setStyleSheet("color: #64748b;")
        self.input_note.setObjectName("input_note")
        self.formatInputContentLayout.addWidget(self.input_note)
        self.formatInputContentLayout.setStretch(2, 1)
        self.formatInputSectionLayout.addWidget(self.formatInputContent)
        self.formatInputSectionLayout.setStretch(2, 1)
        self.inputPageLayout.addWidget(self.format_input_section)
        self.stack.addWidget(self.input_page)
        self.configure_page = QtWidgets.QWidget()
        self.configure_page.setObjectName("configure_page")
        self.configurePageLayout = QtWidgets.QVBoxLayout(self.configure_page)
        self.configurePageLayout.setObjectName("configurePageLayout")
        self.format_configure_section = QtWidgets.QFrame(self.configure_page)
        self.format_configure_section.setProperty("gimapSection", True)
        self.format_configure_section.setObjectName("format_configure_section")
        self.formatConfigureSectionLayout = QtWidgets.QVBoxLayout(self.format_configure_section)
        self.formatConfigureSectionLayout.setContentsMargins(12, 10, 12, 12)
        self.formatConfigureSectionLayout.setSpacing(8)
        self.formatConfigureSectionLayout.setObjectName("formatConfigureSectionLayout")
        self.formatConfigureTitle = QtWidgets.QLabel(self.format_configure_section)
        self.formatConfigureTitle.setProperty("gimapSectionTitle", True)
        self.formatConfigureTitle.setObjectName("formatConfigureTitle")
        self.formatConfigureSectionLayout.addWidget(self.formatConfigureTitle)
        self.formatConfigureDescription = QtWidgets.QLabel(self.format_configure_section)
        self.formatConfigureDescription.setProperty("gimapSectionDescription", True)
        self.formatConfigureDescription.setWordWrap(True)
        self.formatConfigureDescription.setObjectName("formatConfigureDescription")
        self.formatConfigureSectionLayout.addWidget(self.formatConfigureDescription)
        self.formatConfigureContent = QtWidgets.QWidget(self.format_configure_section)
        self.formatConfigureContent.setObjectName("formatConfigureContent")
        self.formatConfigureContentLayout = QtWidgets.QVBoxLayout(self.formatConfigureContent)
        self.formatConfigureContentLayout.setContentsMargins(0, 0, 0, 0)
        self.formatConfigureContentLayout.setSpacing(8)
        self.formatConfigureContentLayout.setObjectName("formatConfigureContentLayout")
        self.selectionToolsLayout = QtWidgets.QHBoxLayout()
        self.selectionToolsLayout.setObjectName("selectionToolsLayout")
        self.select_all_button = QtWidgets.QPushButton(self.formatConfigureContent)
        self.select_all_button.setObjectName("select_all_button")
        self.selectionToolsLayout.addWidget(self.select_all_button)
        self.select_none_button = QtWidgets.QPushButton(self.formatConfigureContent)
        self.select_none_button.setObjectName("select_none_button")
        self.selectionToolsLayout.addWidget(self.select_none_button)
        self.remove_selected_button = QtWidgets.QPushButton(self.formatConfigureContent)
        self.remove_selected_button.setObjectName("remove_selected_button")
        self.selectionToolsLayout.addWidget(self.remove_selected_button)
        self.sort_button = QtWidgets.QPushButton(self.formatConfigureContent)
        self.sort_button.setObjectName("sort_button")
        self.selectionToolsLayout.addWidget(self.sort_button)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.selectionToolsLayout.addItem(spacerItem1)
        self.filter_edit = QtWidgets.QLineEdit(self.formatConfigureContent)
        self.filter_edit.setObjectName("filter_edit")
        self.selectionToolsLayout.addWidget(self.filter_edit)
        self.formatConfigureContentLayout.addLayout(self.selectionToolsLayout)
        self.selection_splitter = QtWidgets.QSplitter(self.formatConfigureContent)
        self.selection_splitter.setOrientation(QtCore.Qt.Horizontal)
        self.selection_splitter.setObjectName("selection_splitter")
        self.selection_left = QtWidgets.QWidget(self.selection_splitter)
        self.selection_left.setObjectName("selection_left")
        self.selectionLeftLayout = QtWidgets.QVBoxLayout(self.selection_left)
        self.selectionLeftLayout.setContentsMargins(0, 0, 0, 0)
        self.selectionLeftLayout.setObjectName("selectionLeftLayout")
        self.selection_table = QtWidgets.QTableWidget(self.selection_left)
        self.selection_table.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.selection_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.selection_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.selection_table.setObjectName("selection_table")
        self.selection_table.setColumnCount(5)
        self.selection_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.selection_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.selection_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.selection_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.selection_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.selection_table.setHorizontalHeaderItem(4, item)
        self.selectionLeftLayout.addWidget(self.selection_table)
        self.frame_advanced_section = QtWidgets.QFrame(self.selection_left)
        self.frame_advanced_section.setProperty("gimapSection", True)
        self.frame_advanced_section.setObjectName("frame_advanced_section")
        self.frameAdvancedLayout = QtWidgets.QVBoxLayout(self.frame_advanced_section)
        self.frameAdvancedLayout.setContentsMargins(8, 8, 8, 8)
        self.frameAdvancedLayout.setSpacing(7)
        self.frameAdvancedLayout.setObjectName("frameAdvancedLayout")
        self.frameAdvancedToggle = QtWidgets.QToolButton(self.frame_advanced_section)
        self.frameAdvancedToggle.setProperty("gimapAdvancedToggle", True)
        self.frameAdvancedToggle.setCheckable(True)
        self.frameAdvancedToggle.setChecked(False)
        self.frameAdvancedToggle.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.frameAdvancedToggle.setArrowType(QtCore.Qt.RightArrow)
        self.frameAdvancedToggle.setObjectName("frameAdvancedToggle")
        self.frameAdvancedLayout.addWidget(self.frameAdvancedToggle)
        self.frameAdvancedDescription = QtWidgets.QLabel(self.frame_advanced_section)
        self.frameAdvancedDescription.setVisible(False)
        self.frameAdvancedDescription.setProperty("gimapSectionDescription", True)
        self.frameAdvancedDescription.setWordWrap(True)
        self.frameAdvancedDescription.setObjectName("frameAdvancedDescription")
        self.frameAdvancedLayout.addWidget(self.frameAdvancedDescription)
        self.frameAdvancedContent = QtWidgets.QWidget(self.frame_advanced_section)
        self.frameAdvancedContent.setVisible(False)
        self.frameAdvancedContent.setObjectName("frameAdvancedContent")
        self.frameAdvancedContentLayout = QtWidgets.QVBoxLayout(self.frameAdvancedContent)
        self.frameAdvancedContentLayout.setContentsMargins(4, 2, 4, 4)
        self.frameAdvancedContentLayout.setSpacing(8)
        self.frameAdvancedContentLayout.setObjectName("frameAdvancedContentLayout")
        self.frame_group = QtWidgets.QGroupBox(self.frameAdvancedContent)
        self.frame_group.setObjectName("frame_group")
        self.frameLayout = QtWidgets.QGridLayout(self.frame_group)
        self.frameLayout.setObjectName("frameLayout")
        self.frameModeLabel = QtWidgets.QLabel(self.frame_group)
        self.frameModeLabel.setObjectName("frameModeLabel")
        self.frameLayout.addWidget(self.frameModeLabel, 0, 0, 1, 1)
        self.frame_mode = QtWidgets.QComboBox(self.frame_group)
        self.frame_mode.setObjectName("frame_mode")
        self.frame_mode.addItem("")
        self.frame_mode.addItem("")
        self.frame_mode.addItem("")
        self.frame_mode.addItem("")
        self.frame_mode.addItem("")
        self.frameLayout.addWidget(self.frame_mode, 0, 1, 1, 3)
        self.rangeLabel = QtWidgets.QLabel(self.frame_group)
        self.rangeLabel.setObjectName("rangeLabel")
        self.frameLayout.addWidget(self.rangeLabel, 1, 0, 1, 1)
        self.range_start = QtWidgets.QSpinBox(self.frame_group)
        self.range_start.setObjectName("range_start")
        self.frameLayout.addWidget(self.range_start, 1, 1, 1, 1)
        self.rangeToLabel = QtWidgets.QLabel(self.frame_group)
        self.rangeToLabel.setObjectName("rangeToLabel")
        self.frameLayout.addWidget(self.rangeToLabel, 1, 2, 1, 1)
        self.range_end = QtWidgets.QSpinBox(self.frame_group)
        self.range_end.setObjectName("range_end")
        self.frameLayout.addWidget(self.range_end, 1, 3, 1, 1)
        self.customLabel = QtWidgets.QLabel(self.frame_group)
        self.customLabel.setObjectName("customLabel")
        self.frameLayout.addWidget(self.customLabel, 2, 0, 1, 1)
        self.custom_frames = QtWidgets.QLineEdit(self.frame_group)
        self.custom_frames.setObjectName("custom_frames")
        self.frameLayout.addWidget(self.custom_frames, 2, 1, 1, 3)
        self.nthLabel = QtWidgets.QLabel(self.frame_group)
        self.nthLabel.setObjectName("nthLabel")
        self.frameLayout.addWidget(self.nthLabel, 3, 0, 1, 1)
        self.nth_frame = QtWidgets.QSpinBox(self.frame_group)
        self.nth_frame.setMinimum(1)
        self.nth_frame.setMaximum(1000000)
        self.nth_frame.setProperty("value", 10)
        self.nth_frame.setObjectName("nth_frame")
        self.frameLayout.addWidget(self.nth_frame, 3, 1, 1, 1)
        self.apply_frames = QtWidgets.QPushButton(self.frame_group)
        self.apply_frames.setObjectName("apply_frames")
        self.frameLayout.addWidget(self.apply_frames, 3, 3, 1, 1)
        self.frameAdvancedContentLayout.addWidget(self.frame_group)
        self.frameAdvancedLayout.addWidget(self.frameAdvancedContent)
        self.selectionLeftLayout.addWidget(self.frame_advanced_section)
        self.selectionLeftLayout.setStretch(0, 1)
        self.preview_scroll = QtWidgets.QScrollArea(self.selection_splitter)
        self.preview_scroll.setWidgetResizable(True)
        self.preview_scroll.setObjectName("preview_scroll")
        self.preview_scroll_content = QtWidgets.QWidget()
        self.preview_scroll_content.setGeometry(QtCore.QRect(0, 0, 320, 650))
        self.preview_scroll_content.setObjectName("preview_scroll_content")
        self.previewScrollLayout = QtWidgets.QVBoxLayout(self.preview_scroll_content)
        self.previewScrollLayout.setObjectName("previewScrollLayout")
        self.format_preview_panel = QtWidgets.QFrame(self.preview_scroll_content)
        self.format_preview_panel.setProperty("gimapSection", True)
        self.format_preview_panel.setObjectName("format_preview_panel")
        self.formatPreviewPanelLayout = QtWidgets.QVBoxLayout(self.format_preview_panel)
        self.formatPreviewPanelLayout.setContentsMargins(12, 10, 12, 12)
        self.formatPreviewPanelLayout.setSpacing(8)
        self.formatPreviewPanelLayout.setObjectName("formatPreviewPanelLayout")
        self.formatPreviewTitle = QtWidgets.QLabel(self.format_preview_panel)
        self.formatPreviewTitle.setProperty("gimapSectionTitle", True)
        self.formatPreviewTitle.setObjectName("formatPreviewTitle")
        self.formatPreviewPanelLayout.addWidget(self.formatPreviewTitle)
        self.formatPreviewDescription = QtWidgets.QLabel(self.format_preview_panel)
        self.formatPreviewDescription.setProperty("gimapSectionDescription", True)
        self.formatPreviewDescription.setWordWrap(True)
        self.formatPreviewDescription.setObjectName("formatPreviewDescription")
        self.formatPreviewPanelLayout.addWidget(self.formatPreviewDescription)
        self.formatPreviewContent = QtWidgets.QWidget(self.format_preview_panel)
        self.formatPreviewContent.setObjectName("formatPreviewContent")
        self.formatPreviewContentLayout = QtWidgets.QVBoxLayout(self.formatPreviewContent)
        self.formatPreviewContentLayout.setContentsMargins(0, 0, 0, 0)
        self.formatPreviewContentLayout.setSpacing(8)
        self.formatPreviewContentLayout.setObjectName("formatPreviewContentLayout")
        self.first_preview_caption = QtWidgets.QLabel(self.formatPreviewContent)
        self.first_preview_caption.setStyleSheet("font-weight: 600;")
        self.first_preview_caption.setObjectName("first_preview_caption")
        self.formatPreviewContentLayout.addWidget(self.first_preview_caption)
        self.first_preview_label = QtWidgets.QLabel(self.formatPreviewContent)
        self.first_preview_label.setMinimumSize(QtCore.QSize(220, 150))
        self.first_preview_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.first_preview_label.setAlignment(QtCore.Qt.AlignCenter)
        self.first_preview_label.setObjectName("first_preview_label")
        self.formatPreviewContentLayout.addWidget(self.first_preview_label)
        self.middle_preview_caption = QtWidgets.QLabel(self.formatPreviewContent)
        self.middle_preview_caption.setStyleSheet("font-weight: 600;")
        self.middle_preview_caption.setObjectName("middle_preview_caption")
        self.formatPreviewContentLayout.addWidget(self.middle_preview_caption)
        self.middle_preview_label = QtWidgets.QLabel(self.formatPreviewContent)
        self.middle_preview_label.setMinimumSize(QtCore.QSize(220, 150))
        self.middle_preview_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.middle_preview_label.setAlignment(QtCore.Qt.AlignCenter)
        self.middle_preview_label.setObjectName("middle_preview_label")
        self.formatPreviewContentLayout.addWidget(self.middle_preview_label)
        self.last_preview_caption = QtWidgets.QLabel(self.formatPreviewContent)
        self.last_preview_caption.setStyleSheet("font-weight: 600;")
        self.last_preview_caption.setObjectName("last_preview_caption")
        self.formatPreviewContentLayout.addWidget(self.last_preview_caption)
        self.last_preview_label = QtWidgets.QLabel(self.formatPreviewContent)
        self.last_preview_label.setMinimumSize(QtCore.QSize(220, 150))
        self.last_preview_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.last_preview_label.setAlignment(QtCore.Qt.AlignCenter)
        self.last_preview_label.setObjectName("last_preview_label")
        self.formatPreviewContentLayout.addWidget(self.last_preview_label)
        self.preview_stats = QtWidgets.QLabel(self.formatPreviewContent)
        self.preview_stats.setWordWrap(True)
        self.preview_stats.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.preview_stats.setObjectName("preview_stats")
        self.formatPreviewContentLayout.addWidget(self.preview_stats)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formatPreviewContentLayout.addItem(spacerItem2)
        self.formatPreviewPanelLayout.addWidget(self.formatPreviewContent)
        self.formatPreviewPanelLayout.setStretch(2, 1)
        self.previewScrollLayout.addWidget(self.format_preview_panel)
        self.preview_scroll.setWidget(self.preview_scroll_content)
        self.formatConfigureContentLayout.addWidget(self.selection_splitter)
        self.formatConfigureContentLayout.setStretch(1, 1)
        self.formatConfigureSectionLayout.addWidget(self.formatConfigureContent)
        self.formatConfigureSectionLayout.setStretch(2, 1)
        self.configurePageLayout.addWidget(self.format_configure_section)
        self.stack.addWidget(self.configure_page)
        self.output_page = QtWidgets.QWidget()
        self.output_page.setObjectName("output_page")
        self.outputPageLayout = QtWidgets.QVBoxLayout(self.output_page)
        self.outputPageLayout.setObjectName("outputPageLayout")
        self.output_scroll = QtWidgets.QScrollArea(self.output_page)
        self.output_scroll.setWidgetResizable(True)
        self.output_scroll.setObjectName("output_scroll")
        self.output_scroll_content = QtWidgets.QWidget()
        self.output_scroll_content.setGeometry(QtCore.QRect(0, 0, 1000, 800))
        self.output_scroll_content.setObjectName("output_scroll_content")
        self.outputContentLayout = QtWidgets.QVBoxLayout(self.output_scroll_content)
        self.outputContentLayout.setObjectName("outputContentLayout")
        self.format_output_section = QtWidgets.QFrame(self.output_scroll_content)
        self.format_output_section.setProperty("gimapSection", True)
        self.format_output_section.setObjectName("format_output_section")
        self.formatOutputSectionLayout = QtWidgets.QVBoxLayout(self.format_output_section)
        self.formatOutputSectionLayout.setContentsMargins(12, 10, 12, 12)
        self.formatOutputSectionLayout.setSpacing(8)
        self.formatOutputSectionLayout.setObjectName("formatOutputSectionLayout")
        self.formatOutputTitle = QtWidgets.QLabel(self.format_output_section)
        self.formatOutputTitle.setProperty("gimapSectionTitle", True)
        self.formatOutputTitle.setObjectName("formatOutputTitle")
        self.formatOutputSectionLayout.addWidget(self.formatOutputTitle)
        self.formatOutputDescription = QtWidgets.QLabel(self.format_output_section)
        self.formatOutputDescription.setProperty("gimapSectionDescription", True)
        self.formatOutputDescription.setWordWrap(True)
        self.formatOutputDescription.setObjectName("formatOutputDescription")
        self.formatOutputSectionLayout.addWidget(self.formatOutputDescription)
        self.formatOutputContent = QtWidgets.QWidget(self.format_output_section)
        self.formatOutputContent.setObjectName("formatOutputContent")
        self.formatOutputContentLayout = QtWidgets.QVBoxLayout(self.formatOutputContent)
        self.formatOutputContentLayout.setContentsMargins(0, 0, 0, 0)
        self.formatOutputContentLayout.setSpacing(8)
        self.formatOutputContentLayout.setObjectName("formatOutputContentLayout")
        self.output_format_group = QtWidgets.QGroupBox(self.formatOutputContent)
        self.output_format_group.setObjectName("output_format_group")
        self.outputFormatLayout = QtWidgets.QHBoxLayout(self.output_format_group)
        self.outputFormatLayout.setObjectName("outputFormatLayout")
        self.tiff_format_button = QtWidgets.QRadioButton(self.output_format_group)
        self.tiff_format_button.setChecked(True)
        self.tiff_format_button.setObjectName("tiff_format_button")
        self.outputFormatLayout.addWidget(self.tiff_format_button)
        self.cbf_format_button = QtWidgets.QRadioButton(self.output_format_group)
        self.cbf_format_button.setObjectName("cbf_format_button")
        self.outputFormatLayout.addWidget(self.cbf_format_button)
        self.hdf5_format_button = QtWidgets.QRadioButton(self.output_format_group)
        self.hdf5_format_button.setObjectName("hdf5_format_button")
        self.outputFormatLayout.addWidget(self.hdf5_format_button)
        self.numpy_format_button = QtWidgets.QRadioButton(self.output_format_group)
        self.numpy_format_button.setObjectName("numpy_format_button")
        self.outputFormatLayout.addWidget(self.numpy_format_button)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.outputFormatLayout.addItem(spacerItem3)
        self.formatOutputContentLayout.addWidget(self.output_format_group)
        self.destination_group = QtWidgets.QGroupBox(self.formatOutputContent)
        self.destination_group.setObjectName("destination_group")
        self.destinationForm = QtWidgets.QFormLayout(self.destination_group)
        self.destinationForm.setObjectName("destinationForm")
        self.destinationLabel = QtWidgets.QLabel(self.destination_group)
        self.destinationLabel.setObjectName("destinationLabel")
        self.destinationForm.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.destinationLabel)
        self.destinationLayout = QtWidgets.QHBoxLayout()
        self.destinationLayout.setObjectName("destinationLayout")
        self.destination_edit = QtWidgets.QLineEdit(self.destination_group)
        self.destination_edit.setObjectName("destination_edit")
        self.destinationLayout.addWidget(self.destination_edit)
        self.destination_button = QtWidgets.QPushButton(self.destination_group)
        self.destination_button.setObjectName("destination_button")
        self.destinationLayout.addWidget(self.destination_button)
        self.destinationForm.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.destinationLayout)
        self.namingLabel = QtWidgets.QLabel(self.destination_group)
        self.namingLabel.setObjectName("namingLabel")
        self.destinationForm.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.namingLabel)
        self.naming_combo = QtWidgets.QComboBox(self.destination_group)
        self.naming_combo.setEditable(True)
        self.naming_combo.setObjectName("naming_combo")
        self.naming_combo.addItem("")
        self.naming_combo.addItem("")
        self.destinationForm.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.naming_combo)
        self.naming_example = QtWidgets.QLabel(self.destination_group)
        self.naming_example.setStyleSheet("color: #475569;")
        self.naming_example.setObjectName("naming_example")
        self.destinationForm.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.naming_example)
        self.add_suffix = QtWidgets.QCheckBox(self.destination_group)
        self.add_suffix.setChecked(True)
        self.add_suffix.setObjectName("add_suffix")
        self.destinationForm.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.add_suffix)
        self.formatOutputContentLayout.addWidget(self.destination_group)
        self.formatOutputSectionLayout.addWidget(self.formatOutputContent)
        self.outputContentLayout.addWidget(self.format_output_section)
        self.format_output_advanced = QtWidgets.QFrame(self.output_scroll_content)
        self.format_output_advanced.setProperty("gimapSection", True)
        self.format_output_advanced.setObjectName("format_output_advanced")
        self.formatOutputAdvancedLayout = QtWidgets.QVBoxLayout(self.format_output_advanced)
        self.formatOutputAdvancedLayout.setContentsMargins(8, 8, 8, 8)
        self.formatOutputAdvancedLayout.setSpacing(7)
        self.formatOutputAdvancedLayout.setObjectName("formatOutputAdvancedLayout")
        self.formatOutputAdvancedToggle = QtWidgets.QToolButton(self.format_output_advanced)
        self.formatOutputAdvancedToggle.setProperty("gimapAdvancedToggle", True)
        self.formatOutputAdvancedToggle.setCheckable(True)
        self.formatOutputAdvancedToggle.setChecked(False)
        self.formatOutputAdvancedToggle.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.formatOutputAdvancedToggle.setArrowType(QtCore.Qt.RightArrow)
        self.formatOutputAdvancedToggle.setObjectName("formatOutputAdvancedToggle")
        self.formatOutputAdvancedLayout.addWidget(self.formatOutputAdvancedToggle)
        self.formatOutputAdvancedDescription = QtWidgets.QLabel(self.format_output_advanced)
        self.formatOutputAdvancedDescription.setVisible(False)
        self.formatOutputAdvancedDescription.setProperty("gimapSectionDescription", True)
        self.formatOutputAdvancedDescription.setWordWrap(True)
        self.formatOutputAdvancedDescription.setObjectName("formatOutputAdvancedDescription")
        self.formatOutputAdvancedLayout.addWidget(self.formatOutputAdvancedDescription)
        self.formatOutputAdvancedContent = QtWidgets.QWidget(self.format_output_advanced)
        self.formatOutputAdvancedContent.setVisible(False)
        self.formatOutputAdvancedContent.setObjectName("formatOutputAdvancedContent")
        self.formatOutputAdvancedContentLayout = QtWidgets.QVBoxLayout(self.formatOutputAdvancedContent)
        self.formatOutputAdvancedContentLayout.setContentsMargins(4, 2, 4, 4)
        self.formatOutputAdvancedContentLayout.setSpacing(8)
        self.formatOutputAdvancedContentLayout.setObjectName("formatOutputAdvancedContentLayout")
        self.values_group = QtWidgets.QGroupBox(self.formatOutputAdvancedContent)
        self.values_group.setObjectName("values_group")
        self.valuesLayout = QtWidgets.QVBoxLayout(self.values_group)
        self.valuesLayout.setObjectName("valuesLayout")
        self.preserve_values = QtWidgets.QCheckBox(self.values_group)
        self.preserve_values.setChecked(True)
        self.preserve_values.setObjectName("preserve_values")
        self.valuesLayout.addWidget(self.preserve_values)
        self.data_mode = QtWidgets.QComboBox(self.values_group)
        self.data_mode.setObjectName("data_mode")
        self.data_mode.addItem("")
        self.data_mode.addItem("")
        self.data_mode.addItem("")
        self.data_mode.addItem("")
        self.valuesLayout.addWidget(self.data_mode)
        self.dtype_warning = QtWidgets.QLabel(self.values_group)
        self.dtype_warning.setStyleSheet("color: #a16207;")
        self.dtype_warning.setText("")
        self.dtype_warning.setWordWrap(True)
        self.dtype_warning.setObjectName("dtype_warning")
        self.valuesLayout.addWidget(self.dtype_warning)
        self.formatOutputAdvancedContentLayout.addWidget(self.values_group)
        self.metadata_group = QtWidgets.QGroupBox(self.formatOutputAdvancedContent)
        self.metadata_group.setObjectName("metadata_group")
        self.metadataLayout = QtWidgets.QVBoxLayout(self.metadata_group)
        self.metadataLayout.setObjectName("metadataLayout")
        self.preserve_metadata = QtWidgets.QCheckBox(self.metadata_group)
        self.preserve_metadata.setChecked(True)
        self.preserve_metadata.setObjectName("preserve_metadata")
        self.metadataLayout.addWidget(self.preserve_metadata)
        self.write_sidecar = QtWidgets.QCheckBox(self.metadata_group)
        self.write_sidecar.setChecked(True)
        self.write_sidecar.setObjectName("write_sidecar")
        self.metadataLayout.addWidget(self.write_sidecar)
        self.single_json = QtWidgets.QRadioButton(self.metadata_group)
        self.single_json.setChecked(True)
        self.single_json.setObjectName("single_json")
        self.metadataLayout.addWidget(self.single_json)
        self.per_image_json = QtWidgets.QRadioButton(self.metadata_group)
        self.per_image_json.setObjectName("per_image_json")
        self.metadataLayout.addWidget(self.per_image_json)
        self.formatOutputAdvancedContentLayout.addWidget(self.metadata_group)
        self.advanced_group = QtWidgets.QGroupBox(self.formatOutputAdvancedContent)
        self.advanced_group.setObjectName("advanced_group")
        self.advancedLayout = QtWidgets.QVBoxLayout(self.advanced_group)
        self.advancedLayout.setObjectName("advancedLayout")
        self.container_check = QtWidgets.QCheckBox(self.advanced_group)
        self.container_check.setObjectName("container_check")
        self.advancedLayout.addWidget(self.container_check)
        self.formatOutputAdvancedContentLayout.addWidget(self.advanced_group)
        self.formatOutputAdvancedLayout.addWidget(self.formatOutputAdvancedContent)
        self.outputContentLayout.addWidget(self.format_output_advanced)
        self.format_run_section = QtWidgets.QFrame(self.output_scroll_content)
        self.format_run_section.setProperty("gimapSection", True)
        self.format_run_section.setObjectName("format_run_section")
        self.formatRunSectionLayout = QtWidgets.QVBoxLayout(self.format_run_section)
        self.formatRunSectionLayout.setContentsMargins(12, 10, 12, 12)
        self.formatRunSectionLayout.setSpacing(8)
        self.formatRunSectionLayout.setObjectName("formatRunSectionLayout")
        self.formatRunTitle = QtWidgets.QLabel(self.format_run_section)
        self.formatRunTitle.setProperty("gimapSectionTitle", True)
        self.formatRunTitle.setObjectName("formatRunTitle")
        self.formatRunSectionLayout.addWidget(self.formatRunTitle)
        self.formatRunDescription = QtWidgets.QLabel(self.format_run_section)
        self.formatRunDescription.setProperty("gimapSectionDescription", True)
        self.formatRunDescription.setWordWrap(True)
        self.formatRunDescription.setObjectName("formatRunDescription")
        self.formatRunSectionLayout.addWidget(self.formatRunDescription)
        self.formatRunContent = QtWidgets.QWidget(self.format_run_section)
        self.formatRunContent.setObjectName("formatRunContent")
        self.formatRunContentLayout = QtWidgets.QVBoxLayout(self.formatRunContent)
        self.formatRunContentLayout.setContentsMargins(0, 0, 0, 0)
        self.formatRunContentLayout.setSpacing(8)
        self.formatRunContentLayout.setObjectName("formatRunContentLayout")
        self.output_summary = QtWidgets.QLabel(self.formatRunContent)
        self.output_summary.setText("")
        self.output_summary.setWordWrap(True)
        self.output_summary.setObjectName("output_summary")
        self.formatRunContentLayout.addWidget(self.output_summary)
        self.formatRunSectionLayout.addWidget(self.formatRunContent)
        self.outputContentLayout.addWidget(self.format_run_section)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.outputContentLayout.addItem(spacerItem4)
        self.output_scroll.setWidget(self.output_scroll_content)
        self.outputPageLayout.addWidget(self.output_scroll)
        self.stack.addWidget(self.output_page)
        self.outerLayout.addWidget(self.stack)
        self.navigationLayout = QtWidgets.QHBoxLayout()
        self.navigationLayout.setObjectName("navigationLayout")
        self.back_button = QtWidgets.QPushButton(FormatConverterDialog)
        self.back_button.setObjectName("back_button")
        self.navigationLayout.addWidget(self.back_button)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.navigationLayout.addItem(spacerItem5)
        self.cancel_button = QtWidgets.QPushButton(FormatConverterDialog)
        self.cancel_button.setObjectName("cancel_button")
        self.navigationLayout.addWidget(self.cancel_button)
        self.next_button = QtWidgets.QPushButton(FormatConverterDialog)
        self.next_button.setObjectName("next_button")
        self.navigationLayout.addWidget(self.next_button)
        self.outerLayout.addLayout(self.navigationLayout)
        self.outerLayout.setStretch(1, 1)

        self.retranslateUi(FormatConverterDialog)
        self.stack.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(FormatConverterDialog)
        FormatConverterDialog.setTabOrder(self.add_files_button, self.add_folder_button)
        FormatConverterDialog.setTabOrder(self.add_folder_button, self.current_button)
        FormatConverterDialog.setTabOrder(self.current_button, self.input_tree)
        FormatConverterDialog.setTabOrder(self.input_tree, self.dataset_combo)
        FormatConverterDialog.setTabOrder(self.dataset_combo, self.back_button)
        FormatConverterDialog.setTabOrder(self.back_button, self.cancel_button)
        FormatConverterDialog.setTabOrder(self.cancel_button, self.next_button)

    def retranslateUi(self, FormatConverterDialog):
        _translate = QtCore.QCoreApplication.translate
        FormatConverterDialog.setWindowTitle(_translate("FormatConverterDialog", "Format Converter"))
        self.step_input_label.setText(_translate("FormatConverterDialog", "1  Input"))
        self.step_configure_label.setText(_translate("FormatConverterDialog", "2  Configure & Preview"))
        self.step_output_label.setText(_translate("FormatConverterDialog", "3  Run, Results & Export"))
        self.formatInputTitle.setText(_translate("FormatConverterDialog", "Input"))
        self.formatInputDescription.setText(_translate("FormatConverterDialog", "Add detector files or folders. Sources are inspected without changing them."))
        self.input_intro.setText(_translate("FormatConverterDialog", "Add any combination of NXS, CBF, and TIFF files. GIMaP detects single images and multi-frame inputs automatically."))
        self.add_files_button.setText(_translate("FormatConverterDialog", "Add files"))
        self.add_folder_button.setText(_translate("FormatConverterDialog", "Add folder"))
        self.current_button.setText(_translate("FormatConverterDialog", "Use currently opened file"))
        self.input_tree.headerItem().setText(0, _translate("FormatConverterDialog", "Source"))
        self.input_tree.headerItem().setText(1, _translate("FormatConverterDialog", "Type"))
        self.input_tree.headerItem().setText(2, _translate("FormatConverterDialog", "Images / frames"))
        self.input_tree.headerItem().setText(3, _translate("FormatConverterDialog", "Selection"))
        self.input_tree.headerItem().setText(4, _translate("FormatConverterDialog", "Status"))
        self.dataset_label.setText(_translate("FormatConverterDialog", "Dataset:"))
        self.dataset_note.setText(_translate("FormatConverterDialog", "Recommended dataset is selected automatically."))
        self.input_note.setText(_translate("FormatConverterDialog", "No input files yet."))
        self.formatConfigureTitle.setText(_translate("FormatConverterDialog", "Configure"))
        self.formatConfigureDescription.setText(_translate("FormatConverterDialog", "Choose sources and frame ranges. Existing selection semantics are preserved."))
        self.select_all_button.setText(_translate("FormatConverterDialog", "Select all"))
        self.select_none_button.setText(_translate("FormatConverterDialog", "Select none"))
        self.remove_selected_button.setText(_translate("FormatConverterDialog", "Remove selected"))
        self.sort_button.setText(_translate("FormatConverterDialog", "Sort by filename"))
        self.filter_edit.setPlaceholderText(_translate("FormatConverterDialog", "Filter by filename…"))
        item = self.selection_table.horizontalHeaderItem(0)
        item.setText(_translate("FormatConverterDialog", "Use"))
        item = self.selection_table.horizontalHeaderItem(1)
        item.setText(_translate("FormatConverterDialog", "Source"))
        item = self.selection_table.horizontalHeaderItem(2)
        item.setText(_translate("FormatConverterDialog", "Type"))
        item = self.selection_table.horizontalHeaderItem(3)
        item.setText(_translate("FormatConverterDialog", "Images / frames"))
        item = self.selection_table.horizontalHeaderItem(4)
        item.setText(_translate("FormatConverterDialog", "Selection"))
        self.frameAdvancedToggle.setText(_translate("FormatConverterDialog", "Advanced frame selection"))
        self.frameAdvancedDescription.setText(_translate("FormatConverterDialog", "Use ranges, custom expressions or Every N for multi-frame NXS inputs."))
        self.frame_group.setTitle(_translate("FormatConverterDialog", "Frame selection for selected NXS"))
        self.frameModeLabel.setText(_translate("FormatConverterDialog", "Mode:"))
        self.frame_mode.setItemText(0, _translate("FormatConverterDialog", "All"))
        self.frame_mode.setItemText(1, _translate("FormatConverterDialog", "Current frame"))
        self.frame_mode.setItemText(2, _translate("FormatConverterDialog", "Frame range"))
        self.frame_mode.setItemText(3, _translate("FormatConverterDialog", "Custom"))
        self.frame_mode.setItemText(4, _translate("FormatConverterDialog", "Every Nth frame"))
        self.rangeLabel.setText(_translate("FormatConverterDialog", "Range:"))
        self.rangeToLabel.setText(_translate("FormatConverterDialog", "to"))
        self.customLabel.setText(_translate("FormatConverterDialog", "Custom:"))
        self.custom_frames.setText(_translate("FormatConverterDialog", "1, 5, 8–20"))
        self.nthLabel.setText(_translate("FormatConverterDialog", "Every N:"))
        self.apply_frames.setText(_translate("FormatConverterDialog", "Apply selection"))
        self.formatPreviewTitle.setText(_translate("FormatConverterDialog", "Preview"))
        self.formatPreviewDescription.setText(_translate("FormatConverterDialog", "Inspect representative frames before conversion."))
        self.first_preview_caption.setText(_translate("FormatConverterDialog", "First"))
        self.first_preview_label.setText(_translate("FormatConverterDialog", "No preview"))
        self.middle_preview_caption.setText(_translate("FormatConverterDialog", "Middle"))
        self.middle_preview_label.setText(_translate("FormatConverterDialog", "No preview"))
        self.last_preview_caption.setText(_translate("FormatConverterDialog", "Last"))
        self.last_preview_label.setText(_translate("FormatConverterDialog", "No preview"))
        self.preview_stats.setText(_translate("FormatConverterDialog", "Select an input to inspect its frames."))
        self.formatOutputTitle.setText(_translate("FormatConverterDialog", "Configure output"))
        self.formatOutputDescription.setText(_translate("FormatConverterDialog", "Choose the destination and primary output contract."))
        self.output_format_group.setTitle(_translate("FormatConverterDialog", "Output format"))
        self.tiff_format_button.setProperty("format_name", _translate("FormatConverterDialog", "TIFF"))
        self.tiff_format_button.setText(_translate("FormatConverterDialog", "TIFF"))
        self.cbf_format_button.setProperty("format_name", _translate("FormatConverterDialog", "CBF"))
        self.cbf_format_button.setText(_translate("FormatConverterDialog", "CBF"))
        self.hdf5_format_button.setProperty("format_name", _translate("FormatConverterDialog", "HDF5"))
        self.hdf5_format_button.setText(_translate("FormatConverterDialog", "HDF5"))
        self.numpy_format_button.setProperty("format_name", _translate("FormatConverterDialog", "NumPy"))
        self.numpy_format_button.setText(_translate("FormatConverterDialog", "NumPy (.npy)"))
        self.destination_group.setTitle(_translate("FormatConverterDialog", "Destination and naming"))
        self.destinationLabel.setText(_translate("FormatConverterDialog", "Destination:"))
        self.destination_button.setText(_translate("FormatConverterDialog", "Browse…"))
        self.namingLabel.setText(_translate("FormatConverterDialog", "Multi-frame template:"))
        self.naming_combo.setItemText(0, _translate("FormatConverterDialog", "{source}_{frame:06d}"))
        self.naming_combo.setItemText(1, _translate("FormatConverterDialog", "{source}_img_{frame:06d}"))
        self.naming_example.setText(_translate("FormatConverterDialog", "Example: scan_001_000123.tif"))
        self.add_suffix.setText(_translate("FormatConverterDialog", "Add suffix automatically when names collide"))
        self.formatOutputAdvancedToggle.setText(_translate("FormatConverterDialog", "Advanced output options"))
        self.formatOutputAdvancedDescription.setText(_translate("FormatConverterDialog", "Data type conversion, metadata layout and container options."))
        self.values_group.setTitle(_translate("FormatConverterDialog", "Pixel values and data type"))
        self.preserve_values.setText(_translate("FormatConverterDialog", "Preserve original values and data type when supported"))
        self.data_mode.setItemText(0, _translate("FormatConverterDialog", "Preserve / use loader data type"))
        self.data_mode.setItemText(1, _translate("FormatConverterDialog", "Save as 32-bit float"))
        self.data_mode.setItemText(2, _translate("FormatConverterDialog", "Convert to uint16 using the original data range"))
        self.data_mode.setItemText(3, _translate("FormatConverterDialog", "Clip to the uint16 range"))
        self.metadata_group.setTitle(_translate("FormatConverterDialog", "Metadata"))
        self.preserve_metadata.setText(_translate("FormatConverterDialog", "Preserve metadata where supported"))
        self.write_sidecar.setText(_translate("FormatConverterDialog", "Write metadata sidecar JSON"))
        self.single_json.setText(_translate("FormatConverterDialog", "One metadata file for the whole conversion"))
        self.per_image_json.setText(_translate("FormatConverterDialog", "One JSON file beside each output image"))
        self.advanced_group.setTitle(_translate("FormatConverterDialog", "Advanced"))
        self.container_check.setToolTip(_translate("FormatConverterDialog", "Stores all selected images as compressed datasets in converted_images.h5."))
        self.container_check.setText(_translate("FormatConverterDialog", "Export as one NeXus/HDF5 container"))
        self.formatRunTitle.setText(_translate("FormatConverterDialog", "Run, Results & Export"))
        self.formatRunDescription.setText(_translate("FormatConverterDialog", "Review the estimate, then start conversion. The job dialog provides progress and result links."))
        self.back_button.setText(_translate("FormatConverterDialog", "Back"))
        self.cancel_button.setText(_translate("FormatConverterDialog", "Cancel"))
        self.next_button.setText(_translate("FormatConverterDialog", "Next"))
