"""Framework-neutral GIWAXS metrics the assistant reports, and calibration-file recognition."""

from .calibration_files import (
    GIMAP_CALIBRATION,
    LOG,
    POINT_OF_NORMAL_INCIDENCE,
    READABLE_IMAGE_SUFFIXES,
    READABLE_SUFFIXES,
    STANDARD_IMAGE,
    STANDARD_NAMES,
    SUPPORTED_STANDARDS,
    PoniGeometry,
    classify,
    energy_kev,
    module_series,
    name_preference,
    parse_poni,
    path_candidates,
    private_name,
    private_path,
    standard_from_name,
    suffix,
    text_hints,
    tokens,
    wavelength_angstrom,
)
from .calibration_quality import (
    GOOD_RELATIVE_DQ,
    GOOD_RINGS,
    GOOD_RMS_PX,
    USABLE_RELATIVE_DQ,
    assessment,
    compare_verdict,
    line_quality,
    rms_px,
)
from .gisaxs_cut import HalvesChoice, Spacing, choose_halves, fit_curve, spacing_from_peaks
from .notes import energy_from_notes, incidence_from_notes, pixel_size_from_notes
from .orientation import RingOrientation, SectorComparison, compare_sectors, ring_orientation
from .peaks import BROAD_RELATIVE_WIDTH, DEFAULT_BACKGROUND_WINDOW, GAUSS_AREA, Peak, PeakSearch, caveat, find_peaks
from .profiles import Profile, downsample, significant, snip_background
from .size import DEFAULT_SHAPE_FACTOR, CrystalliteSize, scherrer_size

__all__ = [
    "HalvesChoice",
    "Spacing",
    "choose_halves",
    "fit_curve",
    "spacing_from_peaks",
    "GIMAP_CALIBRATION",
    "LOG",
    "POINT_OF_NORMAL_INCIDENCE",
    "PoniGeometry",
    "READABLE_IMAGE_SUFFIXES",
    "READABLE_SUFFIXES",
    "STANDARD_IMAGE",
    "STANDARD_NAMES",
    "SUPPORTED_STANDARDS",
    "classify",
    "energy_kev",
    "module_series",
    "name_preference",
    "parse_poni",
    "path_candidates",
    "private_name",
    "private_path",
    "standard_from_name",
    "suffix",
    "text_hints",
    "tokens",
    "wavelength_angstrom",
    "GOOD_RELATIVE_DQ",
    "GOOD_RINGS",
    "GOOD_RMS_PX",
    "USABLE_RELATIVE_DQ",
    "assessment",
    "compare_verdict",
    "line_quality",
    "rms_px",
    "BROAD_RELATIVE_WIDTH",
    "CrystalliteSize",
    "DEFAULT_BACKGROUND_WINDOW",
    "DEFAULT_SHAPE_FACTOR",
    "GAUSS_AREA",
    "Peak",
    "PeakSearch",
    "Profile",
    "RingOrientation",
    "SectorComparison",
    "caveat",
    "compare_sectors",
    "downsample",
    "energy_from_notes",
    "find_peaks",
    "incidence_from_notes",
    "pixel_size_from_notes",
    "ring_orientation",
    "scherrer_size",
    "significant",
    "snip_background",
]
